import LeanCfgProject.FixedHCFG.Identification

namespace LeanCfgProject
namespace FixedHCFG

universe u v

/-!
Semantic formalization of the conservative sequential wrapper used in the v60
TCS revision.

The existing `Identification.lean` proves eventual exactness of the batch
hypothesis built from every text prefix.  The v60 manuscript instead keeps the
previous hypothesis whenever the next positive example is already generated,
and rebuilds from the whole accumulated sample only when that example is
missed.  This file formalizes that wrapper at the language level.
-/

/-- The language generated by the batch reconstruction operator on `K`. -/
def BatchLanguage {Sigma : Type u} (Obs : Observer Sigma)
    (K : Language Sigma) : Language Sigma :=
  fun w => StartDerives Obs K w

/--
Every nonempty observed factor derives itself inside its observed context.
This is the derivational core of sample consistency.
-/
theorem visible_self_derives
    {Sigma : Type u} (Obs : Observer Sigma) (K : Language Sigma) :
    ∀ (x u v : Word Sigma),
      x ≠ [] →
      Visible K { x := x, u := u, v := v } →
      Derives Obs K { x := x, u := u, v := v } x := by
  intro x
  induction x with
  | nil =>
      intro u v hne
      exact (hne rfl).elim
  | cons a xs ih =>
      intro u v hne hvis
      cases xs with
      | nil =>
          simpa using Derives.terminal a u v hvis
      | cons b bs =>
          let y : Word Sigma := b :: bs
          have hy_ne : y ≠ [] := by simp [y]
          have hleft : Visible K
              { x := [a], u := u, v := y ++ v } := by
            simpa [Visible, y, List.append_assoc] using hvis
          have hright : Visible K
              { x := y, u := u ++ [a], v := v } := by
            simpa [Visible, y, List.append_assoc] using hvis
          have dleft : Derives Obs K
              { x := [a], u := u, v := y ++ v } [a] :=
            Derives.terminal a u (y ++ v) hleft
          have dright : Derives Obs K
              { x := y, u := u ++ [a], v := v } y := by
            exact ih (u ++ [a]) v hy_ne hright
          have dsplit : Derives Obs K
              { x := [a] ++ y, u := u, v := v } ([a] ++ y) :=
            Derives.split [a] y u v [a] y
              (by simpa [y] using hvis) hleft hright dleft dright
          simpa [y] using dsplit

/-- Lemma `sample-consistency` of the v60 manuscript, at the semantic level. -/
theorem batch_sample_consistency
    {Sigma : Type u} (Obs : Observer Sigma) (K : Language Sigma) :
    K ⊆ BatchLanguage Obs K := by
  intro w hw
  by_cases hnil : w = []
  · subst w
    exact StartDerives.epsilon hw
  · have hvis : Visible K { x := w, u := [], v := [] } := by
      simpa [Visible] using hw
    have hder := visible_self_derives Obs K w [] [] hnil hvis
    exact StartDerives.sample w w hw hder

/-- The v60 conservative hypothesis after reading exactly `n` examples. -/
noncomputable def ConservativeHypothesis
    {Sigma : Type u} (Obs : Observer Sigma) (text : Nat → Word Sigma) :
    Nat → Language Sigma
  | 0 => fun _ => False
  | n + 1 =>
      if ConservativeHypothesis Obs text n (text n) then
        ConservativeHypothesis Obs text n
      else
        BatchLanguage Obs (PrefixSample text n)

/-- A stage rebuilds exactly when the newly read example is absent. -/
def ConservativeRebuildsAt
    {Sigma : Type u} (Obs : Observer Sigma) (text : Nat → Word Sigma)
    (n : Nat) : Prop :=
  ¬ ConservativeHypothesis Obs text n (text n)

/-- Every conservative hypothesis remains sound for a positive target text. -/
theorem conservativeHypothesis_subset_target
    {Sigma : Type u} (Obs : Observer Sigma)
    (L : Language Sigma) (text : Nat → Word Sigma)
    (hText : TextFor L text)
    (hSub : HSubstitutable Obs L) :
    ∀ n : Nat, ConservativeHypothesis Obs text n ⊆ L := by
  intro n
  induction n with
  | zero =>
      intro w hw
      exact False.elim hw
  | succ n ih =>
      classical
      by_cases hmem : ConservativeHypothesis Obs text n (text n)
      · simpa [ConservativeHypothesis, hmem] using ih
      · simp only [ConservativeHypothesis, hmem, if_false]
        intro w hw
        exact theorem_5_6_soundness Obs (PrefixSample text n) L
          (prefixSample_subset_target hText n) hSub hw

/-- After stage `n+1`, every example seen through stage `n` is covered. -/
theorem prefixSample_subset_conservative
    {Sigma : Type u} (Obs : Observer Sigma) (text : Nat → Word Sigma) :
    ∀ n : Nat, PrefixSample text n ⊆ ConservativeHypothesis Obs text (n + 1) := by
  intro n
  induction n with
  | zero =>
      classical
      have hmiss : ¬ ConservativeHypothesis Obs text 0 (text 0) := by
        simp [ConservativeHypothesis]
      simp only [ConservativeHypothesis, hmiss, if_false]
      exact batch_sample_consistency Obs (PrefixSample text 0)
  | succ n ih =>
      classical
      by_cases hmem : ConservativeHypothesis Obs text (n + 1) (text (n + 1))
      · simp only [ConservativeHypothesis, hmem, if_true]
        intro w hw
        rcases hw with ⟨i, hi, rfl⟩
        rcases Nat.lt_or_eq_of_le hi with hlt | rfl
        · have hle : i ≤ n := Nat.le_of_lt_succ hlt
          exact ih ⟨i, hle, rfl⟩
        · exact hmem
      · simp only [ConservativeHypothesis, hmem, if_false]
        exact batch_sample_consistency Obs (PrefixSample text (n + 1))

/--
If the characteristic sample is already present, any subsequent rebuild is
exact.  This is the key v60 reason that at most one post-characteristic-sample
mind change can occur.
-/
theorem conservative_rebuild_exact_after_characteristic
    {Sigma : Type u} {W : Type v}
    {Obs : Observer Sigma} (B : ReconstructionBasis Obs W)
    (hSub : HSubstitutable Obs (BasisLanguage B))
    (text : Nat → Word Sigma)
    (hText : TextFor (BasisLanguage B) text)
    (n : Nat)
    (hCS : B.CS ⊆ PrefixSample text n)
    (hmiss : ConservativeRebuildsAt Obs text n) :
    ConservativeHypothesis Obs text (n + 1) = BasisLanguage B := by
  classical
  have hKL : PrefixSample text n ⊆ BasisLanguage B :=
    prefixSample_subset_target hText n
  have hExact : BatchLanguage Obs (PrefixSample text n) = BasisLanguage B := by
    ext w
    exact theorem_5_7_exact_reconstruction B (PrefixSample text n)
      hCS hKL hSub w
  simp only [ConservativeRebuildsAt] at hmiss
  simp [ConservativeHypothesis, hmiss, hExact]

/-- Once the conservative hypothesis is exact, it is absorbing on a positive text. -/
theorem conservative_exact_is_absorbing
    {Sigma : Type u} (Obs : Observer Sigma)
    (L : Language Sigma) (text : Nat → Word Sigma)
    (hText : TextFor L text)
    (n : Nat)
    (hExact : ConservativeHypothesis Obs text n = L) :
    ConservativeHypothesis Obs text (n + 1) = L := by
  classical
  have hmem : ConservativeHypothesis Obs text n (text n) := by
    rw [hExact]
    exact hText.positive n
  simp [ConservativeHypothesis, hmem, hExact]

end FixedHCFG
end LeanCfgProject
