import LeanCfgProject.FixedHCFG.LinearTrimmed

namespace LeanCfgProject
namespace FixedHCFG

universe u v

/-!
Language semantics and plugging lemmas for strict-linear grammars.

These lemmas are the bridge needed to instantiate the Section-7 reconstruction
basis with the *actual* reachable/productive typed linear grammar `H`, rather
than with an abstract theorem-facing basis.
-/

/-- Terminal language generated by a strict-linear grammar. -/
def StrictLinearLanguage
    {W : Type v} {Sigma : Type u}
    (G : StrictLinearGrammar W Sigma) : Language Sigma :=
  fun w =>
    (w = [] ∧ G.hasEpsilon) ∨
      ∃ X : W, G.startState X ∧ LinearDerives G X w

namespace LinearOccursSpine

/--
Plug a terminal derivation into an occurrence on a strict-linear spine.
This is the formal version of the manuscript step
`S =>* u X v` and `X =>* w` implies `S =>* u w v`.
-/
theorem plug_derivation
    {W : Type v} {Sigma : Type u}
    {G : StrictLinearGrammar W Sigma}
    {X : W} {sp : List W} {l r w : Word Sigma}
    (occ : LinearOccursSpine G X sp l r)
    (der : LinearDerives G X w) :
    StrictLinearLanguage G (l ++ w ++ r) := by
  induction occ with
  | @start X hstart =>
      exact Or.inr ⟨X, hstart, by simpa using der⟩
  | @left X Y a sp l r parent hrule ih =>
      rcases der with ⟨dsp, dY⟩
      have dX : LinearDerives G X (a :: w) :=
        ⟨X :: dsp, LinearDerivesSpine.left hrule dY⟩
      simpa [List.append_assoc] using ih dX
  | @right X Y a sp l r parent hrule ih =>
      rcases der with ⟨dsp, dY⟩
      have dX : LinearDerives G X (w ++ [a]) :=
        ⟨X :: dsp, LinearDerivesSpine.right hrule dY⟩
      simpa [List.append_assoc] using ih dX

end LinearOccursSpine

/-- Ordinary occurrence form of `LinearOccursSpine.plug_derivation`. -/
theorem linear_occurs_plug_derivation
    {W : Type v} {Sigma : Type u}
    {G : StrictLinearGrammar W Sigma}
    {X : W} {l r w : Word Sigma}
    (occ : LinearOccurs G X l r)
    (der : LinearDerives G X w) :
    StrictLinearLanguage G (l ++ w ++ r) := by
  rcases occ with ⟨sp, hocc⟩
  exact LinearOccursSpine.plug_derivation hocc der

namespace LinearDerivesSpine

/-- Forget retained-state subtype annotations from a trimmed derivation spine. -/
theorem forget_trim
    {W : Type v} {Sigma : Type u}
    {G : StrictLinearGrammar W Sigma}
    {X : StrictLinearKeptState G}
    {sp : List (StrictLinearKeptState G)} {w : Word Sigma}
    (d : LinearDerivesSpine (trimStrictLinearGrammar G) X sp w) :
    ∃ sp0 : List W, LinearDerivesSpine G X.1 sp0 w := by
  induction d with
  | @terminal X a hrule =>
      refine ⟨[X.1], LinearDerivesSpine.terminal ?_⟩
      simpa [trimStrictLinearGrammar] using hrule
  | @left X Y a sp w hrule child ih =>
      rcases ih with ⟨sp0, hchild⟩
      refine ⟨X.1 :: sp0, LinearDerivesSpine.left ?_ hchild⟩
      simpa [trimStrictLinearGrammar] using hrule
  | @right X Y a sp w hrule child ih =>
      rcases ih with ⟨sp0, hchild⟩
      refine ⟨X.1 :: sp0, LinearDerivesSpine.right ?_ hchild⟩
      simpa [trimStrictLinearGrammar] using hrule

end LinearDerivesSpine

/-- Forget trimming from ordinary terminal derivability. -/
theorem linear_derives_forget_trim
    {W : Type v} {Sigma : Type u}
    {G : StrictLinearGrammar W Sigma}
    {X : StrictLinearKeptState G} {w : Word Sigma}
    (d : LinearDerives (trimStrictLinearGrammar G) X w) :
    LinearDerives G X.1 w := by
  rcases d with ⟨sp, hd⟩
  exact LinearDerivesSpine.forget_trim hd

namespace LinearOccursSpine

/-- Forget retained-state subtype annotations from a trimmed occurrence spine. -/
theorem forget_trim
    {W : Type v} {Sigma : Type u}
    {G : StrictLinearGrammar W Sigma}
    {X : StrictLinearKeptState G}
    {sp : List (StrictLinearKeptState G)} {l r : Word Sigma}
    (d : LinearOccursSpine (trimStrictLinearGrammar G) X sp l r) :
    ∃ sp0 : List W, LinearOccursSpine G X.1 sp0 l r := by
  induction d with
  | @start X hstart =>
      refine ⟨[X.1], LinearOccursSpine.start ?_⟩
      simpa [trimStrictLinearGrammar] using hstart
  | @left X Y a sp l r parent hrule ih =>
      rcases ih with ⟨sp0, hparent⟩
      refine ⟨sp0.concat Y.1, LinearOccursSpine.left hparent ?_⟩
      simpa [trimStrictLinearGrammar] using hrule
  | @right X Y a sp l r parent hrule ih =>
      rcases ih with ⟨sp0, hparent⟩
      refine ⟨sp0.concat Y.1, LinearOccursSpine.right hparent ?_⟩
      simpa [trimStrictLinearGrammar] using hrule

end LinearOccursSpine

/-- Forget trimming from ordinary reachability/occurrence. -/
theorem linear_occurs_forget_trim
    {W : Type v} {Sigma : Type u}
    {G : StrictLinearGrammar W Sigma}
    {X : StrictLinearKeptState G} {l r : Word Sigma}
    (d : LinearOccurs (trimStrictLinearGrammar G) X l r) :
    LinearOccurs G X.1 l r := by
  rcases d with ⟨sp, hd⟩
  exact LinearOccursSpine.forget_trim hd

/-- Trimming does not add terminal words. -/
theorem trim_strict_linear_language_subset
    {W : Type v} {Sigma : Type u}
    (G : StrictLinearGrammar W Sigma) :
    StrictLinearLanguage (trimStrictLinearGrammar G) ⊆
      StrictLinearLanguage G := by
  intro w hw
  rcases hw with hEps | hWord
  · exact Or.inl ⟨hEps.1, hEps.2⟩
  · rcases hWord with ⟨X, hstart, hder⟩
    refine Or.inr ⟨X.1, ?_, linear_derives_forget_trim hder⟩
    simpa [trimStrictLinearGrammar] using hstart

/-- Every successful full-grammar derivation survives reachable/productive trimming. -/
theorem strict_linear_language_subset_trim
    {W : Type v} {Sigma : Type u}
    (G : StrictLinearGrammar W Sigma) :
    StrictLinearLanguage G ⊆
      StrictLinearLanguage (trimStrictLinearGrammar G) := by
  intro w hw
  rcases hw with hEps | hWord
  · exact Or.inl ⟨hEps.1, hEps.2⟩
  · rcases hWord with ⟨X, hstart, hder⟩
    have hReach : ∃ l r : Word Sigma, LinearOccurs G X l r :=
      ⟨[], [], [X], LinearOccursSpine.start hstart⟩
    let XK : StrictLinearKeptState G := ⟨X, ⟨hder, hReach⟩⟩
    rcases hder with ⟨sp, hd⟩
    have hderK : LinearDerives (trimStrictLinearGrammar G) XK w :=
      lift_linear_derivation_to_trim hd hReach
    refine Or.inr ⟨XK, ?_, hderK⟩
    simpa [XK, trimStrictLinearGrammar] using hstart

/-- Reachable/productive trimming preserves the strict-linear language exactly. -/
theorem trim_strict_linear_language_eq
    {W : Type v} {Sigma : Type u}
    (G : StrictLinearGrammar W Sigma) :
    StrictLinearLanguage (trimStrictLinearGrammar G) =
      StrictLinearLanguage G := by
  apply Set.Subset.antisymm
  · exact trim_strict_linear_language_subset G
  · exact strict_linear_language_subset_trim G

end FixedHCFG
end LeanCfgProject
