import LeanCfgProject.FixedHCFG.LearnerKernel

namespace LeanCfgProject
namespace FixedHCFG

universe u

/--
The strong induction claim used in Theorem 5.6 of the TCS manuscript.

If learner nonterminal `[x : u, v]` derives `w`, then replacing `x` by `w`
inside its recorded outer context stays in the target language, and the fixed
observer assigns the same type to `w` and `x`.
-/
theorem derives_sound {Sigma : Type u}
    (Obs : Observer Sigma)
    (K L : Language Sigma)
    (hKL : K ⊆ L)
    (hSub : HSubstitutable Obs L)
    {q : LearnerNT Sigma} {w : Word Sigma}
    (hder : Derives Obs K q w) :
    q.u ++ w ++ q.v ∈ L ∧ Obs.value w = Obs.value q.x := by
  induction hder with
  | terminal a u v hvis =>
      constructor
      · exact hKL hvis
      · rfl
  | contextTransport x u v u' v' w hsrc hdst htail ih =>
      rcases ih with ⟨hmem, hval⟩
      constructor
      · have hshare : ShareContext L x w := by
          refine ⟨u', v', ?_, ?_⟩
          · exact hKL hdst
          · exact hmem
        have hdist : SameDistribution L x w :=
          hSub x w hval.symm hshare
        exact (hdist u v).mp (hKL hsrc)
      · exact hval
  | typedSubstitution x x' u v w hsrc hdst htype htail ih =>
      rcases ih with ⟨hmem, hval⟩
      constructor
      · exact hmem
      · exact hval.trans htype.symm
  | split x y u v w₁ w₂ hparent hleft hright hder₁ hder₂ ih₁ ih₂ =>
      rcases ih₁ with ⟨hmem₁, hval₁⟩
      rcases ih₂ with ⟨hmem₂, hval₂⟩
      constructor
      · have hxCommon : InDistribution L x u (y ++ v) := by
          change u ++ x ++ (y ++ v) ∈ L
          simpa [List.append_assoc] using hKL hparent
        have hwCommon : InDistribution L w₁ u (y ++ v) := by
          change u ++ w₁ ++ (y ++ v) ∈ L
          simpa [List.append_assoc] using hmem₁
        have hshare : ShareContext L x w₁ :=
          ⟨u, y ++ v, hxCommon, hwCommon⟩
        have hdist : SameDistribution L x w₁ :=
          hSub x w₁ hval₁.symm hshare
        have hxSecond : InDistribution L x u (w₂ ++ v) := by
          change u ++ x ++ (w₂ ++ v) ∈ L
          simpa [List.append_assoc] using hmem₂
        have hwSecond : InDistribution L w₁ u (w₂ ++ v) :=
          (hdist u (w₂ ++ v)).mp hxSecond
        change u ++ (w₁ ++ w₂) ++ v ∈ L
        simpa [List.append_assoc] using hwSecond
      · calc
          Obs.value (w₁ ++ w₂) =
              Obs.mul (Obs.value w₁) (Obs.value w₂) :=
            Obs.value_append w₁ w₂
          _ = Obs.mul (Obs.value x) (Obs.value y) := by
            rw [hval₁, hval₂]
          _ = Obs.value (x ++ y) :=
            (Obs.value_append x y).symm

/-- Theorem 5.6: every terminal word generated by the current hypothesis is in the target. -/
theorem theorem_5_6_soundness {Sigma : Type u}
    (Obs : Observer Sigma)
    (K L : Language Sigma)
    (hKL : K ⊆ L)
    (hSub : HSubstitutable Obs L)
    {w : Word Sigma}
    (hstart : StartDerives Obs K w) :
    w ∈ L := by
  cases hstart with
  | epsilon hmem =>
      exact hKL hmem
  | sample x w hmem hder =>
      have hs := derives_sound Obs K L hKL hSub hder
      simpa using hs.1

end FixedHCFG
end LeanCfgProject
