import LeanCfgProject.MCFGv4.StandardMCFG
import Mathlib.Data.Set.Basic

/-!
# MCFGv4.StandardSemantics

Tuple-generation semantics for the arbitrary-finite-rank standard MCFG syntax
used by the frozen 2026-09-07 manuscript.

This module deliberately does not use the legacy terminal/binary MCFG2
interfaces.  A rule is evaluated against one compatible tuple for each child,
and derivability is the least relation closed under those arbitrary-rank rule
applications, matching Definition `def:standard-mcfg`.
-/

namespace MCFGv4

universe u v

namespace MCFGRule

variable {N : Type v} {α : Type u} {sig : MCFGSignature N}

/-- Values supplied for every child of a rule. -/
abbrev ChildTuples (r : MCFGRule sig α) :=
  (j : Fin r.children.length) → Tuple α (sig.arity (r.children.get j))

/-- Evaluate one child-component variable under compatible child tuples. -/
def evalVariable (r : MCFGRule sig α) (values : r.ChildTuples)
    (rv : RuleVariable sig r.children) : Word α :=
  values rv.child rv.component

/-- Evaluate one template atom. -/
def evalAtom (r : MCFGRule sig α) (values : r.ChildTuples) :
    TemplateAtom sig α r.children → Word α
  | TemplateAtom.terminal a => [a]
  | TemplateAtom.variable rv => r.evalVariable values rv

/-- Evaluate one parent-template component by simultaneous substitution. -/
def evalComponent (r : MCFGRule sig α) (values : r.ChildTuples)
    (component : List (TemplateAtom sig α r.children)) : Word α :=
  component.foldr (fun atom suffix => r.evalAtom values atom ++ suffix) []

/-- Apply an arbitrary-rank MCFG rule to compatible child tuples. -/
def apply (r : MCFGRule sig α) (values : r.ChildTuples) :
    Tuple α (sig.arity r.lhs) :=
  fun i =>
    r.evalComponent values
      (r.components.get (Fin.cast r.components_length.symm i))

/-- Constant rules are exactly the rank-zero instance of `apply`; their result
is independent of the (empty) child assignment. -/
theorem apply_rankZero_irrelevant (r : MCFGRule sig α)
    (hrank : r.rank = 0) (values values' : r.ChildTuples) :
    r.apply values = r.apply values' := by
  funext i
  apply congrArg (r.evalComponent values)
  rfl

end MCFGRule

namespace StandardMCFG

variable {N : Type v} {α : Type u} [Fintype N] [Fintype α]

/-- Finite derivation-tree semantics.  This is the least tuple family closed
under all rule applications from Definition `def:standard-mcfg`. -/
inductive Derives (G : StandardMCFG N α) :
    (A : N) → Tuple α (G.sig.arity A) → Prop where
  | rule
      (r : MCFGRule G.sig α)
      (hr : r ∈ G.rules)
      (values : r.ChildTuples)
      (childrenDerive : ∀ j : Fin r.children.length,
        Derives G (r.children.get j) (values j)) :
      Derives G r.lhs (r.apply values)

/-- Tuple language generated from a nonterminal. -/
def TupleLanguage (G : StandardMCFG N α) (A : N) :
    Set (Tuple α (G.sig.arity A)) :=
  { x | G.Derives A x }

/-- The unary start tuple containing `w`.  The signature invariant records that
the start fan-out is one. -/
def startTuple (G : StandardMCFG N α) (w : Word α) :
    Tuple α (G.sig.arity G.sig.start) :=
  fun _ => w

/-- String language generated by the start symbol. -/
def Language (G : StandardMCFG N α) : Set (Word α) :=
  { w | G.Derives G.sig.start (G.startTuple w) }

end StandardMCFG

end MCFGv4
