import LeanCfgProject.FixedHCFGv44.Language

namespace LeanCfgProject
namespace FixedHCFGv44

universe u v

/-!
Source-side linear CFG semantics and the non-start epsilon-elimination phase of
Appendix A in TCS v49.

A linear production contains either no nonterminal (`A -> w`) or exactly one
continuing nonterminal (`A -> u B v`).  At this source stage terminal words may
be empty and a context rule may be a unit rule.  The epsilon-elimination
relation below removes empty terminal rules and, because there is at most one
nonterminal on a right-hand side, adds at most the single omission alternative
`A -> uv` when `B` is nullable.  Empty yield is recorded only at the separated
start interface.
-/

/-- A source linear-CFG production before epsilon/unit elimination. -/
inductive SourceLinearRule (N : Type v) (Sigma : Type u) where
  | context (lhs : N) (left : Word Sigma) (center : N) (right : Word Sigma)
  | terminal (lhs : N) (word : Word Sigma)

/-- Ordinary recursive semantics of a finite source linear grammar. -/
inductive SourceLinearDerives
    {N : Type v} {Sigma : Type u}
    (rules : List (SourceLinearRule N Sigma)) : N → Word Sigma → Prop
  | context
      {A B : N} {u v z : Word Sigma}
      (hrule : SourceLinearRule.context A u B v ∈ rules)
      (center : SourceLinearDerives rules B z) :
      SourceLinearDerives rules A (u ++ z ++ v)
  | terminal
      {A : N} {w : Word Sigma}
      (hrule : SourceLinearRule.terminal A w ∈ rules) :
      SourceLinearDerives rules A w

/-- Language generated by a source linear grammar from its original start symbol. -/
def SourceLinearLanguage
    {N : Type v} {Sigma : Type u}
    (rules : List (SourceLinearRule N Sigma)) (S : N) : Language Sigma :=
  fun w => SourceLinearDerives rules S w

/-- The fresh separated start interface points only to the old source start symbol. -/
def SourceSeparatedStart {N : Type v} (S : N) : N → Prop :=
  fun A => A = S

/-- Start separation alone is semantics-preserving. -/
theorem source_start_separation_iff
    {N : Type v} {Sigma : Type u}
    (rules : List (SourceLinearRule N Sigma)) (S : N) (w : Word Sigma) :
    (∃ A : N, SourceSeparatedStart S A ∧ SourceLinearDerives rules A w) ↔
      SourceLinearDerives rules S w := by
  constructor
  · rintro ⟨A, rfl, h⟩
    exact h
  · intro h
    exact ⟨S, rfl, h⟩

/-- Source nullability used by the linear epsilon-elimination construction. -/
def SourceNullable
    {N : Type v} {Sigma : Type u}
    (rules : List (SourceLinearRule N Sigma)) (A : N) : Prop :=
  SourceLinearDerives rules A []

/-- Rules admitted after non-start epsilon elimination. -/
inductive EpsilonElimLinearRule
    {N : Type v} {Sigma : Type u}
    (rules : List (SourceLinearRule N Sigma)) :
    SourceLinearRule N Sigma → Prop
  | context
      {A B : N} {u v : Word Sigma}
      (hrule : SourceLinearRule.context A u B v ∈ rules) :
      EpsilonElimLinearRule rules (SourceLinearRule.context A u B v)
  | terminal
      {A : N} {w : Word Sigma}
      (hrule : SourceLinearRule.terminal A w ∈ rules)
      (hne : w ≠ []) :
      EpsilonElimLinearRule rules (SourceLinearRule.terminal A w)
  | omitNullable
      {A B : N} {u v : Word Sigma}
      (hrule : SourceLinearRule.context A u B v ∈ rules)
      (hnullable : SourceNullable rules B)
      (hne : u ++ v ≠ []) :
      EpsilonElimLinearRule rules
        (SourceLinearRule.terminal A (u ++ v))

/-- Derivation semantics after deleting non-start epsilon productions. -/
inductive EpsilonElimLinearDerives
    {N : Type v} {Sigma : Type u}
    (rules : List (SourceLinearRule N Sigma)) : N → Word Sigma → Prop
  | context
      {A B : N} {u v z : Word Sigma}
      (hrule : EpsilonElimLinearRule rules
        (SourceLinearRule.context A u B v))
      (center : EpsilonElimLinearDerives rules B z) :
      EpsilonElimLinearDerives rules A (u ++ z ++ v)
  | terminal
      {A : N} {w : Word Sigma}
      (hrule : EpsilonElimLinearRule rules
        (SourceLinearRule.terminal A w)) :
      EpsilonElimLinearDerives rules A w

/-- Epsilon-eliminated non-start derivations are necessarily nonempty. -/
theorem epsilonElimLinearDerives_nonempty
    {N : Type v} {Sigma : Type u}
    {rules : List (SourceLinearRule N Sigma)}
    {A : N} {w : Word Sigma}
    (d : EpsilonElimLinearDerives rules A w) : w ≠ [] := by
  induction d with
  | @terminal A w hrule =>
      cases hrule with
      | terminal hrule hne => exact hne
      | omitNullable hrule hnullable hne => exact hne
  | @context A B u v z hrule center ih =>
      intro hEmpty
      have hParts : u = [] ∧ z = [] ∧ v = [] := by
        simpa only [List.append_eq_nil_iff] using hEmpty
      exact ih hParts.2.1

/-- Every epsilon-eliminated derivation expands back to a source derivation. -/
theorem epsilonElim_to_source
    {N : Type v} {Sigma : Type u}
    {rules : List (SourceLinearRule N Sigma)}
    {A : N} {w : Word Sigma}
    (d : EpsilonElimLinearDerives rules A w) :
    SourceLinearDerives rules A w := by
  induction d with
  | @context A B u v z hrule center ih =>
      cases hrule with
      | context hsrc =>
          exact SourceLinearDerives.context hsrc ih
  | @terminal A w hrule =>
      cases hrule with
      | terminal hsrc hne =>
          exact SourceLinearDerives.terminal hsrc
      | @omitNullable A B u v hsrc hnullable hne =>
          have hd : SourceLinearDerives rules A (u ++ [] ++ v) :=
            SourceLinearDerives.context hsrc hnullable
          simpa using hd

/-- Every nonempty source derivation survives linear epsilon elimination. -/
theorem source_nonempty_to_epsilonElim
    {N : Type v} {Sigma : Type u}
    {rules : List (SourceLinearRule N Sigma)}
    {A : N} {w : Word Sigma}
    (d : SourceLinearDerives rules A w)
    (hne : w ≠ []) :
    EpsilonElimLinearDerives rules A w := by
  induction d with
  | @terminal A w hrule =>
      exact EpsilonElimLinearDerives.terminal
        (EpsilonElimLinearRule.terminal hrule hne)
  | @context A B u v z hrule center ih =>
      by_cases hz : z = []
      · subst z
        have huv : u ++ v ≠ [] := by
          simpa using hne
        have hRule : EpsilonElimLinearRule rules
            (SourceLinearRule.terminal A (u ++ v)) :=
          EpsilonElimLinearRule.omitNullable hrule center huv
        have hd : EpsilonElimLinearDerives rules A (u ++ v) :=
          EpsilonElimLinearDerives.terminal hRule
        simpa using hd
      · exact EpsilonElimLinearDerives.context
          (EpsilonElimLinearRule.context hrule) (ih hz)

/-- Exact preservation of every nonempty nonterminal language. -/
theorem epsilon_elimination_nonempty_iff
    {N : Type v} {Sigma : Type u}
    (rules : List (SourceLinearRule N Sigma))
    (A : N) (w : Word Sigma) (hne : w ≠ []) :
    EpsilonElimLinearDerives rules A w ↔
      SourceLinearDerives rules A w := by
  constructor
  · exact epsilonElim_to_source
  · intro h
    exact source_nonempty_to_epsilonElim h hne

/--
Separated start language after epsilon elimination.  The empty word is stored
only in the fresh start interface, while all nonempty derivations use the
non-start epsilon-free grammar.
-/
def EpsilonSeparatedLinearLanguage
    {N : Type v} {Sigma : Type u}
    (rules : List (SourceLinearRule N Sigma)) (S : N) : Language Sigma :=
  fun w =>
    (w = [] ∧ SourceNullable rules S) ∨
      (w ≠ [] ∧ EpsilonElimLinearDerives rules S w)

/-- Start separation plus non-start epsilon elimination preserves the source language exactly. -/
theorem epsilon_separated_language_eq_source_v49
    {N : Type v} {Sigma : Type u}
    (rules : List (SourceLinearRule N Sigma)) (S : N) :
    EpsilonSeparatedLinearLanguage rules S = SourceLinearLanguage rules S := by
  ext w
  constructor
  · intro h
    rcases h with hEps | hNonempty
    · rcases hEps with ⟨rfl, hNullable⟩
      exact hNullable
    · exact epsilonElim_to_source hNonempty.2
  · intro h
    by_cases hw : w = []
    · subst w
      exact Or.inl ⟨rfl, h⟩
    · exact Or.inr ⟨hw, source_nonempty_to_epsilonElim h hw⟩

end FixedHCFGv44
end LeanCfgProject
