import LeanCfgProject.FixedHCFGv44.LearnerKernel

namespace LeanCfgProject
namespace FixedHCFGv44

universe u

/-- The language generated from the start symbol of the v44 batch grammar. -/
def HypLanguage {Sigma : Type u} (Obs : Observer Sigma)
    (K : Language Sigma) : Language Sigma :=
  { w | StartDerives Obs K w }

/--
Every observed nonempty factor can reproduce itself in its observed context.
This is the derivation-tree form of the repeated Rule (1) / Rule (4)
argument in the revised sample-consistency lemma.
-/
theorem observed_factor_self_derives {Sigma : Type u}
    (Obs : Observer Sigma) (K : Language Sigma) :
    ∀ (x u v : Word Sigma),
      Internal x →
      Visible K { x := x, u := u, v := v } →
      Derives Obs K { x := x, u := u, v := v } x := by
  intro x
  induction x with
  | nil =>
      intro u v hx _
      exact (hx rfl).elim
  | cons a xs ih =>
      intro u v hx hvis
      cases xs with
      | nil =>
          exact Derives.terminal (Obs := Obs) (K := K) a u v hvis
      | cons b bs =>
          let y : Word Sigma := b :: bs
          have ha : Internal ([a] : Word Sigma) := by
            simp [Internal]
          have hy : Internal y := by
            simp [Internal, y]
          have hparent : Visible K { x := [a] ++ y, u := u, v := v } := by
            simpa [Visible, y, List.append_assoc] using hvis
          have hleft : Visible K { x := [a], u := u, v := y ++ v } := by
            simpa [Visible, y, List.append_assoc] using hvis
          have hright : Visible K { x := y, u := u ++ [a], v := v } := by
            simpa [Visible, y, List.append_assoc] using hvis
          have hdleft : Derives Obs K { x := [a], u := u, v := y ++ v } [a] :=
            Derives.terminal (Obs := Obs) (K := K) a u (y ++ v) hleft
          have hdright : Derives Obs K { x := y, u := u ++ [a], v := v } y := by
            exact ih (u ++ [a]) v hy hright
          have hsplit :
              Derives Obs K { x := [a] ++ y, u := u, v := v } ([a] ++ y) :=
            Derives.split (Obs := Obs) (K := K)
              (x := [a]) (y := y) (u := u) (v := v)
              (w₁ := [a]) (w₂ := y)
              ha hy hparent hleft hright hdleft hdright
          simpa [y] using hsplit

/-- v44 Lemma 5.1: every positive sample is generated by its batch grammar. -/
theorem lemma_sample_consistency {Sigma : Type u}
    (Obs : Observer Sigma) (K : Language Sigma) :
    K ⊆ HypLanguage Obs K := by
  intro w hw
  cases w with
  | nil =>
      exact StartDerives.epsilon (Obs := Obs) (K := K) hw
  | cons a xs =>
      have hx : Internal (a :: xs) := by
        simp [Internal]
      have hvis : Visible K { x := a :: xs, u := [], v := [] } := by
        simpa [Visible] using hw
      have hder : Derives Obs K { x := a :: xs, u := [], v := [] } (a :: xs) :=
        observed_factor_self_derives Obs K (a :: xs) [] [] hx hvis
      exact StartDerives.sample (Obs := Obs) (K := K)
        (x := a :: xs) (w := a :: xs) hx hw hder

end FixedHCFGv44
end LeanCfgProject
