import LeanCfgProject.FixedHCFGv44.SampleConsistency

namespace LeanCfgProject
namespace FixedHCFGv44

universe u

/--
The strong v44 soundness invariant.

Besides target-language membership and preservation of the fixed `h`-type,
we record explicitly that every yield from a non-start hypothesis symbol is
nonempty.  The manuscript obtains this from the absence of erasing rules;
keeping it in the Lean induction hypothesis makes every use of the revised
`Sigma+` substitutability definition explicit.
-/
theorem derives_sound {Sigma : Type u}
    (Obs : Observer Sigma)
    (K L : Language Sigma)
    (hKL : K ⊆ L)
    (hSub : HSubstitutable Obs L)
    {q : LearnerNT Sigma} {w : Word Sigma}
    (hder : Derives Obs K q w) :
    q.u ++ w ++ q.v ∈ L ∧
      obsValue Obs w = obsValue Obs q.x ∧
      Internal w := by
  induction hder with
  | terminal a u v hvis =>
      refine ⟨hKL hvis, rfl, ?_⟩
      simp [Internal]
  | contextTransport x u v u' v' w hx hsrc hdst htail ih =>
      rcases ih with ⟨hmem, hval, hw⟩
      refine ⟨?_, hval, hw⟩
      have hshare : ShareContext L x w := by
        refine ⟨u', v', ?_, ?_⟩
        · exact hKL hdst
        · exact hmem
      have hdist : SameDistribution L x w :=
        hSub x w hx hw hval.symm hshare
      exact (hdist u v).mp (hKL hsrc)
  | typedSubstitution x x' u v w hx hx' hsrc hdst htype htail ih =>
      rcases ih with ⟨hmem, hval, hw⟩
      exact ⟨hmem, hval.trans htype.symm, hw⟩
  | split x y u v w₁ w₂ hx hy hparent hleft hright hder₁ hder₂ ih₁ ih₂ =>
      rcases ih₁ with ⟨hmem₁, hval₁, hw₁⟩
      rcases ih₂ with ⟨hmem₂, hval₂, hw₂⟩
      have hxCommon : InDistribution L x u (y ++ v) := by
        change u ++ x ++ (y ++ v) ∈ L
        simpa [List.append_assoc] using hKL hparent
      have hwCommon : InDistribution L w₁ u (y ++ v) := by
        change u ++ w₁ ++ (y ++ v) ∈ L
        simpa [List.append_assoc] using hmem₁
      have hshare : ShareContext L x w₁ :=
        ⟨u, y ++ v, hxCommon, hwCommon⟩
      have hdist : SameDistribution L x w₁ :=
        hSub x w₁ hx hw₁ hval₁.symm hshare
      have hxSecond : InDistribution L x u (w₂ ++ v) := by
        change u ++ x ++ (w₂ ++ v) ∈ L
        simpa [List.append_assoc] using hmem₂
      have hwSecond : InDistribution L w₁ u (w₂ ++ v) :=
        (hdist u (w₂ ++ v)).mp hxSecond
      have hmem : u ++ (w₁ ++ w₂) ++ v ∈ L := by
        change u ++ w₁ ++ (w₂ ++ v) ∈ L at hwSecond
        simpa [List.append_assoc] using hwSecond
      have hval : obsValue Obs (w₁ ++ w₂) = obsValue Obs (x ++ y) := by
        calc
          obsValue Obs (w₁ ++ w₂) =
              Obs.mul (obsValue Obs w₁) (obsValue Obs w₂) :=
            obsValue_append Obs w₁ w₂
          _ = Obs.mul (obsValue Obs x) (obsValue Obs y) := by
            rw [hval₁, hval₂]
          _ = obsValue Obs (x ++ y) :=
            (obsValue_append Obs x y).symm
      have hw : Internal (w₁ ++ w₂) := by
        cases w₁ with
        | nil => exact (hw₁ rfl).elim
        | cons a as => simp [Internal]
      exact ⟨hmem, hval, hw⟩

/-- v44 soundness theorem: under positive data from a fixed-h substitutable target,
    every word generated by the batch grammar belongs to the target. -/
theorem theorem_soundness {Sigma : Type u}
    (Obs : Observer Sigma)
    (K L : Language Sigma)
    (hKL : K ⊆ L)
    (hSub : HSubstitutable Obs L) :
    HypLanguage Obs K ⊆ L := by
  intro w hstart
  cases hstart with
  | epsilon hmem =>
      exact hKL hmem
  | sample x w hx hmem hder =>
      have hs := derives_sound Obs K L hKL hSub hder
      simpa using hs.1

end FixedHCFGv44
end LeanCfgProject
