import LeanCfgProject.FixedHCFGv44.YieldTypedTrimmed
import LeanCfgProject.FixedHCFGv44.Reconstruction

namespace LeanCfgProject
namespace FixedHCFGv44

universe u v

/-- A retained non-start state of the reduced v44 yield-typed refinement. -/
abbrev KeptState {N : Type v} {Sigma : Type u}
    (Obs : Observer Sigma)
    (terminal : TerminalRules N Sigma) (binary : BinaryRules N)
    (start : StartRules N) :=
  {X : TypedNT N Obs // TypedKept Obs terminal binary start X}

/-- Terminal rules inherited by retained typed states. -/
def keptTerminal {N : Type v} {Sigma : Type u}
    {Obs : Observer Sigma}
    {terminal : TerminalRules N Sigma} {binary : BinaryRules N}
    {start : StartRules N}
    (X : KeptState Obs terminal binary start) (a : Sigma) : Prop :=
  terminal X.1.label a ∧ obsValue Obs [a] = X.1.yieldType

/-- Binary rules inherited by retained typed states. -/
def keptBinary {N : Type v} {Sigma : Type u}
    {Obs : Observer Sigma}
    {terminal : TerminalRules N Sigma} {binary : BinaryRules N}
    {start : StartRules N}
    (X Y Z : KeptState Obs terminal binary start) : Prop :=
  binary X.1.label Y.1.label Z.1.label ∧
    Obs.mul Y.1.yieldType Z.1.yieldType = X.1.yieldType

/-- Retained states directly available from an SSBNF start rule. -/
def keptStart {N : Type v} {Sigma : Type u}
    {Obs : Observer Sigma}
    {terminal : TerminalRules N Sigma} {binary : BinaryRules N}
    {start : StartRules N}
    (X : KeptState Obs terminal binary start) : Prop :=
  start X.1.label

/-- Every non-start typed derivation has a nonempty terminal yield. -/
theorem typed_derives_internal
    {N : Type v} {Sigma : Type u}
    (Obs : Observer Sigma)
    (terminal : TerminalRules N Sigma) (binary : BinaryRules N)
    {X : TypedNT N Obs} {w : Word Sigma}
    (d : TypedDerives Obs terminal binary X w) : Internal w := by
  induction d with
  | terminal hrule =>
      simp [Internal]
  | binary hrule left right ihLeft ihRight =>
      exact internal_append_left ihLeft

/-- An arbitrary productive yield, used before imposing canonical shortlex minimality. -/
noncomputable def chosenOmega
    {N : Type v} {Sigma : Type u}
    {Obs : Observer Sigma}
    {terminal : TerminalRules N Sigma} {binary : BinaryRules N}
    {start : StartRules N}
    (X : KeptState Obs terminal binary start) : Word Sigma :=
  Classical.choose X.property.1

/-- The chosen yield is genuinely generated by the retained typed state. -/
theorem chosenOmega_spec
    {N : Type v} {Sigma : Type u}
    {Obs : Observer Sigma}
    {terminal : TerminalRules N Sigma} {binary : BinaryRules N}
    {start : StartRules N}
    (X : KeptState Obs terminal binary start) :
    TypedDerives Obs terminal binary X.1 (chosenOmega X) := by
  exact Classical.choose_spec X.property.1

/-- The chosen yield is nonempty, as required by the revised learner. -/
theorem chosenOmega_internal
    {N : Type v} {Sigma : Type u}
    {Obs : Observer Sigma}
    {terminal : TerminalRules N Sigma} {binary : BinaryRules N}
    {start : StartRules N}
    (X : KeptState Obs terminal binary start) :
    Internal (chosenOmega X) := by
  exact typed_derives_internal Obs terminal binary (chosenOmega_spec X)

/-- A direct start state occurs in the empty terminal context. -/
theorem keptStart_occurs_empty
    {N : Type v} {Sigma : Type u}
    {Obs : Observer Sigma}
    {terminal : TerminalRules N Sigma} {binary : BinaryRules N}
    {start : StartRules N}
    (X : KeptState Obs terminal binary start)
    (hStart : keptStart X) :
    TypedOccurs Obs terminal binary start X.1 [] [] := by
  rcases X with ⟨⟨A, mu⟩, hKeep⟩
  change start A at hStart
  exact TypedOccurs.start (mu := mu) hStart

/--
Choose a reaching context, normalized so that a state directly under the start
symbol uses the empty context.  Canonical minimum-length/shortlex choice is
added in the manuscript-faithful layer later.
-/
theorem exists_preferred_context
    {N : Type v} {Sigma : Type u}
    {Obs : Observer Sigma}
    {terminal : TerminalRules N Sigma} {binary : BinaryRules N}
    {start : StartRules N}
    (X : KeptState Obs terminal binary start) :
    ∃ u v : Word Sigma,
      TypedOccurs Obs terminal binary start X.1 u v ∧
        (keptStart X → u = [] ∧ v = []) := by
  classical
  by_cases hStart : keptStart X
  · exact ⟨[], [], keptStart_occurs_empty X hStart,
      fun _ => ⟨rfl, rfl⟩⟩
  · rcases X.property.2 with ⟨u, v, hOcc⟩
    exact ⟨u, v, hOcc, fun hs => (hStart hs).elim⟩

noncomputable def chosenLeftCtx
    {N : Type v} {Sigma : Type u}
    {Obs : Observer Sigma}
    {terminal : TerminalRules N Sigma} {binary : BinaryRules N}
    {start : StartRules N}
    (X : KeptState Obs terminal binary start) : Word Sigma :=
  Classical.choose (exists_preferred_context X)

noncomputable def chosenRightCtx
    {N : Type v} {Sigma : Type u}
    {Obs : Observer Sigma}
    {terminal : TerminalRules N Sigma} {binary : BinaryRules N}
    {start : StartRules N}
    (X : KeptState Obs terminal binary start) : Word Sigma :=
  Classical.choose (Classical.choose_spec (exists_preferred_context X))

/-- Specification of the preferred chosen context. -/
theorem chosenContext_spec
    {N : Type v} {Sigma : Type u}
    {Obs : Observer Sigma}
    {terminal : TerminalRules N Sigma} {binary : BinaryRules N}
    {start : StartRules N}
    (X : KeptState Obs terminal binary start) :
    TypedOccurs Obs terminal binary start X.1
      (chosenLeftCtx X) (chosenRightCtx X) ∧
    (keptStart X → chosenLeftCtx X = [] ∧ chosenRightCtx X = []) := by
  exact Classical.choose_spec
    (Classical.choose_spec (exists_preferred_context X))

/-- Anchor witness associated with a retained state. -/
noncomputable def anchorWord
    {N : Type v} {Sigma : Type u}
    {Obs : Observer Sigma}
    {terminal : TerminalRules N Sigma} {binary : BinaryRules N}
    {start : StartRules N}
    (X : KeptState Obs terminal binary start) : Word Sigma :=
  chosenLeftCtx X ++ chosenOmega X ++ chosenRightCtx X

/-- Terminal-rule witness associated with a retained rule. -/
noncomputable def terminalObservationWord
    {N : Type v} {Sigma : Type u}
    {Obs : Observer Sigma}
    {terminal : TerminalRules N Sigma} {binary : BinaryRules N}
    {start : StartRules N}
    (X : KeptState Obs terminal binary start) (a : Sigma) : Word Sigma :=
  chosenLeftCtx X ++ [a] ++ chosenRightCtx X

/-- Binary-rule witness associated with a retained rule. -/
noncomputable def binaryObservationWord
    {N : Type v} {Sigma : Type u}
    {Obs : Observer Sigma}
    {terminal : TerminalRules N Sigma} {binary : BinaryRules N}
    {start : StartRules N}
    (X Y Z : KeptState Obs terminal binary start) : Word Sigma :=
  chosenLeftCtx X ++ chosenOmega Y ++ chosenOmega Z ++ chosenRightCtx X

/--
The four-family witness set of v44: anchors, terminal witnesses, binary
witnesses, and optional epsilon.  At this extraction stage the witnesses are
preferred choices rather than yet the manuscript's canonical minima.
-/
noncomputable def PreferredCS
    {N : Type v} {Sigma : Type u}
    {Obs : Observer Sigma}
    {terminal : TerminalRules N Sigma} {binary : BinaryRules N}
    {start : StartRules N}
    (epsilonStart : Prop) : Language Sigma :=
  fun z =>
    (∃ X : KeptState Obs terminal binary start, z = anchorWord X) ∨
    (∃ (X : KeptState Obs terminal binary start) (a : Sigma),
      keptTerminal X a ∧ z = terminalObservationWord X a) ∨
    (∃ X Y Z : KeptState Obs terminal binary start,
      keptBinary X Y Z ∧ z = binaryObservationWord X Y Z) ∨
    (z = [] ∧ epsilonStart)

/-- Finite encoding of a yield-typed state. -/
def typedNTKey
    {N : Type v} {Sigma : Type u}
    {Obs : Observer Sigma} (X : TypedNT N Obs) : N × Obs.M :=
  (X.label, X.yieldType)

/-- The component encoding is injective. -/
theorem typedNTKey_injective
    {N : Type v} {Sigma : Type u}
    {Obs : Observer Sigma} :
    Function.Injective (typedNTKey (N := N) (Obs := Obs)) := by
  intro X Y h
  rcases X with ⟨xA, xmu⟩
  rcases Y with ⟨yA, ymu⟩
  simp only [typedNTKey] at h
  cases h
  rfl

/-- The yield-typed state space is finite for a finite original grammar. -/
noncomputable instance typedNTFinite
    {N : Type v} {Sigma : Type u} {Obs : Observer Sigma}
    [Finite N] : Finite (TypedNT N Obs) :=
  Finite.of_injective (typedNTKey (N := N) (Obs := Obs))
    typedNTKey_injective

/-- The preferred four-family witness set is finite. -/
theorem preferredCS_finite
    {N : Type v} {Sigma : Type u}
    {Obs : Observer Sigma}
    {terminal : TerminalRules N Sigma} {binary : BinaryRules N}
    {start : StartRules N}
    [Finite N] [Finite Sigma]
    (epsilonStart : Prop) :
    (PreferredCS (Obs := Obs) (terminal := terminal) (binary := binary)
      (start := start) epsilonStart).Finite := by
  let W := KeptState Obs terminal binary start
  let A : Set (Word Sigma) := Set.range (fun X : W => anchorWord X)
  let T : Set (Word Sigma) := Set.range
    (fun p : W × Sigma => terminalObservationWord p.1 p.2)
  let R : Set (Word Sigma) := Set.range
    (fun p : W × W × W => binaryObservationWord p.1 p.2.1 p.2.2)
  have hA : A.Finite := Set.finite_range _
  have hT : T.Finite := Set.finite_range _
  have hR : R.Finite := Set.finite_range _
  have hAll : (A ∪ T ∪ R ∪ ({[]} : Set (Word Sigma))).Finite :=
    (((hA.union hT).union hR).union (Set.finite_singleton []))
  refine hAll.subset ?_
  intro z hz
  rcases hz with hAnchor | hTerminal | hBinary | hEps
  · rcases hAnchor with ⟨X, rfl⟩
    exact Or.inl (Or.inl (Or.inl ⟨X, rfl⟩))
  · rcases hTerminal with ⟨X, a, hRule, rfl⟩
    exact Or.inl (Or.inl (Or.inr ⟨(X, a), rfl⟩))
  · rcases hBinary with ⟨X, Y, Z, hRule, rfl⟩
    exact Or.inl (Or.inr ⟨(X, Y, Z), rfl⟩)
  · rcases hEps with ⟨rfl, hStart⟩
    exact Or.inr (Set.mem_singleton [])

/-- Build the v44 reconstruction interface from retained yield-typed states. -/
noncomputable def preferredReconstructionBasis
    {N : Type v} {Sigma : Type u}
    (Obs : Observer Sigma)
    (terminal : TerminalRules N Sigma) (binary : BinaryRules N)
    (start : StartRules N) (epsilonStart : Prop) :
    ReconstructionBasis Obs (KeptState Obs terminal binary start) where
  terminal := keptTerminal
  binary := keptBinary
  startState := keptStart
  hasEpsilon := epsilonStart
  omega := chosenOmega
  leftCtx := chosenLeftCtx
  rightCtx := chosenRightCtx
  yieldType := fun X => X.1.yieldType
  CS := PreferredCS epsilonStart
  omega_type := by
    intro X
    exact typed_yield_invariant Obs terminal binary (chosenOmega_spec X)
  omega_internal := by
    intro X
    exact chosenOmega_internal X
  terminal_type := by
    intro X a h
    exact h.2
  binary_yield_type := by
    intro X Y Z h
    exact h.2
  anchor_mem := by
    intro X
    exact Or.inl ⟨X, rfl⟩
  terminal_observation_mem := by
    intro X a h
    exact Or.inr (Or.inl ⟨X, a, h, rfl⟩)
  binary_observation_mem := by
    intro X Y Z h
    exact Or.inr (Or.inr (Or.inl ⟨X, Y, Z, h, rfl⟩))
  start_context := by
    intro X h
    exact (chosenContext_spec X).2 h
  epsilon_mem := by
    intro h
    exact Or.inr (Or.inr (Or.inr ⟨rfl, h⟩))

end FixedHCFGv44
end LeanCfgProject
