import LeanCfgProject.TCS1.FixedWindowContextPathBound
import LeanCfgProject.TCS1.YieldTypedRefinementCore

/-!
# TCS #1 v68: semantic dependency-path contexts

Lemma 7.2 bounds a reaching context by choosing a shortest path in the
child-dependency graph and expanding every off-path sibling by a short typed
yield. `FixedWindowContextPathBound` already verifies the finite path and
length arithmetic. This module supplies the missing derivation semantics.

A `ReachingSpine` records the root and target nonterminals, the terminal
left/right context around the target, the nonterminal labels on the chosen
dependency path, and one sibling-yield length for every binary step.

For every such object we prove that plugging any target derivation into the
recorded context gives a genuine root derivation, and that the total context
length is exactly the sum of the sibling lengths. Therefore a repetition-free
path with siblings bounded by B yields the manuscript estimate
|u|+|v| <= |V|*B.

The remaining graph-theoretic obligation is only existence of a shortest
repetition-free dependency path in the reduced typed grammar.
-/

namespace LeanCfgProject
namespace TCS1

universe u v

section FixedWindowContextSemantic

variable {N : Type u}
variable {α : Type v}

/--
A root-to-target dependency spine with terminal off-path siblings.

The word generated by the target will appear between `left` and `right`.
The path contains the root and target labels. The siblings list records the
terminal-yield length of each off-path sibling introduced at a binary step.
-/
inductive ReachingSpine
    (terminalRule : N → α → Prop)
    (binaryRule : N → N → N → Prop) :
    N → N → Word α → Word α → List N → List Nat → Prop
  | hole
      {A : N} :
      ReachingSpine terminalRule binaryRule
        A A [] [] [A] []
  | binaryLeft
      {A B C X : N}
      {left right z : Word α}
      {path : List N}
      {siblings : List Nat}
      (hbin : binaryRule A B C)
      (spine :
        ReachingSpine terminalRule binaryRule
          B X left right path siblings)
      (sibling :
        UntypedDerives terminalRule binaryRule C z) :
      ReachingSpine terminalRule binaryRule
        A X left (right ++ z)
        (A :: path) (z.length :: siblings)
  | binaryRight
      {A B C X : N}
      {left right y : Word α}
      {path : List N}
      {siblings : List Nat}
      (hbin : binaryRule A B C)
      (sibling :
        UntypedDerives terminalRule binaryRule B y)
      (spine :
        ReachingSpine terminalRule binaryRule
          C X left right path siblings) :
      ReachingSpine terminalRule binaryRule
        A X (y ++ left) right
        (A :: path) (y.length :: siblings)

/--
Plugging any derivation of the target into the recorded reaching spine gives a
valid derivation from the root.
-/
theorem reachingSpine_plug
    (terminalRule : N → α → Prop)
    (binaryRule : N → N → N → Prop)
    {A X : N}
    {left right w : Word α}
    {path : List N}
    {siblings : List Nat}
    (spine :
      ReachingSpine terminalRule binaryRule
        A X left right path siblings)
    (dX :
      UntypedDerives terminalRule binaryRule X w) :
    UntypedDerives terminalRule binaryRule
      A (left ++ w ++ right) := by
  induction spine with
  | hole =>
      simpa using dX
  | @binaryLeft A B C X left right z path siblings
      hbin spine sibling ih =>
      have dB :
          UntypedDerives terminalRule binaryRule
            B (left ++ w ++ right) :=
        ih dX
      have dA :
          UntypedDerives terminalRule binaryRule
            A ((left ++ w ++ right) ++ z) :=
        UntypedDerives.binary hbin dB sibling
      simpa only [List.append_assoc] using dA
  | @binaryRight A B C X left right y path siblings
      hbin sibling spine ih =>
      have dC :
          UntypedDerives terminalRule binaryRule
            C (left ++ w ++ right) :=
        ih dX
      have dA :
          UntypedDerives terminalRule binaryRule
            A (y ++ (left ++ w ++ right)) :=
        UntypedDerives.binary hbin sibling dC
      simpa only [List.append_assoc] using dA

/-- The terminal context consists exactly of the off-path sibling yields. -/
theorem reachingSpine_context_length_eq
    (terminalRule : N → α → Prop)
    (binaryRule : N → N → N → Prop)
    {A X : N}
    {left right : Word α}
    {path : List N}
    {siblings : List Nat}
    (spine :
      ReachingSpine terminalRule binaryRule
        A X left right path siblings) :
    left.length + right.length = siblings.sum := by
  induction spine with
  | hole =>
      simp
  | binaryLeft hbin spine sibling ih =>
      simp only [List.length_append, List.sum_cons]
      omega
  | binaryRight hbin sibling spine ih =>
      simp only [List.length_append, List.sum_cons]
      omega

/-- There is at most one recorded sibling per path vertex. -/
theorem reachingSpine_siblings_length_le_path
    (terminalRule : N → α → Prop)
    (binaryRule : N → N → N → Prop)
    {A X : N}
    {left right : Word α}
    {path : List N}
    {siblings : List Nat}
    (spine :
      ReachingSpine terminalRule binaryRule
        A X left right path siblings) :
    siblings.length ≤ path.length := by
  induction spine with
  | hole =>
      simp
  | binaryLeft hbin spine sibling ih =>
      simp only [List.length_cons]
      exact Nat.succ_le_succ ih
  | binaryRight hbin sibling spine ih =>
      simp only [List.length_cons]
      exact Nat.succ_le_succ ih

/--
If a label occurs on a repetition-free reaching spine, the suffix beginning
at that occurrence is itself a repetition-free reaching spine to the same
target. Uniform sibling-length bounds are inherited.
-/
theorem reachingSubspine_of_mem_of_nodup
    (terminalRule : N → α → Prop)
    (binaryRule : N → N → N → Prop)
    (bound : Nat)
    {A X Y : N}
    {left right : Word α}
    {path : List N}
    {siblings : List Nat}
    (spine :
      ReachingSpine terminalRule binaryRule
        A X left right path siblings)
    (hnodup : path.Nodup)
    (heach : ∀ s ∈ siblings, s ≤ bound)
    (hmem : Y ∈ path) :
    ∃ left' right' path' siblings',
      ReachingSpine terminalRule binaryRule
        Y X left' right' path' siblings'
      ∧ path'.Nodup
      ∧ (∀ s ∈ siblings', s ≤ bound) := by
  induction spine generalizing Y with
  | @hole A =>
      simp only [List.mem_singleton] at hmem
      subst Y
      exact
        ⟨[], [], [A], [],
          ReachingSpine.hole,
          by simp,
          by simp⟩
  | @binaryLeft A B C X left right z path siblings
      hbin child sibling ih =>
      rw [List.nodup_cons] at hnodup
      simp only [List.mem_cons] at hmem
      have htail : ∀ s ∈ siblings, s ≤ bound := by
        intro s hs
        exact heach s (List.mem_cons_of_mem _ hs)
      rcases hmem with hYA | hYtail
      · subst Y
        exact
          ⟨left, right ++ z, A :: path, z.length :: siblings,
            ReachingSpine.binaryLeft hbin child sibling,
            (by rw [List.nodup_cons]; exact hnodup),
            heach⟩
      · exact ih hnodup.2 htail hYtail
  | @binaryRight A B C X left right y path siblings
      hbin sibling child ih =>
      rw [List.nodup_cons] at hnodup
      simp only [List.mem_cons] at hmem
      have htail : ∀ s ∈ siblings, s ≤ bound := by
        intro s hs
        exact heach s (List.mem_cons_of_mem _ hs)
      rcases hmem with hYA | hYtail
      · subst Y
        exact
          ⟨y ++ left, right, A :: path, y.length :: siblings,
            ReachingSpine.binaryRight hbin sibling child,
            (by rw [List.nodup_cons]; exact hnodup),
            heach⟩
      · exact ih hnodup.2 htail hYtail

/--
For every reaching spine, the number of binary steps plus the target vertex is
exactly the path length.
-/
theorem reachingSpine_siblings_length_add_one_eq_path
    (terminalRule : N → α → Prop)
    (binaryRule : N → N → N → Prop)
    {A X : N}
    {left right : Word α}
    {path : List N}
    {siblings : List Nat}
    (spine :
      ReachingSpine terminalRule binaryRule
        A X left right path siblings) :
    siblings.length + 1 = path.length := by
  induction spine with
  | hole =>
      simp
  | binaryLeft hbin child sibling ih =>
      simp only [List.length_cons]
      omega
  | binaryRight hbin sibling child ih =>
      simp only [List.length_cons]
      omega

/--
Unbounded suffix extraction.  This is the structural version used when only
cycle elimination is needed, without carrying a numerical sibling bound.
-/
theorem reachingSubspine_of_mem_of_nodup_unbounded
    (terminalRule : N → α → Prop)
    (binaryRule : N → N → N → Prop)
    {A X Y : N}
    {left right : Word α}
    {path : List N}
    {siblings : List Nat}
    (spine :
      ReachingSpine terminalRule binaryRule
        A X left right path siblings)
    (hnodup : path.Nodup)
    (hmem : Y ∈ path) :
    ∃ left' right' path' siblings',
      ReachingSpine terminalRule binaryRule
        Y X left' right' path' siblings'
      ∧ path'.Nodup := by
  induction spine generalizing Y with
  | @hole A =>
      simp only [List.mem_singleton] at hmem
      subst Y
      exact
        ⟨[], [], [A], [],
          ReachingSpine.hole,
          by simp⟩
  | @binaryLeft A B C X left right z path siblings
      hbin child sibling ih =>
      rw [List.nodup_cons] at hnodup
      simp only [List.mem_cons] at hmem
      rcases hmem with hYA | hYtail
      · subst Y
        exact
          ⟨left, right ++ z, A :: path, z.length :: siblings,
            ReachingSpine.binaryLeft hbin child sibling,
            (by rw [List.nodup_cons]; exact hnodup)⟩
      · exact ih hnodup.2 hYtail
  | @binaryRight A B C X left right y path siblings
      hbin sibling child ih =>
      rw [List.nodup_cons] at hnodup
      simp only [List.mem_cons] at hmem
      rcases hmem with hYA | hYtail
      · subst Y
        exact
          ⟨y ++ left, right, A :: path, y.length :: siblings,
            ReachingSpine.binaryRight hbin sibling child,
            (by rw [List.nodup_cons]; exact hnodup)⟩
      · exact ih hnodup.2 hYtail

/--
Every reaching spine can be cycle-shortened to a repetition-free path, with
no quantitative hypothesis on sibling yields.
-/
theorem normalize_reachingSpine_to_nodup_unbounded
    (terminalRule : N → α → Prop)
    (binaryRule : N → N → N → Prop)
    {A X : N}
    {left right : Word α}
    {path : List N}
    {siblings : List Nat}
    (spine :
      ReachingSpine terminalRule binaryRule
        A X left right path siblings) :
    ∃ left' right' path' siblings',
      ReachingSpine terminalRule binaryRule
        A X left' right' path' siblings'
      ∧ path'.Nodup := by
  induction spine with
  | @hole A =>
      exact
        ⟨[], [], [A], [],
          ReachingSpine.hole,
          by simp⟩

  | @binaryLeft A B C X left right z path siblings
      hbin child sibling ih =>
      obtain ⟨left', right', path', siblings',
          child', hnodup⟩ := ih
      by_cases hmem : A ∈ path'
      · exact
          reachingSubspine_of_mem_of_nodup_unbounded
            terminalRule binaryRule
            child' hnodup hmem
      · exact
          ⟨left', right' ++ z, A :: path',
            z.length :: siblings',
            ReachingSpine.binaryLeft hbin child' sibling,
            (by rw [List.nodup_cons]; exact ⟨hmem, hnodup⟩)⟩

  | @binaryRight A B C X left right y path siblings
      hbin sibling child ih =>
      obtain ⟨left', right', path', siblings',
          child', hnodup⟩ := ih
      by_cases hmem : A ∈ path'
      · exact
          reachingSubspine_of_mem_of_nodup_unbounded
            terminalRule binaryRule
            child' hnodup hmem
      · exact
          ⟨y ++ left', right', A :: path',
            y.length :: siblings',
            ReachingSpine.binaryRight hbin sibling child',
            (by rw [List.nodup_cons]; exact ⟨hmem, hnodup⟩)⟩

/--
Cycle-shortening normalization for reaching spines.

Normalize the child spine first. If the current root label already occurs
below, jump directly to that lower occurrence; otherwise reattach the current
binary step. This is the semantic version of the manuscript's
"choose a shortest path, hence no typed symbol repeats" argument.
-/
theorem normalize_reachingSpine_to_nodup
    (terminalRule : N → α → Prop)
    (binaryRule : N → N → N → Prop)
    (bound : Nat)
    {A X : N}
    {left right : Word α}
    {path : List N}
    {siblings : List Nat}
    (spine :
      ReachingSpine terminalRule binaryRule
        A X left right path siblings)
    (heach : ∀ s ∈ siblings, s ≤ bound) :
    ∃ left' right' path' siblings',
      ReachingSpine terminalRule binaryRule
        A X left' right' path' siblings'
      ∧ path'.Nodup
      ∧ (∀ s ∈ siblings', s ≤ bound) := by
  induction spine with
  | @hole A =>
      exact
        ⟨[], [], [A], [],
          ReachingSpine.hole,
          by simp,
          by simp⟩

  | @binaryLeft A B C X left right z path siblings
      hbin child sibling ih =>
      have hhead : z.length ≤ bound :=
        heach z.length (List.mem_cons_self ..)
      have htail : ∀ s ∈ siblings, s ≤ bound := by
        intro s hs
        exact heach s (List.mem_cons_of_mem _ hs)
      obtain ⟨left', right', path', siblings',
          child', hnodup, heach'⟩ :=
        ih htail
      by_cases hmem : A ∈ path'
      · exact
          reachingSubspine_of_mem_of_nodup
            terminalRule binaryRule bound
            child' hnodup heach' hmem
      · refine
          ⟨left', right' ++ z, A :: path',
            z.length :: siblings',
            ReachingSpine.binaryLeft hbin child' sibling,
            ?_,
            ?_⟩
        · rw [List.nodup_cons]
          exact ⟨hmem, hnodup⟩
        · intro s hs
          simp only [List.mem_cons] at hs
          rcases hs with rfl | hs
          · exact hhead
          · exact heach' s hs

  | @binaryRight A B C X left right y path siblings
      hbin sibling child ih =>
      have hhead : y.length ≤ bound :=
        heach y.length (List.mem_cons_self ..)
      have htail : ∀ s ∈ siblings, s ≤ bound := by
        intro s hs
        exact heach s (List.mem_cons_of_mem _ hs)
      obtain ⟨left', right', path', siblings',
          child', hnodup, heach'⟩ :=
        ih htail
      by_cases hmem : A ∈ path'
      · exact
          reachingSubspine_of_mem_of_nodup
            terminalRule binaryRule bound
            child' hnodup heach' hmem
      · refine
          ⟨y ++ left', right', A :: path',
            y.length :: siblings',
            ReachingSpine.binaryRight hbin sibling child',
            ?_,
            ?_⟩
        · rw [List.nodup_cons]
          exact ⟨hmem, hnodup⟩
        · intro s hs
          simp only [List.mem_cons] at hs
          rcases hs with rfl | hs
          · exact hhead
          · exact heach' s hs

/--
Parameterized semantic form of the dependency-path context bound used by
Lemma 7.2.
-/
theorem reachingSpine_context_length_le
    [Fintype N] [DecidableEq N]
    (terminalRule : N → α → Prop)
    (binaryRule : N → N → N → Prop)
    {A X : N}
    {left right : Word α}
    {path : List N}
    {siblings : List Nat}
    (B : Nat)
    (spine :
      ReachingSpine terminalRule binaryRule
        A X left right path siblings)
    (hnodup : path.Nodup)
    (heach : ∀ s ∈ siblings, s ≤ B) :
    left.length + right.length ≤
      Fintype.card N * B := by
  have hcount :
      siblings.length ≤ Fintype.card N := by
    exact le_trans
      (reachingSpine_siblings_length_le_path
        terminalRule binaryRule spine)
      (dependency_path_vertices_le path hnodup)
  have hsum :
      siblings.sum ≤ Fintype.card N * B :=
    chainExpansion_sum_le
      siblings (Fintype.card N) B
      hcount heach
  rw [reachingSpine_context_length_eq
    terminalRule binaryRule spine]
  exact hsum

/--
Any reaching spine whose off-path siblings are uniformly B-bounded can be
cycle-shortened to a repetition-free reaching spine with a concrete context
of length at most |V|*B.  Thus the shortest-path step of Lemma 7.2 is no
longer an external combinatorial assumption once a reaching spine exists.
-/
theorem reachingSpine_nodup_context_exists
    [Fintype N] [DecidableEq N]
    (terminalRule : N → α → Prop)
    (binaryRule : N → N → N → Prop)
    {A X : N}
    {left right : Word α}
    {path : List N}
    {siblings : List Nat}
    (B : Nat)
    (spine :
      ReachingSpine terminalRule binaryRule
        A X left right path siblings)
    (heach : ∀ s ∈ siblings, s ≤ B) :
    ∃ left' right' path' siblings',
      ReachingSpine terminalRule binaryRule
        A X left' right' path' siblings'
      ∧ path'.Nodup
      ∧ (∀ s ∈ siblings', s ≤ B)
      ∧ left'.length + right'.length ≤
          Fintype.card N * B := by
  obtain ⟨left', right', path', siblings',
      spine', hnodup, heach'⟩ :=
    normalize_reachingSpine_to_nodup
      terminalRule binaryRule B spine heach
  refine
    ⟨left', right', path', siblings',
      spine', hnodup, heach', ?_⟩
  exact
    reachingSpine_context_length_le
      terminalRule binaryRule B
      spine' hnodup heach'

/--
Semantic reaching-context theorem in the form used by Lemma 7.2.

Given any structurally reaching spine and any derivation from the target, cycle
shortening produces another terminal context whose total length is at most
|V|*B and into which the target derivation can be plugged successfully.
-/
theorem reachingSpine_short_context_for_derivation
    [Fintype N] [DecidableEq N]
    (terminalRule : N → α → Prop)
    (binaryRule : N → N → N → Prop)
    {A X : N}
    {left right w : Word α}
    {path : List N}
    {siblings : List Nat}
    (B : Nat)
    (spine :
      ReachingSpine terminalRule binaryRule
        A X left right path siblings)
    (heach : ∀ s ∈ siblings, s ≤ B)
    (dX :
      UntypedDerives terminalRule binaryRule X w) :
    ∃ left' right' : Word α,
      UntypedDerives terminalRule binaryRule
        A (left' ++ w ++ right')
      ∧
      left'.length + right'.length ≤
        Fintype.card N * B := by
  obtain ⟨left', right', path', siblings',
      spine', hnodup, heach', hlen⟩ :=
    reachingSpine_nodup_context_exists
      terminalRule binaryRule B spine heach
  exact
    ⟨left', right',
      reachingSpine_plug
        terminalRule binaryRule spine' dX,
      hlen⟩

/--
Paper-facing version with an external bound Nt on the number of typed
nonterminals.
-/
theorem reachingSpine_context_length_le_Nt
    [Fintype N] [DecidableEq N]
    (terminalRule : N → α → Prop)
    (binaryRule : N → N → N → Prop)
    {A X : N}
    {left right : Word α}
    {path : List N}
    {siblings : List Nat}
    (B Nt : Nat)
    (spine :
      ReachingSpine terminalRule binaryRule
        A X left right path siblings)
    (hnodup : path.Nodup)
    (heach : ∀ s ∈ siblings, s ≤ B)
    (hNt : Fintype.card N ≤ Nt) :
    left.length + right.length ≤ Nt * B := by
  have h0 :
      left.length + right.length ≤
        Fintype.card N * B :=
    reachingSpine_context_length_le
      terminalRule binaryRule B spine hnodup heach
  exact le_trans h0 (Nat.mul_le_mul_right B hNt)

/--
A concrete reaching spine together with a target derivation therefore supplies
both the target word in context and the quantitative context bound.
-/
theorem reachingSpine_plug_with_bound
    [Fintype N] [DecidableEq N]
    (terminalRule : N → α → Prop)
    (binaryRule : N → N → N → Prop)
    {A X : N}
    {left right w : Word α}
    {path : List N}
    {siblings : List Nat}
    (B : Nat)
    (spine :
      ReachingSpine terminalRule binaryRule
        A X left right path siblings)
    (hnodup : path.Nodup)
    (heach : ∀ s ∈ siblings, s ≤ B)
    (dX :
      UntypedDerives terminalRule binaryRule X w) :
    UntypedDerives terminalRule binaryRule
        A (left ++ w ++ right)
      ∧
    left.length + right.length ≤ Fintype.card N * B := by
  constructor
  · exact
      reachingSpine_plug
        terminalRule binaryRule spine dX
  · exact
      reachingSpine_context_length_le
        terminalRule binaryRule B spine hnodup heach

end FixedWindowContextSemantic

end TCS1
end LeanCfgProject
