import LeanCfgProject.TCS1.LinearSeparatorExample

/-!
# TCS #1 v78: exact semantics of the displayed linear grammar for L_{±,e}

This file formalizes the four displayed productions

  S -> U_ev | U_e
  U_ev -> c | a U_odd b
  U_odd -> d | a U_ev b
  U_e -> e | a U_e b

at the non-start level.  The start language is the union of the languages of
U_ev and U_e.  The main theorem proves that this grammar generates exactly
L_{±,e}.
-/

namespace LeanCfgProject
namespace TCS1

open LpmSymbol

inductive LpmLinearNT where
  | ev
  | odd
  | ee
  deriving DecidableEq, Fintype, Repr

/-- Derivation relation for the three non-start symbols of the displayed grammar. -/
inductive LpmLinearDerives :
    LpmLinearNT → Word LpmSymbol → Prop
  | ev_c :
      LpmLinearDerives .ev [c]
  | ev_wrap_odd
      {w : Word LpmSymbol}
      (d : LpmLinearDerives .odd w) :
      LpmLinearDerives .ev
        (a :: w ++ [b])
  | odd_d :
      LpmLinearDerives .odd [d]
  | odd_wrap_ev
      {w : Word LpmSymbol}
      (d : LpmLinearDerives .ev w) :
      LpmLinearDerives .odd
        (a :: w ++ [b])
  | ee_e :
      LpmLinearDerives .ee [e]
  | ee_wrap
      {w : Word LpmSymbol}
      (d : LpmLinearDerives .ee w) :
      LpmLinearDerives .ee
        (a :: w ++ [b])

/-- The start symbol chooses U_ev or U_e. -/
def LpmDisplayedLinearLanguage :
    Set (Word LpmSymbol) :=
  { w |
      LpmLinearDerives .ev w ∨
      LpmLinearDerives .ee w }

@[simp] theorem lpmCore_succ
    (n : Nat) (z : LpmSymbol) :
    a :: lpmCore n z ++ [b] =
      lpmCore (n + 1) z := by
  simp [lpmCore, List.replicate_succ,
    List.replicate_succ', List.append_assoc]

/-- Closed-form language generated by each displayed nonterminal. -/
def LpmLinearShape :
    LpmLinearNT → Word LpmSymbol → Prop
  | .ev, w =>
      (∃ m : Nat, w = lpmCore (2 * m) c) ∨
      (∃ m : Nat, w = lpmCore (2 * m + 1) d)
  | .odd, w =>
      (∃ m : Nat, w = lpmCore (2 * m) d) ∨
      (∃ m : Nat, w = lpmCore (2 * m + 1) c)
  | .ee, w =>
      ∃ n : Nat, w = lpmCore n e

/-- Every derivation of the displayed grammar has the expected closed form. -/
theorem lpmLinearDerives_shape
    {A : LpmLinearNT}
    {w : Word LpmSymbol}
    (d : LpmLinearDerives A w) :
    LpmLinearShape A w := by
  induction d with
  | ev_c =>
      exact Or.inl ⟨0, by simp [lpmCore]⟩
  | @ev_wrap_odd w der ih =>
      change
        (∃ m, a :: w ++ [b] =
            lpmCore (2 * m) c) ∨
        (∃ m, a :: w ++ [b] =
            lpmCore (2 * m + 1) d)
      change
        (∃ m, w = lpmCore (2 * m) d) ∨
        (∃ m, w = lpmCore (2 * m + 1) c) at ih
      rcases ih with ⟨m, rfl⟩ | ⟨m, rfl⟩
      · exact Or.inr ⟨m, by simp; congr 1; omega⟩
      · refine Or.inl ⟨m + 1, ?_⟩
        simp
        congr 1
        omega
  | odd_d =>
      exact Or.inl ⟨0, by simp [lpmCore]⟩
  | @odd_wrap_ev w der ih =>
      change
        (∃ m, a :: w ++ [b] =
            lpmCore (2 * m) d) ∨
        (∃ m, a :: w ++ [b] =
            lpmCore (2 * m + 1) c)
      change
        (∃ m, w = lpmCore (2 * m) c) ∨
        (∃ m, w = lpmCore (2 * m + 1) d) at ih
      rcases ih with ⟨m, rfl⟩ | ⟨m, rfl⟩
      · exact Or.inr ⟨m, by simp; congr 1; omega⟩
      · refine Or.inl ⟨m + 1, ?_⟩
        simp
        congr 1
        omega
  | ee_e =>
      exact ⟨0, by simp [lpmCore]⟩
  | @ee_wrap w der ih =>
      change ∃ n, a :: w ++ [b] = lpmCore n e
      rcases ih with ⟨n, rfl⟩
      exact ⟨n + 1, by simp⟩

/-- Even-depth c derivations from U_ev. -/
theorem lpmLinearDerives_ev_c
    (m : Nat) :
    LpmLinearDerives .ev
      (lpmCore (2 * m) c) := by
  induction m with
  | zero =>
      simpa [lpmCore] using
        LpmLinearDerives.ev_c
  | succ m ih =>
      have hodd :
          LpmLinearDerives .odd
            (lpmCore (2 * m + 1) c) := by
        have := LpmLinearDerives.odd_wrap_ev ih
        simpa using this
      have hev :=
        LpmLinearDerives.ev_wrap_odd hodd
      simpa using hev

/-- Odd-depth d derivations from U_ev. -/
theorem lpmLinearDerives_ev_d
    (m : Nat) :
    LpmLinearDerives .ev
      (lpmCore (2 * m + 1) d) := by
  induction m with
  | zero =>
      have h :=
        LpmLinearDerives.ev_wrap_odd
          LpmLinearDerives.odd_d
      simpa [lpmCore] using h
  | succ m ih =>
      have hodd :
          LpmLinearDerives .odd
            (lpmCore (2 * m + 2) d) := by
        have := LpmLinearDerives.odd_wrap_ev ih
        simpa using this
      have hev :=
        LpmLinearDerives.ev_wrap_odd hodd
      simpa using hev

/-- Every balanced e-word is generated from U_e. -/
theorem lpmLinearDerives_ee
    (n : Nat) :
    LpmLinearDerives .ee
      (lpmCore n e) := by
  induction n with
  | zero =>
      simpa [lpmCore] using
        LpmLinearDerives.ee_e
  | succ n ih =>
      have h :=
        LpmLinearDerives.ee_wrap ih
      simpa [Nat.add_comm] using h

/-- Exact generated-language theorem for the displayed linear grammar. -/
theorem lpm_displayed_linear_language_eq :
    LpmDisplayedLinearLanguage =
      LpmLanguage := by
  apply Set.ext
  intro w
  constructor
  · intro hw
    rcases hw with hev | hee
    · have hs :=
        lpmLinearDerives_shape hev
      change
        (∃ m, w = lpmCore (2 * m) c) ∨
        (∃ m, w = lpmCore (2 * m + 1) d) at hs
      rcases hs with ⟨m, rfl⟩ | ⟨m, rfl⟩
      · exact
          (lpmCore_mem_iff (2 * m) c).2
            (by simp [LpmAccepted])
      · exact
          (lpmCore_mem_iff (2 * m + 1) d).2
            (by simp [LpmAccepted])
    · have hs :=
        lpmLinearDerives_shape hee
      change ∃ n, w = lpmCore n e at hs
      rcases hs with ⟨n, rfl⟩
      exact lpm_e_mem n
  · rintro ⟨n, z, rfl, hacc⟩
    cases z with
    | a =>
        simp [LpmAccepted] at hacc
    | b =>
        simp [LpmAccepted] at hacc
    | c =>
        left
        have hpar : n % 2 = 0 := by
          simpa [LpmAccepted] using hacc
        have hn :
            n = 2 * (n / 2) := by
          omega
        rw [hn]
        exact lpmLinearDerives_ev_c (n / 2)
    | d =>
        left
        have hpar : n % 2 = 1 := by
          simpa [LpmAccepted] using hacc
        have hn :
            n = 2 * (n / 2) + 1 := by
          omega
        rw [hn]
        exact lpmLinearDerives_ev_d (n / 2)
    | e =>
        right
        exact lpmLinearDerives_ee n

end TCS1
end LeanCfgProject
