import LeanCfgProject.ObservedResidualConcept.ObservedSyntacticQuotientPaperSummary
set_option linter.unusedVariables false
set_option linter.unusedTactic false
set_option linter.unusedSimpArgs false
set_option linter.unusedSectionVars false

namespace LeanCfgProject

universe u

/-
ObservedSyntacticConcreteQuotient.lean

Theorem-body experiment.

Purpose:
  construct the concrete quotient type by SameObservedSyntactic S and install
  its multiplication, monoid law, projection map, exact kernel theorem, and
  projection homomorphism theorem.

This file is meant to turn the paper's "actual quotient-monoid specialization"
target from a future target into a checked theorem-body layer.
-/

variable {Q : Type u} [Monoid Q]

/-- The setoid generated by the observed syntactic congruence. -/
def observedSyntacticSetoid (S : Set Q) : Setoid Q where
  r x y := SameObservedSyntactic S x y
  iseqv := by
    refine ⟨?refl, ?symm, ?trans⟩
    · intro x a b
      rfl
    · intro x y hxy a b
      exact (hxy a b).symm
    · intro x y z hxy hyz a b
      exact (hxy a b).trans (hyz a b)

/-- The concrete observed syntactic quotient type. -/
abbrev ObservedSyntacticQuotient (S : Set Q) :=
  Quotient (observedSyntacticSetoid (Q := Q) S)

/-- The quotient projection. -/
def observedSyntacticQuotientMap (S : Set Q) :
    Q → ObservedSyntacticQuotient (Q := Q) S :=
  fun x => Quotient.mk (observedSyntacticSetoid (Q := Q) S) x

/-- Compatibility of multiplication with SameObservedSyntactic. -/
theorem sameObservedSyntactic_mul_compat
    (S : Set Q)
    {x x' y y' : Q}
    (hx : SameObservedSyntactic S x x')
    (hy : SameObservedSyntactic S y y') :
    SameObservedSyntactic S (x * y) (x' * y') := by
  intro a b
  calc
    a * (x * y) * b ∈ S
        ↔ (a * x) * y * b ∈ S := by
          simp [mul_assoc]
    _   ↔ (a * x) * y' * b ∈ S := by
          exact hy (a * x) b
    _   ↔ a * x * (y' * b) ∈ S := by
          simp [mul_assoc]
    _   ↔ a * x' * (y' * b) ∈ S := by
          exact hx a (y' * b)
    _   ↔ a * (x' * y') * b ∈ S := by
          simp [mul_assoc]

/-- Multiplication on the concrete observed syntactic quotient. -/
protected def ObservedSyntacticQuotient.mul
    (S : Set Q) :
    ObservedSyntacticQuotient (Q := Q) S →
    ObservedSyntacticQuotient (Q := Q) S →
    ObservedSyntacticQuotient (Q := Q) S :=
  Quotient.lift₂
    (fun x y => observedSyntacticQuotientMap (Q := Q) S (x * y))
    (by
      intro a b c d hac hbd
      apply Quotient.sound
      exact sameObservedSyntactic_mul_compat S hac hbd)

/-- The unit on the concrete observed syntactic quotient. -/
protected def ObservedSyntacticQuotient.one
    (S : Set Q) :
    ObservedSyntacticQuotient (Q := Q) S :=
  observedSyntacticQuotientMap (Q := Q) S 1

instance observedSyntacticQuotientMonoid
    (S : Set Q) :
    Monoid (ObservedSyntacticQuotient (Q := Q) S) where
  one := ObservedSyntacticQuotient.one (Q := Q) S
  mul := ObservedSyntacticQuotient.mul (Q := Q) S
  mul_assoc := by
    intro x y z
    refine Quotient.inductionOn₃ x y z ?_
    intro a b c
    change
      observedSyntacticQuotientMap (Q := Q) S ((a * b) * c)
        =
      observedSyntacticQuotientMap (Q := Q) S (a * (b * c))
    rw [mul_assoc]
  one_mul := by
    intro x
    refine Quotient.inductionOn x ?_
    intro a
    change
      observedSyntacticQuotientMap (Q := Q) S (1 * a)
        =
      observedSyntacticQuotientMap (Q := Q) S a
    rw [one_mul]
  mul_one := by
    intro x
    refine Quotient.inductionOn x ?_
    intro a
    change
      observedSyntacticQuotientMap (Q := Q) S (a * 1)
        =
      observedSyntacticQuotientMap (Q := Q) S a
    rw [mul_one]

@[simp]
theorem observedSyntacticQuotient_mk_mul_mk
    (S : Set Q) (x y : Q) :
    (observedSyntacticQuotientMap (Q := Q) S x)
      *
    (observedSyntacticQuotientMap (Q := Q) S y)
      =
    observedSyntacticQuotientMap (Q := Q) S (x * y) := by
  rfl

@[simp]
theorem observedSyntacticQuotient_mk_one
    (S : Set Q) :
    observedSyntacticQuotientMap (Q := Q) S (1 : Q)
      =
    (1 : ObservedSyntacticQuotient (Q := Q) S) := by
  rfl

/--
The quotient projection is multiplicative.
-/
theorem observedSyntacticQuotientMap_mul
    (S : Set Q) (x y : Q) :
    observedSyntacticQuotientMap (Q := Q) S (x * y)
      =
    observedSyntacticQuotientMap (Q := Q) S x
      *
    observedSyntacticQuotientMap (Q := Q) S y := by
  rfl

/--
The quotient projection preserves the unit.
-/
theorem observedSyntacticQuotientMap_one
    (S : Set Q) :
    observedSyntacticQuotientMap (Q := Q) S (1 : Q)
      =
    (1 : ObservedSyntacticQuotient (Q := Q) S) := by
  rfl

/-- The quotient projection is surjective. -/
theorem observedSyntacticQuotientMap_surjective
    (S : Set Q) :
    ∀ y : ObservedSyntacticQuotient (Q := Q) S,
      ∃ x : Q, observedSyntacticQuotientMap (Q := Q) S x = y := by
  intro y
  refine Quotient.inductionOn y ?_
  intro x
  exact ⟨x, rfl⟩

/-- The kernel of the concrete quotient projection is exactly SameObservedSyntactic. -/
theorem observedSyntacticQuotientMap_kernel
    (S : Set Q) (x y : Q) :
    observedSyntacticQuotientMap (Q := Q) S x
      =
    observedSyntacticQuotientMap (Q := Q) S y
      ↔
    SameObservedSyntactic S x y := by
  constructor
  · intro h
    exact Quotient.exact h
  · intro h
    exact Quotient.sound h

/--
The concrete quotient projection is an exact observed quotient map in the sense
used by the abstract exact quotient-map layer.
-/
theorem observedSyntacticQuotientMap_exact_package
    (S : Set Q) :
    (∀ x y : Q,
      observedSyntacticQuotientMap (Q := Q) S (x * y)
        =
      observedSyntacticQuotientMap (Q := Q) S x
        *
      observedSyntacticQuotientMap (Q := Q) S y)
      ∧
    observedSyntacticQuotientMap (Q := Q) S (1 : Q)
      =
    (1 : ObservedSyntacticQuotient (Q := Q) S)
      ∧
    (∀ y : ObservedSyntacticQuotient (Q := Q) S,
      ∃ x : Q, observedSyntacticQuotientMap (Q := Q) S x = y)
      ∧
    (∀ x y : Q,
      observedSyntacticQuotientMap (Q := Q) S x
        =
      observedSyntacticQuotientMap (Q := Q) S y
        ↔
      SameObservedSyntactic S x y) := by
  constructor
  · intro x y
    exact observedSyntacticQuotientMap_mul (Q := Q) S x y
  constructor
  · exact observedSyntacticQuotientMap_one (Q := Q) S
  constructor
  · exact observedSyntacticQuotientMap_surjective (Q := Q) S
  · intro x y
    exact observedSyntacticQuotientMap_kernel (Q := Q) S x y

end LeanCfgProject
