import LeanCfgProject.ObservedResidualConcept.PointFrameCorollaries
set_option linter.unusedVariables false
set_option linter.unusedTactic false
set_option linter.unusedSimpArgs false

namespace LeanCfgProject

universe u v

/-
ReducedFrameModelCoreDefs.lean

A lightweight Lean definition layer for the reduced-frame-model viewpoint.
The full lattice-isomorphism theorem is intentionally left to a later module.
This file records the model interface and the canonical model generated by the
already checked incidence theorem.
-/

variable (Q : Type u) [Mul Q] (S : Set Q)

/-- A faithful point-frame representation of the two-sided incidence. -/
structure FrameModelCore where
  Carrier : Type v
  le : Carrier → Carrier → Prop
  pt : Q → Carrier
  fr : Q → Q → Carrier
  incidence :
    ∀ gamma a b : Q,
      le (pt gamma) (fr a b) ↔ a * gamma * b ∈ S

namespace FrameModelCore

variable {Q : Type u} [Mul Q] {S : Set Q}

/-- The set of points below a model element. -/
def extent (M : FrameModelCore Q S) (c : M.Carrier) : Set Q :=
  {gamma : Q | M.le (M.pt gamma) c}

/-- A model homomorphism preserving points and frames. -/
structure Hom (M N : FrameModelCore Q S) where
  map : M.Carrier → N.Carrier
  preserves_points : ∀ gamma : Q, map (M.pt gamma) = N.pt gamma
  preserves_frames : ∀ a b : Q, map (M.fr a b) = N.fr a b

theorem extent_frame_eq_residual
    (M : FrameModelCore Q S) (a b : Q) :
    M.extent (M.fr a b) = TwoSidedResidual S a b := by
  ext gamma
  exact M.incidence gamma a b

end FrameModelCore

/-- The canonical model whose carrier is the residual concept universe. -/
def canonicalFrameModelCore :
    FrameModelCore Q S where
  Carrier := Set Q
  le := fun A B => A ⊆ B
  pt := CanonicalPoint S
  fr := CanonicalFrame S
  incidence := by
    intro gamma a b
    exact canonicalPoint_subset_frame_iff S gamma a b

theorem canonicalFrameModelCore_extent_frame
    (a b : Q) :
    (canonicalFrameModelCore Q S).extent
        ((canonicalFrameModelCore Q S).fr a b)
      =
    TwoSidedResidual S a b := by
  exact FrameModelCore.extent_frame_eq_residual
    (canonicalFrameModelCore Q S) a b

theorem canonicalFrameModelCore_point_collapse
    (x y : Q) :
    (canonicalFrameModelCore Q S).pt x =
      (canonicalFrameModelCore Q S).pt y
    ↔ SameObservedSyntactic S x y := by
  exact canonicalPoint_eq_iff_sameObservedSyntactic S x y

theorem canonicalFrameModelCore_summary :
    (∀ gamma a b : Q,
      (canonicalFrameModelCore Q S).le
        ((canonicalFrameModelCore Q S).pt gamma)
        ((canonicalFrameModelCore Q S).fr a b)
        ↔ a * gamma * b ∈ S)
    ∧
    (∀ x y : Q,
      (canonicalFrameModelCore Q S).pt x =
        (canonicalFrameModelCore Q S).pt y
        ↔ SameObservedSyntactic S x y) := by
  constructor
  · intro gamma a b
    exact (canonicalFrameModelCore Q S).incidence gamma a b
  · intro x y
    exact canonicalFrameModelCore_point_collapse Q S x y

end LeanCfgProject
