import LeanCfgProject.FrameAdequacyCriterion

set_option linter.unusedVariables false
set_option linter.unusedTactic false
set_option linter.unusedSimpArgs false

namespace LeanCfgProject

universe u

/-
ObservedSyntacticConcept.lean

This file starts the v25.1 canonical-object layer.

This v2 removes unsafe local reducibility attributes rejected by Lean 4.31.
All definitional unfolding is handled explicitly in the proofs instead.

It formalizes the observed syntactic congruence of a monoid subset `(Q,S)` and
proves the core residual-concept facts that are independent of any grammar
presentation:

* observed syntactic equivalence is an equivalence relation;
* concept closures are saturated under observed syntactic equivalence;
* two-sided residuals are saturated under observed syntactic equivalence;
* every two-sided residual is already concept-closed;
* if a residual is contained in a single observed syntactic block, then every
  nonempty subset of that residual generates the whole residual by concept
  closure.

This is the Lean counterpart of the new v25.1 "observed syntactic concept
object" and "syntactic-block adequacy" paper layer.
-/

variable {Q : Type u} [Mul Q]

/--
The observed two-sided syntactic equivalence induced by a subset `S ⊆ Q`.

Two elements are equivalent when all two-sided `S`-membership tests agree.
-/
def SameObservedSyntactic (S : Set Q) (x y : Q) : Prop :=
  ∀ a b : Q, a * x * b ∈ S ↔ a * y * b ∈ S

/-- Reflexivity of observed syntactic equivalence. -/
theorem sameObservedSyntactic_refl
    (S : Set Q) (x : Q) :
    SameObservedSyntactic S x x := by
  intro a b
  rfl

/-- Symmetry of observed syntactic equivalence. -/
theorem sameObservedSyntactic_symm
    {S : Set Q} {x y : Q}
    (hxy : SameObservedSyntactic S x y) :
    SameObservedSyntactic S y x := by
  intro a b
  exact (hxy a b).symm

/-- Transitivity of observed syntactic equivalence. -/
theorem sameObservedSyntactic_trans
    {S : Set Q} {x y z : Q}
    (hxy : SameObservedSyntactic S x y)
    (hyz : SameObservedSyntactic S y z) :
    SameObservedSyntactic S x z := by
  intro a b
  exact Iff.trans (hxy a b) (hyz a b)

/--
Membership in any residual concept closure is saturated by the observed
syntactic equivalence.
-/
theorem sameObservedSyntactic_conceptClosure_mem_iff
    (S U : Set Q) {x y : Q}
    (hxy : SameObservedSyntactic S x y) :
    x ∈ ConceptClosure S U ↔ y ∈ ConceptClosure S U := by
  constructor
  · intro hx ab hab
    exact (hxy ab.1 ab.2).mp (hx ab hab)
  · intro hy ab hab
    exact (hxy ab.1 ab.2).mpr (hy ab hab)

/--
Forward form: concept closures are unions of observed syntactic blocks.
-/
theorem conceptClosure_saturated_under_sameObservedSyntactic
    (S U : Set Q) {x y : Q}
    (hxy : SameObservedSyntactic S x y)
    (hx : x ∈ ConceptClosure S U) :
    y ∈ ConceptClosure S U :=
  (sameObservedSyntactic_conceptClosure_mem_iff S U hxy).mp hx

/--
Membership in a two-sided residual is saturated by the observed syntactic
equivalence.
-/
theorem sameObservedSyntactic_residual_mem_iff
    (S : Set Q) (a b : Q) {x y : Q}
    (hxy : SameObservedSyntactic S x y) :
    x ∈ TwoSidedResidual S a b ↔ y ∈ TwoSidedResidual S a b := by
  simpa [TwoSidedResidual] using hxy a b

/--
Forward form: each two-sided residual is a union of observed syntactic blocks.
-/
theorem twoSidedResidual_saturated_under_sameObservedSyntactic
    (S : Set Q) (a b : Q) {x y : Q}
    (hxy : SameObservedSyntactic S x y)
    (hx : x ∈ TwoSidedResidual S a b) :
    y ∈ TwoSidedResidual S a b :=
  (sameObservedSyntactic_residual_mem_iff S a b hxy).mp hx

/--
A two-sided residual is already closed for the residual concept closure.

This is the formal core of the "canonical residual closure system" viewpoint:
frame residuals are concept extents.
-/
theorem conceptClosure_twoSidedResidual_eq
    (S : Set Q) (a b : Q) :
    ConceptClosure S (TwoSidedResidual S a b) =
      TwoSidedResidual S a b := by
  apply Set.Subset.antisymm
  · intro gamma hgamma
    have hab :
        (a, b) ∈ CommonContexts S (TwoSidedResidual S a b) := by
      intro delta hdelta
      simpa [TwoSidedResidual] using hdelta
    simpa [TwoSidedResidual] using hgamma (a, b) hab
  · exact subset_conceptClosure S (TwoSidedResidual S a b)

/--
Concept closure as the intersection of all common two-sided residuals.

This is a concrete form of the statement that closed extents are generated by
two-sided residual tests.
-/
theorem conceptClosure_eq_commonResidualIntersection
    (S U : Set Q) :
    ConceptClosure S U =
      { gamma : Q |
        ∀ ab : Q × Q,
          ab ∈ CommonContexts S U →
            gamma ∈ TwoSidedResidual S ab.1 ab.2 } := by
  apply Set.ext
  intro gamma
  constructor
  · intro hgamma ab hab
    simpa [TwoSidedResidual] using hgamma ab hab
  · intro hgamma ab hab
    simpa [TwoSidedResidual] using hgamma ab hab

/--
A context `(a,b)` common for `U` is exactly the same as the inclusion
`U ⊆ Res_S(a,b)`.
-/
theorem commonContext_iff_subset_residual
    (S U : Set Q) (a b : Q) :
    (a, b) ∈ CommonContexts S U ↔
      U ⊆ TwoSidedResidual S a b := by
  constructor
  · intro hcommon gamma hgamma
    simpa [TwoSidedResidual] using hcommon gamma hgamma
  · intro hsub gamma hgamma
    simpa [TwoSidedResidual] using hsub hgamma

/--
Single-block adequacy, pointed version.

If a residual is contained in the observed syntactic block of one element `u0`,
and `U` is a nonempty subset of that residual containing `u0`, then `U`
generates the whole residual by concept closure.
-/
theorem conceptClosure_eq_residual_of_subset_singleBlock
    (S U : Set Q) (a b u0 : Q)
    (hU : U ⊆ TwoSidedResidual S a b)
    (hu0 : u0 ∈ U)
    (hblock :
      ∀ rho : Q,
        rho ∈ TwoSidedResidual S a b →
          SameObservedSyntactic S rho u0) :
    ConceptClosure S U = TwoSidedResidual S a b := by
  apply Set.Subset.antisymm
  · intro gamma hgamma
    have hab : (a, b) ∈ CommonContexts S U := by
      exact (commonContext_iff_subset_residual S U a b).mpr hU
    simpa [TwoSidedResidual] using hgamma (a, b) hab
  · intro rho hrho
    intro ab hab
    have hu0S : ab.1 * u0 * ab.2 ∈ S := hab u0 hu0
    exact ((hblock rho hrho) ab.1 ab.2).mpr hu0S

/--
Single-block adequacy, pairwise-block version.

If all elements of the residual lie in one observed syntactic block and `U` is
a nonempty subset of the residual, then `U` generates the whole residual by
concept closure.
-/
theorem conceptClosure_eq_residual_of_nonempty_subset_pairwiseBlock
    (S U : Set Q) (a b : Q)
    (hU : U ⊆ TwoSidedResidual S a b)
    (hne : ∃ u0 : Q, u0 ∈ U)
    (hblock :
      ∀ x y : Q,
        x ∈ TwoSidedResidual S a b →
        y ∈ TwoSidedResidual S a b →
          SameObservedSyntactic S x y) :
    ConceptClosure S U = TwoSidedResidual S a b := by
  rcases hne with ⟨u0, hu0⟩
  exact conceptClosure_eq_residual_of_subset_singleBlock
    S U a b u0 hU hu0
    (fun rho hrho => hblock rho u0 hrho (hU hu0))

/--
Coverage form of single-block adequacy.

Under the same single-block hypotheses, the residual is covered by the concept
closure of every nonempty subset of it.
-/
theorem residual_subset_conceptClosure_of_nonempty_subset_pairwiseBlock
    (S U : Set Q) (a b : Q)
    (hU : U ⊆ TwoSidedResidual S a b)
    (hne : ∃ u0 : Q, u0 ∈ U)
    (hblock :
      ∀ x y : Q,
        x ∈ TwoSidedResidual S a b →
        y ∈ TwoSidedResidual S a b →
          SameObservedSyntactic S x y) :
    TwoSidedResidual S a b ⊆ ConceptClosure S U := by
  rw [conceptClosure_eq_residual_of_nonempty_subset_pairwiseBlock
    S U a b hU hne hblock]

/--
Nonempty residuals contained in a single observed syntactic block are exactly
generated by any nonempty sound state image inside them.

This is the statement closest to the v25.1 paper theorem
"Syntactic-block adequacy".
-/
theorem syntacticBlockAdequacy
    (S U : Set Q) (a b : Q)
    (hU : U ⊆ TwoSidedResidual S a b)
    (hne : ∃ u0 : Q, u0 ∈ U)
    (hblock :
      ∀ x y : Q,
        x ∈ TwoSidedResidual S a b →
        y ∈ TwoSidedResidual S a b →
          SameObservedSyntactic S x y) :
    ConceptClosure S U = TwoSidedResidual S a b :=
  conceptClosure_eq_residual_of_nonempty_subset_pairwiseBlock
    S U a b hU hne hblock

end LeanCfgProject
