import LeanCfgProject.ObservedSyntacticQuotientPaperSummary

set_option linter.unusedVariables false
set_option linter.unusedTactic false
set_option linter.unusedSimpArgs false
set_option linter.unusedSectionVars false

namespace LeanCfgProject

universe u

/-
ObservedSyntacticConcreteQuotient.lean

Theorem-body experiment.

Purpose:
  construct the concrete quotient type by SameObservedSyntactic S and install
  its multiplication, semigroup law, projection map, exact kernel theorem, and
  projection homomorphism theorem.

This file is meant to turn the paper's actual quotient-monoid specialization
into a checked theorem-body layer.
-/

variable {Q : Type u} [Monoid Q]

/-- The setoid generated by the observed syntactic congruence. -/
def observedSyntacticSetoid (S : Set Q) : Setoid Q where
  r x y := SameObservedSyntactic S x y
  iseqv := by
    refine ⟨?refl, ?symm, ?trans⟩
    · intro x
      intro a b
      rfl
    · intro x y hxy
      intro a b
      exact (hxy a b).symm
    · intro x y z hxy hyz
      intro a b
      exact (hxy a b).trans (hyz a b)

/-- The concrete observed syntactic quotient type. -/
abbrev ObservedSyntacticQuotient (S : Set Q) :=
  Quotient (observedSyntacticSetoid (Q := Q) S)

/-- The quotient projection. -/
def observedSyntacticQuotientMap (S : Set Q) :
    Q → ObservedSyntacticQuotient (Q := Q) S :=
  fun x => Quotient.mk (observedSyntacticSetoid (Q := Q) S) x

/-- Compatibility of multiplication with SameObservedSyntactic. -/
theorem sameObservedSyntactic_mul_compat
    (S : Set Q)
    {x x' y y' : Q}
    (hx : SameObservedSyntactic S x x')
    (hy : SameObservedSyntactic S y y') :
    SameObservedSyntactic S (x * y) (x' * y') := by
  intro a b
  calc
    a * (x * y) * b ∈ S
        ↔ (a * x) * y * b ∈ S := by
          simp [mul_assoc]
    _   ↔ (a * x) * y' * b ∈ S := by
          exact hy (a * x) b
    _   ↔ a * x * (y' * b) ∈ S := by
          simp [mul_assoc]
    _   ↔ a * x' * (y' * b) ∈ S := by
          exact hx a (y' * b)
    _   ↔ a * (x' * y') * b ∈ S := by
          simp [mul_assoc]

/-- Multiplication on the concrete observed syntactic quotient. -/
protected def ObservedSyntacticQuotient.mul
    (S : Set Q) :
    ObservedSyntacticQuotient (Q := Q) S →
    ObservedSyntacticQuotient (Q := Q) S →
    ObservedSyntacticQuotient (Q := Q) S :=
  Quotient.lift₂
    (fun x y => observedSyntacticQuotientMap (Q := Q) S (x * y))
    (by
      intro x x' hx y y' hy
      apply Quotient.sound
      exact sameObservedSyntactic_mul_compat S hx hy)

instance observedSyntacticQuotientMul
    (S : Set Q) :
    Mul (ObservedSyntacticQuotient (Q := Q) S) where
  mul := ObservedSyntacticQuotient.mul (Q := Q) S

@[simp]
theorem observedSyntacticQuotient_mk_mul_mk
    (S : Set Q) (x y : Q) :
    (observedSyntacticQuotientMap (Q := Q) S x)
      *
    (observedSyntacticQuotientMap (Q := Q) S y)
      =
    observedSyntacticQuotientMap (Q := Q) S (x * y) := by
  rfl

/-- Associativity of the concrete quotient multiplication. -/
instance observedSyntacticQuotientSemigroup
    (S : Set Q) :
    Semigroup (ObservedSyntacticQuotient (Q := Q) S) where
  mul_assoc := by
    intro x y z
    refine Quotient.inductionOn x ?_
    intro a
    refine Quotient.inductionOn y ?_
    intro b
    refine Quotient.inductionOn z ?_
    intro c
    apply Quotient.sound
    intro l r
    simp [observedSyntacticQuotientMap, ObservedSyntacticQuotient.mul, mul_assoc]

/-- Unit element of the concrete quotient. -/
instance observedSyntacticQuotientOne
    (S : Set Q) :
    One (ObservedSyntacticQuotient (Q := Q) S) where
  one := observedSyntacticQuotientMap (Q := Q) S 1

/-- Left unit law for the concrete quotient multiplication. -/
theorem observedSyntacticQuotient_one_mul
    (S : Set Q)
    (x : ObservedSyntacticQuotient (Q := Q) S) :
    (1 : ObservedSyntacticQuotient (Q := Q) S) * x = x := by
  refine Quotient.inductionOn x ?_
  intro a
  apply Quotient.sound
  intro l r
  simp [observedSyntacticQuotientMap, ObservedSyntacticQuotient.mul]

/-- Right unit law for the concrete quotient multiplication. -/
theorem observedSyntacticQuotient_mul_one
    (S : Set Q)
    (x : ObservedSyntacticQuotient (Q := Q) S) :
    x * (1 : ObservedSyntacticQuotient (Q := Q) S) = x := by
  refine Quotient.inductionOn x ?_
  intro a
  apply Quotient.sound
  intro l r
  simp [observedSyntacticQuotientMap, ObservedSyntacticQuotient.mul]

/-- The quotient projection is multiplicative. -/
theorem observedSyntacticQuotientMap_mul
    (S : Set Q) (x y : Q) :
    observedSyntacticQuotientMap (Q := Q) S (x * y)
      =
    observedSyntacticQuotientMap (Q := Q) S x
      *
    observedSyntacticQuotientMap (Q := Q) S y := by
  rfl

/-- The quotient projection preserves the unit. -/
theorem observedSyntacticQuotientMap_one
    (S : Set Q) :
    observedSyntacticQuotientMap (Q := Q) S 1
      =
    (1 : ObservedSyntacticQuotient (Q := Q) S) := by
  rfl

/-- The quotient projection is surjective. -/
theorem observedSyntacticQuotientMap_surjective
    (S : Set Q) :
    ∀ y : ObservedSyntacticQuotient (Q := Q) S,
      ∃ x : Q, observedSyntacticQuotientMap (Q := Q) S x = y := by
  intro y
  refine Quotient.inductionOn y ?_
  intro x
  exact ⟨x, rfl⟩

/-- The kernel of the concrete quotient projection is exactly SameObservedSyntactic. -/
theorem observedSyntacticQuotientMap_kernel
    (S : Set Q) (x y : Q) :
    observedSyntacticQuotientMap (Q := Q) S x
      =
    observedSyntacticQuotientMap (Q := Q) S y
      ↔
    SameObservedSyntactic S x y := by
  constructor
  · intro h
    exact Quotient.exact h
  · intro h
    exact Quotient.sound h

/--
The concrete quotient projection is an exact observed quotient map in the sense
used by the abstract exact quotient-map layer.
-/
theorem observedSyntacticQuotientMap_exact_package
    (S : Set Q) :
    (∀ x y : Q,
      observedSyntacticQuotientMap (Q := Q) S (x * y)
        =
      observedSyntacticQuotientMap (Q := Q) S x
        *
      observedSyntacticQuotientMap (Q := Q) S y)
      ∧
    (observedSyntacticQuotientMap (Q := Q) S 1
      =
      (1 : ObservedSyntacticQuotient (Q := Q) S))
      ∧
    (∀ y : ObservedSyntacticQuotient (Q := Q) S,
      ∃ x : Q, observedSyntacticQuotientMap (Q := Q) S x = y)
      ∧
    (∀ x y : Q,
      observedSyntacticQuotientMap (Q := Q) S x
        =
      observedSyntacticQuotientMap (Q := Q) S y
        ↔
      SameObservedSyntactic S x y) := by
  constructor
  · intro x y
    exact observedSyntacticQuotientMap_mul (Q := Q) S x y
  constructor
  · exact observedSyntacticQuotientMap_one (Q := Q) S
  constructor
  · exact observedSyntacticQuotientMap_surjective (Q := Q) S
  · intro x y
    exact observedSyntacticQuotientMap_kernel (Q := Q) S x y

end LeanCfgProject
