import LeanCfgProject.CanonicalResidualClosureSystem

set_option linter.unusedVariables false
set_option linter.unusedTactic false
set_option linter.unusedSimpArgs false

namespace LeanCfgProject

universe u

/-
SingletonClosureIncidence.lean

Core incidence lemma for the canonical reduced frame representation layer.

This is the Lean-side form of the paper lemma:
  ConceptClosure S {gamma} subset Res_S(a,b) iff a * gamma * b is in S.
-/

variable {Q : Type u} [Mul Q]

/-- The point concept generated by a single observed element. -/
def SingletonConcept (S : Set Q) (gamma : Q) : Set Q :=
  ConceptClosure S ({gamma} : Set Q)

/--
The singleton incidence representation lemma.
-/
theorem singletonConcept_subset_residual_iff
    (S : Set Q) (gamma a b : Q) :
    SingletonConcept S gamma ⊆ TwoSidedResidual S a b
      ↔ a * gamma * b ∈ S := by
  constructor
  · intro hsub
    have hmem : gamma ∈ SingletonConcept S gamma := by
      exact subset_conceptClosure S ({gamma} : Set Q) (by simp)
    simpa [SingletonConcept, TwoSidedResidual] using hsub hmem
  · intro hmem delta hdelta
    have hab : (a, b) ∈ CommonContexts S ({gamma} : Set Q) := by
      intro z hz
      have hz' : z = gamma := by
        simpa using hz
      subst z
      exact hmem
    simpa [SingletonConcept, ConceptClosure, ElementsOfContexts,
      TwoSidedResidual] using hdelta (a, b) hab

/--
A direct residual-membership form of the singleton incidence lemma.
-/
theorem singletonConcept_subset_frame_iff
    (S : Set Q) (gamma a b : Q) :
    SingletonConcept S gamma ⊆ TwoSidedResidual S a b
      ↔ gamma ∈ TwoSidedResidual S a b := by
  simpa [TwoSidedResidual] using
    singletonConcept_subset_residual_iff S gamma a b

/--
The canonical point concept is always contained in every residual that contains
the point itself.
-/
theorem singletonConcept_subset_residual_of_mem
    (S : Set Q) {gamma a b : Q}
    (hmem : gamma ∈ TwoSidedResidual S a b) :
    SingletonConcept S gamma ⊆ TwoSidedResidual S a b := by
  exact (singletonConcept_subset_frame_iff S gamma a b).2 hmem

end LeanCfgProject
