/-
Copyright (c) 2026 Takayuki Kuriyama. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Takayuki Kuriyama
-/
import LeanCfgProject.MCFG.ConcreteCanonicalLearnerIdentification

/-!
# ConcreteCanonicalLearnerClassTheorem.lean

`ConcreteCanonicalLearnerIdentification.lean` proves the end-to-end theorem
for one target grammar.  This file packages that result at the language-class
level.

For fixed terminal alphabet `α`, finite observation monoid `M`, observation
map `obs`, and fan-out bound `f`, a language belongs to
`CorrectedConcreteTargetClass` when it is generated by some finite-nonterminal
working MCFG satisfying:

* exact working conditions;
* start separation;
* fan-out at most `f`;
* fixed-observation named-tuple substitutability.

The nonterminal type is existentially hidden inside the target witness.  Thus
the class may contain grammars with different finite nonterminal types.

The learner is uniform:

```lean
correctedConcreteCanonicalLearner
```

depends only on the observed finite sample.  It does not receive the target
grammar, its nonterminal type, or any target-specific presentation.

The main theorem

```lean
correctedConcreteCanonicalLearner_identifies_targetClass
```

states that this one learner identifies every language in the class from every
positive text.

The file also proves:

* monotonicity of the corrected learner language under sample extension;
* consistency with every input sample;
* existence of a finite characteristic sample for every language in the class;
* a uniform finite-tell-tale theorem for the entire class.

No `sorry`, `admit`, or `axiom` is used.
-/

namespace MCFG

universe u v w

section LearnerStructuralProperties

variable {α : Type u}
variable {M : Type w} [Monoid M]

/-- The corrected concrete learner language is monotone under inclusion of
finite samples. -/
theorem correctedConcreteCanonicalLearnerLanguage_mono
    {S K : Finset (Word α)}
    {obs : α → M}
    {f : Nat}
    (hSK :
      (S : Set (Word α)) ⊆
        (K : Set (Word α))) :
    CorrectedConcreteCanonicalLearnerLanguage
        S obs f ⊆
      CorrectedConcreteCanonicalLearnerLanguage
        K obs f := by
  rw [
    correctedConcreteCanonicalLearnerLanguage_eq_exactReachable,
    correctedConcreteCanonicalLearnerLanguage_eq_exactReachable
  ]
  exact exactReachableSampleStringLanguage_mono hSK

/-- The corrected learner is consistent: every observed sample word belongs to
the language hypothesized from that sample. -/
theorem correctedConcreteCanonicalLearner_consistent
    (K : Finset (Word α))
    (obs : α → M)
    (f : Nat) :
    (K : Set (Word α)) ⊆
      correctedConcreteCanonicalHypLanguage obs f
        (correctedConcreteCanonicalLearner
          (α := α) K) := by
  simpa using
    sample_subset_correctedConcreteCanonicalLearnerLanguage
      K obs f

/-- The language interpretation of the corrected set-driven learner is
monotone in its finite input. -/
theorem correctedConcreteCanonicalHypLanguage_mono
    {S K : Finset (Word α)}
    {obs : α → M}
    {f : Nat}
    (hSK :
      (S : Set (Word α)) ⊆
        (K : Set (Word α))) :
    correctedConcreteCanonicalHypLanguage obs f
        (correctedConcreteCanonicalLearner
          (α := α) S) ⊆
      correctedConcreteCanonicalHypLanguage obs f
        (correctedConcreteCanonicalLearner
          (α := α) K) := by
  exact correctedConcreteCanonicalLearnerLanguage_mono
    hSK

end LearnerStructuralProperties


section TargetWitness

variable (α : Type u)
variable (M : Type w) [Monoid M]
variable (obs : α → M)
variable (f : Nat)

/-- A target-language witness for the corrected concrete canonical learner.

The finite nonterminal type is stored inside the witness, so different target
languages may use different finite nonterminal types. -/
structure CorrectedConcreteTargetWitness
    (L : Set (Word α)) where

  nonterminal : Type v

  fintypeNonterminal :
    Fintype nonterminal

  grammar :
    WorkingMCFG nonterminal α

  exactWorking :
    grammar.ExactWorkingConditions

  startSeparated :
    grammar.StartSeparated

  fanout :
    grammar.FanoutAtMost f

  substitutable :
    FixedNamedTupleSubstitutable
      f obs grammar.StringLanguage

  language_eq :
    grammar.StringLanguage = L

/-- The class of languages represented by some finite target witness. -/
def CorrectedConcreteTargetClass :
    Set (Set (Word α)) :=
  fun L =>
    Nonempty
      (CorrectedConcreteTargetWitness
        α M obs f L)

end TargetWitness


section IdentificationPredicates

variable {α : Type u}
variable {Hyp : Type v}

/-- A set-driven learner identifies one language from every positive text. -/
def IdentifiesLanguageFromPositiveData
    [DecidableEq α]
    (lang : HypLanguage α Hyp)
    (learner : SetDrivenLearner α Hyp)
    (L : Set (Word α)) :
    Prop :=
  ∀ T : TextFor L,
    EventuallyCorrectOnText
      lang learner T

/-- One set-driven learner identifies every language in a class. -/
def IdentifiesClassFromPositiveData
    [DecidableEq α]
    (lang : HypLanguage α Hyp)
    (learner : SetDrivenLearner α Hyp)
    (C : Set (Set (Word α))) :
    Prop :=
  ∀ L : Set (Word α),
    L ∈ C →
      IdentifiesLanguageFromPositiveData
        lang learner L

end IdentificationPredicates


section WitnessCharacteristicSample

variable {α : Type u}
variable {M : Type w}
variable [Fintype M]
variable [DecidableEq α] [DecidableEq M]
variable [Monoid M]
variable {obs : α → M}
variable {f : Nat}
variable {L : Set (Word α)}

/-- Every target witness supplies an actual finite characteristic sample for
the corrected concrete learner. -/
theorem CorrectedConcreteTargetWitness.exists_characteristicSample
    (W :
      CorrectedConcreteTargetWitness
        α M obs f L) :
    ∃ S : Finset (Word α),
      CharacteristicSample
        (correctedConcreteCanonicalHypLanguage
          obs f)
        (correctedConcreteCanonicalLearner
          (α := α))
        S L := by

  letI : Fintype W.nonterminal :=
    W.fintypeNonterminal

  obtain
      ⟨S,
        hSpositive,
        hSexact,
        hSupersets,
        hTexts⟩ :=
    correctedConcreteCanonicalLearner_conclusion_package
      (G := W.grammar)
      (obs := obs)
      W.exactWorking
      W.startSeparated
      W.fanout
      W.substitutable

  refine ⟨S, ?_⟩

  constructor

  · simpa [W.language_eq] using
      hSpositive

  · intro K hSK hKpositive

    have hKgrammar :
        (K : Set (Word α)) ⊆
          W.grammar.StringLanguage := by
      simpa [W.language_eq] using
        hKpositive

    have hExactGrammar :
        CorrectedConcreteCanonicalLearnerLanguage
            K obs f =
          W.grammar.StringLanguage :=
      hSupersets K hSK hKgrammar

    simpa [W.language_eq] using
      hExactGrammar

/-- Every target witness is identified from every positive text by the same
corrected concrete learner. -/
theorem CorrectedConcreteTargetWitness.identified
    (W :
      CorrectedConcreteTargetWitness
        α M obs f L) :
    IdentifiesLanguageFromPositiveData
      (correctedConcreteCanonicalHypLanguage
        obs f)
      (correctedConcreteCanonicalLearner
        (α := α))
      L := by

  obtain ⟨S, hS⟩ :=
    W.exists_characteristicSample

  intro T

  exact
    characteristicSample_eventual_correct_on_every_text
      (correctedConcreteCanonicalHypLanguage
        obs f)
      (correctedConcreteCanonicalLearner
        (α := α))
      S hS T

/-- Every target witness has a finite tell-tale that forces the corrected
learner to output the target on all positive finite supersets. -/
theorem CorrectedConcreteTargetWitness.exists_finite_tellTale
    (W :
      CorrectedConcreteTargetWitness
        α M obs f L) :
    ∃ S : Finset (Word α),
      (S : Set (Word α)) ⊆ L ∧
      ∀ K : Finset (Word α),
        (S : Set (Word α)) ⊆
            (K : Set (Word α)) →
        (K : Set (Word α)) ⊆ L →
        correctedConcreteCanonicalHypLanguage
            obs f
            (correctedConcreteCanonicalLearner
              (α := α) K) =
          L := by

  obtain ⟨S, hS⟩ :=
    W.exists_characteristicSample

  exact ⟨S, hS.1, hS.2⟩

end WitnessCharacteristicSample


section ClassTheorem

variable {α : Type u}
variable {M : Type w}
variable [Fintype M]
variable [DecidableEq α] [DecidableEq M]
variable [Monoid M]
variable (obs : α → M)
variable (f : Nat)

/-- Every language in the target class has a finite characteristic sample for
the single corrected concrete canonical learner. -/
theorem correctedConcreteCanonicalLearner_characteristicSample_for_targetClass
    {L : Set (Word α)}
    (hL :
      L ∈ CorrectedConcreteTargetClass
        (v := v) α M obs f) :
    ∃ S : Finset (Word α),
      CharacteristicSample
        (correctedConcreteCanonicalHypLanguage
          obs f)
        (correctedConcreteCanonicalLearner
          (α := α))
        S L := by

  change
    Nonempty
      (CorrectedConcreteTargetWitness
        (v := v) α M obs f L) at hL

  rcases hL with ⟨W⟩

  exact W.exists_characteristicSample

/-- Uniform finite-tell-tale theorem for the entire target class. -/
theorem correctedConcreteCanonicalLearner_finite_tellTale_for_targetClass
    {L : Set (Word α)}
    (hL :
      L ∈ CorrectedConcreteTargetClass
        (v := v) α M obs f) :
    ∃ S : Finset (Word α),
      (S : Set (Word α)) ⊆ L ∧
      ∀ K : Finset (Word α),
        (S : Set (Word α)) ⊆
            (K : Set (Word α)) →
        (K : Set (Word α)) ⊆ L →
        correctedConcreteCanonicalHypLanguage
            obs f
            (correctedConcreteCanonicalLearner
              (α := α) K) =
          L := by

  change
    Nonempty
      (CorrectedConcreteTargetWitness
        (v := v) α M obs f L) at hL

  rcases hL with ⟨W⟩

  exact W.exists_finite_tellTale

/-- Main class-level theorem: one target-independent corrected concrete learner
identifies every language in the represented finite-MCFG class from positive
data. -/
theorem correctedConcreteCanonicalLearner_identifies_targetClass :
    IdentifiesClassFromPositiveData
      (correctedConcreteCanonicalHypLanguage
        obs f)
      (correctedConcreteCanonicalLearner
        (α := α))
      (CorrectedConcreteTargetClass
        (v := v) α M obs f) := by

  intro L hL

  change
    Nonempty
      (CorrectedConcreteTargetWitness
        (v := v) α M obs f L) at hL

  rcases hL with ⟨W⟩

  exact W.identified

/-- Expanded form of the class theorem, exposing quantification over target
languages and positive texts. -/
theorem correctedConcreteCanonicalLearner_identifies_every_target_text :
    ∀ L : Set (Word α),
      L ∈ CorrectedConcreteTargetClass
          (v := v) α M obs f →
      ∀ T : TextFor L,
        EventuallyCorrectOnText
          (correctedConcreteCanonicalHypLanguage
            obs f)
          (correctedConcreteCanonicalLearner
            (α := α))
          T := by

  intro L hL T

  exact
    correctedConcreteCanonicalLearner_identifies_targetClass
      (v := v) obs f L hL T

/-- Paper-style class conclusion package.

It exposes learner consistency, monotonicity, finite characteristic samples for
all targets, and uniform identification of the whole class. -/
theorem correctedConcreteCanonicalLearner_class_conclusion_package :
    ((∀ K : Finset (Word α),
        (K : Set (Word α)) ⊆
          correctedConcreteCanonicalHypLanguage
            obs f
            (correctedConcreteCanonicalLearner
              (α := α) K))) ∧
    ((∀ S K : Finset (Word α),
        (S : Set (Word α)) ⊆
            (K : Set (Word α)) →
        correctedConcreteCanonicalHypLanguage
            obs f
            (correctedConcreteCanonicalLearner
              (α := α) S) ⊆
          correctedConcreteCanonicalHypLanguage
            obs f
            (correctedConcreteCanonicalLearner
              (α := α) K))) ∧
    ((∀ L : Set (Word α),
        L ∈ CorrectedConcreteTargetClass
            (v := v) α M obs f →
        ∃ S : Finset (Word α),
          CharacteristicSample
            (correctedConcreteCanonicalHypLanguage
              obs f)
            (correctedConcreteCanonicalLearner
              (α := α))
            S L)) ∧
    IdentifiesClassFromPositiveData
      (correctedConcreteCanonicalHypLanguage
        obs f)
      (correctedConcreteCanonicalLearner
        (α := α))
      (CorrectedConcreteTargetClass
        (v := v) α M obs f) := by

  refine ⟨?_, ?_, ?_, ?_⟩

  · intro K
    exact correctedConcreteCanonicalLearner_consistent
      K obs f

  · intro S K hSK
    exact correctedConcreteCanonicalHypLanguage_mono
      hSK

  · intro L hL
    exact
      correctedConcreteCanonicalLearner_characteristicSample_for_targetClass
        (v := v) obs f hL

  · exact
      correctedConcreteCanonicalLearner_identifies_targetClass
        (v := v) obs f

end ClassTheorem

end MCFG
