/-
Copyright (c) 2026 Takayuki Kuriyama. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Takayuki Kuriyama
-/
import LeanCfgProject.MCFG2.ConcreteCanonicalLearnerWorkingGrammarStructuralConditions

/-!
# ConcreteCanonicalLearnerWorkingGrammarRepresentation.lean

The compiled grammar has now been analyzed semantically, quantitatively, and
structurally.  This file turns those facts into a representation theorem for
the whole semantic target class.

The correct output class is not the paper's exact-working normal form.  It is
the class of languages represented by finite `WorkingMCFG` objects satisfying

```lean
WorkingMCFG.CutCompiledConditions f.
```

These conditions record exactly what the compiler preserves:

* start arity one;
* well-typed start rules;
* well-typed terminal rules;
* fan-out at most `max 1 f`.

The representation structure is:

```lean
CutCompiledWorkingGrammarRepresentation α f L.
```

For each finite positive sample `K`, the actual learner output gives such a
representation of its corrected concrete language.

More importantly, every language in

```lean
StartRootedCorrectedConcreteTargetClass α M obs f
```

has a finite characteristic sample `S`.  Running the actual grammar-valued
learner on `S` already returns a grammar whose language is exactly the target.
Thus every target admits:

* a finite positive construction sample;
* an actual finite `WorkingMCFG`;
* exact language equality;
* the verified cut-compiled structural conditions;
* the source-rule count bound;
* the compiled grammar-rule count bound;
* the complete nonterminal-plus-rule presentation-item bound.

The main class inclusion is:

```lean
startRootedTargetClass_subset_cutCompiledWorkingGrammarLanguageClass.
```

The strongest witness endpoint is:

```lean
correctedConcreteWorkingGrammarLearner_targetRepresentation_package.
```

No target grammar is supplied to the learner.
No `sorry`, `admit`, or `axiom` is used.
-/

namespace MCFG

universe u v w

section CutCompiledRepresentationClass

variable (α : Type u)

/-- A language representation by one actual working grammar satisfying the
positive structural conditions preserved by the cut compiler. -/
structure CutCompiledWorkingGrammarRepresentation
    (f : Nat)
    (L : Set (Word α)) where

  Nonterminal :
    Type w

  grammar :
    WorkingMCFG Nonterminal α

  conditions :
    grammar.CutCompiledConditions f

  language_eq :
    grammar.StringLanguage = L

/-- Class of languages having a cut-compiled working-grammar representation in
the selected universe. -/
def CutCompiledWorkingGrammarLanguageClass
    (f : Nat) :
    Set (Set (Word α)) :=
  {L |
    Nonempty
      (CutCompiledWorkingGrammarRepresentation
        (w := w) α f L)}

namespace CutCompiledWorkingGrammarRepresentation

variable {α : Type u}
variable {f : Nat}
variable {L : Set (Word α)}

/-- Symmetric orientation of the representation equality. -/
theorem target_eq_language
    (R :
      CutCompiledWorkingGrammarRepresentation
        (w := w) α f L) :
    L = R.grammar.StringLanguage :=
  R.language_eq.symm

/-- A represented language is generated by an actual bounded-fan-out grammar. -/
theorem fanoutAtMost_max
    (R :
      CutCompiledWorkingGrammarRepresentation
        (w := w) α f L) :
    R.grammar.FanoutAtMost
      (max 1 f) :=
  R.conditions.2.2.2

/-- A represented language has a start symbol of arity one. -/
theorem startArityOne
    (R :
      CutCompiledWorkingGrammarRepresentation
        (w := w) α f L) :
    R.grammar.StartArityOne :=
  R.conditions.1

/-- All start rules of a represented grammar are well-typed. -/
theorem startRulesWellTyped
    (R :
      CutCompiledWorkingGrammarRepresentation
        (w := w) α f L) :
    R.grammar.StartRulesWellTyped :=
  R.conditions.2.1

/-- All terminal rules of a represented grammar are well-typed. -/
theorem terminalRulesWellTyped
    (R :
      CutCompiledWorkingGrammarRepresentation
        (w := w) α f L) :
    R.grammar.TerminalRulesWellTyped :=
  R.conditions.2.2.1

end CutCompiledWorkingGrammarRepresentation

end CutCompiledRepresentationClass


section RepresentationFromOneLearnerOutput

variable {α : Type u}
variable {M : Type v}
variable [Monoid M]

/-- Every actual learner output supplies a cut-compiled representation of its
own grammar language. -/
noncomputable def correctedConcreteWorkingGrammarOutputRepresentation
    (hα : Nonempty α)
    (obs : α → M)
    (f : Nat)
    (K : Finset (Word α)) :
    CutCompiledWorkingGrammarRepresentation
      (w := max u v)
      α f
      ((correctedConcreteWorkingGrammarLearner
        hα obs f K).grammar.StringLanguage) where

  Nonterminal :=
    (correctedConcreteWorkingGrammarLearner
      hα obs f K).Nonterminal

  grammar :=
    (correctedConcreteWorkingGrammarLearner
      hα obs f K).grammar

  conditions :=
    correctedConcreteWorkingGrammarLearner_cutCompiledConditions
      hα obs f K

  language_eq :=
    rfl

/-- Every corrected concrete sample language belongs to the cut-compiled
working-grammar language class. -/
theorem correctedConcreteCanonicalLearnerLanguage_mem_cutCompiledClass
    (hα : Nonempty α)
    (obs : α → M)
    (f : Nat)
    (K : Finset (Word α)) :
    CorrectedConcreteCanonicalLearnerLanguage
        K obs f ∈
      CutCompiledWorkingGrammarLanguageClass
        (w := max u v) α f := by

  unfold
    CutCompiledWorkingGrammarLanguageClass

  let H :=
    correctedConcreteWorkingGrammarLearner
      hα obs f K

  refine
    ⟨{ Nonterminal := H.Nonterminal
       grammar := H.grammar
       conditions :=
         correctedConcreteWorkingGrammarLearner_cutCompiledConditions
           hα obs f K
       language_eq := ?_ }⟩

  exact
    correctedConcreteWorkingGrammarLearner_stringLanguage_eq_corrected
      hα obs f K

/-- The exact-once reachable sample language also has an actual cut-compiled
working-grammar representation. -/
theorem exactReachableSampleStringLanguage_mem_cutCompiledClass
    (hα : Nonempty α)
    (obs : α → M)
    (f : Nat)
    (K : Finset (Word α)) :
    ExactReachableSampleStringLanguage
        K obs f ∈
      CutCompiledWorkingGrammarLanguageClass
        (w := max u v) α f := by

  unfold
    CutCompiledWorkingGrammarLanguageClass

  let H :=
    correctedConcreteWorkingGrammarLearner
      hα obs f K

  refine
    ⟨{ Nonterminal := H.Nonterminal
       grammar := H.grammar
       conditions :=
         correctedConcreteWorkingGrammarLearner_cutCompiledConditions
           hα obs f K
       language_eq := ?_ }⟩

  exact
    correctedConcreteWorkingGrammarHypLanguage_eq_exactReachable
      hα obs f K

end RepresentationFromOneLearnerOutput


section TargetRepresentationWitness

variable {α : Type u}
variable {M : Type v}
variable [Monoid M]

/-- A target representation obtained by running the actual grammar-valued
learner on one finite positive sample. -/
structure CorrectedConcreteWorkingGrammarTargetRepresentationWitness
    (hα : Nonempty α)
    (obs : α → M)
    (f : Nat)
    (L : Set (Word α)) where

  sample :
    Finset (Word α)

  sample_positive :
    (sample : Set (Word α)) ⊆ L

  output_exact :
    (correctedConcreteWorkingGrammarLearner
      hα obs f sample).grammar.StringLanguage =
        L

namespace CorrectedConcreteWorkingGrammarTargetRepresentationWitness

variable {hα : Nonempty α}
variable {obs : α → M}
variable {f : Nat}
variable {L : Set (Word α)}

/-- Actual learner hypothesis selected by the finite construction sample. -/
noncomputable def output
    (W :
      CorrectedConcreteWorkingGrammarTargetRepresentationWitness
        hα obs f L) :
    CorrectedConcreteWorkingGrammarHypothesis
      α M obs f :=
  correctedConcreteWorkingGrammarLearner
    hα obs f W.sample

/-- The witness output satisfies the compiler's positive structural
conditions. -/
theorem output_conditions
    (W :
      CorrectedConcreteWorkingGrammarTargetRepresentationWitness
        hα obs f L) :
    W.output.grammar.CutCompiledConditions f := by

  exact
    correctedConcreteWorkingGrammarLearner_cutCompiledConditions
      hα obs f W.sample

/-- The witness determines a representation object of the target language. -/
noncomputable def toCutCompiledRepresentation
    (W :
      CorrectedConcreteWorkingGrammarTargetRepresentationWitness
        hα obs f L) :
    CutCompiledWorkingGrammarRepresentation
      (w := max u v) α f L where

  Nonterminal :=
    W.output.Nonterminal

  grammar :=
    W.output.grammar

  conditions :=
    W.output_conditions

  language_eq :=
    W.output_exact

/-- Therefore the target belongs to the cut-compiled language class. -/
theorem target_mem_cutCompiledClass
    (W :
      CorrectedConcreteWorkingGrammarTargetRepresentationWitness
        hα obs f L) :
    L ∈
      CutCompiledWorkingGrammarLanguageClass
        (w := max u v) α f := by

  exact
    ⟨W.toCutCompiledRepresentation⟩

/-- The source finite-rule object in the exact target representation satisfies
the verified paper-facing bound. -/
theorem sourceRuleCount_le
    (W :
      CorrectedConcreteWorkingGrammarTargetRepresentationWitness
        hα obs f L) :
    W.output.sourceRuleCount ≤
      correctedLearnerPaperRuleCountBound
        (sampleLengthBudget W.sample) f := by

  exact
    correctedConcreteWorkingGrammarLearner_sourceRuleCount_le_explicit_paperPower
      hα obs f W.sample

/-- The actual compiled grammar-rule lists in the exact target representation
satisfy their paper-facing bound. -/
theorem grammarRuleCount_le
    (W :
      CorrectedConcreteWorkingGrammarTargetRepresentationWitness
        hα obs f L) :
    W.output.grammarRuleCount ≤
      correctedConcreteCompiledGrammarRuleCountBound
        (sampleLengthBudget W.sample) f := by

  exact
    correctedConcreteWorkingGrammarLearner_grammarRuleCount_le_paperBound
      hα obs f W.sample

/-- The complete nonterminal-plus-rule presentation of the exact target
representation satisfies its paper-facing item bound. -/
theorem presentationItemCount_le
    (W :
      CorrectedConcreteWorkingGrammarTargetRepresentationWitness
        hα obs f L) :
    W.output.presentationItemCount ≤
      correctedConcreteCompiledGrammarPresentationItemBound
        (sampleLengthBudget W.sample) f := by

  exact
    correctedConcreteWorkingGrammarLearner_presentationItemCount_le_paperBound
      hα obs f W.sample

/-- Positive fan-out form when the fixed fan-out parameter is nonzero. -/
theorem output_fanoutAtMost
    (W :
      CorrectedConcreteWorkingGrammarTargetRepresentationWitness
        hα obs f L)
    (hf : 1 ≤ f) :
    W.output.grammar.FanoutAtMost f := by

  exact
    correctedConcreteWorkingGrammarLearner_fanoutAtMost
      hα obs f hf W.sample

end CorrectedConcreteWorkingGrammarTargetRepresentationWitness

end TargetRepresentationWitness


section WitnessFromCharacteristicSample

variable {α : Type u}
variable {M : Type v}
variable [Monoid M]
variable [DecidableEq α]

/-- A characteristic sample for the actual working-grammar learner immediately
gives an exact target representation by running the learner on the
characteristic sample itself. -/
noncomputable def correctedConcreteWorkingGrammarTargetRepresentation_of_characteristicSample
    (hα : Nonempty α)
    (obs : α → M)
    (f : Nat)
    (S : Finset (Word α))
    (L : Set (Word α))
    (hS :
      CharacteristicSample
        (correctedConcreteWorkingGrammarHypLanguage
          obs f)
        (correctedConcreteWorkingGrammarLearner
          hα obs f)
        S L) :
    CorrectedConcreteWorkingGrammarTargetRepresentationWitness
      hα obs f L where

  sample :=
    S

  sample_positive :=
    hS.1

  output_exact :=
    hS.2 S
      Set.Subset.rfl
      hS.1

/-- Existential form: every characteristic sample yields one finite positive
sample whose actual output grammar is already exact. -/
theorem exists_exact_workingGrammar_output_of_characteristicSample
    (hα : Nonempty α)
    (obs : α → M)
    (f : Nat)
    (S : Finset (Word α))
    (L : Set (Word α))
    (hS :
      CharacteristicSample
        (correctedConcreteWorkingGrammarHypLanguage
          obs f)
        (correctedConcreteWorkingGrammarLearner
          hα obs f)
        S L) :
    ∃ K : Finset (Word α),
      (K : Set (Word α)) ⊆ L ∧
      (correctedConcreteWorkingGrammarLearner
        hα obs f K).grammar.StringLanguage =
          L := by

  exact
    ⟨S,
      hS.1,
      hS.2 S Set.Subset.rfl hS.1⟩

end WitnessFromCharacteristicSample


section StartRootedTargetRepresentation

variable {α : Type u}
variable {M : Type v}
variable [Fintype M]
variable [DecidableEq α]
variable [DecidableEq M]
variable [Monoid M]
variable (hα : Nonempty α)
variable (obs : α → M)
variable (f : Nat)

/-- Every target in the semantic start-rooted class has a finite positive
sample whose actual learner output grammar is exactly the target. -/
theorem correctedConcreteWorkingGrammarLearner_exists_targetRepresentation
    {L : Set (Word α)}
    (hL :
      L ∈ StartRootedCorrectedConcreteTargetClass
        (v := w) α M obs f) :
    Nonempty
      (CorrectedConcreteWorkingGrammarTargetRepresentationWitness
        hα obs f L) := by

  obtain ⟨S, hS⟩ :=
    correctedConcreteWorkingGrammarLearner_characteristicSample_for_startRootedTargetClass
      (v := w) hα obs f hL

  exact
    ⟨correctedConcreteWorkingGrammarTargetRepresentation_of_characteristicSample
      hα obs f S L hS⟩

/-- Every semantic start-rooted target belongs to the language class represented
by actual cut-compiled working grammars. -/
theorem correctedConcreteWorkingGrammarLearner_target_mem_cutCompiledClass
    {L : Set (Word α)}
    (hL :
      L ∈ StartRootedCorrectedConcreteTargetClass
        (v := w) α M obs f) :
    L ∈
      CutCompiledWorkingGrammarLanguageClass
        (w := max u v) α f := by

  rcases
      correctedConcreteWorkingGrammarLearner_exists_targetRepresentation
        (v := w) hα obs f hL with
    ⟨W⟩

  exact W.target_mem_cutCompiledClass

/-- Class inclusion form of the target representation theorem. -/
theorem startRootedTargetClass_subset_cutCompiledWorkingGrammarLanguageClass :
    StartRootedCorrectedConcreteTargetClass
        (v := w) α M obs f ⊆
      CutCompiledWorkingGrammarLanguageClass
        (w := max u v) α f := by

  intro L hL

  exact
    correctedConcreteWorkingGrammarLearner_target_mem_cutCompiledClass
      (v := w) hα obs f hL

/-- Expanded exact-representation statement exposing the finite positive
construction sample and actual learner output. -/
theorem correctedConcreteWorkingGrammarLearner_exists_exact_output_for_target
    {L : Set (Word α)}
    (hL :
      L ∈ StartRootedCorrectedConcreteTargetClass
        (v := w) α M obs f) :
    ∃ S : Finset (Word α),
      (S : Set (Word α)) ⊆ L ∧
      (correctedConcreteWorkingGrammarLearner
          hα obs f S).grammar.CutCompiledConditions f ∧
      (correctedConcreteWorkingGrammarLearner
          hα obs f S).grammar.StringLanguage =
        L := by

  rcases
      correctedConcreteWorkingGrammarLearner_exists_targetRepresentation
        (v := w) hα obs f hL with
    ⟨W⟩

  exact
    ⟨W.sample,
      W.sample_positive,
      W.output_conditions,
      W.output_exact⟩

/-- Exact target representation together with all three verified size bounds. -/
theorem correctedConcreteWorkingGrammarLearner_exists_bounded_exact_output_for_target
    {L : Set (Word α)}
    (hL :
      L ∈ StartRootedCorrectedConcreteTargetClass
        (v := w) α M obs f) :
    ∃ S : Finset (Word α),
      (S : Set (Word α)) ⊆ L ∧
      (correctedConcreteWorkingGrammarLearner
          hα obs f S).grammar.StringLanguage =
        L ∧
      (correctedConcreteWorkingGrammarLearner
          hα obs f S).sourceRuleCount ≤
        correctedLearnerPaperRuleCountBound
          (sampleLengthBudget S) f ∧
      (correctedConcreteWorkingGrammarLearner
          hα obs f S).grammarRuleCount ≤
        correctedConcreteCompiledGrammarRuleCountBound
          (sampleLengthBudget S) f ∧
      (correctedConcreteWorkingGrammarLearner
          hα obs f S).presentationItemCount ≤
        correctedConcreteCompiledGrammarPresentationItemBound
          (sampleLengthBudget S) f := by

  rcases
      correctedConcreteWorkingGrammarLearner_exists_targetRepresentation
        (v := w) hα obs f hL with
    ⟨W⟩

  exact
    ⟨W.sample,
      W.sample_positive,
      W.output_exact,
      W.sourceRuleCount_le,
      W.grammarRuleCount_le,
      W.presentationItemCount_le⟩

end StartRootedTargetRepresentation


section RepresentationPackages

variable {α : Type u}
variable {M : Type v}
variable [Fintype M]
variable [DecidableEq α]
variable [DecidableEq M]
variable [Monoid M]
variable (hα : Nonempty α)
variable (obs : α → M)
variable (f : Nat)

/-- Paper-facing target representation package.

Each semantic target has a finite positive construction sample, an actual
bounded-fan-out working grammar with exact target language, and the verified
finite size bounds. -/
theorem correctedConcreteWorkingGrammarLearner_targetRepresentation_package :
    (StartRootedCorrectedConcreteTargetClass
          (v := w) α M obs f ⊆
        CutCompiledWorkingGrammarLanguageClass
          (w := max u v) α f) ∧
      (∀ L : Set (Word α),
        L ∈ StartRootedCorrectedConcreteTargetClass
            (v := w) α M obs f →
        ∃ S : Finset (Word α),
          (S : Set (Word α)) ⊆ L ∧
          (correctedConcreteWorkingGrammarLearner
              hα obs f S).grammar.CutCompiledConditions f ∧
          (correctedConcreteWorkingGrammarLearner
              hα obs f S).grammar.StringLanguage =
            L ∧
          (correctedConcreteWorkingGrammarLearner
              hα obs f S).sourceRuleCount ≤
            correctedLearnerPaperRuleCountBound
              (sampleLengthBudget S) f ∧
          (correctedConcreteWorkingGrammarLearner
              hα obs f S).grammarRuleCount ≤
            correctedConcreteCompiledGrammarRuleCountBound
              (sampleLengthBudget S) f ∧
          (correctedConcreteWorkingGrammarLearner
              hα obs f S).presentationItemCount ≤
            correctedConcreteCompiledGrammarPresentationItemBound
              (sampleLengthBudget S) f) := by

  refine
    ⟨startRootedTargetClass_subset_cutCompiledWorkingGrammarLanguageClass
        (v := w) hα obs f,
      ?_⟩

  intro L hL

  rcases
      correctedConcreteWorkingGrammarLearner_exists_targetRepresentation
        (v := w) hα obs f hL with
    ⟨W⟩

  exact
    ⟨W.sample,
      W.sample_positive,
      W.output_conditions,
      W.output_exact,
      W.sourceRuleCount_le,
      W.grammarRuleCount_le,
      W.presentationItemCount_le⟩

/-- Combined representation-and-identification endpoint.

The same target-independent learner both identifies the target class and
provides an exact finite grammar representation for each target from one finite
positive sample. -/
theorem correctedConcreteWorkingGrammarLearner_representation_identification_package :
    IdentifiesClassFromPositiveData
        (correctedConcreteWorkingGrammarHypLanguage
          obs f)
        (correctedConcreteWorkingGrammarLearner
          hα obs f)
        (StartRootedCorrectedConcreteTargetClass
          (v := w) α M obs f) ∧
      (StartRootedCorrectedConcreteTargetClass
          (v := w) α M obs f ⊆
        CutCompiledWorkingGrammarLanguageClass
          (w := max u v) α f) ∧
      (∀ L : Set (Word α),
        L ∈ StartRootedCorrectedConcreteTargetClass
            (v := w) α M obs f →
        Nonempty
          (CorrectedConcreteWorkingGrammarTargetRepresentationWitness
            hα obs f L)) := by

  exact
    ⟨correctedConcreteWorkingGrammarLearner_identifies_startRootedTargetClass
        (v := w) hα obs f,
      startRootedTargetClass_subset_cutCompiledWorkingGrammarLanguageClass
        (v := w) hα obs f,
      fun L hL =>
        correctedConcreteWorkingGrammarLearner_exists_targetRepresentation
          (v := w) hα obs f hL⟩

end RepresentationPackages

end MCFG
