/-
Copyright (c) 2026 Takayuki Kuriyama. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Takayuki Kuriyama
-/
import LeanCfgProject.MCFG.CharacteristicSampleSkeleton

/-!
# ExactReconstructionSkeleton.lean

Fourteenth clean Lean experiment for the fixed-observation MCFG project.

This file packages the current soundness and completeness skeletons into an
exact-reconstruction statement.

At this stage, the concrete finite canonical learner is still represented by
sample-level derivation relations.  Accordingly, this file distinguishes:

* `SampleStringLanguage`: strings derived from actual sample start words;
* `CharacteristicReachableLanguage`: strings reachable from the characteristic
  start anchor supplied by `CharacteristicSampleData`.

We already know:

* `SampleStringLanguage ⊆ G.StringLanguage` by soundness;
* `G.StringLanguage ⊆ CharacteristicReachableLanguage` by characteristic-data
  completeness.

The remaining concrete-learner bridge is represented by `ReconstructionBridge`,
which says that every characteristic-anchor reachable word is also generated
from a sample start word.  Once this bridge is available, exact reconstruction
follows immediately.

No theorem here uses `sorry`.
-/

namespace MCFG

universe u v w

section SampleStringLanguage

variable {α : Type u} {M : Type v} [Monoid M]

/-- The string language generated by the current sample-level learner model:
a word is included if it is derived from some start word in the finite sample. -/
def SampleStringLanguage
    (K : Finset (Word α)) (obs : α → M) (f : Nat) : Set (Word α) :=
  { word | SampleStringDerives K obs f word }

/-- Soundness of the sample-level string language. -/
theorem sampleStringLanguage_sound
    {N : Type w}
    (G : WorkingMCFG N α)
    {K : Finset (Word α)} {obs : α → M} {f : Nat}
    (hL : FixedNamedTupleSubstitutable f obs G.StringLanguage)
    (hK : PositiveSample G K) :
    SampleStringLanguage K obs f ⊆ G.StringLanguage := by
  intro word hword
  exact SampleStringDerives.sound_for_grammar G hL hK hword

/-- Every sample word is in the sample-level string language. -/
theorem sample_mem_sampleStringLanguage
    {K : Finset (Word α)} {obs : α → M} {f : Nat}
    {word : Word α}
    (hword : word ∈ K) :
    word ∈ SampleStringLanguage K obs f :=
  SampleStringDerives.of_sample_word hword

end SampleStringLanguage


section CharacteristicReachableLanguage

variable {N : Type w} {α : Type u} {M : Type v} [Monoid M]
variable {G : WorkingMCFG N α}
variable {K : Finset (Word α)} {obs : α → M} {f : Nat}

/-- The language reachable from the characteristic start anchor.

This is the completeness-side language produced by `CharacteristicSampleData`.
It is deliberately separate from `SampleStringLanguage`: later concrete learner
files will bridge the characteristic start anchor to actual sample start rules. -/
def CharacteristicReachableLanguage
    (D : CharacteristicSampleData G K obs f) : Set (Word α) :=
  { word |
    ∃ hstart : 1 = G.arity G.start,
      SampleLearnerReachable K obs f
        (D.anchor G.start)
        (castTuple hstart (singletonTuple word)) }

/-- Characteristic-sample data gives completeness into the characteristic
reachable language. -/
theorem target_subset_characteristicReachableLanguage
    (D : CharacteristicSampleData G K obs f)
    (hfan : G.FanoutAtMost f) :
    G.StringLanguage ⊆ CharacteristicReachableLanguage D := by
  intro word hword
  exact D.reaches_of_string_mem hfan hword

/-- Soundness of the characteristic reachable language, provided the start
anchor itself is known to be sound in the target language through the generated
reachable tuple.

This theorem is a useful transport form: if a word is characteristic-reachable
and one can independently show that the same reachable singleton tuple is
accepted, then the word is in the target language. -/
theorem word_mem_of_characteristic_reachable_and_singleton_mem
    (D : CharacteristicSampleData G K obs f)
    {word : Word α}
    (hreach : word ∈ CharacteristicReachableLanguage D)
    (hmem :
      ∀ hstart : 1 = G.arity G.start,
        SampleLearnerReachable K obs f
          (D.anchor G.start)
          (castTuple hstart (singletonTuple word)) →
        castTuple hstart (singletonTuple word) =
          castTuple hstart (singletonTuple word) →
        word ∈ G.StringLanguage) :
    word ∈ G.StringLanguage := by
  rcases hreach with ⟨hstart, hderiv⟩
  exact hmem hstart hderiv rfl

end CharacteristicReachableLanguage


section ReconstructionBridge

variable {N : Type w} {α : Type u} {M : Type v} [Monoid M]
variable {G : WorkingMCFG N α}
variable {K : Finset (Word α)} {obs : α → M} {f : Nat}

/-- The remaining bridge between characteristic-anchor reachability and the
actual sample-start string language.

Later, this should be constructed from the fact that the characteristic start
anchor is exposed by an actual sample start rule, as in the paper's
start-child convention. -/
structure ReconstructionBridge
    (D : CharacteristicSampleData G K obs f) where
  toSampleString :
    CharacteristicReachableLanguage D ⊆ SampleStringLanguage K obs f

namespace ReconstructionBridge

/-- With a reconstruction bridge, characteristic reachability is sound because
it is included in the sample-level string language. -/
theorem characteristicReachable_sound
    (D : CharacteristicSampleData G K obs f)
    (B : ReconstructionBridge D)
    (hL : FixedNamedTupleSubstitutable f obs G.StringLanguage)
    (hK : PositiveSample G K) :
    CharacteristicReachableLanguage D ⊆ G.StringLanguage := by
  intro word hword
  exact sampleStringLanguage_sound G hL hK (B.toSampleString hword)

/-- Exact reconstruction from positive samples, in skeleton form.

Assumptions:
* `K` is positive for the target;
* the target satisfies the fixed-observation promise;
* characteristic-sample data supplies rule-by-rule completeness;
* the bridge connects the characteristic start anchor to actual sample starts.

Conclusion:
the sample-level learner language equals the target language. -/
theorem exact_reconstruction
    (D : CharacteristicSampleData G K obs f)
    (B : ReconstructionBridge D)
    (hfan : G.FanoutAtMost f)
    (hL : FixedNamedTupleSubstitutable f obs G.StringLanguage)
    (hK : PositiveSample G K) :
    SampleStringLanguage K obs f = G.StringLanguage := by
  ext word
  constructor
  · intro hword
    exact sampleStringLanguage_sound G hL hK hword
  · intro hword
    exact B.toSampleString
      (target_subset_characteristicReachableLanguage D hfan hword)

/-- A version stated as mutual inclusions. -/
theorem exact_reconstruction_inclusions
    (D : CharacteristicSampleData G K obs f)
    (B : ReconstructionBridge D)
    (hfan : G.FanoutAtMost f)
    (hL : FixedNamedTupleSubstitutable f obs G.StringLanguage)
    (hK : PositiveSample G K) :
    SampleStringLanguage K obs f ⊆ G.StringLanguage ∧
      G.StringLanguage ⊆ SampleStringLanguage K obs f := by
  constructor
  · exact sampleStringLanguage_sound G hL hK
  · intro word hword
    exact B.toSampleString
      (target_subset_characteristicReachableLanguage D hfan hword)

end ReconstructionBridge

end ReconstructionBridge

end MCFG
