/-
Copyright (c) 2026 Takayuki Kuriyama. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Takayuki Kuriyama
-/
import LeanCfgProject.MCFG2.LearnerSoundnessCore

/-!
# LearnerDerivationSoundness.lean

Ninth clean Lean experiment for the fixed-observation MCFG project.

This file proves the induction principle behind learner soundness.

Instead of constructing the full finite canonical learner, we define an abstract
learner-derivation relation whose constructors correspond to the semantic
evidence already verified in `LearnerSoundnessCore.lean`:

* identity/base derivations;
* unit-rule steps justified by `NamedUnitEvidence`;
* binary-rule steps justified by `NamedBinaryEvidence`.

The main theorem says that every such abstract learner derivation is sound:
the tuple produced by the derivation is fixed-observation distributionally
equivalent to the tuple labeling the source nonterminal.

This is the core induction used later by the concrete canonical learner.

No theorem here uses `sorry`.
-/

namespace MCFG

universe u v w

section AbstractLearnerDerivation

variable {α : Type u} {M : Type v} [Monoid M]

/-- Abstract learner derivations generated by sound semantic evidence.

`AbstractLearnerDerives obs L f x u` means: from the learner nonterminal
labeled by tuple `x`, the abstract learner can derive tuple `u`.

The relation is arity-indexed: source and output tuples have the same arity.
The constructors mirror the soundness proof of the canonical learner, without
yet committing to a finite enumeration of observed tuples and witnesses. -/
inductive AbstractLearnerDerives
    (obs : α → M) (L : Set (Word α)) (f : Nat) :
    {d : Nat} → Tuple α d → Tuple α d → Prop where
  | self {d : Nat} (x : Tuple α d) :
      AbstractLearnerDerives obs L f x x
  | unit {d : Nat} {x y u : Tuple α d}
      (hd : d ≤ f)
      (hpos : 0 < d)
      (U : NamedUnitEvidence obs L x y)
      (hyu : AbstractLearnerDerives obs L f y u) :
      AbstractLearnerDerives obs L f x u
  | binary {e dB dC : Nat}
      {parent : NamedSentenceContext α e}
      {body : TemplateTuple α e dB dC}
      {x u : Tuple α dB}
      {y v : Tuple α dC}
      (he : e ≤ f)
      (hpos : 0 < e)
      (B : NamedBinaryEvidence L parent body x y)
      (hx : AbstractLearnerDerives obs L f x u)
      (hy : AbstractLearnerDerives obs L f y v) :
      AbstractLearnerDerives obs L f
        (evalTemplateTuple body x y)
        (evalTemplateTuple body u v)

namespace AbstractLearnerDerives

variable {obs : α → M} {L : Set (Word α)} {f : Nat}

/-- Soundness of abstract learner derivations.

If the target language satisfies the fixed-observation tuple-substitutability
promise, then any tuple derived from a learner nonterminal labeled by `x` is
distributionally equivalent to `x`. -/
theorem sound
    (hL : FixedNamedTupleSubstitutable f obs L)
    {d : Nat} {x u : Tuple α d}
    (h : AbstractLearnerDerives obs L f x u) :
    FixedNamedDistributionalEquivalent obs L u x := by
  induction h with
  | self x =>
      exact fixedNamedDistributionalEquivalent_refl x
  | unit hd hpos U _ ih =>
      have hxy : FixedNamedDistributionalEquivalent obs L _ _ :=
        U.sound hL hd hpos
      exact fixedNamedDistributionalEquivalent_trans ih
        (fixedNamedDistributionalEquivalent_symm hxy)
  | binary he hpos B _ _ ihx ihy =>
      exact NamedBinaryEvidence.sound hL he hpos B ihx ihy

/-- A derived tuple has the same componentwise observation type as its source
label. -/
theorem tupleType_eq_of_derives
    (hL : FixedNamedTupleSubstitutable f obs L)
    {d : Nat} {x u : Tuple α d}
    (h : AbstractLearnerDerives obs L f x u) :
    tupleType obs u = tupleType obs x :=
  (h.sound hL).1

/-- Any accepting context for the source tuple also accepts the derived tuple. -/
theorem mem_right_of_derives
    (hL : FixedNamedTupleSubstitutable f obs L)
    {d : Nat} {x u : Tuple α d}
    (h : AbstractLearnerDerives obs L f x u)
    {c : NamedSentenceContext α d}
    (hc : namedFill d c x ∈ L) :
    namedFill d c u ∈ L :=
  fixedNamedDistributionalEquivalent_mem_left
    (x := u)
    (y := x)
    (c := c)
    (h.sound hL)
    hc

/-- Any accepting context for the derived tuple also accepts the source tuple. -/
theorem mem_left_of_derives
    (hL : FixedNamedTupleSubstitutable f obs L)
    {d : Nat} {x u : Tuple α d}
    (h : AbstractLearnerDerives obs L f x u)
    {c : NamedSentenceContext α d}
    (hc : namedFill d c u ∈ L) :
    namedFill d c x ∈ L :=
  fixedNamedDistributionalEquivalent_mem_right
    (x := u)
    (y := x)
    (c := c)
    (h.sound hL)
    hc

/-- Unit extension preserves soundness by one additional semantic unit step.

This is a convenient named wrapper for later concrete learner files. -/
theorem sound_unit_step
    (hL : FixedNamedTupleSubstitutable f obs L)
    {d : Nat} {x y u : Tuple α d}
    (hd : d ≤ f)
    (hpos : 0 < d)
    (U : NamedUnitEvidence obs L x y)
    (hyu : AbstractLearnerDerives obs L f y u) :
    FixedNamedDistributionalEquivalent obs L u x :=
  (AbstractLearnerDerives.unit hd hpos U hyu).sound hL

/-- Binary composition preserves soundness by one additional semantic binary
witness step. -/
theorem sound_binary_step
    (hL : FixedNamedTupleSubstitutable f obs L)
    {e dB dC : Nat}
    {parent : NamedSentenceContext α e}
    {body : TemplateTuple α e dB dC}
    {x u : Tuple α dB}
    {y v : Tuple α dC}
    (he : e ≤ f)
    (hpos : 0 < e)
    (B : NamedBinaryEvidence L parent body x y)
    (hx : AbstractLearnerDerives obs L f x u)
    (hy : AbstractLearnerDerives obs L f y v) :
    FixedNamedDistributionalEquivalent obs L
      (evalTemplateTuple body u v)
      (evalTemplateTuple body x y) :=
  (AbstractLearnerDerives.binary he hpos B hx hy).sound hL

end AbstractLearnerDerives

end AbstractLearnerDerivation


section GrammarSpecialization

variable {N : Type w} {α : Type u} {M : Type v} [Monoid M]

/-- Grammar-language specialization of abstract learner soundness. -/
theorem grammarAbstractLearnerDerives_sound
    (G : WorkingMCFG N α)
    {f d : Nat} {obs : α → M}
    (hL : FixedNamedTupleSubstitutable f obs G.StringLanguage)
    {x u : Tuple α d}
    (h : AbstractLearnerDerives obs G.StringLanguage f x u) :
    GrammarNamedDistributionalEquivalent G obs u x :=
  h.sound hL

/-- Grammar-language specialization: a derived tuple has the same observation
type as its source label. -/
theorem grammarAbstractLearnerDerives_tupleType_eq
    (G : WorkingMCFG N α)
    {f d : Nat} {obs : α → M}
    (hL : FixedNamedTupleSubstitutable f obs G.StringLanguage)
    {x u : Tuple α d}
    (h : AbstractLearnerDerives obs G.StringLanguage f x u) :
    tupleType obs u = tupleType obs x :=
  (grammarAbstractLearnerDerives_sound G hL h).1

/-- Grammar-language specialization: accepting contexts transport from the
source tuple to the derived tuple. -/
theorem grammarAbstractLearnerDerives_mem_right
    (G : WorkingMCFG N α)
    {f d : Nat} {obs : α → M}
    (hL : FixedNamedTupleSubstitutable f obs G.StringLanguage)
    {x u : Tuple α d}
    (h : AbstractLearnerDerives obs G.StringLanguage f x u)
    {c : NamedSentenceContext α d}
    (hc : namedFill d c x ∈ G.StringLanguage) :
    namedFill d c u ∈ G.StringLanguage :=
  AbstractLearnerDerives.mem_right_of_derives hL h hc

end GrammarSpecialization

end MCFG
