/-
Copyright (c) 2026 Takayuki Kuriyama. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Takayuki Kuriyama
-/
import LeanCfgProject.MCFG2.WitnessedComposition

/-!
# LearnerSoundnessCore.lean

Eighth clean Lean experiment for the fixed-observation MCFG project.

This file extracts the semantic core of learner soundness.

The canonical learner in the paper has three important rule types for the
soundness proof:

* terminal rules;
* unit rules generated by same output type plus one shared accepting context;
* binary rules generated by witnessed template composition.

The full finite learner construction is postponed.  This file proves that the
semantic evidence used by such rules is sound with respect to the target
language promise.

No theorem here uses `sorry`.
-/

namespace MCFG

universe u v w

section NamedEquivalenceUtilities

variable {α : Type u} {M : Type v} [Monoid M]
variable {obs : α → M} {L : Set (Word α)}

/-- Named distributional equivalence is reflexive. -/
theorem fixedNamedDistributionalEquivalent_refl {d : Nat}
    (x : Tuple α d) :
    FixedNamedDistributionalEquivalent obs L x x :=
  FixedDistributionalEquivalent.refl (fill := namedFill) x

/-- Named distributional equivalence is symmetric. -/
theorem fixedNamedDistributionalEquivalent_symm {d : Nat}
    {x y : Tuple α d}
    (h : FixedNamedDistributionalEquivalent obs L x y) :
    FixedNamedDistributionalEquivalent obs L y x :=
  FixedDistributionalEquivalent.symm (fill := namedFill) h

/-- Named distributional equivalence is transitive. -/
theorem fixedNamedDistributionalEquivalent_trans {d : Nat}
    {x y z : Tuple α d}
    (hxy : FixedNamedDistributionalEquivalent obs L x y)
    (hyz : FixedNamedDistributionalEquivalent obs L y z) :
    FixedNamedDistributionalEquivalent obs L x z :=
  FixedDistributionalEquivalent.trans (fill := namedFill) hxy hyz

/-- Named distributional equivalence transports named-context membership. -/
theorem fixedNamedDistributionalEquivalent_mem_right {d : Nat}
    {x y : Tuple α d}
    (h : FixedNamedDistributionalEquivalent obs L x y)
    {c : NamedSentenceContext α d}
    (hc : namedFill d c x ∈ L) :
    namedFill d c y ∈ L :=
  FixedNamedDistributionalEquivalent.namedFill_mem_right h hc

/-- Named distributional equivalence transports named-context membership in the
reverse direction. -/
theorem fixedNamedDistributionalEquivalent_mem_left {d : Nat}
    {x y : Tuple α d}
    (h : FixedNamedDistributionalEquivalent obs L x y)
    {c : NamedSentenceContext α d}
    (hc : namedFill d c y ∈ L) :
    namedFill d c x ∈ L :=
  FixedNamedDistributionalEquivalent.namedFill_mem_left h hc

end NamedEquivalenceUtilities


section UnitRuleSoundness

variable {α : Type u} {M : Type v} [Monoid M]

/-- Semantic evidence for a learner unit rule between two observed tuples.

This is the target-language version of the learner condition:
same componentwise observation type and one shared accepting named context. -/
structure NamedUnitEvidence
    {d : Nat} (obs : α → M) (L : Set (Word α))
    (x y : Tuple α d) where
  context : NamedSentenceContext α d
  type_eq : tupleType obs x = tupleType obs y
  left_mem : namedFill d context x ∈ L
  right_mem : namedFill d context y ∈ L

namespace NamedUnitEvidence

/-- A semantic unit-rule evidence is sound under the fixed-observation promise. -/
theorem sound
    {f d : Nat} {obs : α → M} {L : Set (Word α)}
    (hL : FixedNamedTupleSubstitutable f obs L)
    (hd : d ≤ f)
    (hpos : 0 < d)
    {x y : Tuple α d}
    (U : NamedUnitEvidence obs L x y) :
    FixedNamedDistributionalEquivalent obs L x y :=
  fixedNamedDistributionalEquivalent_of_common_context
    hL hd hpos U.type_eq U.left_mem U.right_mem

/-- Unit-rule evidence can be reversed. -/
def symm
    {d : Nat} {obs : α → M} {L : Set (Word α)}
    {x y : Tuple α d}
    (U : NamedUnitEvidence obs L x y) :
    NamedUnitEvidence obs L y x :=
  { context := U.context,
    type_eq := U.type_eq.symm,
    left_mem := U.right_mem,
    right_mem := U.left_mem }

end NamedUnitEvidence

/-- Sample-level evidence for a unit rule is sound for a grammar target when
the finite sample is positive. -/
theorem sampleUnitEvidence_sound_for_grammar
    {N : Type w}
    (G : WorkingMCFG N α)
    {f d : Nat} {obs : α → M}
    (hL : FixedNamedTupleSubstitutable f obs G.StringLanguage)
    (hd : d ≤ f)
    (hpos : 0 < d)
    (K : Finset (Word α))
    (hK : PositiveSample G K)
    {x y : Tuple α d}
    (c : NamedSentenceContext α d)
    (htype : tupleType obs x = tupleType obs y)
    (hcx : namedFill d c x ∈ K)
    (hcy : namedFill d c y ∈ K) :
    GrammarNamedDistributionalEquivalent G obs x y := by
  exact grammarNamedDistributionalEquivalent_of_common_context
    G hd hpos hL htype
    (hK (namedFill d c x) hcx)
    (hK (namedFill d c y) hcy)

end UnitRuleSoundness


section BinaryRuleSoundness

variable {α : Type u} {M : Type v} [Monoid M]

/-- Semantic evidence for a learner binary rule.

A binary witness records:
* the parent named context;
* the binary template body;
* the target-language acceptance of the original composed tuple;
* filling-identity witnesses that allow child substitutions inside the parent
  context.

The `rightIdentity` field is indexed by the left tuple used after the first
replacement.  This reflects the proof order: replace the left child first, then
replace the right child while holding the new left child fixed. -/
structure NamedBinaryEvidence
    {e dB dC : Nat}
    (L : Set (Word α))
    (parent : NamedSentenceContext α e)
    (body : TemplateTuple α e dB dC)
    (x : Tuple α dB) (y : Tuple α dC) where
  parent_mem : namedFill e parent (evalTemplateTuple body x y) ∈ L
  leftIdentity : LeftFillingIdentity namedFill parent body y
  rightIdentity : ∀ u : Tuple α dB,
    RightFillingIdentity namedFill parent body u

namespace NamedBinaryEvidence

/-- Binary evidence transports acceptance along equivalent child tuples. -/
theorem accepts
    {e dB dC : Nat}
    {L : Set (Word α)} {obs : α → M}
    {parent : NamedSentenceContext α e}
    {body : TemplateTuple α e dB dC}
    {x u : Tuple α dB}
    {y v : Tuple α dC}
    (B : NamedBinaryEvidence L parent body x y)
    (hux : FixedNamedDistributionalEquivalent obs L u x)
    (hvy : FixedNamedDistributionalEquivalent obs L v y) :
    namedFill e parent (evalTemplateTuple body u v) ∈ L :=
  named_witnessedComposition_accepts
    B.leftIdentity (B.rightIdentity u) hux hvy B.parent_mem

/-- Binary evidence is sound under the fixed-observation promise: equivalent
children produce equivalent parents. -/
theorem sound
    {f e dB dC : Nat}
    {L : Set (Word α)} {obs : α → M}
    (hL : FixedNamedTupleSubstitutable f obs L)
    (he : e ≤ f)
    (hpos : 0 < e)
    {parent : NamedSentenceContext α e}
    {body : TemplateTuple α e dB dC}
    {x u : Tuple α dB}
    {y v : Tuple α dC}
    (B : NamedBinaryEvidence L parent body x y)
    (hux : FixedNamedDistributionalEquivalent obs L u x)
    (hvy : FixedNamedDistributionalEquivalent obs L v y) :
    FixedNamedDistributionalEquivalent obs L
      (evalTemplateTuple body u v)
      (evalTemplateTuple body x y) :=
  named_witnessedComposition_preserves_equivalence
    hL he hpos B.leftIdentity (B.rightIdentity u) hux hvy B.parent_mem

/-- The original composed tuple is equivalent to itself. -/
theorem sound_self
    {f e dB dC : Nat}
    {L : Set (Word α)} {obs : α → M}
    (hL : FixedNamedTupleSubstitutable f obs L)
    (he : e ≤ f)
    (hpos : 0 < e)
    {parent : NamedSentenceContext α e}
    {body : TemplateTuple α e dB dC}
    {x : Tuple α dB}
    {y : Tuple α dC}
    (B : NamedBinaryEvidence L parent body x y) :
    FixedNamedDistributionalEquivalent obs L
      (evalTemplateTuple body x y)
      (evalTemplateTuple body x y) :=
  sound hL he hpos B
    (fixedNamedDistributionalEquivalent_refl x)
    (fixedNamedDistributionalEquivalent_refl y)

end NamedBinaryEvidence

/-- Grammar-language specialization of binary evidence soundness. -/
theorem grammarBinaryEvidence_sound
    {N : Type w}
    (G : WorkingMCFG N α)
    {f e dB dC : Nat} {obs : α → M}
    (hL : FixedNamedTupleSubstitutable f obs G.StringLanguage)
    (he : e ≤ f)
    (hpos : 0 < e)
    {parent : NamedSentenceContext α e}
    {body : TemplateTuple α e dB dC}
    {x u : Tuple α dB}
    {y v : Tuple α dC}
    (B : NamedBinaryEvidence G.StringLanguage parent body x y)
    (hux : GrammarNamedDistributionalEquivalent G obs u x)
    (hvy : GrammarNamedDistributionalEquivalent G obs v y) :
    GrammarNamedDistributionalEquivalent G obs
      (evalTemplateTuple body u v)
      (evalTemplateTuple body x y) :=
  NamedBinaryEvidence.sound hL he hpos B hux hvy

end BinaryRuleSoundness


section TerminalRuleSoundness

variable {α : Type u} {M : Type v} [Monoid M]
variable {obs : α → M} {L : Set (Word α)}

/-- A terminal tuple is distributionally equivalent to itself. -/
theorem terminalTuple_sound_self (a : α) :
    FixedNamedDistributionalEquivalent obs L
      (singletonTuple ([a] : Word α))
      (singletonTuple ([a] : Word α)) :=
  fixedNamedDistributionalEquivalent_refl
    (singletonTuple ([a] : Word α))

/-- Any observed tuple is distributionally equivalent to itself.

This is the semantic core of the learner's identity/base case. -/
theorem observedTuple_sound_self {d : Nat} (x : Tuple α d) :
    FixedNamedDistributionalEquivalent obs L x x :=
  fixedNamedDistributionalEquivalent_refl x

end TerminalRuleSoundness

end MCFG
