/-
Copyright (c) 2026 Takayuki Kuriyama. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Takayuki Kuriyama
-/
import LeanCfgProject.MCFG2.CharacteristicSampleExactOnceSuccessfulOccurrenceRoute

/-!
# OutputTypeTrimmedPresentationSuccessfulOccurrenceConstruction.lean

`TrimmedOutputTypePresentation` still stores an abstract
`TrimmedNonterminalWitnesses` field: for every present typed nonterminal it
assumes an anchor tuple, an exposing named context, a type equation, and
positivity of the exposed anchor word.

The preceding files constructed a more concrete semantic object,

```lean
ExactSuccessfulDerivationOccurrence G A x c
```

recording that `x` occurs at nonterminal `A` in a successful exact-once
derivation and that the surrounding derivation induces the context `c`.

This file uses those concrete occurrences to construct the entire
`TrimmedNonterminalWitnesses` object.  For every present typed nonterminal we
supply:

* a successful occurrence whose tuple has the stored output type;
* the occurrence tuple as the anchor;
* the occurrence context as the exposing context;
* anchor positivity from the successful occurrence itself;
* universal acceptance of every derivable tuple from the occurrence spine.

Thus the witness component of a trimmed output-type presentation is no longer
an unrelated semantic assumption: it is generated by explicit successful
derivation occurrences.

This file does not yet construct the finite complete presentation or choose one
typed representative for every base nonterminal.  It isolates and discharges
the successful-occurrence-to-trimmed-witnesses construction.
-/

namespace MCFG

universe u v w

section PresentTypedSuccessfulOccurrences

variable {N : Type v} {α : Type u} {M : Type w}
variable [DecidableEq α] [Monoid M]
variable {G : WorkingMCFG N α} {obs : α → M}
variable {P : OutputTypeRefinementPresentation G obs}

/-- A concrete successful occurrence realizing one present typed
nonterminal.

The successful occurrence supplies derivability and its surrounding exposing
context.  The final field states that the selected occurrence tuple has exactly
the output type stored in the typed nonterminal. -/
structure PresentTypedSuccessfulOccurrence
    (X : PresentTypedNonterminal P) where
  anchor :
    Tuple α (G.arity X.node.base)

  expose :
    NamedSentenceContext α (G.arity X.node.base)

  occurrence :
    ExactSuccessfulDerivationOccurrence G X.node.base anchor expose

  anchor_matches :
    X.node.Matches obs anchor

namespace PresentTypedSuccessfulOccurrence

variable {X : PresentTypedNonterminal P}

/-- The selected anchor is genuinely derivable from the base nonterminal. -/
def anchorDerives
    (O : PresentTypedSuccessfulOccurrence X) :
    DerivesTuple G X.node.base O.anchor :=
  O.occurrence.derives

/-- The selected exposing context is generated by an explicit successful
derivation spine. -/
def exposeSpine
    (O : PresentTypedSuccessfulOccurrence X) :
    ExactSuccessfulDerivationSpine G X.node.base O.expose :=
  O.occurrence.spine

/-- The selected exposed anchor word belongs to the target language. -/
theorem expose_accepts_anchor
    (O : PresentTypedSuccessfulOccurrence X) :
    namedFill (G.arity X.node.base) O.expose O.anchor ∈
      G.StringLanguage :=
  O.occurrence.accepts

/-- The successful occurrence spine accepts every tuple derivable from the
same base nonterminal. -/
theorem expose_accepts_derives
    (O : PresentTypedSuccessfulOccurrence X)
    {x : Tuple α (G.arity X.node.base)}
    (hx : DerivesTuple G X.node.base x) :
    namedFill (G.arity X.node.base) O.expose x ∈
      G.StringLanguage :=
  O.exposeSpine.acceptsDerives hx

/-- The selected tuple has the stored componentwise observation type. -/
theorem anchor_tupleType
    (O : PresentTypedSuccessfulOccurrence X) :
    tupleType obs O.anchor = X.node.out :=
  O.anchor_matches

/-- A successful typed occurrence gives the corresponding ordinary exposed
tuple witness. -/
theorem exposedWithContext
    (O : PresentTypedSuccessfulOccurrence X) :
    ExposedWithContext G X.node.base O.anchor O.expose :=
  O.occurrence.exposedWithContext

end PresentTypedSuccessfulOccurrence

end PresentTypedSuccessfulOccurrences


section SuccessfulOccurrenceFamilies

variable {N : Type v} {α : Type u} {M : Type w}
variable [DecidableEq α] [Monoid M]
variable {G : WorkingMCFG N α} {obs : α → M}
variable {P : OutputTypeRefinementPresentation G obs}

/-- A concrete successful occurrence for every typed nonterminal present in a
finite output-type presentation. -/
structure TypedSuccessfulOccurrenceFamily
    (P : OutputTypeRefinementPresentation G obs) where
  occurrence :
    ∀ X : PresentTypedNonterminal P,
      PresentTypedSuccessfulOccurrence X

namespace TypedSuccessfulOccurrenceFamily

/-- The occurrence family constructs all anchor/exposure witnesses required by
`TrimmedOutputTypePresentation`. -/
def toTrimmedNonterminalWitnesses
    (F : TypedSuccessfulOccurrenceFamily P) :
    TrimmedNonterminalWitnesses P where
  anchor := fun X =>
    (F.occurrence X).anchor

  expose := fun X =>
    (F.occurrence X).expose

  anchor_matches := fun X =>
    (F.occurrence X).anchor_matches

  expose_accepts := fun X =>
    (F.occurrence X).expose_accepts_anchor

@[simp] theorem toTrimmedNonterminalWitnesses_anchor
    (F : TypedSuccessfulOccurrenceFamily P)
    (X : PresentTypedNonterminal P) :
    F.toTrimmedNonterminalWitnesses.anchor X =
      (F.occurrence X).anchor :=
  rfl

@[simp] theorem toTrimmedNonterminalWitnesses_expose
    (F : TypedSuccessfulOccurrenceFamily P)
    (X : PresentTypedNonterminal P) :
    F.toTrimmedNonterminalWitnesses.expose X =
      (F.occurrence X).expose :=
  rfl

/-- Every constructed typed anchor is genuinely derivable. -/
theorem anchor_derives
    (F : TypedSuccessfulOccurrenceFamily P)
    (X : PresentTypedNonterminal P) :
    DerivesTuple G X.node.base
      (F.toTrimmedNonterminalWitnesses.anchor X) :=
  (F.occurrence X).anchorDerives

/-- Every constructed exposing context accepts every tuple derivable from its
typed nonterminal's base. -/
theorem expose_accepts_derives
    (F : TypedSuccessfulOccurrenceFamily P)
    (X : PresentTypedNonterminal P)
    {x : Tuple α (G.arity X.node.base)}
    (hx : DerivesTuple G X.node.base x) :
    namedFill (G.arity X.node.base)
        (F.toTrimmedNonterminalWitnesses.expose X)
        x ∈
      G.StringLanguage :=
  (F.occurrence X).expose_accepts_derives hx

/-- The constructed anchor has the output type stored in the present typed
nonterminal. -/
theorem anchor_tupleType
    (F : TypedSuccessfulOccurrenceFamily P)
    (X : PresentTypedNonterminal P) :
    tupleType obs
        (F.toTrimmedNonterminalWitnesses.anchor X) =
      X.node.out :=
  (F.occurrence X).anchor_tupleType

/-- The constructed anchor/context pair is a successful ordinary exposure
witness. -/
theorem anchor_exposed
    (F : TypedSuccessfulOccurrenceFamily P)
    (X : PresentTypedNonterminal P) :
    ExposedWithContext G X.node.base
      (F.toTrimmedNonterminalWitnesses.anchor X)
      (F.toTrimmedNonterminalWitnesses.expose X) :=
  (F.occurrence X).exposedWithContext

end TypedSuccessfulOccurrenceFamily

end SuccessfulOccurrenceFamilies


section CompletePresentationConstruction

variable {N : Type v} {α : Type u} {M : Type w}
variable [DecidableEq α] [Monoid M]
variable {G : WorkingMCFG N α} {obs : α → M}

namespace CompleteOutputTypePresentation

/-- Equip a complete finite output-type presentation with the anchor and
exposing-context witnesses generated by explicit successful occurrences. -/
def withSuccessfulOccurrences
    (C : CompleteOutputTypePresentation G obs)
    (F : TypedSuccessfulOccurrenceFamily C.presentation) :
    TrimmedOutputTypePresentation G obs :=
  TrimmedOutputTypePresentation.ofComplete C
    F.toTrimmedNonterminalWitnesses

@[simp] theorem withSuccessfulOccurrences_presentation
    (C : CompleteOutputTypePresentation G obs)
    (F : TypedSuccessfulOccurrenceFamily C.presentation) :
    (C.withSuccessfulOccurrences F).presentation =
      C.presentation :=
  rfl

@[simp] theorem withSuccessfulOccurrences_anchor
    (C : CompleteOutputTypePresentation G obs)
    (F : TypedSuccessfulOccurrenceFamily C.presentation)
    (X : PresentTypedNonterminal C.presentation) :
    (C.withSuccessfulOccurrences F).anchor X =
      (F.occurrence X).anchor :=
  rfl

@[simp] theorem withSuccessfulOccurrences_expose
    (C : CompleteOutputTypePresentation G obs)
    (F : TypedSuccessfulOccurrenceFamily C.presentation)
    (X : PresentTypedNonterminal C.presentation) :
    (C.withSuccessfulOccurrences F).expose X =
      (F.occurrence X).expose :=
  rfl

/-- The anchor selected by the constructed trimmed presentation is genuinely
derived. -/
theorem withSuccessfulOccurrences_anchor_derives
    (C : CompleteOutputTypePresentation G obs)
    (F : TypedSuccessfulOccurrenceFamily C.presentation)
    (X : PresentTypedNonterminal C.presentation) :
    DerivesTuple G X.node.base
      ((C.withSuccessfulOccurrences F).anchor X) :=
  (F.occurrence X).anchorDerives

/-- The exposing context selected by the constructed trimmed presentation
accepts every tuple derivable from the corresponding base nonterminal. -/
theorem withSuccessfulOccurrences_expose_accepts_derives
    (C : CompleteOutputTypePresentation G obs)
    (F : TypedSuccessfulOccurrenceFamily C.presentation)
    (X : PresentTypedNonterminal C.presentation)
    {x : Tuple α (G.arity X.node.base)}
    (hx : DerivesTuple G X.node.base x) :
    namedFill (G.arity X.node.base)
        ((C.withSuccessfulOccurrences F).expose X)
        x ∈
      G.StringLanguage :=
  (F.occurrence X).expose_accepts_derives hx

/-- The constructed trimmed presentation stores the intended observation type
at every selected anchor. -/
theorem withSuccessfulOccurrences_anchor_tupleType
    (C : CompleteOutputTypePresentation G obs)
    (F : TypedSuccessfulOccurrenceFamily C.presentation)
    (X : PresentTypedNonterminal C.presentation) :
    tupleType obs
        ((C.withSuccessfulOccurrences F).anchor X) =
      X.node.out :=
  (F.occurrence X).anchor_tupleType

/-- Every selected anchor/context pair in the constructed trimmed presentation
is an explicit successful occurrence. -/
theorem withSuccessfulOccurrences_anchor_occurrence
    (C : CompleteOutputTypePresentation G obs)
    (F : TypedSuccessfulOccurrenceFamily C.presentation)
    (X : PresentTypedNonterminal C.presentation) :
    ExactSuccessfulDerivationOccurrence G X.node.base
      ((C.withSuccessfulOccurrences F).anchor X)
      ((C.withSuccessfulOccurrences F).expose X) :=
  F.occurrence X |>.occurrence

/-- The constructed trimmed presentation retains the complete presentation's
language exactly. -/
theorem withSuccessfulOccurrences_language_eq
    (C : CompleteOutputTypePresentation G obs)
    (F : TypedSuccessfulOccurrenceFamily C.presentation) :
    (C.withSuccessfulOccurrences F).language =
      G.StringLanguage :=
  (C.withSuccessfulOccurrences F).language_eq

end CompleteOutputTypePresentation

end CompletePresentationConstruction


section PackagedSuccessfulTrimmedPresentation

variable {N : Type v} {α : Type u} {M : Type w}
variable [DecidableEq α] [Monoid M]
variable {G : WorkingMCFG N α} {obs : α → M}

/-- A complete finite typed presentation together with explicit successful
occurrences for all of its present typed nonterminals.

This is a concrete construction package for the witness-bearing trimmed
presentation layer. -/
structure SuccessfulOccurrenceCompletePresentation
    (G : WorkingMCFG N α) (obs : α → M) where
  completePresentation :
    CompleteOutputTypePresentation G obs

  occurrences :
    TypedSuccessfulOccurrenceFamily
      completePresentation.presentation

namespace SuccessfulOccurrenceCompletePresentation

/-- Construct the witness-bearing trimmed output-type presentation. -/
def toTrimmedOutputTypePresentation
    (S : SuccessfulOccurrenceCompletePresentation G obs) :
    TrimmedOutputTypePresentation G obs :=
  S.completePresentation.withSuccessfulOccurrences S.occurrences

/-- The constructed presentation has exactly the target language. -/
theorem language_eq
    (S : SuccessfulOccurrenceCompletePresentation G obs) :
    S.toTrimmedOutputTypePresentation.language =
      G.StringLanguage :=
  S.toTrimmedOutputTypePresentation.language_eq

/-- Every typed anchor in the constructed presentation is genuinely
derivable. -/
theorem anchor_derives
    (S : SuccessfulOccurrenceCompletePresentation G obs)
    (X :
      PresentTypedNonterminal
        S.completePresentation.presentation) :
    DerivesTuple G X.node.base
      (S.toTrimmedOutputTypePresentation.anchor X) :=
  S.completePresentation.withSuccessfulOccurrences_anchor_derives
    S.occurrences X

/-- Every typed exposing context in the constructed presentation accepts all
tuples derivable from its base nonterminal. -/
theorem expose_accepts_derives
    (S : SuccessfulOccurrenceCompletePresentation G obs)
    (X :
      PresentTypedNonterminal
        S.completePresentation.presentation)
    {x : Tuple α (G.arity X.node.base)}
    (hx : DerivesTuple G X.node.base x) :
    namedFill (G.arity X.node.base)
        (S.toTrimmedOutputTypePresentation.expose X)
        x ∈
      G.StringLanguage :=
  S.completePresentation.withSuccessfulOccurrences_expose_accepts_derives
    S.occurrences X hx

/-- Every typed anchor/context pair is represented by an explicit successful
occurrence. -/
theorem anchor_occurrence
    (S : SuccessfulOccurrenceCompletePresentation G obs)
    (X :
      PresentTypedNonterminal
        S.completePresentation.presentation) :
    ExactSuccessfulDerivationOccurrence G X.node.base
      (S.toTrimmedOutputTypePresentation.anchor X)
      (S.toTrimmedOutputTypePresentation.expose X) :=
  S.completePresentation.withSuccessfulOccurrences_anchor_occurrence
    S.occurrences X

end SuccessfulOccurrenceCompletePresentation

end PackagedSuccessfulTrimmedPresentation

end MCFG
