/-
Copyright (c) 2026 Takayuki Kuriyama. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Takayuki Kuriyama
-/
import LeanCfgProject.MCFG2.CharacteristicSampleExactOnceCanonicalRuleClosureRoute

/-!
# OutputTypePresentationWorkingGrammar.lean

The output-type-refinement layer has so far represented a finite typed grammar
by `OutputTypeRefinementPresentation`.  This file turns such a presentation
into an actual `WorkingMCFG`.

The new grammar has:

* one fresh start nonterminal;
* one grammar nonterminal for every output-typed nonterminal;
* the original start arity at the fresh start;
* one lifted start rule for every present typed start rule;
* one lifted terminal rule for every present typed terminal rule;
* one lifted binary rule for every present typed binary rule.

Presentation derivations lift to derivations of this concrete grammar, and
presentation string derivations lift to its generated string language.
Moreover, basic and exact working conditions are inherited from the original
grammar because every present typed rule carries an original-rule membership
certificate.

This is a genuine grammar construction: the output is a concrete
`WorkingMCFG`, not another theorem-facing assumption record.
-/

namespace MCFG

universe u v w

section PresentationGrammarSyntax

variable {N : Type v} {α : Type u} {M : Type w}

/-- Nonterminals of the concrete grammar generated by an output-type
presentation.

`start` is a fresh start symbol.  `typed X` is the grammar nonterminal
corresponding to the output-typed nonterminal `X`. -/
inductive PresentationGrammarNonterminal
    (G : WorkingMCFG N α) (M : Type w) where
  | start
  | typed (node : TypedNonterminal G M)

/-- Arity of the concrete presentation grammar. -/
def presentationGrammarArity
    (G : WorkingMCFG N α) :
    PresentationGrammarNonterminal G M → Nat
  | .start => G.arity G.start
  | .typed X => G.arity X.base

@[simp] theorem presentationGrammarArity_start
    (G : WorkingMCFG N α) :
    presentationGrammarArity (M := M) G
        (PresentationGrammarNonterminal.start) =
      G.arity G.start :=
  rfl

@[simp] theorem presentationGrammarArity_typed
    (G : WorkingMCFG N α)
    (X : TypedNonterminal G M) :
    presentationGrammarArity (M := M) G
        (PresentationGrammarNonterminal.typed X) =
      G.arity X.base :=
  rfl

end PresentationGrammarSyntax


section LiftedPresentationRules

variable {N : Type v} {α : Type u} {M : Type w}
variable [Monoid M]
variable {G : WorkingMCFG N α} {obs : α → M}

/-- Lift a typed start rule to the concrete presentation grammar. -/
def liftPresentationStartRule
    (σ : TypedStartRule G M) :
    StartRule (PresentationGrammarNonterminal G M) where
  child := .typed σ.child

/-- Lift a typed terminal rule to the concrete presentation grammar. -/
def liftPresentationTerminalRule
    (τ : TypedTerminalRule G) :
    TerminalRule (PresentationGrammarNonterminal G M) α where
  lhs := .typed (τ.lhs obs)
  terminal := τ.baseRule.terminal

/-- Lift a typed binary rule to the concrete presentation grammar. -/
def liftPresentationBinaryRule
    (τ : TypedBinaryRule G M) :
    BinaryRule
      (PresentationGrammarNonterminal G M)
      α
      (presentationGrammarArity (M := M) G) where
  lhs := .typed (τ.lhs obs)
  left := .typed τ.left
  right := .typed τ.right
  body := τ.baseRule.body

@[simp] theorem liftPresentationStartRule_child
    (σ : TypedStartRule G M) :
    (liftPresentationStartRule σ).child =
      PresentationGrammarNonterminal.typed σ.child :=
  rfl

@[simp] theorem liftPresentationTerminalRule_lhs
    (τ : TypedTerminalRule G) :
    (liftPresentationTerminalRule (M := M) (obs := obs) τ).lhs =
      PresentationGrammarNonterminal.typed (τ.lhs obs) :=
  rfl

@[simp] theorem liftPresentationTerminalRule_terminal
    (τ : TypedTerminalRule G) :
    (liftPresentationTerminalRule (M := M) (obs := obs) τ).terminal =
      τ.baseRule.terminal :=
  rfl

@[simp] theorem liftPresentationBinaryRule_lhs
    (τ : TypedBinaryRule G M) :
    (liftPresentationBinaryRule (obs := obs) τ).lhs =
      PresentationGrammarNonterminal.typed (τ.lhs obs) :=
  rfl

@[simp] theorem liftPresentationBinaryRule_left
    (τ : TypedBinaryRule G M) :
    (liftPresentationBinaryRule (obs := obs) τ).left =
      PresentationGrammarNonterminal.typed τ.left :=
  rfl

@[simp] theorem liftPresentationBinaryRule_right
    (τ : TypedBinaryRule G M) :
    (liftPresentationBinaryRule (obs := obs) τ).right =
      PresentationGrammarNonterminal.typed τ.right :=
  rfl

@[simp] theorem liftPresentationBinaryRule_body
    (τ : TypedBinaryRule G M) :
    (liftPresentationBinaryRule (obs := obs) τ).body =
      τ.baseRule.body :=
  rfl

end LiftedPresentationRules


section ConcretePresentationGrammar

variable {N : Type v} {α : Type u} {M : Type w}
variable [Monoid M]
variable {G : WorkingMCFG N α} {obs : α → M}

/-- The concrete working grammar carried by a finite output-type
presentation. -/
def OutputTypeRefinementPresentation.toWorkingMCFG
    (P : OutputTypeRefinementPresentation G obs) :
    WorkingMCFG (PresentationGrammarNonterminal G M) α where

  start := .start

  arity := presentationGrammarArity (M := M) G

  arity_pos := by
    intro A
    cases A with
    | start =>
        exact G.arity_pos G.start
    | typed X =>
        exact G.arity_pos X.base

  startRules :=
    P.startRules.toList.map liftPresentationStartRule

  terminalRules :=
    P.terminalRules.toList.map
      (liftPresentationTerminalRule (M := M) (obs := obs))

  binaryRules :=
    P.binaryRules.toList.map
      (liftPresentationBinaryRule (obs := obs))

namespace OutputTypeRefinementPresentation

variable (P : OutputTypeRefinementPresentation G obs)

/-- Every present typed start rule occurs in the concrete grammar. -/
theorem liftStartRule_mem
    {σ : TypedStartRule G M}
    (hσ : P.HasStartRule σ) :
    liftPresentationStartRule σ ∈
      P.toWorkingMCFG.startRules := by
  simp [OutputTypeRefinementPresentation.toWorkingMCFG, hσ]

/-- Every present typed terminal rule occurs in the concrete grammar. -/
theorem liftTerminalRule_mem
    {τ : TypedTerminalRule G}
    (hτ : P.HasTerminalRule τ) :
    liftPresentationTerminalRule (M := M) (obs := obs) τ ∈
      P.toWorkingMCFG.terminalRules := by
  simp [OutputTypeRefinementPresentation.toWorkingMCFG, hτ]

/-- Every present typed binary rule occurs in the concrete grammar. -/
theorem liftBinaryRule_mem
    {τ : TypedBinaryRule G M}
    (hτ : P.HasBinaryRule τ) :
    liftPresentationBinaryRule (obs := obs) τ ∈
      P.toWorkingMCFG.binaryRules := by
  simp [OutputTypeRefinementPresentation.toWorkingMCFG, hτ]

/-- The fresh start retains the original start arity. -/
theorem toWorkingMCFG_start_arity :
    P.toWorkingMCFG.arity P.toWorkingMCFG.start =
      G.arity G.start :=
  rfl

/-- A lifted start rule retains the original typed start-rule arity
equation. -/
theorem liftStartRule_wellTyped
    (σ : TypedStartRule G M) :
    (liftPresentationStartRule σ).WellTyped
      P.toWorkingMCFG := by
  exact σ.wellTyped

/-- A lifted terminal rule is well typed. -/
theorem liftTerminalRule_wellTyped
    (τ : TypedTerminalRule G) :
    TerminalRule.WellTyped
      P.toWorkingMCFG.arity
      (liftPresentationTerminalRule
        (M := M) (obs := obs) τ) := by
  exact τ.wellTyped

/-- Basic working conditions pass from the original grammar to the concrete
presentation grammar. -/
theorem toWorkingMCFG_basicWorkingConditions
    (hworking : G.BasicWorkingConditions) :
    P.toWorkingMCFG.BasicWorkingConditions := by
  refine ⟨?_, ?_, ?_, ?_⟩
  · exact hworking.1
  · intro ρ hρ
    rcases List.mem_map.mp hρ with ⟨σ, hσ, rfl⟩
    exact P.liftStartRule_wellTyped σ
  · intro ρ hρ
    rcases List.mem_map.mp hρ with ⟨τ, hτ, rfl⟩
    exact P.liftTerminalRule_wellTyped τ
  · intro ρ hρ
    rcases List.mem_map.mp hρ with ⟨τ, hτ, rfl⟩
    exact hworking.2.2.2 τ.baseRule τ.inGrammar

/-- Exact-once working conditions pass from the original grammar to the
concrete presentation grammar. -/
theorem toWorkingMCFG_exactWorkingConditions
    (hworking : G.ExactWorkingConditions) :
    P.toWorkingMCFG.ExactWorkingConditions := by
  refine ⟨P.toWorkingMCFG_basicWorkingConditions hworking.basic, ?_⟩
  intro ρ hρ
  rcases List.mem_map.mp hρ with ⟨τ, hτ, rfl⟩
  exact hworking.2 τ.baseRule τ.inGrammar

/-- A fan-out bound for the original grammar is inherited by the concrete
presentation grammar. -/
theorem toWorkingMCFG_fanoutAtMost
    {f : Nat}
    (hfan : G.FanoutAtMost f) :
    P.toWorkingMCFG.FanoutAtMost f := by
  intro A
  cases A with
  | start =>
      exact hfan G.start
  | typed X =>
      exact hfan X.base

end OutputTypeRefinementPresentation

end ConcretePresentationGrammar


section PresentationDerivationEmbedding

variable {N : Type v} {α : Type u} {M : Type w}
variable [Monoid M]
variable {G : WorkingMCFG N α} {obs : α → M}
variable {P : OutputTypeRefinementPresentation G obs}

namespace PresentationDerives

/-- Every tuple derivation of a finite typed presentation is a derivation of
the concrete working grammar constructed from that presentation. -/
theorem toWorkingMCFG
    {X : TypedNonterminal G M}
    {x : Tuple α (G.arity X.base)}
    (h : PresentationDerives P X x) :
    DerivesTuple P.toWorkingMCFG
      (PresentationGrammarNonterminal.typed X)
      x := by
  induction h with
  | terminal hτ =>
      exact DerivesTuple.terminal
        (P.liftTerminalRule_mem hτ)
        τ.wellTyped
  | binary hτ hx hy ihx ihy =>
      exact DerivesTuple.binary
        (P.liftBinaryRule_mem hτ)
        ihx ihy

end PresentationDerives


namespace PresentationStringDerives

/-- Every presentation string derivation is a string derivation of the
concrete working grammar constructed from the presentation. -/
theorem toWorkingMCFG
    {word : Word α}
    (D : PresentationStringDerives P word) :
    word ∈ P.toWorkingMCFG.StringLanguage := by
  refine ⟨D.start_arity, ?_⟩
  have hstart :
      DerivesTuple P.toWorkingMCFG
        P.toWorkingMCFG.start
        (castTuple D.startRule.wellTyped D.childTuple) :=
    DerivesTuple.start
      (P.liftStartRule_mem D.start_mem)
      D.child_derives.toWorkingMCFG
      D.startRule.wellTyped
  rw [D.word_eq]
  exact hstart

end PresentationStringDerives

/-- The language of a finite typed presentation is contained in the language
of its concrete working grammar. -/
theorem presentationStringLanguage_subset_workingGrammar
    (P : OutputTypeRefinementPresentation G obs) :
    PresentationStringLanguage P ⊆
      P.toWorkingMCFG.StringLanguage := by
  intro word hword
  exact hword.toWorkingMCFG

end PresentationDerivationEmbedding


section CompletePresentationEmbedding

variable {N : Type v} {α : Type u} {M : Type w}
variable [Monoid M]
variable {G : WorkingMCFG N α} {obs : α → M}

/-- A complete finite presentation embeds the whole original target language
into the concrete working grammar generated by that presentation. -/
theorem CompleteOutputTypePresentation.original_subset_workingGrammar
    (C : CompleteOutputTypePresentation G obs) :
    G.StringLanguage ⊆
      C.presentation.toWorkingMCFG.StringLanguage := by
  intro word hword
  exact
    presentationStringLanguage_subset_workingGrammar
      C.presentation
      (C.complete.mem_presentation hword)

/-- The concrete grammar generated by a complete presentation contains every
word generated by that presentation. -/
theorem CompleteOutputTypePresentation.presentation_subset_workingGrammar
    (C : CompleteOutputTypePresentation G obs) :
    C.language ⊆
      C.presentation.toWorkingMCFG.StringLanguage :=
  presentationStringLanguage_subset_workingGrammar C.presentation

/-- Exact working conditions and fan-out bounds transfer to the concrete
grammar generated by a complete presentation. -/
theorem CompleteOutputTypePresentation.workingGrammar_conditions
    (C : CompleteOutputTypePresentation G obs)
    (hworking : G.ExactWorkingConditions)
    {f : Nat}
    (hfan : G.FanoutAtMost f) :
    C.presentation.toWorkingMCFG.ExactWorkingConditions ∧
      C.presentation.toWorkingMCFG.FanoutAtMost f :=
  ⟨C.presentation.toWorkingMCFG_exactWorkingConditions hworking,
    C.presentation.toWorkingMCFG_fanoutAtMost hfan⟩

end CompletePresentationEmbedding

end MCFG
