/-
Copyright (c) 2026 Takayuki Kuriyama. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Takayuki Kuriyama
-/
import LeanCfgProject.MCFG2.OutputTypeRefinementPresentation

/-!
# OutputTypePresentationLanguage.lean

Thirty-eighth clean Lean experiment for the fixed-observation MCFG project.

`OutputTypeRefinementPresentation.lean` introduced finite presentations of
typed nonterminals and typed terminal/binary/start rules.

This file adds the string-language layer for such a finite typed presentation.
A word is generated by the presentation if some present typed start rule selects
a present typed child derivation whose transported tuple is the singleton tuple
of that word.

The main theorem says that the string language of any typed presentation is
included in the string language of the original grammar.

No theorem here uses `sorry`.
-/

namespace MCFG

universe u v w

section PresentationStringLanguage

variable {N : Type v} {α : Type u} {M : Type w} [Monoid M]
variable {G : WorkingMCFG N α} {obs : α → M}

/-- A word is derived by a finite output-type presentation if a present typed
start rule selects a tuple derived by the typed presentation, and after the
start-rule arity transport the tuple is the singleton tuple of the word. -/
structure PresentationStringDerives
    (P : OutputTypeRefinementPresentation G obs)
    (word : Word α) where
  startRule : TypedStartRule G M
  start_mem : P.HasStartRule startRule
  childTuple : Tuple α (G.arity startRule.baseRule.child)
  child_derives : PresentationDerives P startRule.child childTuple
  start_arity : 1 = G.arity G.start
  word_eq :
    castTuple start_arity (singletonTuple word) =
      castTuple startRule.wellTyped childTuple

namespace PresentationStringDerives

variable {P : OutputTypeRefinementPresentation G obs}
variable {word : Word α}

/-- The selected typed start-rule child is present among the finite typed
nonterminals of the presentation. -/
theorem child_present
    (D : PresentationStringDerives P word) :
    P.HasNonterminal D.startRule.child :=
  P.start_child_present D.start_mem

/-- The child derivation of a presentation string derivation erases to an
ordinary derivation in the original grammar. -/
theorem child_erases
    (D : PresentationStringDerives P word) :
    DerivesTuple G D.startRule.baseRule.child D.childTuple :=
  D.child_derives.erase

/-- The child derivation also yields an output-typed derivation over the
original grammar. -/
theorem child_output_typed_derives
    (D : PresentationStringDerives P word) :
    OutputTypedDerives (G := G) (obs := obs)
      D.startRule.child D.childTuple :=
  D.child_derives.toOutputTypedDerives

/-- The derived child tuple has the output type stored in the typed start rule. -/
theorem child_tuple_type_eq
    (D : PresentationStringDerives P word) :
    tupleType obs D.childTuple = D.startRule.childOut :=
  D.child_derives.tuple_type_eq

/-- A presentation string derivation gives membership in the original grammar's
string language. -/
theorem sound
    (D : PresentationStringDerives P word) :
    word ∈ G.StringLanguage :=
  mem_stringLanguage_of_typedStartRule
    (G := G) (obs := obs)
    D.startRule
    D.child_output_typed_derives
    D.start_arity
    word
    D.word_eq

end PresentationStringDerives

/-- The string language generated by a finite output-type presentation. -/
def PresentationStringLanguage
    (P : OutputTypeRefinementPresentation G obs) : Set (Word α) :=
  { word | Nonempty (PresentationStringDerives P word) }

/-- The presentation string language is sound with respect to the original
grammar. -/
theorem presentationStringLanguage_sound
    (P : OutputTypeRefinementPresentation G obs) :
    PresentationStringLanguage P ⊆ G.StringLanguage := by
  intro word hword
  rcases hword with ⟨D⟩
  exact D.sound

/-- Pointwise soundness form. -/
theorem mem_original_of_mem_presentationStringLanguage
    (P : OutputTypeRefinementPresentation G obs)
    {word : Word α}
    (hword : word ∈ PresentationStringLanguage P) :
    word ∈ G.StringLanguage :=
  presentationStringLanguage_sound P hword

/-- A constructor form for membership in the presentation string language. -/
theorem mem_presentationStringLanguage_of_start
    (P : OutputTypeRefinementPresentation G obs)
    {word : Word α}
    (startRule : TypedStartRule G M)
    (hstartRule : P.HasStartRule startRule)
    (childTuple : Tuple α (G.arity startRule.baseRule.child))
    (hchild : PresentationDerives P startRule.child childTuple)
    (hstart : 1 = G.arity G.start)
    (hword :
      castTuple hstart (singletonTuple word) =
        castTuple startRule.wellTyped childTuple) :
    word ∈ PresentationStringLanguage P :=
  ⟨{ startRule := startRule,
     start_mem := hstartRule,
     childTuple := childTuple,
     child_derives := hchild,
     start_arity := hstart,
     word_eq := hword }⟩

/-- The previous constructor is sound for the original grammar. -/
theorem mem_original_of_presentation_start
    (P : OutputTypeRefinementPresentation G obs)
    {word : Word α}
    (startRule : TypedStartRule G M)
    (hstartRule : P.HasStartRule startRule)
    (childTuple : Tuple α (G.arity startRule.baseRule.child))
    (hchild : PresentationDerives P startRule.child childTuple)
    (hstart : 1 = G.arity G.start)
    (hword :
      castTuple hstart (singletonTuple word) =
        castTuple startRule.wellTyped childTuple) :
    word ∈ G.StringLanguage :=
  mem_original_of_mem_presentationStringLanguage P
    (mem_presentationStringLanguage_of_start
      P startRule hstartRule childTuple hchild hstart hword)

end PresentationStringLanguage

end MCFG
