/-
Copyright (c) 2026 Takayuki Kuriyama. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Takayuki Kuriyama
-/
import LeanCfgProject.MCFG2.FiniteTextCoverage

/-!
# ReachableStartBridge.lean

Seventeenth clean Lean experiment for the fixed-observation MCFG project.

`ExactReconstructionSkeleton.lean` used `SampleStringLanguage`, based on
`SampleLearnerDerives`.  The completeness side, however, naturally uses the
transitive closure `SampleLearnerReachable`.

This file introduces the corresponding reachable string language and bridges
the characteristic start anchor to an actual sample start word.

Main idea:

If the characteristic start anchor is the singleton tuple of some sample word
`w₀ ∈ K`, then any word reachable from the characteristic start anchor is
reachable from the actual sample start word.  Hence the completeness-side
reachable language is included in the reachable sample string language.

No theorem here uses `sorry`.
-/

namespace MCFG

universe u v w

section ReachableSampleStringLanguage

variable {α : Type u} {M : Type v} [Monoid M]

/-- String-level derivation using `SampleLearnerReachable`.

A word is reachable if it is obtained from the singleton tuple of some sample
start word. -/
structure ReachableSampleStringDerives
    (K : Finset (Word α)) (obs : α → M) (f : Nat)
    (word : Word α) where
  startWord : Word α
  start_mem : startWord ∈ K
  reachable : SampleLearnerReachable K obs f
    (singletonTuple startWord)
    (singletonTuple word)

/-- The string language generated by reachable sample-start derivations. -/
def ReachableSampleStringLanguage
    (K : Finset (Word α)) (obs : α → M) (f : Nat) : Set (Word α) :=
  { word | ReachableSampleStringDerives K obs f word }

namespace ReachableSampleStringDerives

/-- Any ordinary sample string derivation is also a reachable string derivation. -/
def ofSampleStringDerives
    {K : Finset (Word α)} {obs : α → M} {f : Nat}
    {word : Word α}
    (D : SampleStringDerives K obs f word) :
    ReachableSampleStringDerives K obs f word :=
  { startWord := D.startWord,
    start_mem := D.start_mem,
    reachable := SampleLearnerReachable.of_derives D.derives }

/-- Any sample word is in the reachable sample string language. -/
def of_sample_word
    {K : Finset (Word α)} {obs : α → M} {f : Nat}
    {word : Word α}
    (hword : word ∈ K) :
    ReachableSampleStringDerives K obs f word :=
  { startWord := word,
    start_mem := hword,
    reachable := SampleLearnerReachable.self (singletonTuple word) }

/-- Soundness of reachable sample string derivations. -/
theorem sound_for_grammar
    {N : Type w}
    {K : Finset (Word α)} {obs : α → M} {f : Nat}
    (G : WorkingMCFG N α)
    (hL : FixedNamedTupleSubstitutable f obs G.StringLanguage)
    (hK : PositiveSample G K)
    {word : Word α}
    (D : ReachableSampleStringDerives K obs f word) :
    word ∈ G.StringLanguage := by
  have hstart :
      namedFill 1 unaryIdentityContext
        (singletonTuple D.startWord) ∈ G.StringLanguage := by
    exact unaryIdentityContext_mem_of_word_mem
      (hK D.startWord D.start_mem)
  have hderived :
      namedFill 1 unaryIdentityContext
        (singletonTuple word) ∈ G.StringLanguage :=
    SampleLearnerReachable.mem_right_for_grammar
      G hL hK D.reachable hstart
  exact word_mem_of_unaryIdentityContext_mem hderived

end ReachableSampleStringDerives

/-- Soundness of the reachable sample string language. -/
theorem reachableSampleStringLanguage_sound
    {N : Type w}
    (G : WorkingMCFG N α)
    {K : Finset (Word α)} {obs : α → M} {f : Nat}
    (hL : FixedNamedTupleSubstitutable f obs G.StringLanguage)
    (hK : PositiveSample G K) :
    ReachableSampleStringLanguage K obs f ⊆ G.StringLanguage := by
  intro word hword
  exact ReachableSampleStringDerives.sound_for_grammar G hL hK hword

/-- The previous `SampleStringLanguage` is included in the reachable version. -/
theorem sampleStringLanguage_subset_reachableSampleStringLanguage
    {K : Finset (Word α)} {obs : α → M} {f : Nat} :
    SampleStringLanguage K obs f ⊆
      ReachableSampleStringLanguage K obs f := by
  intro word hword
  exact ReachableSampleStringDerives.ofSampleStringDerives hword

end ReachableSampleStringLanguage


section CharacteristicStartBridge

variable {N : Type w} {α : Type u} {M : Type v} [Monoid M]
variable {G : WorkingMCFG N α}
variable {K : Finset (Word α)} {obs : α → M} {f : Nat}

/-- Data saying that the characteristic start anchor is actually the singleton
tuple of a sample word.

The equality is quantified over the proof of start arity so that later
transports do not depend on proof irrelevance details. -/
structure StartAnchorAsSampleWord
    (D : CharacteristicSampleData G K obs f) where
  startWord : Word α
  start_mem : startWord ∈ K
  anchor_eq :
    ∀ hstart : 1 = G.arity G.start,
      D.anchor G.start = castTuple hstart (singletonTuple startWord)

namespace StartAnchorAsSampleWord

/-- A characteristic-reachable word is reachable from an actual sample start
word if the start anchor is that sample word's singleton tuple. -/
theorem characteristic_subset_reachableSample
    (D : CharacteristicSampleData G K obs f)
    (B : StartAnchorAsSampleWord D) :
    CharacteristicReachableLanguage D ⊆
      ReachableSampleStringLanguage K obs f := by
  intro word hword
  rcases hword with ⟨hstart, hreach⟩
  cases hstart
  have hreach' :
      SampleLearnerReachable K obs f
        (singletonTuple B.startWord)
        (singletonTuple word) := by
    simpa [B.anchor_eq rfl] using hreach
  exact
    { startWord := B.startWord,
      start_mem := B.start_mem,
      reachable := hreach' }

/-- Exact reconstruction using the reachable sample string language.

This is the reachable-language version of the exact reconstruction skeleton,
with the start-anchor bridge filled by `StartAnchorAsSampleWord`. -/
theorem exact_reconstruction_reachable
    (D : CharacteristicSampleData G K obs f)
    (B : StartAnchorAsSampleWord D)
    (hfan : G.FanoutAtMost f)
    (hL : FixedNamedTupleSubstitutable f obs G.StringLanguage)
    (hK : PositiveSample G K) :
    ReachableSampleStringLanguage K obs f = G.StringLanguage := by
  ext word
  constructor
  · intro hword
    exact reachableSampleStringLanguage_sound G hL hK hword
  · intro hword
    exact B.characteristic_subset_reachableSample D
      (target_subset_characteristicReachableLanguage D hfan hword)

/-- Mutual-inclusion form of reachable exact reconstruction. -/
theorem exact_reconstruction_reachable_inclusions
    (D : CharacteristicSampleData G K obs f)
    (B : StartAnchorAsSampleWord D)
    (hfan : G.FanoutAtMost f)
    (hL : FixedNamedTupleSubstitutable f obs G.StringLanguage)
    (hK : PositiveSample G K) :
    ReachableSampleStringLanguage K obs f ⊆ G.StringLanguage ∧
      G.StringLanguage ⊆ ReachableSampleStringLanguage K obs f := by
  constructor
  · exact reachableSampleStringLanguage_sound G hL hK
  · intro word hword
    exact B.characteristic_subset_reachableSample D
      (target_subset_characteristicReachableLanguage D hfan hword)

end StartAnchorAsSampleWord

end CharacteristicStartBridge

end MCFG
