/-
Copyright (c) 2026 Takayuki Kuriyama. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Takayuki Kuriyama
-/
import LeanCfgProject.MCFG2.StartRootedConcreteCanonicalLearnerIdentification

/-!
# StartRootedConcreteCanonicalLearnerClassTheorem.lean

This file lifts the grammar-level start-rooted theorem to a uniform
language-class theorem.

For fixed terminal alphabet `α`, finite observation monoid `M`, observation map
`obs`, and fan-out bound `f`, a language belongs to

```lean
StartRootedCorrectedConcreteTargetClass
```

when it is generated by some finite-nonterminal working MCFG satisfying:

* exact working conditions;
* semantic start-rooted normality;
* fan-out at most `f`;
* fixed-observation named-tuple substitutability.

This class is weaker than the earlier syntactically start-separated class.
The file proves the inclusion

```lean
CorrectedConcreteTargetClass ⊆
  StartRootedCorrectedConcreteTargetClass.
```

For the larger class it constructs:

* a finite characteristic sample for every target language;
* a finite tell-tale for every target language;
* one uniform target-independent learner identifying the entire class;
* a selected characteristic sample for every target;
* a selected coverage/stabilization stage for every positive text;
* eventual exactness and eventual semantic constancy after that stage.

No `sorry`, `admit`, or `axiom` is used.
-/

namespace MCFG

universe u v w

section StartRootedTargetWitness

variable (α : Type u)
variable (M : Type w) [Monoid M]
variable (obs : α → M)
variable (f : Nat)

/-- Target-language witness using semantic start-rooted normality rather than
syntactic start separation. -/
structure StartRootedCorrectedConcreteTargetWitness
    (L : Set (Word α)) where

  nonterminal : Type v

  fintypeNonterminal :
    Fintype nonterminal

  grammar :
    WorkingMCFG nonterminal α

  exactWorking :
    grammar.ExactWorkingConditions

  startRooted :
    grammar.StartRootedNormal

  fanout :
    grammar.FanoutAtMost f

  substitutable :
    FixedNamedTupleSubstitutable
      f obs grammar.StringLanguage

  language_eq :
    grammar.StringLanguage = L

/-- The language class represented by finite start-rooted-normal target
grammars. -/
def StartRootedCorrectedConcreteTargetClass :
    Set (Set (Word α)) :=
  fun L =>
    Nonempty
      (StartRootedCorrectedConcreteTargetWitness
        α M obs f L)

end StartRootedTargetWitness


section OldClassInclusion

variable {α : Type u}
variable {M : Type w} [Monoid M]
variable {obs : α → M}
variable {f : Nat}
variable {L : Set (Word α)}

/-- Every syntactically start-separated witness is a semantically
start-rooted-normal witness. -/
def CorrectedConcreteTargetWitness.toStartRooted
    (W :
      CorrectedConcreteTargetWitness
        α M obs f L) :
    StartRootedCorrectedConcreteTargetWitness
      α M obs f L where

  nonterminal :=
    W.nonterminal

  fintypeNonterminal :=
    W.fintypeNonterminal

  grammar :=
    W.grammar

  exactWorking :=
    W.exactWorking

  startRooted :=
    WorkingMCFG.StartRootedNormal.of_startSeparated
      W.exactWorking.basic
      W.startSeparated

  fanout :=
    W.fanout

  substitutable :=
    W.substitutable

  language_eq :=
    W.language_eq

/-- The earlier syntactic target class is contained in the larger semantic
start-rooted class. -/
theorem correctedConcreteTargetClass_subset_startRooted
    (α : Type u)
    (M : Type w)
    [Monoid M]
    (obs : α → M)
    (f : Nat) :
    CorrectedConcreteTargetClass
        (v := v) α M obs f ⊆
      StartRootedCorrectedConcreteTargetClass
        (v := v) α M obs f := by
  intro L hL

  change
    Nonempty
      (CorrectedConcreteTargetWitness
        (v := v) α M obs f L) at hL

  rcases hL with ⟨W⟩

  exact ⟨W.toStartRooted⟩

end OldClassInclusion


section StartRootedWitnessCharacteristicSample

variable {α : Type u}
variable {M : Type w}
variable [Fintype M]
variable [DecidableEq α] [DecidableEq M]
variable [Monoid M]
variable {obs : α → M}
variable {f : Nat}
variable {L : Set (Word α)}

/-- Every semantic start-rooted target witness supplies a finite
characteristic sample for the single corrected concrete learner. -/
theorem StartRootedCorrectedConcreteTargetWitness.exists_characteristicSample
    (W :
      StartRootedCorrectedConcreteTargetWitness
        α M obs f L) :
    ∃ S : Finset (Word α),
      CharacteristicSample
        (correctedConcreteCanonicalHypLanguage
          obs f)
        (correctedConcreteCanonicalLearner
          (α := α))
        S L := by

  letI : Fintype W.nonterminal :=
    W.fintypeNonterminal

  obtain
      ⟨S,
        hSpositive,
        hSexact,
        hSupersets,
        hTexts⟩ :=
    correctedConcreteCanonicalLearner_conclusion_package_of_startRooted
      (G := W.grammar)
      (obs := obs)
      W.exactWorking
      W.startRooted
      W.fanout
      W.substitutable

  refine ⟨S, ?_⟩

  constructor

  · simpa [W.language_eq] using
      hSpositive

  · intro K hSK hKpositive

    have hKgrammar :
        (K : Set (Word α)) ⊆
          W.grammar.StringLanguage := by
      simpa [W.language_eq] using
        hKpositive

    have hExactGrammar :
        CorrectedConcreteCanonicalLearnerLanguage
            K obs f =
          W.grammar.StringLanguage :=
      hSupersets K hSK hKgrammar

    simpa [W.language_eq] using
      hExactGrammar

/-- Every semantic start-rooted target witness is identified from every
positive text by the uniform corrected concrete learner. -/
theorem StartRootedCorrectedConcreteTargetWitness.identified
    (W :
      StartRootedCorrectedConcreteTargetWitness
        α M obs f L) :
    IdentifiesLanguageFromPositiveData
      (correctedConcreteCanonicalHypLanguage
        obs f)
      (correctedConcreteCanonicalLearner
        (α := α))
      L := by

  obtain ⟨S, hS⟩ :=
    W.exists_characteristicSample

  intro T

  exact
    characteristicSample_eventual_correct_on_every_text
      (correctedConcreteCanonicalHypLanguage
        obs f)
      (correctedConcreteCanonicalLearner
        (α := α))
      S hS T

/-- Every semantic start-rooted target witness has a finite tell-tale forcing
the learner to output the target on every positive finite extension. -/
theorem StartRootedCorrectedConcreteTargetWitness.exists_finite_tellTale
    (W :
      StartRootedCorrectedConcreteTargetWitness
        α M obs f L) :
    ∃ S : Finset (Word α),
      (S : Set (Word α)) ⊆ L ∧
      ∀ K : Finset (Word α),
        (S : Set (Word α)) ⊆
            (K : Set (Word α)) →
        (K : Set (Word α)) ⊆ L →
        correctedConcreteCanonicalHypLanguage
            obs f
            (correctedConcreteCanonicalLearner
              (α := α) K) =
          L := by

  obtain ⟨S, hS⟩ :=
    W.exists_characteristicSample

  exact ⟨S, hS.1, hS.2⟩

end StartRootedWitnessCharacteristicSample


section StartRootedClassTheorem

variable {α : Type u}
variable {M : Type w}
variable [Fintype M]
variable [DecidableEq α] [DecidableEq M]
variable [Monoid M]
variable (obs : α → M)
variable (f : Nat)

/-- Every language in the semantic start-rooted target class has a finite
characteristic sample for the uniform learner. -/
theorem correctedConcreteCanonicalLearner_characteristicSample_for_startRootedTargetClass
    {L : Set (Word α)}
    (hL :
      L ∈ StartRootedCorrectedConcreteTargetClass
        (v := v) α M obs f) :
    ∃ S : Finset (Word α),
      CharacteristicSample
        (correctedConcreteCanonicalHypLanguage
          obs f)
        (correctedConcreteCanonicalLearner
          (α := α))
        S L := by

  change
    Nonempty
      (StartRootedCorrectedConcreteTargetWitness
        (v := v) α M obs f L) at hL

  rcases hL with ⟨W⟩

  exact W.exists_characteristicSample

/-- Uniform finite-tell-tale theorem for the semantic start-rooted target
class. -/
theorem correctedConcreteCanonicalLearner_finite_tellTale_for_startRootedTargetClass
    {L : Set (Word α)}
    (hL :
      L ∈ StartRootedCorrectedConcreteTargetClass
        (v := v) α M obs f) :
    ∃ S : Finset (Word α),
      (S : Set (Word α)) ⊆ L ∧
      ∀ K : Finset (Word α),
        (S : Set (Word α)) ⊆
            (K : Set (Word α)) →
        (K : Set (Word α)) ⊆ L →
        correctedConcreteCanonicalHypLanguage
            obs f
            (correctedConcreteCanonicalLearner
              (α := α) K) =
          L := by

  change
    Nonempty
      (StartRootedCorrectedConcreteTargetWitness
        (v := v) α M obs f L) at hL

  rcases hL with ⟨W⟩

  exact W.exists_finite_tellTale

/-- Main class-level theorem under semantic start-rooted normality. -/
theorem correctedConcreteCanonicalLearner_identifies_startRootedTargetClass :
    IdentifiesClassFromPositiveData
      (correctedConcreteCanonicalHypLanguage
        obs f)
      (correctedConcreteCanonicalLearner
        (α := α))
      (StartRootedCorrectedConcreteTargetClass
        (v := v) α M obs f) := by

  intro L hL

  change
    Nonempty
      (StartRootedCorrectedConcreteTargetWitness
        (v := v) α M obs f L) at hL

  rcases hL with ⟨W⟩

  exact W.identified

/-- Expanded positive-text form of the semantic start-rooted class theorem. -/
theorem correctedConcreteCanonicalLearner_identifies_every_startRooted_target_text :
    ∀ L : Set (Word α),
      L ∈ StartRootedCorrectedConcreteTargetClass
          (v := v) α M obs f →
      ∀ T : TextFor L,
        EventuallyCorrectOnText
          (correctedConcreteCanonicalHypLanguage
            obs f)
          (correctedConcreteCanonicalLearner
            (α := α))
          T := by

  intro L hL T

  exact
    correctedConcreteCanonicalLearner_identifies_startRootedTargetClass
      (v := v) obs f L hL T

/-- Paper-style class conclusion package under semantic start-rooted
normality. -/
theorem correctedConcreteCanonicalLearner_startRooted_class_conclusion_package :
    ((∀ K : Finset (Word α),
        (K : Set (Word α)) ⊆
          correctedConcreteCanonicalHypLanguage
            obs f
            (correctedConcreteCanonicalLearner
              (α := α) K))) ∧
    ((∀ S K : Finset (Word α),
        (S : Set (Word α)) ⊆
            (K : Set (Word α)) →
        correctedConcreteCanonicalHypLanguage
            obs f
            (correctedConcreteCanonicalLearner
              (α := α) S) ⊆
          correctedConcreteCanonicalHypLanguage
            obs f
            (correctedConcreteCanonicalLearner
              (α := α) K))) ∧
    ((∀ L : Set (Word α),
        L ∈ StartRootedCorrectedConcreteTargetClass
            (v := v) α M obs f →
        ∃ S : Finset (Word α),
          CharacteristicSample
            (correctedConcreteCanonicalHypLanguage
              obs f)
            (correctedConcreteCanonicalLearner
              (α := α))
            S L)) ∧
    IdentifiesClassFromPositiveData
      (correctedConcreteCanonicalHypLanguage
        obs f)
      (correctedConcreteCanonicalLearner
        (α := α))
      (StartRootedCorrectedConcreteTargetClass
        (v := v) α M obs f) := by

  refine ⟨?_, ?_, ?_, ?_⟩

  · intro K
    exact
      correctedConcreteCanonicalLearner_consistent
        K obs f

  · intro S K hSK
    exact
      correctedConcreteCanonicalHypLanguage_mono
        hSK

  · intro L hL
    exact
      correctedConcreteCanonicalLearner_characteristicSample_for_startRootedTargetClass
        (v := v) obs f hL

  · exact
      correctedConcreteCanonicalLearner_identifies_startRootedTargetClass
        (v := v) obs f

end StartRootedClassTheorem


section StartRootedTargetSelectors

variable {α : Type u}
variable {M : Type w}
variable [Fintype M]
variable [DecidableEq α] [DecidableEq M]
variable [Monoid M]
variable (obs : α → M)
variable (f : Nat)

/-- Choose one finite characteristic sample for a target language in the
semantic start-rooted class. -/
noncomputable def startRootedCorrectedConcreteTargetCharacteristicSample
    {L : Set (Word α)}
    (hL :
      L ∈ StartRootedCorrectedConcreteTargetClass
        (v := v) α M obs f) :
    Finset (Word α) :=
  Classical.choose
    (correctedConcreteCanonicalLearner_characteristicSample_for_startRootedTargetClass
      (v := v) obs f hL)

/-- The selected finite sample is characteristic. -/
theorem startRootedCorrectedConcreteTargetCharacteristicSample_characteristic
    {L : Set (Word α)}
    (hL :
      L ∈ StartRootedCorrectedConcreteTargetClass
        (v := v) α M obs f) :
    CharacteristicSample
      (correctedConcreteCanonicalHypLanguage
        obs f)
      (correctedConcreteCanonicalLearner
        (α := α))
      (startRootedCorrectedConcreteTargetCharacteristicSample
        (v := v) obs f hL)
      L :=
  Classical.choose_spec
    (correctedConcreteCanonicalLearner_characteristicSample_for_startRootedTargetClass
      (v := v) obs f hL)

/-- Positivity of the selected finite sample. -/
theorem startRootedCorrectedConcreteTargetCharacteristicSample_positive
    {L : Set (Word α)}
    (hL :
      L ∈ StartRootedCorrectedConcreteTargetClass
        (v := v) α M obs f) :
    (startRootedCorrectedConcreteTargetCharacteristicSample
        (v := v) obs f hL :
      Set (Word α)) ⊆
      L :=
  (startRootedCorrectedConcreteTargetCharacteristicSample_characteristic
    (v := v) obs f hL).1

/-- Every positive finite extension of the selected sample yields the target
language exactly. -/
theorem startRootedCorrectedConcreteTargetCharacteristicSample_exact_for_positive_superset
    {L : Set (Word α)}
    (hL :
      L ∈ StartRootedCorrectedConcreteTargetClass
        (v := v) α M obs f)
    {K : Finset (Word α)}
    (hSK :
      (startRootedCorrectedConcreteTargetCharacteristicSample
          (v := v) obs f hL :
        Set (Word α)) ⊆
        (K : Set (Word α)))
    (hKpositive :
      (K : Set (Word α)) ⊆ L) :
    correctedConcreteCanonicalHypLanguage
        obs f
        (correctedConcreteCanonicalLearner
          (α := α) K) =
      L :=
  (startRootedCorrectedConcreteTargetCharacteristicSample_characteristic
    (v := v) obs f hL).2
      K hSK hKpositive

/-- Exact reconstruction on the selected sample itself. -/
theorem startRootedCorrectedConcreteTargetCharacteristicSample_exact
    {L : Set (Word α)}
    (hL :
      L ∈ StartRootedCorrectedConcreteTargetClass
        (v := v) α M obs f) :
    correctedConcreteCanonicalHypLanguage
        obs f
        (correctedConcreteCanonicalLearner
          (α := α)
          (startRootedCorrectedConcreteTargetCharacteristicSample
            (v := v) obs f hL)) =
      L := by

  apply
    startRootedCorrectedConcreteTargetCharacteristicSample_exact_for_positive_superset
      (v := v) obs f hL

  · exact Set.Subset.rfl

  · exact
      startRootedCorrectedConcreteTargetCharacteristicSample_positive
        (v := v) obs f hL

end StartRootedTargetSelectors


section StartRootedCoverageStage

variable {α : Type u}
variable {M : Type w}
variable [Fintype M]
variable [DecidableEq α] [DecidableEq M]
variable [Monoid M]
variable (obs : α → M)
variable (f : Nat)

/-- Choose a stage after which every text prefix contains the selected
start-rooted target characteristic sample. -/
noncomputable def startRootedCorrectedConcreteTargetCoverageStage
    {L : Set (Word α)}
    (hL :
      L ∈ StartRootedCorrectedConcreteTargetClass
        (v := v) α M obs f)
    (T : TextFor L) :
    Nat :=
  Classical.choose
    (TextFor.eventuallyContains_finite_subset
      (startRootedCorrectedConcreteTargetCharacteristicSample
        (v := v) obs f hL)
      (startRootedCorrectedConcreteTargetCharacteristicSample_positive
        (v := v) obs f hL)
      T)

/-- Every prefix after the selected stage contains the selected finite
characteristic sample. -/
theorem startRootedCorrectedConcreteTargetCharacteristicSample_subset_prefix_after
    {L : Set (Word α)}
    (hL :
      L ∈ StartRootedCorrectedConcreteTargetClass
        (v := v) α M obs f)
    (T : TextFor L)
    {n : Nat}
    (hn :
      startRootedCorrectedConcreteTargetCoverageStage
          (v := v) obs f hL T ≤ n) :
    (startRootedCorrectedConcreteTargetCharacteristicSample
        (v := v) obs f hL :
      Set (Word α)) ⊆
      (T.prefixSample n : Set (Word α)) := by

  exact
    (Classical.choose_spec
      (TextFor.eventuallyContains_finite_subset
        (startRootedCorrectedConcreteTargetCharacteristicSample
          (v := v) obs f hL)
        (startRootedCorrectedConcreteTargetCharacteristicSample_positive
          (v := v) obs f hL)
        T))
      n hn

/-- Every prefix after the selected stage yields exactly the target language. -/
theorem correctedConcreteCanonicalLearner_correct_after_startRootedCoverageStage
    {L : Set (Word α)}
    (hL :
      L ∈ StartRootedCorrectedConcreteTargetClass
        (v := v) α M obs f)
    (T : TextFor L)
    {n : Nat}
    (hn :
      startRootedCorrectedConcreteTargetCoverageStage
          (v := v) obs f hL T ≤ n) :
    correctedConcreteCanonicalHypLanguage
        obs f
        (correctedConcreteCanonicalLearner
          (α := α) (T.prefixSample n)) =
      L := by

  exact
    startRootedCorrectedConcreteTargetCharacteristicSample_exact_for_positive_superset
      (v := v) obs f hL
      (startRootedCorrectedConcreteTargetCharacteristicSample_subset_prefix_after
        (v := v) obs f hL T hn)
      (T.prefixSample_subset n)

/-- At the selected stage itself the learner is already correct. -/
theorem correctedConcreteCanonicalLearner_correct_at_startRootedCoverageStage
    {L : Set (Word α)}
    (hL :
      L ∈ StartRootedCorrectedConcreteTargetClass
        (v := v) α M obs f)
    (T : TextFor L) :
    correctedConcreteCanonicalHypLanguage
        obs f
        (correctedConcreteCanonicalLearner
          (α := α)
          (T.prefixSample
            (startRootedCorrectedConcreteTargetCoverageStage
              (v := v) obs f hL T))) =
      L := by

  exact
    correctedConcreteCanonicalLearner_correct_after_startRootedCoverageStage
      (v := v) obs f hL T
      (Nat.le_refl _)

/-- Any two hypothesis languages after the selected stage are equal. -/
theorem correctedConcreteCanonicalLearner_eventually_language_constant_of_startRootedClass
    {L : Set (Word α)}
    (hL :
      L ∈ StartRootedCorrectedConcreteTargetClass
        (v := v) α M obs f)
    (T : TextFor L)
    {m n : Nat}
    (hm :
      startRootedCorrectedConcreteTargetCoverageStage
          (v := v) obs f hL T ≤ m)
    (hn :
      startRootedCorrectedConcreteTargetCoverageStage
          (v := v) obs f hL T ≤ n) :
    correctedConcreteCanonicalHypLanguage
        obs f
        (correctedConcreteCanonicalLearner
          (α := α) (T.prefixSample m)) =
      correctedConcreteCanonicalHypLanguage
        obs f
        (correctedConcreteCanonicalLearner
          (α := α) (T.prefixSample n)) := by

  rw [
    correctedConcreteCanonicalLearner_correct_after_startRootedCoverageStage
      (v := v) obs f hL T hm,
    correctedConcreteCanonicalLearner_correct_after_startRootedCoverageStage
      (v := v) obs f hL T hn
  ]

/-- Selected-stage semantic stabilization theorem for every target in the
semantic start-rooted class. -/
theorem correctedConcreteCanonicalLearner_has_startRooted_stabilizationStage
    {L : Set (Word α)}
    (hL :
      L ∈ StartRootedCorrectedConcreteTargetClass
        (v := v) α M obs f)
    (T : TextFor L) :
    ∃ n0 : Nat,
      (∀ n : Nat, n0 ≤ n →
        correctedConcreteCanonicalHypLanguage
            obs f
            (correctedConcreteCanonicalLearner
              (α := α) (T.prefixSample n)) =
          L) ∧
      (∀ m n : Nat, n0 ≤ m → n0 ≤ n →
        correctedConcreteCanonicalHypLanguage
            obs f
            (correctedConcreteCanonicalLearner
              (α := α) (T.prefixSample m)) =
          correctedConcreteCanonicalHypLanguage
            obs f
            (correctedConcreteCanonicalLearner
              (α := α) (T.prefixSample n))) := by

  refine
    ⟨startRootedCorrectedConcreteTargetCoverageStage
        (v := v) obs f hL T,
      ?_,
      ?_⟩

  · intro n hn
    exact
      correctedConcreteCanonicalLearner_correct_after_startRootedCoverageStage
        (v := v) obs f hL T hn

  · intro m n hm hn
    exact
      correctedConcreteCanonicalLearner_eventually_language_constant_of_startRootedClass
        (v := v) obs f hL T hm hn

end StartRootedCoverageStage


section StartRootedUniformStabilization

variable {α : Type u}
variable {M : Type w}
variable [Fintype M]
variable [DecidableEq α] [DecidableEq M]
variable [Monoid M]
variable (obs : α → M)
variable (f : Nat)

/-- Uniform selected-sample and selected-stage theorem for the semantic
start-rooted target class. -/
theorem correctedConcreteCanonicalLearner_uniform_startRooted_selected_stabilization :
    ∀ L : Set (Word α),
      ∀ hL :
        L ∈ StartRootedCorrectedConcreteTargetClass
          (v := v) α M obs f,
        CharacteristicSample
          (correctedConcreteCanonicalHypLanguage
            obs f)
          (correctedConcreteCanonicalLearner
            (α := α))
          (startRootedCorrectedConcreteTargetCharacteristicSample
            (v := v) obs f hL)
          L ∧
        ∀ T : TextFor L,
          ∀ n : Nat,
            startRootedCorrectedConcreteTargetCoverageStage
                (v := v) obs f hL T ≤ n →
              correctedConcreteCanonicalHypLanguage
                  obs f
                  (correctedConcreteCanonicalLearner
                    (α := α) (T.prefixSample n)) =
                L := by

  intro L hL

  constructor

  · exact
      startRootedCorrectedConcreteTargetCharacteristicSample_characteristic
        (v := v) obs f hL

  · intro T n hn
    exact
      correctedConcreteCanonicalLearner_correct_after_startRootedCoverageStage
        (v := v) obs f hL T hn

/-- Paper-style stabilization package for the larger semantic class. -/
theorem correctedConcreteCanonicalLearner_startRooted_stabilization_conclusion_package :
    ∀ L : Set (Word α),
      ∀ hL :
        L ∈ StartRootedCorrectedConcreteTargetClass
          (v := v) α M obs f,
        let S :=
          startRootedCorrectedConcreteTargetCharacteristicSample
            (v := v) obs f hL
        (S : Set (Word α)) ⊆ L ∧
        correctedConcreteCanonicalHypLanguage
            obs f
            (correctedConcreteCanonicalLearner
              (α := α) S) =
          L ∧
        ∀ T : TextFor L,
          let n0 :=
            startRootedCorrectedConcreteTargetCoverageStage
              (v := v) obs f hL T
          (∀ n : Nat, n0 ≤ n →
            correctedConcreteCanonicalHypLanguage
                obs f
                (correctedConcreteCanonicalLearner
                  (α := α) (T.prefixSample n)) =
              L) ∧
          (∀ m n : Nat, n0 ≤ m → n0 ≤ n →
            correctedConcreteCanonicalHypLanguage
                obs f
                (correctedConcreteCanonicalLearner
                  (α := α) (T.prefixSample m)) =
              correctedConcreteCanonicalHypLanguage
                obs f
                (correctedConcreteCanonicalLearner
                  (α := α) (T.prefixSample n))) := by

  intro L hL
  dsimp

  refine
    ⟨startRootedCorrectedConcreteTargetCharacteristicSample_positive
        (v := v) obs f hL,
      startRootedCorrectedConcreteTargetCharacteristicSample_exact
        (v := v) obs f hL,
      ?_⟩

  intro T
  dsimp

  constructor

  · intro n hn
    exact
      correctedConcreteCanonicalLearner_correct_after_startRootedCoverageStage
        (v := v) obs f hL T hn

  · intro m n hm hn
    exact
      correctedConcreteCanonicalLearner_eventually_language_constant_of_startRootedClass
        (v := v) obs f hL T hm hn

end StartRootedUniformStabilization

end MCFG
