/-
Copyright (c) 2026 Takayuki Kuriyama. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Takayuki Kuriyama
-/
import LeanCfgProject.MCFG2.ConcreteCanonicalLearnerStabilization

/-!
# StartRootedConcreteCanonicalLearnerIdentification.lean

The previous end-to-end theorem assumed the syntactic condition

```lean
G.StartSeparated.
```

Inspection of the successful-trim completeness proof shows that the actual
semantic requirement is only

```lean
G.StringLanguage ⊆ StartRootedStringLanguage G.
```

This file names that weaker property `WorkingMCFG.StartRootedNormal` and rebuilds
the entire concrete route under it:

* completeness of the concrete successful trim;
* extraction of successful typed occurrences;
* construction of the finite typed characteristic sample;
* exact reconstruction by the corrected finite enumerated learner;
* exactness for every positive finite superset;
* eventual exactness on every positive text;
* Gold identification and the paper-style conclusion package.

`StartSeparated` is retained only as a sufficient syntactic criterion.  The
main theorem of this file no longer requires it.

No `sorry`, `admit`, or `axiom` is used.
-/

namespace MCFG

universe u v w

section StartRootedNormalProperty

variable {N : Type v} {α : Type u}

/-- Semantic start-rooted normality.

Every ordinary string derivation admits one start rule at the root and a
start-free derivation below it. -/
def WorkingMCFG.StartRootedNormal
    (G : WorkingMCFG N α) : Prop :=
  G.StringLanguage ⊆
    StartRootedStringLanguage G

namespace WorkingMCFG.StartRootedNormal

/-- Start-rooted normality gives equality between the start-rooted language and
the ordinary string language. -/
theorem language_eq
    {G : WorkingMCFG N α}
    (hnormal : G.StartRootedNormal) :
    StartRootedStringLanguage G =
      G.StringLanguage := by
  apply Set.Subset.antisymm
  · exact startRootedStringLanguage_subset_stringLanguage G
  · exact hnormal

/-- The syntactic start-separation condition implies semantic start-rooted
normality. -/
theorem of_startSeparated
    {G : WorkingMCFG N α}
    (hworking : G.BasicWorkingConditions)
    (hsep : G.StartSeparated) :
    G.StartRootedNormal :=
  stringLanguage_subset_startRooted_of_startSeparated
    hworking hsep

end WorkingMCFG.StartRootedNormal

end StartRootedNormalProperty


section SuccessfulTrimCompletenessOfStartRooted

variable {N : Type v} {α : Type u} {M : Type w}
variable [Fintype N] [Fintype M]
variable [DecidableEq M] [Monoid M]
variable {G : WorkingMCFG N α} {obs : α → M}

/-- Every word of an exact start-rooted-normal grammar is generated by the
concrete successful trim. -/
theorem stringLanguage_subset_concreteSuccessfulPresentation_of_startRooted
    (hworking : G.ExactWorkingConditions)
    (hnormal : G.StartRootedNormal) :
    G.StringLanguage ⊆
      PresentationStringLanguage
        (ConcreteSuccessfulOutputTypeRefinement.presentation
          (G := G) (obs := obs) hworking.basic) := by
  intro word hword

  let D : StartRootedStringDerives G word :=
    hnormal hword

  have hchildDerives :
      DerivesTuple G D.startRule.child D.childTuple :=
    D.child_derives.toDerivesTuple

  have hstartDerives :
      DerivesTuple G G.start
        (castTuple D.start_wellTyped D.childTuple) :=
    DerivesTuple.start
      D.start_mem
      hchildDerives
      D.start_wellTyped

  let rootOccurrence :
      ExactSuccessfulDerivationOccurrence G G.start
        (castTuple D.start_wellTyped D.childTuple)
        (startIdentityNamedContext G D.start_arity) :=
    ExactSuccessfulDerivationOccurrence.root
      D.start_arity hstartDerives

  let childOccurrence :
      ExactSuccessfulDerivationOccurrence G D.startRule.child
        D.childTuple
        (transportNamedSentenceContext
          D.start_wellTyped.symm
          (startIdentityNamedContext G D.start_arity)) :=
    ExactSuccessfulDerivationOccurrence.throughStart
      D.start_mem
      D.start_wellTyped
      hchildDerives
      rootOccurrence

  have hchild :
      PresentationDerives
        (ConcreteSuccessfulOutputTypeRefinement.presentation
          (G := G) (obs := obs) hworking.basic)
        (TypedNonterminal.ofTuple obs
          D.startRule.child D.childTuple)
        D.childTuple :=
    D.child_derives.toConcreteSuccessfulPresentation
      (obs := obs) hworking childOccurrence

  let σ :=
    ConcreteOutputTypeRefinement.canonicalStartRule
      hworking.basic
      D.startRule
      D.start_mem
      (tupleType obs D.childTuple)

  have hσmem :
      (ConcreteSuccessfulOutputTypeRefinement.presentation
        (G := G) (obs := obs) hworking.basic).
        HasStartRule σ :=
    ConcreteSuccessfulOutputTypeRefinement.canonicalStartRule_mem
      (obs := obs) hworking
      D.startRule D.start_mem childOccurrence

  have hchildσ :
      PresentationDerives
        (ConcreteSuccessfulOutputTypeRefinement.presentation
          (G := G) (obs := obs) hworking.basic)
        σ.child D.childTuple := by
    simpa [σ,
      ConcreteOutputTypeRefinement.canonicalStartRule,
      TypedStartRule.child,
      TypedNonterminal.ofTuple] using hchild

  exact
    { startRule := σ
      start_mem := hσmem
      childTuple := D.childTuple
      child_derives := hchildσ
      start_arity := D.start_arity
      word_eq := by
        have hp :
            D.start_wellTyped = σ.wellTyped :=
          Subsingleton.elim _ _
        cases hp
        exact D.word_eq }

/-- Completeness of the concrete successful trim under semantic start-rooted
normality. -/
def concreteSuccessfulPresentationCompleteFor_of_startRooted
    (hworking : G.ExactWorkingConditions)
    (hnormal : G.StartRootedNormal) :
    PresentationCompleteFor
      (ConcreteSuccessfulOutputTypeRefinement.presentation
        (G := G) (obs := obs) hworking.basic) where
  complete :=
    stringLanguage_subset_concreteSuccessfulPresentation_of_startRooted
      (obs := obs) hworking hnormal

/-- The concrete successful trim generates exactly the original language under
semantic start-rooted normality. -/
theorem concreteSuccessfulPresentation_stringLanguage_eq_original_of_startRooted
    (hworking : G.ExactWorkingConditions)
    (hnormal : G.StartRootedNormal) :
    PresentationStringLanguage
        (ConcreteSuccessfulOutputTypeRefinement.presentation
          (G := G) (obs := obs) hworking.basic) =
      G.StringLanguage :=
  (concreteSuccessfulPresentationCompleteFor_of_startRooted
    (obs := obs) hworking hnormal).language_eq

/-- Complete successful finite output-type presentation under semantic
start-rooted normality. -/
noncomputable def concreteSuccessfulCompleteOutputTypePresentation_of_startRooted
    (hworking : G.ExactWorkingConditions)
    (hnormal : G.StartRootedNormal) :
    CompleteOutputTypePresentation G obs where
  presentation :=
    ConcreteSuccessfulOutputTypeRefinement.presentation
      (G := G) (obs := obs) hworking.basic
  complete :=
    concreteSuccessfulPresentationCompleteFor_of_startRooted
      (obs := obs) hworking hnormal

/-- The actual working grammar generated by the successful trim remains
language-equivalent to the target under semantic start-rooted normality. -/
theorem concreteSuccessfulWorkingGrammar_stringLanguage_eq_original_of_startRooted
    (hworking : G.ExactWorkingConditions)
    (hnormal : G.StartRootedNormal) :
    (ConcreteSuccessfulOutputTypeRefinement.presentation
      (G := G) (obs := obs) hworking.basic).
        toWorkingMCFG.StringLanguage =
      G.StringLanguage := by
  calc
    (ConcreteSuccessfulOutputTypeRefinement.presentation
      (G := G) (obs := obs) hworking.basic).
        toWorkingMCFG.StringLanguage =
        PresentationStringLanguage
          (ConcreteSuccessfulOutputTypeRefinement.presentation
            (G := G) (obs := obs) hworking.basic) :=
      presentationStringLanguage_workingGrammar_eq _
    _ = G.StringLanguage :=
      concreteSuccessfulPresentation_stringLanguage_eq_original_of_startRooted
        (obs := obs) hworking hnormal

end SuccessfulTrimCompletenessOfStartRooted


section SuccessfulOccurrencePackageOfStartRooted

variable {N : Type v} {α : Type u} {M : Type w}
variable [Fintype N] [Fintype M]
variable [DecidableEq α] [DecidableEq M] [Monoid M]
variable {G : WorkingMCFG N α} {obs : α → M}

/-- Complete successful presentation and automatically extracted occurrence
family under semantic start-rooted normality. -/
noncomputable def concreteSuccessfulOccurrenceCompletePresentation_of_startRooted
    (hworking : G.ExactWorkingConditions)
    (hnormal : G.StartRootedNormal) :
    SuccessfulOccurrenceCompletePresentation G obs where
  completePresentation :=
    concreteSuccessfulCompleteOutputTypePresentation_of_startRooted
      (obs := obs) hworking hnormal
  occurrences :=
    concreteTypedSuccessfulOccurrenceFamily
      (obs := obs) hworking

/-- Corresponding trimmed presentation package. -/
noncomputable def concreteTrimmedOutputTypePresentation_of_startRooted
    (hworking : G.ExactWorkingConditions)
    (hnormal : G.StartRootedNormal) :
    TrimmedOutputTypePresentation G obs :=
  (concreteSuccessfulOccurrenceCompletePresentation_of_startRooted
    (obs := obs) hworking hnormal).
      toTrimmedOutputTypePresentation

/-- The selected anchor and exposing context carry a concrete exact successful
occurrence. -/
theorem concreteTrimmed_anchor_occurrence_of_startRooted
    (hworking : G.ExactWorkingConditions)
    (hnormal : G.StartRootedNormal)
    (X :
      PresentTypedNonterminal
        (ConcreteSuccessfulOutputTypeRefinement.presentation
          (G := G) (obs := obs) hworking.basic)) :
    ExactSuccessfulDerivationOccurrence G X.node.base
      ((concreteTrimmedOutputTypePresentation_of_startRooted
        (obs := obs) hworking hnormal).anchor X)
      ((concreteTrimmedOutputTypePresentation_of_startRooted
        (obs := obs) hworking hnormal).expose X) :=
  (concreteSuccessfulOccurrenceCompletePresentation_of_startRooted
    (obs := obs) hworking hnormal).anchor_occurrence X

end SuccessfulOccurrencePackageOfStartRooted


section ConcreteTypedSampleOfStartRooted

variable {N : Type v} {α : Type u} {M : Type w}
variable [Fintype N] [Fintype M]
variable [DecidableEq α] [DecidableEq M] [Monoid M]
variable {G : WorkingMCFG N α} {obs : α → M}
variable {f : Nat}

/-- Fully concrete typed characteristic sample under semantic start-rooted
normality. -/
noncomputable def concreteTypedCharacteristicSample_of_startRooted
    (hworking : G.ExactWorkingConditions)
    (hnormal : G.StartRootedNormal) :
    Finset (Word α) :=
  typedCharacteristicSample
    (concreteSuccessfulOccurrenceCompletePresentation_of_startRooted
      (obs := obs) hworking hnormal)
    hworking.basic.1.symm

/-- Positivity of the start-rooted-normal concrete typed sample. -/
theorem concreteTypedCharacteristicSample_positive_of_startRooted
    (hworking : G.ExactWorkingConditions)
    (hnormal : G.StartRootedNormal) :
    (concreteTypedCharacteristicSample_of_startRooted
      (obs := obs) hworking hnormal :
        Set (Word α)) ⊆
      G.StringLanguage :=
  typedCharacteristicSample_positive
    (concreteSuccessfulOccurrenceCompletePresentation_of_startRooted
      (obs := obs) hworking hnormal)
    hworking.basic.1.symm

/-- Exact reconstruction by the corrected finite enumerated learner under the
weaker semantic start-rooted-normal assumption. -/
theorem concreteTypedCharacteristicSample_correctedConcrete_exact_of_startRooted
    (hworking : G.ExactWorkingConditions)
    (hnormal : G.StartRootedNormal)
    (hfan : G.FanoutAtMost f)
    (hL :
      FixedNamedTupleSubstitutable
        f obs G.StringLanguage) :
    CorrectedConcreteCanonicalLearnerLanguage
        (concreteTypedCharacteristicSample_of_startRooted
          (obs := obs) hworking hnormal)
        obs f =
      G.StringLanguage :=
  typedCharacteristicSample_correctedConcrete_reconstruction
    (concreteSuccessfulOccurrenceCompletePresentation_of_startRooted
      (obs := obs) hworking hnormal)
    hworking hfan hL

/-- Every positive finite superset of the selected concrete sample reconstructs
the target exactly. -/
theorem concreteTypedCharacteristicSample_correctedConcrete_exact_for_positive_superset_of_startRooted
    (hworking : G.ExactWorkingConditions)
    (hnormal : G.StartRootedNormal)
    (hfan : G.FanoutAtMost f)
    (hL :
      FixedNamedTupleSubstitutable
        f obs G.StringLanguage)
    {K : Finset (Word α)}
    (hSK :
      (concreteTypedCharacteristicSample_of_startRooted
        (obs := obs) hworking hnormal :
          Set (Word α)) ⊆
        (K : Set (Word α)))
    (hKpos :
      (K : Set (Word α)) ⊆
        G.StringLanguage) :
    CorrectedConcreteCanonicalLearnerLanguage
        K obs f =
      G.StringLanguage := by
  apply Set.Subset.antisymm

  · exact
      correctedConcreteCanonicalLearnerLanguage_sound
        G hL hKpos

  · intro word hword

    have hbase :
        word ∈
          ExactReachableSampleStringLanguage
            (concreteTypedCharacteristicSample_of_startRooted
              (obs := obs) hworking hnormal)
            obs f := by
      rw [
        ← correctedConcreteCanonicalLearnerLanguage_eq_exactReachable,
        concreteTypedCharacteristicSample_correctedConcrete_exact_of_startRooted
          (obs := obs)
          hworking hnormal hfan hL
      ]
      exact hword

    have hlarger :
        word ∈
          ExactReachableSampleStringLanguage
            K obs f :=
      exactReachableSampleStringLanguage_mono
        hSK hbase

    exact hlarger.toCorrectedConcrete

/-- Eventual exactness on every positive text under semantic start-rooted
normality. -/
theorem concreteTypedCharacteristicSample_correctedConcrete_prefix_exact_of_startRooted
    (hworking : G.ExactWorkingConditions)
    (hnormal : G.StartRootedNormal)
    (hfan : G.FanoutAtMost f)
    (hL :
      FixedNamedTupleSubstitutable
        f obs G.StringLanguage) :
    ∀ T : TextFor G.StringLanguage,
      ∃ n0 : Nat, ∀ n : Nat, n0 ≤ n →
        CorrectedConcreteCanonicalLearnerLanguage
            (T.prefixSample n)
            obs f =
          G.StringLanguage := by
  intro T

  obtain ⟨n0, hn0⟩ :=
    TextFor.eventuallyContains_finite_subset
      (concreteTypedCharacteristicSample_of_startRooted
        (obs := obs) hworking hnormal)
      (concreteTypedCharacteristicSample_positive_of_startRooted
        (obs := obs) hworking hnormal)
      T

  refine ⟨n0, ?_⟩

  intro n hn

  exact
    concreteTypedCharacteristicSample_correctedConcrete_exact_for_positive_superset_of_startRooted
      (obs := obs)
      hworking hnormal hfan hL
      (hn0 n hn)
      (T.prefixSample_subset n)

/-- Gold identification by the corrected finite learner under semantic
start-rooted normality. -/
theorem correctedConcreteCanonicalLearner_identifies_from_positive_text_of_startRooted
    (hworking : G.ExactWorkingConditions)
    (hnormal : G.StartRootedNormal)
    (hfan : G.FanoutAtMost f)
    (hL :
      FixedNamedTupleSubstitutable
        f obs G.StringLanguage) :
    ∀ T : TextFor G.StringLanguage,
      EventuallyCorrectOnText
        (correctedConcreteCanonicalHypLanguage
          obs f)
        (correctedConcreteCanonicalLearner
          (α := α))
        T := by
  intro T

  exact
    concreteTypedCharacteristicSample_correctedConcrete_prefix_exact_of_startRooted
      (obs := obs)
      hworking hnormal hfan hL T

/-- Main paper theorem with the weaker semantic start-rooted-normal
assumption. -/
theorem correctedConcreteCanonicalLearner_paper_main_theorem_of_startRooted
    (hworking : G.ExactWorkingConditions)
    (hnormal : G.StartRootedNormal)
    (hfan : G.FanoutAtMost f)
    (hL :
      FixedNamedTupleSubstitutable
        f obs G.StringLanguage) :
    ∃ S : Finset (Word α),
      (S : Set (Word α)) ⊆
          G.StringLanguage ∧
      CorrectedConcreteCanonicalLearnerLanguage
          S obs f =
        G.StringLanguage ∧
      ∀ T : TextFor G.StringLanguage,
        EventuallyCorrectOnText
          (correctedConcreteCanonicalHypLanguage
            obs f)
          (correctedConcreteCanonicalLearner
            (α := α))
          T := by
  refine
    ⟨concreteTypedCharacteristicSample_of_startRooted
        (obs := obs) hworking hnormal,
      concreteTypedCharacteristicSample_positive_of_startRooted
        (obs := obs) hworking hnormal,
      concreteTypedCharacteristicSample_correctedConcrete_exact_of_startRooted
        (obs := obs)
        hworking hnormal hfan hL,
      ?_⟩

  exact
    correctedConcreteCanonicalLearner_identifies_from_positive_text_of_startRooted
      (obs := obs)
      hworking hnormal hfan hL

/-- Full conclusion package under semantic start-rooted normality. -/
theorem correctedConcreteCanonicalLearner_conclusion_package_of_startRooted
    (hworking : G.ExactWorkingConditions)
    (hnormal : G.StartRootedNormal)
    (hfan : G.FanoutAtMost f)
    (hL :
      FixedNamedTupleSubstitutable
        f obs G.StringLanguage) :
    ∃ S : Finset (Word α),
      (S : Set (Word α)) ⊆
          G.StringLanguage ∧
      CorrectedConcreteCanonicalLearnerLanguage
          S obs f =
        G.StringLanguage ∧
      (∀ K : Finset (Word α),
        (S : Set (Word α)) ⊆
            (K : Set (Word α)) →
        (K : Set (Word α)) ⊆
            G.StringLanguage →
        CorrectedConcreteCanonicalLearnerLanguage
            K obs f =
          G.StringLanguage) ∧
      (∀ T : TextFor G.StringLanguage,
        EventuallyCorrectOnText
          (correctedConcreteCanonicalHypLanguage
            obs f)
          (correctedConcreteCanonicalLearner
            (α := α))
          T) := by
  let S :=
    concreteTypedCharacteristicSample_of_startRooted
      (obs := obs) hworking hnormal

  refine
    ⟨S,
      concreteTypedCharacteristicSample_positive_of_startRooted
        (obs := obs) hworking hnormal,
      concreteTypedCharacteristicSample_correctedConcrete_exact_of_startRooted
        (obs := obs)
        hworking hnormal hfan hL,
      ?_,
      correctedConcreteCanonicalLearner_identifies_from_positive_text_of_startRooted
        (obs := obs)
        hworking hnormal hfan hL⟩

  intro K hSK hKpos

  exact
    concreteTypedCharacteristicSample_correctedConcrete_exact_for_positive_superset_of_startRooted
      (obs := obs)
      hworking hnormal hfan hL
      hSK hKpos

end ConcreteTypedSampleOfStartRooted


section StartSeparatedRecovery

variable {N : Type v} {α : Type u} {M : Type w}
variable [Fintype N] [Fintype M]
variable [DecidableEq α] [DecidableEq M] [Monoid M]
variable {G : WorkingMCFG N α} {obs : α → M}
variable {f : Nat}

/-- The previous syntactic theorem is recovered immediately because
`StartSeparated` implies `StartRootedNormal`. -/
theorem correctedConcreteCanonicalLearner_paper_main_theorem_from_startSeparated
    (hworking : G.ExactWorkingConditions)
    (hsep : G.StartSeparated)
    (hfan : G.FanoutAtMost f)
    (hL :
      FixedNamedTupleSubstitutable
        f obs G.StringLanguage) :
    ∃ S : Finset (Word α),
      (S : Set (Word α)) ⊆
          G.StringLanguage ∧
      CorrectedConcreteCanonicalLearnerLanguage
          S obs f =
        G.StringLanguage ∧
      ∀ T : TextFor G.StringLanguage,
        EventuallyCorrectOnText
          (correctedConcreteCanonicalHypLanguage
            obs f)
          (correctedConcreteCanonicalLearner
            (α := α))
          T :=
  correctedConcreteCanonicalLearner_paper_main_theorem_of_startRooted
    (obs := obs)
    hworking
    (WorkingMCFG.StartRootedNormal.of_startSeparated
      hworking.basic hsep)
    hfan hL

end StartSeparatedRecovery

end MCFG
