/-
Copyright (c) 2026 Takayuki Kuriyama. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Takayuki Kuriyama
-/
import LeanCfgProject.MCFG.TupleOccurrences

/-!
# BinaryWitnesses.lean

This file constructs the second finite rule component of the concrete canonical
learner.

For fixed arities `e`, `dB`, and `dC`, a finite sample `K`, and a finite
length bound, it actually enumerates:

* finite exact-once binary template tuples over the alphabet occurring in `K`;
* a parent tuple occurrence of arity `e`;
* a left tuple occurrence of arity `dB`;
* a right tuple occurrence of arity `dC`;
* the candidates for which the parent tuple is exactly the evaluation of the
  template on the two child tuples.

Every enumerated witness is converted to the already verified
`SampleBinaryEvidence`.  The filling identities are not assumptions: they are
constructed by `ExactSplicing.exactSplice` from the enumerated exact-once
template.

All definitions depend only on `K`, the arities, and the explicit finite bound.
No target grammar is an input.
-/

namespace MCFG

universe u

section FiniteTemplateAtoms

variable {α : Type u}

/-- The finite set of template atoms generated by a finite terminal alphabet
and the two finite variable sets. -/
noncomputable def finiteTemplateAtoms
    (A : Finset α)
    (dB dC : Nat) :
    Finset (TemplateAtom α dB dC) := by
  classical
  let terminals : Finset (TemplateAtom α dB dC) :=
    A.image (fun a => TemplateAtom.terminal a)
  let leftVariables : Finset (TemplateAtom α dB dC) :=
    (Finset.univ : Finset (Fin dB)).image
      (fun i => TemplateAtom.leftVar i)
  let rightVariables : Finset (TemplateAtom α dB dC) :=
    (Finset.univ : Finset (Fin dC)).image
      (fun j => TemplateAtom.rightVar j)
  exact terminals ∪ leftVariables ∪ rightVariables

/-- Enumerate all binary template words of length at most `bound`. -/
noncomputable def finiteTemplateWordsUpTo
    (A : Finset α)
    (dB dC bound : Nat) :
    Finset (TemplateWord α dB dC) :=
  finiteWordsUpTo
    (finiteTemplateAtoms A dB dC)
    bound

end FiniteTemplateAtoms


section FiniteTemplateTuples

variable {α : Type u}

/-- A finite code for a binary template tuple of output arity `e`. -/
structure FiniteTemplateTupleCode
    (α : Type u)
    (e dB dC : Nat) where
  outputs :
    FiniteListCode
      (TemplateWord α dB dC)
      e

namespace FiniteTemplateTupleCode

/-- Template tuple represented by a finite code. -/
def body
    {e dB dC : Nat}
    (C : FiniteTemplateTupleCode α e dB dC) :
    TemplateTuple α e dB dC :=
  C.outputs.toFunction

@[simp] theorem body_apply
    {e dB dC : Nat}
    (C : FiniteTemplateTupleCode α e dB dC)
    (i : Fin e) :
    C.body i = C.outputs.toFunction i :=
  rfl

end FiniteTemplateTupleCode

/-- A finite template-tuple code carrying a proved exact-once certificate. -/
structure FiniteExactTemplateTupleCode
    (α : Type u)
    (e dB dC : Nat) where
  code :
    FiniteTemplateTupleCode α e dB dC

  exactOnce :
    TemplateTuple.ExactlyOnce code.body

namespace FiniteExactTemplateTupleCode

/-- Exact-once template represented by the code. -/
def body
    {e dB dC : Nat}
    (C : FiniteExactTemplateTupleCode α e dB dC) :
    TemplateTuple α e dB dC :=
  C.code.body

/-- The represented body is exact-once. -/
theorem body_exactOnce
    {e dB dC : Nat}
    (C : FiniteExactTemplateTupleCode α e dB dC) :
    TemplateTuple.ExactlyOnce C.body :=
  C.exactOnce

end FiniteExactTemplateTupleCode

/-- Enumerate all output-arity-`e` template-tuple codes whose component words
have length at most `bound`. -/
noncomputable def finiteTemplateTupleCodesUpTo
    (A : Finset α)
    (e dB dC bound : Nat) :
    Finset (FiniteTemplateTupleCode α e dB dC) := by
  classical
  exact
    (finiteListsOver
      (finiteTemplateWordsUpTo A dB dC bound)
      e).image
      (fun outputs =>
        { outputs := outputs })

/-- Keep exactly the exact-once template tuples among the bounded candidates. -/
noncomputable def finiteExactTemplateTupleCodesUpTo
    (A : Finset α)
    (e dB dC bound : Nat) :
    Finset (FiniteExactTemplateTupleCode α e dB dC) := by
  classical
  let good :=
    (finiteTemplateTupleCodesUpTo A e dB dC bound).filter
      (fun C =>
        TemplateTuple.ExactlyOnce C.body)
  exact
    good.attach.image
      (fun C =>
        { code := C.1
          exactOnce :=
            (Finset.mem_filter.mp C.2).2 })

/-- Every enumerated exact template carries an exact-once body. -/
theorem finiteExactTemplateTupleCode_exactOnce
    (A : Finset α)
    (e dB dC bound : Nat)
    {C : FiniteExactTemplateTupleCode α e dB dC}
    (hC :
      C ∈ finiteExactTemplateTupleCodesUpTo
        A e dB dC bound) :
    TemplateTuple.ExactlyOnce C.body :=
  C.exactOnce

end FiniteTemplateTuples


section EnumeratedOccurrences

variable {α : Type u}

/-- A tuple occurrence together with its proof of membership in the finite
bounded occurrence enumeration. -/
abbrev EnumeratedTupleOccurrence
    (K : Finset (Word α))
    (d bound : Nat) :=
  { O : FiniteTupleOccurrenceCandidate α d //
      O ∈ tupleOccurrencesUpTo K d bound }

/-- Every enumerated occurrence fills to a word of the sample. -/
theorem EnumeratedTupleOccurrence.word_mem
    {K : Finset (Word α)}
    {d bound : Nat}
    (O : EnumeratedTupleOccurrence K d bound) :
    O.1.word ∈ K :=
  tupleOccurrence_word_mem K d bound O.2

end EnumeratedOccurrences


section BinaryWitnessCandidates

variable {α : Type u}

/-- One finite binary-witness candidate.

The three occurrence fields already carry proofs that their filled words are
in `K`.  The template field already carries exact-once linearity. -/
structure FiniteBinaryWitnessCandidate
    (K : Finset (Word α))
    (e dB dC bound : Nat) where

  parent :
    EnumeratedTupleOccurrence K e bound

  left :
    EnumeratedTupleOccurrence K dB bound

  right :
    EnumeratedTupleOccurrence K dC bound

  template :
    FiniteExactTemplateTupleCode α e dB dC

namespace FiniteBinaryWitnessCandidate

/-- Parent named context of a binary-witness candidate. -/
def parentContext
    {K : Finset (Word α)}
    {e dB dC bound : Nat}
    (B : FiniteBinaryWitnessCandidate K e dB dC bound) :
    NamedSentenceContext α e :=
  B.parent.1.context

/-- Left child tuple of a binary-witness candidate. -/
def leftTuple
    {K : Finset (Word α)}
    {e dB dC bound : Nat}
    (B : FiniteBinaryWitnessCandidate K e dB dC bound) :
    Tuple α dB :=
  B.left.1.tuple

/-- Right child tuple of a binary-witness candidate. -/
def rightTuple
    {K : Finset (Word α)}
    {e dB dC bound : Nat}
    (B : FiniteBinaryWitnessCandidate K e dB dC bound) :
    Tuple α dC :=
  B.right.1.tuple

/-- Exact-once template body of a binary-witness candidate. -/
def body
    {K : Finset (Word α)}
    {e dB dC bound : Nat}
    (B : FiniteBinaryWitnessCandidate K e dB dC bound) :
    TemplateTuple α e dB dC :=
  B.template.body

/-- Parent tuple produced by applying the candidate template to the two child
tuples. -/
def composedTuple
    {K : Finset (Word α)}
    {e dB dC bound : Nat}
    (B : FiniteBinaryWitnessCandidate K e dB dC bound) :
    Tuple α e :=
  evalTemplateTuple B.body
    B.leftTuple B.rightTuple

/-- The candidate template is exact-once. -/
theorem body_exactOnce
    {K : Finset (Word α)}
    {e dB dC bound : Nat}
    (B : FiniteBinaryWitnessCandidate K e dB dC bound) :
    TemplateTuple.ExactlyOnce B.body :=
  B.template.exactOnce

end FiniteBinaryWitnessCandidate

/-- Enumerate all bounded parent/left/right occurrence triples together with
all bounded exact-once template tuples. -/
noncomputable def binaryWitnessCandidatesUpTo
    (K : Finset (Word α))
    (e dB dC bound : Nat) :
    Finset
      (FiniteBinaryWitnessCandidate
        K e dB dC bound) := by
  classical
  let parents :=
    (tupleOccurrencesUpTo K e bound).attach
  let lefts :=
    (tupleOccurrencesUpTo K dB bound).attach
  let rights :=
    (tupleOccurrencesUpTo K dC bound).attach
  let templates :=
    finiteExactTemplateTupleCodesUpTo
      (sampleAlphabet K)
      e dB dC bound

  exact
    ((((parents.product lefts).product rights).product
      templates)).image
      (fun p =>
        { parent := p.1.1.1
          left := p.1.1.2
          right := p.1.2
          template := p.2 })

/-- Keep exactly the candidates whose enumerated parent tuple is the template
evaluation of the two enumerated child tuples. -/
noncomputable def concreteBinaryWitnessesUpTo
    (K : Finset (Word α))
    (e dB dC bound : Nat) :
    Finset
      (FiniteBinaryWitnessCandidate
        K e dB dC bound) := by
  classical
  exact
    (binaryWitnessCandidatesUpTo
      K e dB dC bound).filter
      (fun B =>
        B.parent.1.tuple =
          B.composedTuple)

/-- Default finite binary-witness enumeration, using the sample length budget. -/
noncomputable def concreteBinaryWitnesses
    (K : Finset (Word α))
    (e dB dC : Nat) :
    Finset
      (FiniteBinaryWitnessCandidate
        K e dB dC (sampleLengthBudget K)) :=
  concreteBinaryWitnessesUpTo
    K e dB dC (sampleLengthBudget K)

/-- Membership in the bounded witness set exposes candidate membership and the
parent-tuple equation. -/
theorem mem_concreteBinaryWitnessesUpTo_iff
    (K : Finset (Word α))
    (e dB dC bound : Nat)
    (B :
      FiniteBinaryWitnessCandidate
        K e dB dC bound) :
    B ∈ concreteBinaryWitnessesUpTo
        K e dB dC bound ↔
      B ∈ binaryWitnessCandidatesUpTo
          K e dB dC bound ∧
        B.parent.1.tuple =
          B.composedTuple := by
  classical
  simp [concreteBinaryWitnessesUpTo]

/-- Every enumerated witness has a sample parent occurrence, sample child
occurrences, an exact-once template, and the required parent-tuple equality. -/
theorem concreteBinaryWitness_spec
    (K : Finset (Word α))
    (e dB dC bound : Nat)
    {B :
      FiniteBinaryWitnessCandidate
        K e dB dC bound}
    (hB :
      B ∈ concreteBinaryWitnessesUpTo
        K e dB dC bound) :
    B.parent.1.word ∈ K ∧
      B.left.1.word ∈ K ∧
      B.right.1.word ∈ K ∧
      TemplateTuple.ExactlyOnce B.body ∧
      B.parent.1.tuple =
        B.composedTuple := by
  exact
    ⟨B.parent.word_mem,
      B.left.word_mem,
      B.right.word_mem,
      B.body_exactOnce,
      (mem_concreteBinaryWitnessesUpTo_iff
        K e dB dC bound B).mp hB |>.2⟩

end BinaryWitnessCandidates


section BinaryEvidenceExtraction

variable {α : Type u}

/-- Every enumerated bounded binary witness determines valid
`SampleBinaryEvidence`.

The parent membership comes from the enumerated parent occurrence.  The left
and right filling identities are constructed from the exact-once template by
the concrete splicing theorem. -/
def sampleBinaryEvidenceOfConcreteWitnessUpTo
    (K : Finset (Word α))
    (e dB dC bound : Nat)
    (B :
      FiniteBinaryWitnessCandidate
        K e dB dC bound)
    (hB :
      B ∈ concreteBinaryWitnessesUpTo
        K e dB dC bound) :
    SampleBinaryEvidence K
      B.parentContext
      B.body
      B.leftTuple
      B.rightTuple := by

  have htuple :
      B.parent.1.tuple =
        B.composedTuple :=
    (mem_concreteBinaryWitnessesUpTo_iff
      K e dB dC bound B).mp hB |>.2

  have hparent :
      namedFill e
          B.parentContext
          B.parent.1.tuple ∈ K := by
    simpa
      [FiniteTupleOccurrenceCandidate.word,
       FiniteBinaryWitnessCandidate.parentContext]
      using B.parent.word_mem

  let splice :=
    ExactSplicing.exactSplice
      B.parentContext
      B.body
      B.body_exactOnce

  exact
    { parent_mem := by
        change
          namedFill e B.parentContext
            B.composedTuple ∈ K
        rw [← htuple]
        exact hparent

      leftIdentity :=
        splice.leftIdentity B.rightTuple

      rightIdentity :=
        fun u =>
          splice.rightIdentity u }

/-- Every default enumerated binary witness determines valid
`SampleBinaryEvidence`. -/
def sampleBinaryEvidenceOfConcreteWitness
    (K : Finset (Word α))
    (e dB dC : Nat)
    (B :
      FiniteBinaryWitnessCandidate
        K e dB dC (sampleLengthBudget K))
    (hB :
      B ∈ concreteBinaryWitnesses
        K e dB dC) :
    SampleBinaryEvidence K
      B.parentContext
      B.body
      B.leftTuple
      B.rightTuple :=
  sampleBinaryEvidenceOfConcreteWitnessUpTo
    K e dB dC
    (sampleLengthBudget K)
    B hB

/-- The source parent tuple of an enumerated binary witness is definitionally
the template composition of its two child tuples. -/
theorem concreteBinaryWitness_parent_eq
    (K : Finset (Word α))
    (e dB dC bound : Nat)
    {B :
      FiniteBinaryWitnessCandidate
        K e dB dC bound}
    (hB :
      B ∈ concreteBinaryWitnessesUpTo
        K e dB dC bound) :
    B.parent.1.tuple =
      evalTemplateTuple B.body
        B.leftTuple B.rightTuple :=
  (mem_concreteBinaryWitnessesUpTo_iff
    K e dB dC bound B).mp hB |>.2

end BinaryEvidenceExtraction

end MCFG
