import LeanCfgProject.MCFG.FI_v2_1_SampleGeneratedWordParseWitness

/-!
# FI v2.1 Lean experiment: exact package for word-level parse witnesses

This layer packages word-level and sample-level parse witnesses against the
concrete generated prefix-node grammar shell.  It is the first explicit
sample-consistency package for the generated `WorkingMCFG` shell: once every
sample word has a prefix-node parse witness, every sample word lies in the
output grammar's string language.
-/

namespace FIv21

universe u v w

section SampleGeneratedWordParseWitnessExact

variable {N : Type w} {α : Type u}
variable [DecidableEq α]
variable {M : Type v} [Monoid M] [Fintype M]

/-- Exact package for word-level parse witnesses. -/
structure SampleGeneratedWordParseWitnessExact
    (G : WorkingMCFG N α) (obs : α → M) (K : Finset (Word α)) where
  prefixNodeExact : SampleGeneratedPrefixNodeEnumerationExact G obs K

namespace SampleGeneratedWordParseWitnessExact

/-- The underlying rule skeleton. -/
def ruleSkeleton
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (E : SampleGeneratedWordParseWitnessExact G obs K) :
    SampleGeneratedRuleSkeleton G obs K :=
  E.prefixNodeExact.ruleSkeleton

/-- The generated rule-list package. -/
noncomputable def ruleLists
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (E : SampleGeneratedWordParseWitnessExact G obs K) :
    SampleGeneratedRuleListPackage G obs K :=
  E.prefixNodeExact.ruleLists

/-- The generated working grammar shell. -/
noncomputable def toWorkingMCFG
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (E : SampleGeneratedWordParseWitnessExact G obs K) :
    WorkingMCFG (SampleGeneratedGrammarNonterminal
      E.ruleLists.ruleSkeleton.skeleton) α :=
  E.prefixNodeExact.toWorkingMCFG

/-- The generated grammar shell is semantically well-formed. -/
theorem semanticWorkingConditions
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (E : SampleGeneratedWordParseWitnessExact G obs K) :
    E.toWorkingMCFG.SemanticWorkingConditions := by
  exact E.prefixNodeExact.semanticWorkingConditions

/-- A word-level witness gives membership in the generated grammar shell. -/
theorem wordWitness_mem_stringLanguage
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (E : SampleGeneratedWordParseWitnessExact G obs K)
    {w : Word α}
    (W : SampleGeneratedWordParseWitness (M := M) E.ruleSkeleton w) :
    w ∈ E.toWorkingMCFG.StringLanguage := by
  exact E.prefixNodeExact.prefixNodeEnumeration_mem_stringLanguage (M := M) W.parse

/-- A sample-level witness package gives sample inclusion in the generated
grammar shell. -/
theorem sampleWitnesses_subset_stringLanguage
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (E : SampleGeneratedWordParseWitnessExact G obs K)
    (P : SampleGeneratedSampleParseWitnesses (M := M) E.ruleSkeleton) :
    ∀ w : Word α, w ∈ K → w ∈ E.toWorkingMCFG.StringLanguage := by
  intro w hw
  exact E.wordWitness_mem_stringLanguage (M := M) (P.witnessOfMem (M := M) hw)

end SampleGeneratedWordParseWitnessExact

/-- Exact package including parse witnesses for every sample word. -/
structure SampleGeneratedSampleParseWitnessesExact
    (G : WorkingMCFG N α) (obs : α → M) (K : Finset (Word α)) where
  exactPackage : SampleGeneratedWordParseWitnessExact G obs K
  parses : SampleGeneratedSampleParseWitnesses (M := M) exactPackage.ruleSkeleton

namespace SampleGeneratedSampleParseWitnessesExact

/-- The generated grammar shell. -/
noncomputable def toWorkingMCFG
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (E : SampleGeneratedSampleParseWitnessesExact G obs K) :
    WorkingMCFG (SampleGeneratedGrammarNonterminal
      E.exactPackage.ruleLists.ruleSkeleton.skeleton) α :=
  E.exactPackage.toWorkingMCFG

/-- The generated grammar shell is semantically well-formed. -/
theorem semanticWorkingConditions
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (E : SampleGeneratedSampleParseWitnessesExact G obs K) :
    E.toWorkingMCFG.SemanticWorkingConditions := by
  exact E.exactPackage.semanticWorkingConditions

/-- Every sample word is generated by the generated grammar shell. -/
theorem sample_subset_stringLanguage
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (E : SampleGeneratedSampleParseWitnessesExact G obs K) :
    ∀ w : Word α, w ∈ K → w ∈ E.toWorkingMCFG.StringLanguage := by
  exact E.exactPackage.sampleWitnesses_subset_stringLanguage (M := M) E.parses

end SampleGeneratedSampleParseWitnessesExact

/-- Concrete exact package using the enumerated prefix-node grammar shell. -/
noncomputable def enumeratedSampleGeneratedWordParseWitnessExact
    (G : WorkingMCFG N α) (obs : α → M) (K : Finset (Word α))
    (f : Nat) (hfanout : 1 ≤ f) (hG : G.SemanticWorkingConditions) :
    SampleGeneratedWordParseWitnessExact G obs K :=
  { prefixNodeExact :=
      enumeratedSampleGeneratedPrefixNodeEnumerationExact G obs K f hfanout hG }

/-- The concrete generated grammar shell is semantically well-formed. -/
theorem enumeratedSampleGeneratedWordParseWitnessExact_semantic
    (G : WorkingMCFG N α) (obs : α → M) (K : Finset (Word α))
    (f : Nat) (hfanout : 1 ≤ f) (hG : G.SemanticWorkingConditions) :
    (enumeratedSampleGeneratedWordParseWitnessExact
      G obs K f hfanout hG).toWorkingMCFG.SemanticWorkingConditions := by
  exact (enumeratedSampleGeneratedWordParseWitnessExact
    G obs K f hfanout hG).semanticWorkingConditions

end SampleGeneratedWordParseWitnessExact

end FIv21
