import LeanCfgProject.MCFG.FI_v2_1_LearnerWordSemanticsGold

/-!
# FI v2.1 Lean experiment: canonical learner grammar interface

This fiftieth layer introduces a small package for the eventual canonical
learner grammar extracted from a finite positive sample.

The full grammar construction is still not implemented here.  Instead, the
package records exactly the data that the already-checked development can use:
concrete extracted sample data, together with a learner-side word semantics
certificate for that data.  A later concrete grammar construction should
instantiate this interface by taking the word language to be the string language
of the constructed learner grammar.
-/

namespace FIv21

universe u v w

section CanonicalLearnerGrammarInterface

variable {N : Type w} {α : Type u}
variable [DecidableEq α]
variable {M : Type v} [Monoid M] [Fintype M]

/-- A one-sample package for the eventual canonical learner grammar.

The field `data` is the implementation-facing extracted sample data already
connected to finite hypotheses and refined-rule certificates.  The field
`semantics` supplies the learner-side word language for this extracted datum and
proves that it contains every word of the finite sample.
-/
structure CanonicalLearnerGrammarPackage
    (G : WorkingMCFG N α) (obs : α → M) (K : Finset (Word α)) where
  data : ConcreteExtractedSampleData G obs K
  semantics : ConcreteExtractedSampleWordSemanticsCertificate data

namespace CanonicalLearnerGrammarPackage

/-- Forget the grammar package to its concrete extracted sample data. -/
def toConcreteExtractedSampleData
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (P : CanonicalLearnerGrammarPackage G obs K) :
    ConcreteExtractedSampleData G obs K :=
  P.data

/-- The finite learner hypothesis induced by the package. -/
def toFiniteLearnerHypothesis
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (P : CanonicalLearnerGrammarPackage G obs K) :
    FiniteLearnerHypothesis α M :=
  P.data.toFiniteLearnerHypothesis

/-- The package uses exactly the external finite sample. -/
theorem finiteHypothesis_sampleSet
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (P : CanonicalLearnerGrammarPackage G obs K) :
    P.toFiniteLearnerHypothesis.sampleSet = K := by
  exact P.data.finiteHypothesis_sampleSet

/-- The learner-side word language carried by the package. -/
def wordLanguage
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (P : CanonicalLearnerGrammarPackage G obs K) : Set (Word α) :=
  P.semantics.wordLanguage

/-- Every sampled word is generated by the packaged learner-side word
semantics. -/
theorem sample_word_generated
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (P : CanonicalLearnerGrammarPackage G obs K)
    (w : Word α) (hw : w ∈ K) :
    w ∈ P.wordLanguage := by
  exact P.semantics.sample_word_generated w hw

/-- The packaged semantics induces the previously checked learner-word
consistency predicate. -/
theorem learner_word_consistent
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (P : CanonicalLearnerGrammarPackage G obs K) :
    ConcreteExtractedSampleLearnerWordConsistent P.data P.wordLanguage := by
  exact P.semantics.sample_consistent

/-- The approximate named-context distribution induced by the package. -/
def ApproxDistribution
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (P : CanonicalLearnerGrammarPackage G obs K)
    {d : Nat} (x : Tuple α d) : Set (NamedSentenceContext α d) :=
  P.data.ApproxDistribution x

/-- Unit reachability induced by the package. -/
def UnitReach
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (P : CanonicalLearnerGrammarPackage G obs K)
    {d : Nat} (x y : Tuple α d) : Prop :=
  P.data.UnitReach x y

/-- A listed unit edge yields package-level unit reachability. -/
theorem listedEdge_reach
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (P : CanonicalLearnerGrammarPackage G obs K)
    {d : Nat} {x y : Tuple α d}
    (hxy : P.data.support.SupportsUnitEdge x y) :
    P.UnitReach x y := by
  exact P.data.listedEdge_reach hxy

/-- Distributional soundness of the package-level approximate distribution. -/
theorem approxDistribution_sound_for_language
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (P : CanonicalLearnerGrammarPackage G obs K)
    {L : Set (Word α)}
    (hK : PositiveForLanguage P.toFiniteLearnerHypothesis.sampleSet L)
    (hL : FixedNamedTupleSubstitutable P.data.f obs L)
    {d : Nat} (x : Tuple α d) :
    P.ApproxDistribution x ⊆ NamedDistribution L x := by
  exact P.data.approxDistribution_sound_for_language hK hL x

/-- The concrete refined-rule enumeration carried by the package. -/
def concreteRules
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (P : CanonicalLearnerGrammarPackage G obs K) :
    FintypeConcreteRuleEnumeration G obs :=
  P.data.concreteRules

/-- Refined tuple language carried by the package's concrete refined-rule
enumeration. -/
noncomputable def RefinedTupleLanguage
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (P : CanonicalLearnerGrammarPackage G obs K)
    (A : RefinedNonterminal G M) : Set (Tuple α (G.arity A.base)) :=
  P.data.RefinedTupleLanguage A

/-- Soundness of the package-level refined tuple language. -/
theorem refinedTupleLanguage_sound
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (P : CanonicalLearnerGrammarPackage G obs K)
    (A : RefinedNonterminal G M) :
    P.RefinedTupleLanguage A ⊆ OutputTypedTupleLanguage G obs A := by
  intro x hx
  exact P.data.refinedTupleLanguage_sound A hx

/-- Forgetting output types maps package-level refined derivations to the base
tuple language. -/
theorem refinedTupleLanguage_forgets_to_base
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (P : CanonicalLearnerGrammarPackage G obs K)
    (A : RefinedNonterminal G M) :
    P.RefinedTupleLanguage A ⊆ FIv21.TupleLanguage G A.base := by
  intro x hx
  exact P.data.refinedTupleLanguage_forgets_to_base A hx

/-- Package-level refined derivations have the advertised output type. -/
theorem refinedTupleLanguage_has_output_type
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (P : CanonicalLearnerGrammarPackage G obs K)
    (A : RefinedNonterminal G M)
    {x : Tuple α (G.arity A.base)}
    (hx : x ∈ P.RefinedTupleLanguage A) :
    tupleType obs x = A.outTy := by
  exact P.data.refinedTupleLanguage_has_output_type A hx

end CanonicalLearnerGrammarPackage

end CanonicalLearnerGrammarInterface

end FIv21
