import LeanCfgProject.MCFG.FI_v2_1_RawSampleDecompositionGenerationGold

/-!
# FI v2.1 Lean experiment: enumerating elementary raw sample decompositions

This file is a deliberately concrete vertical step after
`RawSampleDecompositionGeneration`.

The previous layers accepted a finite list of raw decomposition witnesses.  Here
we construct, for every sampled word `w ∈ K`, a canonical one-hole raw
sample-decomposition witness

`w = namedFill 1 identityNamedContext (singletonTuple w)`.

This is not yet the full enumeration of all subtuple/context decompositions
needed for the final learner.  It is the first actual enumeration layer: raw
sample words are no longer merely assumed to have listed decompositions; each
sample word contributes at least its trivial one-hole decomposition to the raw
support pipeline.
-/

namespace FIv21

universe u v w

noncomputable section RawSampleDecompositionEnumeration

variable {N : Type w} {α : Type u}
variable [DecidableEq α]
variable {M : Type v} [Monoid M] [Fintype M]

/-- The identity one-hole named sentence context.  Filling it with the singleton
word tuple returns the word itself. -/
def identityNamedContext : NamedSentenceContext α 1 :=
  { val :=
      { chunks := [([] : Word α), ([] : Word α)]
        holes := [finOne] }
    property := by
      constructor
      · rfl
      constructor
      · simp
      · intro i
        have hi : i = finOne := by
          apply Fin.ext
          simpa [finOne] using Nat.eq_zero_of_lt_one i.isLt
        simp [hi] }

@[simp] theorem namedFill_identityNamedContext_singletonTuple
    (w : Word α) :
    namedFill 1 (identityNamedContext (α := α)) (singletonTuple w) = w := by
  simpa [identityNamedContext, namedFill, singletonTuple] using
    (rawNamedFill_twoSided ([] : Word α) ([] : Word α) (singletonTuple w))

/-- The canonical trivial raw decomposition of a sampled word. -/
def singletonRawSampleDecomposition
    (K : Finset (Word α))
    (w : { w // w ∈ K }) : RawSampleDecomposition (α := α) K :=
  { d := 1
    tuple := singletonTuple w.1
    context := identityNamedContext (α := α)
    sampleWord := w.1
    sampleWord_mem := w.2
    filled_eq := by
      exact namedFill_identityNamedContext_singletonTuple (α := α) w.1 }

/-- The finite list of trivial one-hole decompositions generated by the sample
itself. -/
noncomputable def singletonRawSampleDecompositions
    (K : Finset (Word α)) : List (RawSampleDecomposition (α := α) K) := by
  classical
  exact K.attach.toList.map (singletonRawSampleDecomposition (α := α) K)

/-- Every attached sample word contributes its trivial decomposition to the
finite decomposition list. -/
theorem singletonRawSampleDecomposition_mem
    {K : Finset (Word α)}
    (w : { w // w ∈ K }) :
    singletonRawSampleDecomposition (α := α) K w ∈
      singletonRawSampleDecompositions (α := α) K := by
  unfold singletonRawSampleDecompositions
  exact List.mem_map.mpr ⟨w, by simp, rfl⟩

/-- Every word in the sample is covered by a listed trivial raw decomposition. -/
theorem exists_singletonRawSampleDecomposition_of_mem
    {K : Finset (Word α)} {w : Word α}
    (hw : w ∈ K) :
    ∃ R : RawSampleDecomposition (α := α) K,
      R ∈ singletonRawSampleDecompositions (α := α) K ∧
      R.sampleWord = w ∧
      namedFill R.d R.context R.tuple = w := by
  let sw : { w // w ∈ K } := ⟨w, hw⟩
  refine ⟨singletonRawSampleDecomposition (α := α) K sw, ?_, rfl, ?_⟩
  · exact singletonRawSampleDecomposition_mem (α := α) sw
  · exact namedFill_identityNamedContext_singletonTuple (α := α) w

/-- Raw decomposition data whose decomposition list contains the trivial
one-hole decomposition of every sample word and whose unit-edge witness list is
empty. -/
noncomputable def sampleWordOnlyRawSampleDecompositionData
    (G : WorkingMCFG N α) (obs : α → M) (K : Finset (Word α))
    (f : Nat) (hG : G.SemanticWorkingConditions) :
    RawSampleDecompositionData G obs K :=
  { f := f
    decompositions := singletonRawSampleDecompositions (α := α) K
    unitEdgeWitnesses := []
    semanticWorking := hG }

@[simp] theorem sampleWordOnlyRawSampleDecompositionData_decompositions
    (G : WorkingMCFG N α) (obs : α → M) (K : Finset (Word α))
    (f : Nat) (hG : G.SemanticWorkingConditions) :
    (sampleWordOnlyRawSampleDecompositionData G obs K f hG).decompositions =
      singletonRawSampleDecompositions (α := α) K := by
  rfl

@[simp] theorem sampleWordOnlyRawSampleDecompositionData_unitEdgeWitnesses
    (G : WorkingMCFG N α) (obs : α → M) (K : Finset (Word α))
    (f : Nat) (hG : G.SemanticWorkingConditions) :
    (sampleWordOnlyRawSampleDecompositionData G obs K f hG).unitEdgeWitnesses =
      ([] : List (RawSampleUnitEdgeWitness (α := α) K obs f)) := by
  rfl

namespace RawSampleDecompositionData

/-- If the decomposition list is the singleton-word enumeration, then every
sample word has a listed raw decomposition. -/
theorem covers_sample_of_singletonDecompositions
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (D : RawSampleDecompositionData G obs K)
    (hD : D.decompositions = singletonRawSampleDecompositions (α := α) K)
    {w : Word α} (hw : w ∈ K) :
    ∃ R : RawSampleDecomposition (α := α) K,
      R ∈ D.decompositions ∧
      R.sampleWord = w ∧
      namedFill R.d R.context R.tuple = w := by
  rcases exists_singletonRawSampleDecomposition_of_mem (α := α) hw with
    ⟨R, hR, hWord, hFill⟩
  refine ⟨R, ?_, hWord, hFill⟩
  simpa [hD] using hR

/-- If the decomposition list is the singleton-word enumeration, then every
sample word has a listed decomposition whose tuple and context are supported and
whose context is licensed by the sample distribution. -/
theorem supported_singletonDecomposition_of_sample_mem
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (D : RawSampleDecompositionData G obs K)
    (hD : D.decompositions = singletonRawSampleDecompositions (α := α) K)
    {w : Word α} (hw : w ∈ K) :
    ∃ R : RawSampleDecomposition (α := α) K,
      R ∈ D.decompositions ∧
      R.sampleWord = w ∧
      D.support.SupportsTuple R.tuple ∧
      D.support.SupportsContext R.context ∧
      R.context ∈ SampleNamedDistribution K R.tuple := by
  rcases D.covers_sample_of_singletonDecompositions hD hw with
    ⟨R, hR, hWord, _hFill⟩
  have hSupp := D.decomposition_supported hR
  have hLic := D.decomposition_sample_licensed hR
  exact ⟨R, hR, hWord, hSupp.1, hSupp.2, hLic⟩

end RawSampleDecompositionData

/-- The sample-word-only data covers every sample word by a listed raw
decomposition. -/
theorem sampleWordOnlyRawSampleDecompositionData_covers_sample
    (G : WorkingMCFG N α) (obs : α → M) (K : Finset (Word α))
    (f : Nat) (hG : G.SemanticWorkingConditions)
    {w : Word α} (hw : w ∈ K) :
    ∃ R : RawSampleDecomposition (α := α) K,
      R ∈ (sampleWordOnlyRawSampleDecompositionData G obs K f hG).decompositions ∧
      R.sampleWord = w ∧
      namedFill R.d R.context R.tuple = w := by
  exact RawSampleDecompositionData.covers_sample_of_singletonDecompositions
    (sampleWordOnlyRawSampleDecompositionData G obs K f hG) rfl hw

/-- The sample-word-only data supports the tuple and context of the trivial
raw decomposition of every sampled word. -/
theorem sampleWordOnlyRawSampleDecompositionData_supported_sample_word
    (G : WorkingMCFG N α) (obs : α → M) (K : Finset (Word α))
    (f : Nat) (hG : G.SemanticWorkingConditions)
    {w : Word α} (hw : w ∈ K) :
    ∃ R : RawSampleDecomposition (α := α) K,
      R ∈ (sampleWordOnlyRawSampleDecompositionData G obs K f hG).decompositions ∧
      R.sampleWord = w ∧
      (sampleWordOnlyRawSampleDecompositionData G obs K f hG).support.SupportsTuple R.tuple ∧
      (sampleWordOnlyRawSampleDecompositionData G obs K f hG).support.SupportsContext R.context ∧
      R.context ∈ SampleNamedDistribution K R.tuple := by
  exact RawSampleDecompositionData.supported_singletonDecomposition_of_sample_mem
    (sampleWordOnlyRawSampleDecompositionData G obs K f hG) rfl hw

/-- A learner that always uses the sample-word-only raw decomposition data. -/
noncomputable def sampleWordOnlyRawSampleDecompositionLearner
    (G : WorkingMCFG N α) (obs : α → M)
    (f : Nat) (hG : G.SemanticWorkingConditions) :
    RawSampleDecompositionLearner G obs :=
  fun K => sampleWordOnlyRawSampleDecompositionData G obs K f hG

/-- The sample-word-only learner covers every word of its input sample. -/
theorem sampleWordOnlyRawSampleDecompositionLearner_covers_sample
    (G : WorkingMCFG N α) (obs : α → M)
    (f : Nat) (hG : G.SemanticWorkingConditions)
    (K : Finset (Word α)) {w : Word α} (hw : w ∈ K) :
    ∃ R : RawSampleDecomposition (α := α) K,
      R ∈ (sampleWordOnlyRawSampleDecompositionLearner G obs f hG K).decompositions ∧
      R.sampleWord = w ∧
      namedFill R.d R.context R.tuple = w := by
  exact sampleWordOnlyRawSampleDecompositionData_covers_sample G obs K f hG hw

end RawSampleDecompositionEnumeration

end FIv21
