import LeanCfgProject.MCFG.FI_v2_1_SampleGeneratedTerminalEnumerationExact

/-!
# FI v2.1 Lean experiment: Gold wrapper for terminal-enumerated generated grammars

This file lifts the terminal-enumerated generated grammar shell to a learner-like
object.  The important concrete exported fact is: for the concrete enumerated
learner, every singleton sample word `[a]` is actually generated by the output
`WorkingMCFG` shell.
-/

namespace FIv21

universe u v w

section SampleGeneratedTerminalEnumerationGold

variable {N : Type w} {α : Type u}
variable [DecidableEq α]
variable {M : Type v} [Monoid M] [Fintype M]

/-- Learner-like map from samples to terminal-enumerated generated working
grammars. -/
structure SampleGeneratedTerminalEnumerationLearner
    (G : WorkingMCFG N α) (obs : α → M) where
  exactPackage :
    (K : Finset (Word α)) → SampleGeneratedTerminalEnumerationExact G obs K

namespace SampleGeneratedTerminalEnumerationLearner

/-- Rule lists after seeing finite sample `K`. -/
noncomputable def ruleLists
    {G : WorkingMCFG N α} {obs : α → M}
    (L : SampleGeneratedTerminalEnumerationLearner G obs)
    (K : Finset (Word α)) : SampleGeneratedRuleListPackage G obs K :=
  (L.exactPackage K).ruleLists

/-- Output grammar after seeing finite sample `K`. -/
noncomputable def grammar
    {G : WorkingMCFG N α} {obs : α → M}
    (L : SampleGeneratedTerminalEnumerationLearner G obs)
    (K : Finset (Word α)) :
    WorkingMCFG (SampleGeneratedGrammarNonterminal
      (L.ruleLists K).ruleSkeleton.skeleton) α :=
  (L.exactPackage K).toWorkingMCFG

/-- Every output grammar is semantically well-formed. -/
theorem grammar_semanticWorkingConditions
    {G : WorkingMCFG N α} {obs : α → M}
    (L : SampleGeneratedTerminalEnumerationLearner G obs)
    (K : Finset (Word α)) :
    (L.grammar K).SemanticWorkingConditions := by
  exact (L.exactPackage K).semanticWorkingConditions

end SampleGeneratedTerminalEnumerationLearner

/-- Concrete terminal-enumerated learner for a fixed fanout bound. -/
noncomputable def enumeratedSampleGeneratedTerminalEnumerationLearner
    (G : WorkingMCFG N α) (obs : α → M)
    (f : Nat) (hfanout : 1 ≤ f) (hG : G.SemanticWorkingConditions) :
    SampleGeneratedTerminalEnumerationLearner G obs :=
  { exactPackage := fun K =>
      enumeratedSampleGeneratedTerminalEnumerationExact G obs K f hfanout hG }

/-- Concrete singleton-generation theorem for the terminal-enumerated learner. -/
theorem enumeratedSampleGeneratedTerminalEnumerationLearner_singleton
    (G : WorkingMCFG N α) (obs : α → M)
    (f : Nat) (hfanout : 1 ≤ f) (hG : G.SemanticWorkingConditions)
    (K : Finset (Word α)) {a : α}
    (ha : ([a] : Word α) ∈ K) :
    ([a] : Word α) ∈
      ((enumeratedSampleGeneratedTerminalEnumerationLearner G obs f hfanout hG)
        .grammar K).StringLanguage := by
  exact enumeratedSampleGeneratedTerminalEnumerationExact_singleton
    (M := M) G obs K f hfanout hG ha

/-- Gold-style summary for the terminal-enumerated generated grammar shell. -/
structure SampleGeneratedTerminalEnumerationGoldSummary
    (G : WorkingMCFG N α) (obs : α → M) where
  learner : SampleGeneratedTerminalEnumerationLearner G obs
  characteristicSample : Finset (Word α)

namespace SampleGeneratedTerminalEnumerationGoldSummary

/-- Output grammar after finite sample `K`. -/
noncomputable def grammar
    {G : WorkingMCFG N α} {obs : α → M}
    (S : SampleGeneratedTerminalEnumerationGoldSummary G obs)
    (K : Finset (Word α)) :
    WorkingMCFG (SampleGeneratedGrammarNonterminal
      (S.learner.ruleLists K).ruleSkeleton.skeleton) α :=
  S.learner.grammar K

/-- Output grammar is semantically well-formed. -/
theorem grammar_semanticWorkingConditions
    {G : WorkingMCFG N α} {obs : α → M}
    (S : SampleGeneratedTerminalEnumerationGoldSummary G obs)
    (K : Finset (Word α)) :
    (S.grammar K).SemanticWorkingConditions := by
  exact S.learner.grammar_semanticWorkingConditions K

end SampleGeneratedTerminalEnumerationGoldSummary

/-- Concrete enumerated Gold-style terminal-enumeration summary. -/
noncomputable def enumeratedSampleGeneratedTerminalEnumerationGoldSummary
    (G : WorkingMCFG N α) (obs : α → M)
    (f : Nat) (hfanout : 1 ≤ f) (hG : G.SemanticWorkingConditions)
    (CS : Finset (Word α)) :
    SampleGeneratedTerminalEnumerationGoldSummary G obs :=
  { learner := enumeratedSampleGeneratedTerminalEnumerationLearner
      G obs f hfanout hG
    characteristicSample := CS }

end SampleGeneratedTerminalEnumerationGold

end FIv21
