import LeanCfgProject.MCFG.FI_v2_1_SampleGeneratedConsistencyToPackage

/-!
# FI v2.1 Lean experiment: exact wrapper for generated consistency packages

This layer keeps the bridge package as a first-class exact object.  It exposes
its generated grammar, generated language, semantic well-formedness, and
positive-sample certificate in a form convenient for later learner-style
wrappers.
-/

namespace FIv21

universe u v w

section SampleGeneratedConsistencyToPackageExact

variable {N : Type w} {α : Type u}
variable [DecidableEq α]
variable {M : Type v} [Monoid M] [Fintype M]

/-- Exact object whose main content is a generated consistency package. -/
structure SampleGeneratedConsistencyPackageExact
    (G : WorkingMCFG N α) (obs : α → M) (K : Finset (Word α)) where
  package : SampleGeneratedConsistencyPackage G obs K

namespace SampleGeneratedConsistencyPackageExact

/-- The previous nonempty exact package. -/
def exactPackage
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (E : SampleGeneratedConsistencyPackageExact G obs K) :
    SampleGeneratedNonemptySampleConsistencyExact G obs K :=
  E.package.exactPackage

/-- The rule skeleton. -/
def ruleSkeleton
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (E : SampleGeneratedConsistencyPackageExact G obs K) :
    SampleGeneratedRuleSkeleton G obs K :=
  E.package.ruleSkeleton

/-- The generated rule-list package. -/
noncomputable def ruleLists
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (E : SampleGeneratedConsistencyPackageExact G obs K) :
    SampleGeneratedRuleListPackage G obs K :=
  E.package.ruleLists

/-- The generated grammar. -/
noncomputable def grammar
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (E : SampleGeneratedConsistencyPackageExact G obs K) :
    WorkingMCFG (SampleGeneratedGrammarNonterminal
      E.ruleLists.ruleSkeleton.skeleton) α :=
  E.package.grammar

/-- The generated language. -/
noncomputable def language
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (E : SampleGeneratedConsistencyPackageExact G obs K) : Set (Word α) :=
  E.grammar.StringLanguage

/-- The generated grammar is semantically well-formed. -/
theorem semanticWorkingConditions
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (E : SampleGeneratedConsistencyPackageExact G obs K) :
    E.grammar.SemanticWorkingConditions := by
  exact E.package.semanticWorkingConditions

/-- The sample has no empty words. -/
def nonemptySample
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (E : SampleGeneratedConsistencyPackageExact G obs K) :
    NonemptyWordSample K :=
  E.package.nonemptySample

/-- Every sample word is generated by the generated grammar. -/
theorem sample_subset_language
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (E : SampleGeneratedConsistencyPackageExact G obs K) :
    ∀ w : Word α, w ∈ K → w ∈ E.language := by
  exact E.package.sample_subset_language

/-- Positivity certificate for the generated language. -/
theorem positiveForLanguage
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (E : SampleGeneratedConsistencyPackageExact G obs K) :
    PositiveForLanguage K E.language := by
  exact E.sample_subset_language

/-- Compact word-language certificate. -/
noncomputable def toWordLanguageCertificate
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (E : SampleGeneratedConsistencyPackageExact G obs K) :
    SampleGeneratedWordLanguageCertificate (α := α) K :=
  { language := E.language
    positive := E.positiveForLanguage }

/-- Pointwise sample generation. -/
theorem word_mem_generatedLanguage
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (E : SampleGeneratedConsistencyPackageExact G obs K)
    {w : Word α} (hw : w ∈ K) :
    w ∈ E.language := by
  exact E.sample_subset_language w hw

end SampleGeneratedConsistencyPackageExact

/-- Build the exact bridge from the previous nonempty exact package. -/
def SampleGeneratedConsistencyPackageExact.ofNonemptyExact
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (E : SampleGeneratedNonemptySampleConsistencyExact G obs K) :
    SampleGeneratedConsistencyPackageExact G obs K :=
  { package := SampleGeneratedConsistencyPackage.ofExact (M := M) E }

/-- Concrete enumerated exact bridge package. -/
noncomputable def enumeratedSampleGeneratedConsistencyPackageExact
    (G : WorkingMCFG N α) (obs : α → M) (K : Finset (Word α))
    (f : Nat) (hfanout : 1 ≤ f) (hG : G.SemanticWorkingConditions)
    (F : SampleGeneratedNonemptyPrefixEnumerationFamily (M := M)
      (enumeratedSampleGeneratedWordParseWitnessConstructionExact
        G obs K f hfanout hG).ruleSkeleton) :
    SampleGeneratedConsistencyPackageExact G obs K :=
  { package :=
      enumeratedSampleGeneratedConsistencyPackage G obs K f hfanout hG F }

/-- The concrete enumerated exact bridge package is semantically well-formed. -/
theorem enumeratedSampleGeneratedConsistencyPackageExact_semantic
    (G : WorkingMCFG N α) (obs : α → M) (K : Finset (Word α))
    (f : Nat) (hfanout : 1 ≤ f) (hG : G.SemanticWorkingConditions)
    (F : SampleGeneratedNonemptyPrefixEnumerationFamily (M := M)
      (enumeratedSampleGeneratedWordParseWitnessConstructionExact
        G obs K f hfanout hG).ruleSkeleton) :
    (enumeratedSampleGeneratedConsistencyPackageExact
      G obs K f hfanout hG F).grammar.SemanticWorkingConditions := by
  exact (enumeratedSampleGeneratedConsistencyPackageExact
    G obs K f hfanout hG F).semanticWorkingConditions

end SampleGeneratedConsistencyToPackageExact

end FIv21
