import LeanCfgProject.MCFG.FI_v2_1_ObservedSampleAtomsGold

/-!
# FI v2.1 Lean experiment: raw sample decompositions

This file is the next vertical step after `ObservedSampleAtoms`.

The previous layer accepted explicit tuple/context/unit-edge atom lists.  Here
we introduce a witness layer closer to the raw positive sample: a listed tuple
and context atom can now come from an explicit decomposition of a sampled word
as `namedFill d c x`.  Unit edges are generated from explicit shared-context
witnesses carrying the sample-safe merge data.  Thus the finite support is no
longer merely an arbitrary list of atoms: it is assembled from decomposition
and merge witnesses tied to the finite sample.
-/

namespace FIv21

universe u v w

section RawSampleDecomposition

variable {N : Type w} {α : Type u}
variable [DecidableEq α]
variable {M : Type v} [Monoid M] [Fintype M]

/-- A raw decomposition of a sampled word as a named context filled by a tuple.

This is intentionally independent of a grammar occurrence.  It records only the
sample-level fact that the word `sampleWord` belongs to `K` and is obtained by
filling the named context `context` with the tuple `tuple`.  Later occurrence
layers can add derivation-tree information on top of this witness. -/
structure RawSampleDecomposition (K : Finset (Word α)) where
  d : Nat
  tuple : Tuple α d
  context : NamedSentenceContext α d
  sampleWord : Word α
  sampleWord_mem : sampleWord ∈ K
  filled_eq : namedFill d context tuple = sampleWord

namespace RawSampleDecomposition

/-- The tuple atom exposed by a raw sample decomposition. -/
def toTupleAtom {K : Finset (Word α)} (D : RawSampleDecomposition K) : TupleAtom α :=
  Sigma.mk D.d D.tuple

/-- The context atom exposed by a raw sample decomposition. -/
def toContextAtom {K : Finset (Word α)} (D : RawSampleDecomposition K) : ContextAtom α :=
  Sigma.mk D.d D.context

/-- The filled word of a raw decomposition is indeed in the sample. -/
theorem filled_mem_sample {K : Finset (Word α)} (D : RawSampleDecomposition K) :
    namedFill D.d D.context D.tuple ∈ K := by
  simpa [D.filled_eq] using D.sampleWord_mem

/-- A raw decomposition certifies membership in the sample distribution of its
exposed tuple. -/
theorem context_mem_sampleDistribution {K : Finset (Word α)}
    (D : RawSampleDecomposition K) :
    D.context ∈ SampleNamedDistribution K D.tuple := by
  exact D.filled_mem_sample

end RawSampleDecomposition

/-- Tuple atoms generated by a finite list of raw decompositions. -/
def tupleAtomsOfRawSampleDecompositions
    {K : Finset (Word α)}
    (Ds : List (RawSampleDecomposition (α := α) K)) : List (TupleAtom α) :=
  Ds.map RawSampleDecomposition.toTupleAtom

/-- Context atoms generated by a finite list of raw decompositions. -/
def contextAtomsOfRawSampleDecompositions
    {K : Finset (Word α)}
    (Ds : List (RawSampleDecomposition (α := α) K)) : List (ContextAtom α) :=
  Ds.map RawSampleDecomposition.toContextAtom

/-- A listed decomposition contributes its tuple atom to the generated tuple
atom list. -/
theorem tupleAtom_mem_of_rawDecomposition_mem
    {K : Finset (Word α)}
    {Ds : List (RawSampleDecomposition (α := α) K)}
    {D : RawSampleDecomposition (α := α) K}
    (hD : D ∈ Ds) :
    D.toTupleAtom ∈ tupleAtomsOfRawSampleDecompositions Ds := by
  exact List.mem_map.mpr ⟨D, hD, rfl⟩

/-- A listed decomposition contributes its context atom to the generated context
atom list. -/
theorem contextAtom_mem_of_rawDecomposition_mem
    {K : Finset (Word α)}
    {Ds : List (RawSampleDecomposition (α := α) K)}
    {D : RawSampleDecomposition (α := α) K}
    (hD : D ∈ Ds) :
    D.toContextAtom ∈ contextAtomsOfRawSampleDecompositions Ds := by
  exact List.mem_map.mpr ⟨D, hD, rfl⟩

/-- A raw sample unit-edge witness.

It records the exact sample-level data needed for the unit-edge safety
condition: the two tuples share the same named context in the sample, have the
same fixed observation type, and satisfy the fan-out/positive-arity side
conditions. -/
structure RawSampleUnitEdgeWitness
    (K : Finset (Word α)) (obs : α → M) (f : Nat) where
  d : Nat
  src : Tuple α d
  tgt : Tuple α d
  context : NamedSentenceContext α d
  hd : d ≤ f
  hpos : 0 < d
  src_mem : namedFill d context src ∈ K
  tgt_mem : namedFill d context tgt ∈ K
  type_eq : tupleType obs src = tupleType obs tgt

namespace RawSampleUnitEdgeWitness

/-- The unit-edge atom represented by a raw unit-edge witness. -/
def toUnitEdgeAtom
    {K : Finset (Word α)} {obs : α → M} {f : Nat}
    (E : RawSampleUnitEdgeWitness K obs f) : UnitEdgeAtom α :=
  Sigma.mk E.d (E.src, E.tgt)

/-- The witness gives the sample-level safe-merge predicate. -/
theorem sampleSafeMerge
    {K : Finset (Word α)} {obs : α → M} {f : Nat}
    (E : RawSampleUnitEdgeWitness K obs f) :
    SampleSafeMerge K obs E.src E.tgt := by
  exact ⟨E.type_eq, ⟨E.context, E.src_mem, E.tgt_mem⟩⟩

end RawSampleUnitEdgeWitness

/-- Unit-edge atoms generated by raw unit-edge witnesses. -/
def unitEdgeAtomsOfRawSampleWitnesses
    {K : Finset (Word α)} {obs : α → M} {f : Nat}
    (Es : List (RawSampleUnitEdgeWitness (α := α) K obs f)) :
    List (UnitEdgeAtom α) :=
  Es.map RawSampleUnitEdgeWitness.toUnitEdgeAtom

/-- A listed raw unit-edge witness contributes its edge atom to the generated
unit-edge atom list. -/
theorem unitEdgeAtom_mem_of_rawWitness_mem
    {K : Finset (Word α)} {obs : α → M} {f : Nat}
    {Es : List (RawSampleUnitEdgeWitness (α := α) K obs f)}
    {E : RawSampleUnitEdgeWitness (α := α) K obs f}
    (hE : E ∈ Es) :
    E.toUnitEdgeAtom ∈ unitEdgeAtomsOfRawSampleWitnesses Es := by
  exact List.mem_map.mpr ⟨E, hE, rfl⟩

/-- Unit-edge atoms generated from raw safe-merge witnesses are listed-edge safe. -/
theorem listedUnitEdgesAreSafe_of_rawWitnesses
    {K : Finset (Word α)} {obs : α → M} {f : Nat}
    (tupleAtoms : List (TupleAtom α))
    (contextAtoms : List (ContextAtom α))
    (Es : List (RawSampleUnitEdgeWitness (α := α) K obs f)) :
    (supportOfObservedAtoms K tupleAtoms contextAtoms
      (unitEdgeAtomsOfRawSampleWitnesses Es)).ListedUnitEdgesAreSafe obs f := by
  intro d x y hxy
  rcases List.mem_map.mp hxy with ⟨E, _hE, hEq⟩
  cases hEq
  exact ⟨E.hd, E.hpos, E.sampleSafeMerge⟩

/-- Raw sample decomposition data.

This removes another arbitrary layer from `ObservedSampleAtoms`: tuple and
context atoms are generated from raw decomposition witnesses, and unit edges are
generated from raw sample-safe merge witnesses. -/
structure RawSampleDecompositionData
    (G : WorkingMCFG N α) (obs : α → M) (K : Finset (Word α)) where
  f : Nat
  decompositions : List (RawSampleDecomposition (α := α) K)
  unitEdgeWitnesses : List (RawSampleUnitEdgeWitness (α := α) K obs f)
  semanticWorking : G.SemanticWorkingConditions

namespace RawSampleDecompositionData

/-- Tuple atoms generated by the raw decompositions. -/
def tupleAtoms
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (D : RawSampleDecompositionData G obs K) : List (TupleAtom α) :=
  tupleAtomsOfRawSampleDecompositions D.decompositions

/-- Context atoms generated by the raw decompositions. -/
def contextAtoms
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (D : RawSampleDecompositionData G obs K) : List (ContextAtom α) :=
  contextAtomsOfRawSampleDecompositions D.decompositions

/-- Unit-edge atoms generated by the raw sample-safe merge witnesses. -/
def unitEdgeAtoms
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (D : RawSampleDecompositionData G obs K) : List (UnitEdgeAtom α) :=
  unitEdgeAtomsOfRawSampleWitnesses D.unitEdgeWitnesses

/-- The finite support assembled from raw sample decompositions and raw unit-edge
witnesses. -/
def support
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (D : RawSampleDecompositionData G obs K) : FiniteLearnerSupport α :=
  supportOfObservedAtoms K D.tupleAtoms D.contextAtoms D.unitEdgeAtoms

/-- The assembled support records the original sample exactly. -/
theorem support_sample_eq
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (D : RawSampleDecompositionData G obs K) :
    D.support.sample = K := by
  rfl

/-- Listed unit edges generated by raw witnesses are safe. -/
theorem support_safeEdges
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (D : RawSampleDecompositionData G obs K) :
    D.support.ListedUnitEdgesAreSafe obs D.f := by
  exact listedUnitEdgesAreSafe_of_rawWitnesses
    D.tupleAtoms D.contextAtoms D.unitEdgeWitnesses

/-- A listed raw decomposition contributes a supported tuple. -/
theorem supportsTuple_of_decomposition_mem
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (D : RawSampleDecompositionData G obs K)
    {R : RawSampleDecomposition (α := α) K}
    (hR : R ∈ D.decompositions) :
    D.support.SupportsTuple R.tuple := by
  exact ObservedSampleAtoms.supportsTuple_of_mem
    { f := D.f
      tupleAtoms := D.tupleAtoms
      contextAtoms := D.contextAtoms
      unitEdgeAtoms := D.unitEdgeAtoms
      safeEdges := D.support_safeEdges
      semanticWorking := D.semanticWorking }
    (tupleAtom_mem_of_rawDecomposition_mem hR)

/-- A listed raw decomposition contributes a supported context. -/
theorem supportsContext_of_decomposition_mem
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (D : RawSampleDecompositionData G obs K)
    {R : RawSampleDecomposition (α := α) K}
    (hR : R ∈ D.decompositions) :
    D.support.SupportsContext R.context := by
  exact ObservedSampleAtoms.supportsContext_of_mem
    { f := D.f
      tupleAtoms := D.tupleAtoms
      contextAtoms := D.contextAtoms
      unitEdgeAtoms := D.unitEdgeAtoms
      safeEdges := D.support_safeEdges
      semanticWorking := D.semanticWorking }
    (contextAtom_mem_of_rawDecomposition_mem hR)

/-- A listed raw unit-edge witness contributes a supported unit edge. -/
theorem supportsUnitEdge_of_witness_mem
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (D : RawSampleDecompositionData G obs K)
    {E : RawSampleUnitEdgeWitness (α := α) K obs D.f}
    (hE : E ∈ D.unitEdgeWitnesses) :
    D.support.SupportsUnitEdge E.src E.tgt := by
  exact ObservedSampleAtoms.supportsUnitEdge_of_mem
    { f := D.f
      tupleAtoms := D.tupleAtoms
      contextAtoms := D.contextAtoms
      unitEdgeAtoms := D.unitEdgeAtoms
      safeEdges := D.support_safeEdges
      semanticWorking := D.semanticWorking }
    (unitEdgeAtom_mem_of_rawWitness_mem hE)

/-- Forget raw decomposition data to the observed-atom extraction layer. -/
noncomputable def toObservedSampleAtoms
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (D : RawSampleDecompositionData G obs K) :
    ObservedSampleAtoms G obs K :=
  { f := D.f
    tupleAtoms := D.tupleAtoms
    contextAtoms := D.contextAtoms
    unitEdgeAtoms := D.unitEdgeAtoms
    safeEdges := D.support_safeEdges
    semanticWorking := D.semanticWorking }

/-- Forget raw decomposition data to the sample-extracted rule-list layer. -/
noncomputable def toSampleExtractedRuleLists
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (D : RawSampleDecompositionData G obs K) :
    SampleExtractedRuleLists G obs K :=
  D.toObservedSampleAtoms.toSampleExtractedRuleLists

/-- Forget raw decomposition data to concrete extracted sample data. -/
noncomputable def toConcreteExtractedSampleData
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (D : RawSampleDecompositionData G obs K) :
    ConcreteExtractedSampleData G obs K :=
  D.toObservedSampleAtoms.toConcreteExtractedSampleData

/-- Forget raw decomposition data to the finite hypothesis. -/
noncomputable def toFiniteLearnerHypothesis
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (D : RawSampleDecompositionData G obs K) :
    FiniteLearnerHypothesis α M :=
  D.toObservedSampleAtoms.toFiniteLearnerHypothesis

/-- The concrete refined rule lists are still the actual finite-monoid lists. -/
theorem concreteRules_eq_actual
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (D : RawSampleDecompositionData G obs K) :
    D.toObservedSampleAtoms.concreteRules =
      actualFintypeConcreteRuleEnumeration G obs D.semanticWorking := by
  exact D.toObservedSampleAtoms.concreteRules_eq_actual

/-- The actual refined rule lists contain all ordinary output-type refinements. -/
theorem concrete_containsAllOrdinaryRuleRefinements
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (D : RawSampleDecompositionData G obs K) :
    D.toObservedSampleAtoms.concreteRules.toFintypeOutputTypeRefinementCertificate.toOutputTypeRefinedGrammar.ContainsAllOrdinaryRuleRefinements := by
  exact D.toObservedSampleAtoms.concrete_containsAllOrdinaryRuleRefinements

/-- The actual refined rule lists are supported by the canonical finite-monoid
rule-enumeration plan. -/
theorem concreteRules_supportedByPlan
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (D : RawSampleDecompositionData G obs K) :
    D.toObservedSampleAtoms.concreteRules.grammar.AllRulesSupportedByPlan
      (FiniteRuleEnumerationPlan.ofFintype G obs) := by
  exact D.toObservedSampleAtoms.concreteRules_supportedByPlan

/-- Approximate distribution induced by raw decomposition data. -/
noncomputable def ApproxDistribution
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (D : RawSampleDecompositionData G obs K)
    {d : Nat} (x : Tuple α d) : Set (NamedSentenceContext α d) :=
  D.toObservedSampleAtoms.ApproxDistribution x

/-- Unit reachability induced by raw decomposition data. -/
noncomputable def UnitReach
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (D : RawSampleDecompositionData G obs K)
    {d : Nat} (x y : Tuple α d) : Prop :=
  D.toObservedSampleAtoms.UnitReach x y

/-- Refined tuple language carried by the actual grammar-side rule lists. -/
noncomputable def RefinedTupleLanguage
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (D : RawSampleDecompositionData G obs K)
    (A : RefinedNonterminal G M) : Set (Tuple α (G.arity A.base)) :=
  D.toObservedSampleAtoms.RefinedTupleLanguage A

/-- Distributional soundness under positivity and fixed-substitutability. -/
theorem approxDistribution_sound_for_language
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (D : RawSampleDecompositionData G obs K)
    {L : Set (Word α)}
    (hK : PositiveForLanguage D.toFiniteLearnerHypothesis.sampleSet L)
    (hL : FixedNamedTupleSubstitutable D.f obs L)
    {d : Nat} (x : Tuple α d) :
    D.ApproxDistribution x ⊆ NamedDistribution L x := by
  exact D.toObservedSampleAtoms.approxDistribution_sound_for_language hK hL x

/-- Soundness of the actual grammar-side refined tuple language. -/
theorem refinedTupleLanguage_sound
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (D : RawSampleDecompositionData G obs K)
    (A : RefinedNonterminal G M) :
    D.RefinedTupleLanguage A ⊆ OutputTypedTupleLanguage G obs A := by
  intro x hx
  exact D.toObservedSampleAtoms.refinedTupleLanguage_sound A hx

end RawSampleDecompositionData

end RawSampleDecomposition

end FIv21
