import LeanCfgProject.MCFG.FI_v2_1_SampleGeneratedPrefixEnumerationFamily

/-!
# FI v2.1 Lean experiment: exact package for prefix-enumeration families

This layer packages a sample-level prefix-enumeration family together with the
existing generated grammar shell.  It is the first fully sample-level statement
in this branch: if every sample word has a listed prefix-node enumeration, then
all sample words are generated by the terminal+concat `WorkingMCFG` shell.
-/

namespace FIv21

universe u v w

section SampleGeneratedPrefixEnumerationFamilyExact

variable {N : Type w} {α : Type u}
variable [DecidableEq α]
variable {M : Type v} [Monoid M] [Fintype M]

/-- Exact package carrying a prefix-enumeration family for all sample words. -/
structure SampleGeneratedPrefixEnumerationFamilyExact
    (G : WorkingMCFG N α) (obs : α → M) (K : Finset (Word α)) where
  exactPackage : SampleGeneratedWordParseWitnessConstructionExact G obs K
  family : SampleGeneratedPrefixEnumerationFamily (M := M) exactPackage.ruleSkeleton

namespace SampleGeneratedPrefixEnumerationFamilyExact

/-- The underlying rule skeleton. -/
def ruleSkeleton
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (E : SampleGeneratedPrefixEnumerationFamilyExact G obs K) :
    SampleGeneratedRuleSkeleton G obs K :=
  E.exactPackage.ruleSkeleton

/-- The generated rule-list package. -/
noncomputable def ruleLists
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (E : SampleGeneratedPrefixEnumerationFamilyExact G obs K) :
    SampleGeneratedRuleListPackage G obs K :=
  E.exactPackage.ruleLists

/-- The generated working grammar shell. -/
noncomputable def toWorkingMCFG
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (E : SampleGeneratedPrefixEnumerationFamilyExact G obs K) :
    WorkingMCFG (SampleGeneratedGrammarNonterminal
      E.ruleLists.ruleSkeleton.skeleton) α :=
  E.exactPackage.toWorkingMCFG

/-- The generated grammar shell is semantically well-formed. -/
theorem semanticWorkingConditions
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (E : SampleGeneratedPrefixEnumerationFamilyExact G obs K) :
    E.toWorkingMCFG.SemanticWorkingConditions := by
  exact E.exactPackage.semanticWorkingConditions

/-- The family viewed as the earlier sample-parse witness construction. -/
def toSampleParseWitnessConstruction
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (E : SampleGeneratedPrefixEnumerationFamilyExact G obs K) :
    SampleGeneratedSampleParseWitnessConstruction (M := M) E.ruleSkeleton :=
  E.family.toSampleParseWitnessConstruction

/-- The family viewed as sample parse witnesses. -/
def toSampleParseWitnesses
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (E : SampleGeneratedPrefixEnumerationFamilyExact G obs K) :
    SampleGeneratedSampleParseWitnesses (M := M) E.ruleSkeleton :=
  E.family.toSampleParseWitnesses

/-- A single sample word has a word-parse construction. -/
def wordConstructionOfMem
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (E : SampleGeneratedPrefixEnumerationFamilyExact G obs K)
    {w : Word α} (hw : w ∈ K) :
    SampleGeneratedWordParseWitnessConstruction (M := M) E.ruleSkeleton w :=
  E.family.wordConstructionOfMem (M := M) hw

/-- Every sample word is generated by the generated grammar shell. -/
theorem sample_subset_stringLanguage
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (E : SampleGeneratedPrefixEnumerationFamilyExact G obs K) :
    ∀ w : Word α, w ∈ K → w ∈ E.toWorkingMCFG.StringLanguage := by
  exact E.exactPackage.sampleConstruction_subset_stringLanguage
    (M := M) E.toSampleParseWitnessConstruction

/-- A single sample word is generated by the generated grammar shell. -/
theorem word_mem_stringLanguage_of_mem
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (E : SampleGeneratedPrefixEnumerationFamilyExact G obs K)
    {w : Word α} (hw : w ∈ K) :
    w ∈ E.toWorkingMCFG.StringLanguage := by
  exact E.sample_subset_stringLanguage w hw

/-- Endpoint equality for the family member associated with a sample word. -/
theorem endpoint_middle_eq_of_mem
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (E : SampleGeneratedPrefixEnumerationFamilyExact G obs K)
    {w : Word α} (hw : w ∈ K) :
    (E.family.endpointOfMem (M := M) hw).middle = w := by
  exact E.family.endpoint_middle_eq_of_mem (M := M) hw

/-- Endpoint sample-distribution licensing for the family member associated with
a sample word. -/
theorem endpoint_context_mem_sampleDistribution_of_mem
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (E : SampleGeneratedPrefixEnumerationFamilyExact G obs K)
    {w : Word α} (hw : w ∈ K) :
    (E.family.endpointOfMem (M := M) hw).context ∈
      SampleNamedDistribution K (E.family.endpointOfMem (M := M) hw).tuple := by
  exact E.family.endpoint_context_mem_sampleDistribution_of_mem (M := M) hw

end SampleGeneratedPrefixEnumerationFamilyExact

/-- Build the family-exact package from the previous construction-exact package
and a family of prefix-node enumerations. -/
def SampleGeneratedPrefixEnumerationFamilyExact.ofConstructionExact
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (E : SampleGeneratedWordParseWitnessConstructionExact G obs K)
    (F : SampleGeneratedPrefixEnumerationFamily (M := M) E.ruleSkeleton) :
    SampleGeneratedPrefixEnumerationFamilyExact G obs K :=
  { exactPackage := E
    family := F }

/-- Concrete exact package shape for a fixed fanout bound, once the family of
prefix-node enumerations is supplied. -/
noncomputable def enumeratedSampleGeneratedPrefixEnumerationFamilyExact
    (G : WorkingMCFG N α) (obs : α → M) (K : Finset (Word α))
    (f : Nat) (hfanout : 1 ≤ f) (hG : G.SemanticWorkingConditions)
    (F : SampleGeneratedPrefixEnumerationFamily (M := M)
      (enumeratedSampleGeneratedWordParseWitnessConstructionExact
        G obs K f hfanout hG).ruleSkeleton) :
    SampleGeneratedPrefixEnumerationFamilyExact G obs K :=
  { exactPackage := enumeratedSampleGeneratedWordParseWitnessConstructionExact
      G obs K f hfanout hG
    family := F }

/-- The concrete family-exact package is semantically well-formed. -/
theorem enumeratedSampleGeneratedPrefixEnumerationFamilyExact_semantic
    (G : WorkingMCFG N α) (obs : α → M) (K : Finset (Word α))
    (f : Nat) (hfanout : 1 ≤ f) (hG : G.SemanticWorkingConditions)
    (F : SampleGeneratedPrefixEnumerationFamily (M := M)
      (enumeratedSampleGeneratedWordParseWitnessConstructionExact
        G obs K f hfanout hG).ruleSkeleton) :
    (enumeratedSampleGeneratedPrefixEnumerationFamilyExact
      G obs K f hfanout hG F).toWorkingMCFG.SemanticWorkingConditions := by
  exact (enumeratedSampleGeneratedPrefixEnumerationFamilyExact
    G obs K f hfanout hG F).semanticWorkingConditions

end SampleGeneratedPrefixEnumerationFamilyExact

end FIv21
