import LeanCfgProject.MCFG.FI_v2_1_OutputTypeRefinement

/-!
# FI v2.1 Lean experiment: output-refined rule skeleton

This file is the fifteenth formalization layer for the FI v2.1 MCFG paper.

The preceding file proved the key output-type computation for binary templates:
the observation type of a binary-rule output is determined by the template and
by the componentwise observation types of the two child tuples.

This file packages the corresponding *refined rule skeleton*.  It still does
not construct the full refined grammar, but it gives typed terminal, binary,
and start-rule steps for refined nonterminals of the form `A^{p_1,...,p_d}`.

The main point is that every ordinary derivation step has a canonical
output-typed version once the child output types are fixed.
-/

namespace FIv21

universe u v w

section CastOutputTypes

variable {α : Type u}
variable {M : Type v} [Monoid M]

/-- Transport an output-type vector across an equality of arities. -/
def castOutputType {d e : Nat} (h : d = e) (ty : Fin d → M) : Fin e → M := by
  subst h
  exact ty

@[simp] theorem castOutputType_rfl {d : Nat} (ty : Fin d → M) :
    castOutputType (rfl : d = d) ty = ty := rfl

/-- Componentwise tuple observation commutes with arity casting. -/
theorem tupleType_castTuple {d e : Nat}
    (obs : α → M) (h : d = e) (x : Tuple α d) :
    tupleType obs (castTuple h x) =
      castOutputType h (tupleType obs x) := by
  subst h
  rfl

end CastOutputTypes

section RefinedTerminalRules

variable {N : Type w} {α : Type u}
variable {M : Type v} [Monoid M]

namespace TerminalRule

/-- The refined left-hand side of a well-typed terminal rule.

A terminal rule produces the one-component tuple `(a)`.  If the grammar says
that the left-hand side has arity one, we cast that tuple to the grammar arity
and use its actual componentwise observation type as the refined output type. -/
def refinedLHS {G : WorkingMCFG N α}
    (obs : α → M) (ρ : TerminalRule N α)
    (hwt : ρ.WellTyped G.arity) : RefinedNonterminal G M :=
  { base := ρ.lhs
    outTy := tupleType obs (castTuple hwt.symm ρ.outputTuple) }

/-- A listed well-typed terminal rule gives a typed derivation step for its
canonical refined left-hand side. -/
theorem derives_refinedLHS {G : WorkingMCFG N α}
    (obs : α → M) (ρ : TerminalRule N α)
    (hρ : ρ ∈ G.terminalRules)
    (hwt : ρ.WellTyped G.arity) :
    DerivesOutputTypedTuple G obs
      (TerminalRule.refinedLHS obs ρ hwt)
      (castTuple hwt.symm ρ.outputTuple) := by
  constructor
  · exact DerivesTuple.terminal ρ hρ hwt
  · rfl

end TerminalRule

/-- A packaged terminal rule together with its membership and typing evidence. -/
structure RefinedTerminalRule (G : WorkingMCFG N α) (obs : α → M) where
  rule : TerminalRule N α
  mem : rule ∈ G.terminalRules
  wellTyped : rule.WellTyped G.arity

namespace RefinedTerminalRule

/-- The output-typed nonterminal generated by a packaged terminal rule. -/
def lhs {G : WorkingMCFG N α} {obs : α → M}
    (ρ : RefinedTerminalRule G obs) : RefinedNonterminal G M :=
  TerminalRule.refinedLHS obs ρ.rule ρ.wellTyped

/-- The terminal tuple generated by a packaged refined terminal rule. -/
def outputTuple {G : WorkingMCFG N α} {obs : α → M}
    (ρ : RefinedTerminalRule G obs) : Tuple α (G.arity ρ.rule.lhs) :=
  castTuple ρ.wellTyped.symm ρ.rule.outputTuple

/-- Packaged terminal rules derive their typed terminal tuple. -/
theorem derives {G : WorkingMCFG N α} {obs : α → M}
    (ρ : RefinedTerminalRule G obs) :
    DerivesOutputTypedTuple G obs ρ.lhs ρ.outputTuple := by
  exact TerminalRule.derives_refinedLHS obs ρ.rule ρ.mem ρ.wellTyped

end RefinedTerminalRule

end RefinedTerminalRules

section RefinedBinaryRules

variable {N : Type w} {α : Type u}
variable {M : Type v} [Monoid M]

namespace BinaryRule

/-- The refined left child nonterminal of a binary rule for a chosen child
output type. -/
def refinedLeft {G : WorkingMCFG N α}
    (ρ : BinaryRule N α G.arity)
    (leftTy : Fin (G.arity ρ.left) → M) : RefinedNonterminal G M :=
  { base := ρ.left
    outTy := leftTy }

/-- The refined right child nonterminal of a binary rule for a chosen child
output type. -/
def refinedRight {G : WorkingMCFG N α}
    (ρ : BinaryRule N α G.arity)
    (rightTy : Fin (G.arity ρ.right) → M) : RefinedNonterminal G M :=
  { base := ρ.right
    outTy := rightTy }

/-- The refined left-hand side of a binary rule, computed from the child output
types and the binary template. -/
def refinedLHS {G : WorkingMCFG N α}
    (obs : α → M) (ρ : BinaryRule N α G.arity)
    (leftTy : Fin (G.arity ρ.left) → M)
    (rightTy : Fin (G.arity ρ.right) → M) : RefinedNonterminal G M :=
  { base := ρ.lhs
    outTy := ρ.outputType obs leftTy rightTy }

/-- A binary derivation step between output-typed children gives an
output-typed parent derivation with the syntactically computed output type. -/
theorem derives_refinedLHS {G : WorkingMCFG N α}
    (obs : α → M) (ρ : BinaryRule N α G.arity)
    (hρ : ρ ∈ G.binaryRules)
    (leftTy : Fin (G.arity ρ.left) → M)
    (rightTy : Fin (G.arity ρ.right) → M)
    (x : Tuple α (G.arity ρ.left))
    (y : Tuple α (G.arity ρ.right))
    (hx : DerivesOutputTypedTuple G obs
      (BinaryRule.refinedLeft ρ leftTy) x)
    (hy : DerivesOutputTypedTuple G obs
      (BinaryRule.refinedRight ρ rightTy) y) :
    DerivesOutputTypedTuple G obs
      (BinaryRule.refinedLHS obs ρ leftTy rightTy)
      (ρ.apply x y) := by
  constructor
  · exact DerivesTuple.binary ρ hρ x y
      (DerivesOutputTypedTuple.derives hx)
      (DerivesOutputTypedTuple.derives hy)
  · exact BinaryRule.apply_has_outputType obs ρ x y leftTy rightTy
      (DerivesOutputTypedTuple.has_output_type hx)
      (DerivesOutputTypedTuple.has_output_type hy)

end BinaryRule

/-- A packaged binary rule together with chosen output types for both children. -/
structure RefinedBinaryRule (G : WorkingMCFG N α) (obs : α → M) where
  rule : BinaryRule N α G.arity
  mem : rule ∈ G.binaryRules
  leftTy : Fin (G.arity rule.left) → M
  rightTy : Fin (G.arity rule.right) → M

namespace RefinedBinaryRule

/-- The refined left child of a packaged binary rule. -/
def left {G : WorkingMCFG N α} {obs : α → M}
    (ρ : RefinedBinaryRule G obs) : RefinedNonterminal G M :=
  BinaryRule.refinedLeft ρ.rule ρ.leftTy

/-- The refined right child of a packaged binary rule. -/
def right {G : WorkingMCFG N α} {obs : α → M}
    (ρ : RefinedBinaryRule G obs) : RefinedNonterminal G M :=
  BinaryRule.refinedRight ρ.rule ρ.rightTy

/-- The refined parent of a packaged binary rule. -/
def lhs {G : WorkingMCFG N α} {obs : α → M}
    (ρ : RefinedBinaryRule G obs) : RefinedNonterminal G M :=
  BinaryRule.refinedLHS obs ρ.rule ρ.leftTy ρ.rightTy

/-- Packaged binary rules preserve output-typed derivability. -/
theorem derives {G : WorkingMCFG N α} {obs : α → M}
    (ρ : RefinedBinaryRule G obs)
    (x : Tuple α (G.arity ρ.rule.left))
    (y : Tuple α (G.arity ρ.rule.right))
    (hx : DerivesOutputTypedTuple G obs ρ.left x)
    (hy : DerivesOutputTypedTuple G obs ρ.right y) :
    DerivesOutputTypedTuple G obs ρ.lhs (ρ.rule.apply x y) := by
  exact BinaryRule.derives_refinedLHS obs ρ.rule ρ.mem
    ρ.leftTy ρ.rightTy x y hx hy

end RefinedBinaryRule

end RefinedBinaryRules

section RefinedStartRules

variable {N : Type w} {α : Type u}
variable {M : Type v} [Monoid M]

namespace StartRule

/-- The refined child of a start rule for a chosen child output type. -/
def refinedChild {G : WorkingMCFG N α}
    (ρ : StartRule N)
    (childTy : Fin (G.arity ρ.child) → M) : RefinedNonterminal G M :=
  { base := ρ.child
    outTy := childTy }

/-- The refined start nonterminal obtained by transporting the child's output
vector across the start-rule arity equality. -/
def refinedStart {G : WorkingMCFG N α}
    (ρ : StartRule N) (hwt : ρ.WellTyped G)
    (childTy : Fin (G.arity ρ.child) → M) : RefinedNonterminal G M :=
  { base := G.start
    outTy := castOutputType hwt childTy }

/-- A start-rule step transports an output-typed child derivation to an
output-typed derivation of the start symbol. -/
theorem derives_refinedStart {G : WorkingMCFG N α}
    (obs : α → M) (ρ : StartRule N)
    (hρ : ρ ∈ G.startRules)
    (hwt : ρ.WellTyped G)
    (childTy : Fin (G.arity ρ.child) → M)
    (x : Tuple α (G.arity ρ.child))
    (hx : DerivesOutputTypedTuple G obs
      (StartRule.refinedChild ρ childTy) x) :
    DerivesOutputTypedTuple G obs
      (StartRule.refinedStart ρ hwt childTy)
      (castTuple hwt x) := by
  constructor
  · exact DerivesTuple.start ρ hρ hwt x
      (DerivesOutputTypedTuple.derives hx)
  · -- Make the equality hidden in `StartRule.WellTyped` explicit.  This avoids
    -- fragile dot-notation/typeclass-transparency behavior around casts.
    let hEq : G.arity ρ.child = G.arity G.start := hwt
    change tupleType obs (castTuple hEq x) =
      castOutputType hEq childTy
    calc
      tupleType obs (castTuple hEq x)
          = castOutputType hEq (tupleType obs x) :=
              tupleType_castTuple obs hEq x
      _ = castOutputType hEq childTy :=
              congrArg (castOutputType hEq)
                (DerivesOutputTypedTuple.has_output_type hx)


end StartRule

/-- A packaged start rule together with a chosen child output type. -/
structure RefinedStartRule (G : WorkingMCFG N α) (obs : α → M) where
  rule : StartRule N
  mem : rule ∈ G.startRules
  wellTyped : rule.WellTyped G
  childTy : Fin (G.arity rule.child) → M

namespace RefinedStartRule

/-- The refined child nonterminal of a packaged start rule. -/
def child {G : WorkingMCFG N α} {obs : α → M}
    (ρ : RefinedStartRule G obs) : RefinedNonterminal G M :=
  StartRule.refinedChild ρ.rule ρ.childTy

/-- The refined start nonterminal of a packaged start rule. -/
def start {G : WorkingMCFG N α} {obs : α → M}
    (ρ : RefinedStartRule G obs) : RefinedNonterminal G M :=
  StartRule.refinedStart ρ.rule ρ.wellTyped ρ.childTy

/-- Packaged start rules preserve output-typed derivability. -/
theorem derives {G : WorkingMCFG N α} {obs : α → M}
    (ρ : RefinedStartRule G obs)
    (x : Tuple α (G.arity ρ.rule.child))
    (hx : DerivesOutputTypedTuple G obs ρ.child x) :
    DerivesOutputTypedTuple G obs ρ.start (castTuple ρ.wellTyped x) := by
  exact StartRule.derives_refinedStart obs ρ.rule ρ.mem
    ρ.wellTyped ρ.childTy x hx

end RefinedStartRule

end RefinedStartRules

section RefinedStepSummary

variable {N : Type w} {α : Type u}
variable {M : Type v} [Monoid M]

/-- A small summary predicate for a grammar and observation: all three ordinary
rule kinds have output-typed counterparts.  This is a theorem rather than an
assumption, but packaging it as a proposition makes later files easier to read. -/
def HasOutputTypedRuleSkeleton (G : WorkingMCFG N α) (obs : α → M) : Prop :=
  (∀ ρ : TerminalRule N α, ρ ∈ G.terminalRules →
      ∀ hwt : ρ.WellTyped G.arity,
        DerivesOutputTypedTuple G obs
          (TerminalRule.refinedLHS obs ρ hwt)
          (castTuple hwt.symm ρ.outputTuple)) ∧
  (∀ ρ : BinaryRule N α G.arity, ρ ∈ G.binaryRules →
      ∀ leftTy : Fin (G.arity ρ.left) → M,
      ∀ rightTy : Fin (G.arity ρ.right) → M,
      ∀ x : Tuple α (G.arity ρ.left),
      ∀ y : Tuple α (G.arity ρ.right),
        DerivesOutputTypedTuple G obs (BinaryRule.refinedLeft ρ leftTy) x →
        DerivesOutputTypedTuple G obs (BinaryRule.refinedRight ρ rightTy) y →
        DerivesOutputTypedTuple G obs
          (BinaryRule.refinedLHS obs ρ leftTy rightTy)
          (ρ.apply x y)) ∧
  (∀ ρ : StartRule N, ρ ∈ G.startRules →
      ∀ hwt : ρ.WellTyped G,
      ∀ childTy : Fin (G.arity ρ.child) → M,
      ∀ x : Tuple α (G.arity ρ.child),
        DerivesOutputTypedTuple G obs (StartRule.refinedChild ρ childTy) x →
        DerivesOutputTypedTuple G obs
          (StartRule.refinedStart ρ hwt childTy)
          (castTuple hwt x))

/-- Every working MCFG has the output-typed rule skeleton for every fixed
observation. -/
theorem hasOutputTypedRuleSkeleton
    (G : WorkingMCFG N α) (obs : α → M) :
    HasOutputTypedRuleSkeleton G obs := by
  constructor
  · intro ρ hρ hwt
    exact TerminalRule.derives_refinedLHS obs ρ hρ hwt
  constructor
  · intro ρ hρ leftTy rightTy x y hx hy
    exact BinaryRule.derives_refinedLHS obs ρ hρ leftTy rightTy x y hx hy
  · intro ρ hρ hwt childTy x hx
    exact StartRule.derives_refinedStart obs ρ hρ hwt childTy x hx

end RefinedStepSummary

end FIv21
