import LeanCfgProject.MCFG.FI_v2_1_SampleGeneratedNonemptySampleConsistencyExact

/-!
# FI v2.1 Lean experiment: Gold wrapper for nonempty sample consistency

This layer is the learner-like wrapper for the nonempty sample-consistency
branch.  For each finite sample, the learner returns a generated working grammar
shell plus nonempty-word prefix-enumeration data.  The checked consequence is
that the finite sample is positive for the generated grammar's string language.
-/

namespace FIv21

universe u v w

section SampleGeneratedNonemptySampleConsistencyGold

variable {N : Type w} {α : Type u}
variable [DecidableEq α]
variable {M : Type v} [Monoid M] [Fintype M]

/-- Learner-like map from finite samples to nonempty-sample-consistent generated
grammar packages. -/
structure SampleGeneratedNonemptySampleConsistencyLearner
    (G : WorkingMCFG N α) (obs : α → M) where
  exactPackage :
    (K : Finset (Word α)) →
      SampleGeneratedNonemptySampleConsistencyExact G obs K

namespace SampleGeneratedNonemptySampleConsistencyLearner

/-- Rule skeleton after finite sample `K`. -/
def ruleSkeleton
    {G : WorkingMCFG N α} {obs : α → M}
    (L : SampleGeneratedNonemptySampleConsistencyLearner G obs)
    (K : Finset (Word α)) : SampleGeneratedRuleSkeleton G obs K :=
  (L.exactPackage K).ruleSkeleton

/-- Rule-list package after finite sample `K`. -/
noncomputable def ruleLists
    {G : WorkingMCFG N α} {obs : α → M}
    (L : SampleGeneratedNonemptySampleConsistencyLearner G obs)
    (K : Finset (Word α)) : SampleGeneratedRuleListPackage G obs K :=
  (L.exactPackage K).ruleLists

/-- Output grammar after finite sample `K`. -/
noncomputable def grammar
    {G : WorkingMCFG N α} {obs : α → M}
    (L : SampleGeneratedNonemptySampleConsistencyLearner G obs)
    (K : Finset (Word α)) :
    WorkingMCFG (SampleGeneratedGrammarNonterminal
      (L.ruleLists K).ruleSkeleton.skeleton) α :=
  (L.exactPackage K).toWorkingMCFG

/-- Output grammar is semantically well-formed. -/
theorem grammar_semanticWorkingConditions
    {G : WorkingMCFG N α} {obs : α → M}
    (L : SampleGeneratedNonemptySampleConsistencyLearner G obs)
    (K : Finset (Word α)) :
    (L.grammar K).SemanticWorkingConditions := by
  exact (L.exactPackage K).semanticWorkingConditions

/-- The sample is nonempty-word shaped for the package at `K`. -/
def nonemptySample
    {G : WorkingMCFG N α} {obs : α → M}
    (L : SampleGeneratedNonemptySampleConsistencyLearner G obs)
    (K : Finset (Word α)) : NonemptyWordSample K :=
  (L.exactPackage K).nonemptySample

/-- Every word in finite sample `K` is generated by the learner's output grammar
for `K`. -/
theorem sample_subset_stringLanguage
    {G : WorkingMCFG N α} {obs : α → M}
    (L : SampleGeneratedNonemptySampleConsistencyLearner G obs)
    (K : Finset (Word α)) :
    ∀ w : Word α, w ∈ K → w ∈ (L.grammar K).StringLanguage := by
  exact (L.exactPackage K).sample_subset_stringLanguage

/-- The sample is positive for the learner's generated language. -/
theorem positiveForGeneratedLanguage
    {G : WorkingMCFG N α} {obs : α → M}
    (L : SampleGeneratedNonemptySampleConsistencyLearner G obs)
    (K : Finset (Word α)) :
    PositiveForLanguage K (L.grammar K).StringLanguage := by
  exact L.sample_subset_stringLanguage K

/-- A single sample word is generated by the learner's output grammar. -/
theorem word_mem_stringLanguage_of_mem
    {G : WorkingMCFG N α} {obs : α → M}
    (L : SampleGeneratedNonemptySampleConsistencyLearner G obs)
    (K : Finset (Word α)) {w : Word α} (hw : w ∈ K) :
    w ∈ (L.grammar K).StringLanguage := by
  exact L.sample_subset_stringLanguage K w hw

end SampleGeneratedNonemptySampleConsistencyLearner

/-- Gold-style summary for nonempty sample consistency. -/
structure SampleGeneratedNonemptySampleConsistencyGoldSummary
    (G : WorkingMCFG N α) (obs : α → M) where
  learner : SampleGeneratedNonemptySampleConsistencyLearner G obs
  characteristicSample : Finset (Word α)

namespace SampleGeneratedNonemptySampleConsistencyGoldSummary

/-- Output grammar after finite sample `K`. -/
noncomputable def grammar
    {G : WorkingMCFG N α} {obs : α → M}
    (S : SampleGeneratedNonemptySampleConsistencyGoldSummary G obs)
    (K : Finset (Word α)) :
    WorkingMCFG (SampleGeneratedGrammarNonterminal
      (S.learner.ruleLists K).ruleSkeleton.skeleton) α :=
  S.learner.grammar K

/-- Output grammar is semantically well-formed. -/
theorem grammar_semanticWorkingConditions
    {G : WorkingMCFG N α} {obs : α → M}
    (S : SampleGeneratedNonemptySampleConsistencyGoldSummary G obs)
    (K : Finset (Word α)) :
    (S.grammar K).SemanticWorkingConditions := by
  exact S.learner.grammar_semanticWorkingConditions K

/-- Every word in finite sample `K` is generated by the summary's output grammar
for `K`. -/
theorem sample_subset_stringLanguage
    {G : WorkingMCFG N α} {obs : α → M}
    (S : SampleGeneratedNonemptySampleConsistencyGoldSummary G obs)
    (K : Finset (Word α)) :
    ∀ w : Word α, w ∈ K → w ∈ (S.grammar K).StringLanguage := by
  exact S.learner.sample_subset_stringLanguage K

/-- The finite sample is positive for the summary's generated language. -/
theorem positiveForGeneratedLanguage
    {G : WorkingMCFG N α} {obs : α → M}
    (S : SampleGeneratedNonemptySampleConsistencyGoldSummary G obs)
    (K : Finset (Word α)) :
    PositiveForLanguage K (S.grammar K).StringLanguage := by
  exact S.sample_subset_stringLanguage K

/-- A single sample word is generated by the summary's output grammar. -/
theorem word_mem_stringLanguage_of_mem
    {G : WorkingMCFG N α} {obs : α → M}
    (S : SampleGeneratedNonemptySampleConsistencyGoldSummary G obs)
    (K : Finset (Word α)) {w : Word α} (hw : w ∈ K) :
    w ∈ (S.grammar K).StringLanguage := by
  exact S.sample_subset_stringLanguage K w hw

end SampleGeneratedNonemptySampleConsistencyGoldSummary

/-- Build a nonempty sample-consistency learner from an exact-package provider. -/
def SampleGeneratedNonemptySampleConsistencyLearner.ofExactPackages
    {G : WorkingMCFG N α} {obs : α → M}
    (E : (K : Finset (Word α)) →
      SampleGeneratedNonemptySampleConsistencyExact G obs K) :
    SampleGeneratedNonemptySampleConsistencyLearner G obs :=
  { exactPackage := E }

end SampleGeneratedNonemptySampleConsistencyGold

end FIv21
