import LeanCfgProject.MCFG.FI_v2_1_SampleGeneratedNonemptySampleConsistency

/-!
# FI v2.1 Lean experiment: exact package for nonempty sample consistency

This layer packages the nonempty-word sample-consistency obligation against the
existing generated terminal+concat `WorkingMCFG` shell.  It is the exact-package
version of the statement that a nonempty prefix-enumeration family gives
`K ⊆ L(G_K)`.
-/

namespace FIv21

universe u v w

section SampleGeneratedNonemptySampleConsistencyExact

variable {N : Type w} {α : Type u}
variable [DecidableEq α]
variable {M : Type v} [Monoid M] [Fintype M]

/-- Exact package carrying nonempty-word sample consistency for the generated
working grammar shell. -/
structure SampleGeneratedNonemptySampleConsistencyExact
    (G : WorkingMCFG N α) (obs : α → M) (K : Finset (Word α)) where
  exactPackage : SampleGeneratedWordParseWitnessConstructionExact G obs K
  consistency :
    SampleGeneratedNonemptySampleConsistency (M := M) exactPackage.ruleSkeleton

namespace SampleGeneratedNonemptySampleConsistencyExact

/-- The underlying rule skeleton. -/
def ruleSkeleton
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (E : SampleGeneratedNonemptySampleConsistencyExact G obs K) :
    SampleGeneratedRuleSkeleton G obs K :=
  E.exactPackage.ruleSkeleton

/-- The generated rule-list package. -/
noncomputable def ruleLists
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (E : SampleGeneratedNonemptySampleConsistencyExact G obs K) :
    SampleGeneratedRuleListPackage G obs K :=
  E.exactPackage.ruleLists

/-- The generated working grammar shell. -/
noncomputable def toWorkingMCFG
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (E : SampleGeneratedNonemptySampleConsistencyExact G obs K) :
    WorkingMCFG (SampleGeneratedGrammarNonterminal
      E.ruleLists.ruleSkeleton.skeleton) α :=
  E.exactPackage.toWorkingMCFG

/-- The generated grammar shell is semantically well-formed. -/
theorem semanticWorkingConditions
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (E : SampleGeneratedNonemptySampleConsistencyExact G obs K) :
    E.toWorkingMCFG.SemanticWorkingConditions := by
  exact E.exactPackage.semanticWorkingConditions

/-- The nonempty-word side condition for the sample. -/
def nonemptySample
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (E : SampleGeneratedNonemptySampleConsistencyExact G obs K) :
    NonemptyWordSample K :=
  E.consistency.nonemptySample

/-- Forget to the previous prefix-enumeration-family exact package. -/
def toPrefixEnumerationFamilyExact
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (E : SampleGeneratedNonemptySampleConsistencyExact G obs K) :
    SampleGeneratedPrefixEnumerationFamilyExact G obs K :=
  { exactPackage := E.exactPackage
    family := E.consistency.toPrefixEnumerationFamily }

/-- Every sample word is generated by the generated grammar shell. -/
theorem sample_subset_stringLanguage
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (E : SampleGeneratedNonemptySampleConsistencyExact G obs K) :
    ∀ w : Word α, w ∈ K → w ∈ E.toWorkingMCFG.StringLanguage := by
  exact E.exactPackage.sampleConstruction_subset_stringLanguage
    (M := M) E.consistency.family.toSampleParseWitnessConstruction

/-- The same sample-inclusion statement as a `PositiveForLanguage` certificate. -/
theorem positiveForGeneratedLanguage
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (E : SampleGeneratedNonemptySampleConsistencyExact G obs K) :
    PositiveForLanguage K E.toWorkingMCFG.StringLanguage := by
  exact E.sample_subset_stringLanguage

/-- A single sample word is generated by the generated grammar shell. -/
theorem word_mem_stringLanguage_of_mem
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (E : SampleGeneratedNonemptySampleConsistencyExact G obs K)
    {w : Word α} (hw : w ∈ K) :
    w ∈ E.toWorkingMCFG.StringLanguage := by
  exact E.sample_subset_stringLanguage w hw

end SampleGeneratedNonemptySampleConsistencyExact

/-- Build the exact package from a word-parse exact package and a nonempty
prefix-enumeration family. -/
def SampleGeneratedNonemptySampleConsistencyExact.ofNonemptyFamily
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (E : SampleGeneratedWordParseWitnessConstructionExact G obs K)
    (F : SampleGeneratedNonemptyPrefixEnumerationFamily (M := M) E.ruleSkeleton) :
    SampleGeneratedNonemptySampleConsistencyExact G obs K :=
  { exactPackage := E
    consistency := { family := F } }

/-- Concrete exact package shape for a fixed fanout bound, once the nonempty
prefix-enumeration family is supplied. -/
noncomputable def enumeratedSampleGeneratedNonemptySampleConsistencyExact
    (G : WorkingMCFG N α) (obs : α → M) (K : Finset (Word α))
    (f : Nat) (hfanout : 1 ≤ f) (hG : G.SemanticWorkingConditions)
    (F : SampleGeneratedNonemptyPrefixEnumerationFamily (M := M)
      (enumeratedSampleGeneratedWordParseWitnessConstructionExact
        G obs K f hfanout hG).ruleSkeleton) :
    SampleGeneratedNonemptySampleConsistencyExact G obs K :=
  { exactPackage := enumeratedSampleGeneratedWordParseWitnessConstructionExact
      G obs K f hfanout hG
    consistency := { family := F } }

/-- The concrete exact package is semantically well-formed. -/
theorem enumeratedSampleGeneratedNonemptySampleConsistencyExact_semantic
    (G : WorkingMCFG N α) (obs : α → M) (K : Finset (Word α))
    (f : Nat) (hfanout : 1 ≤ f) (hG : G.SemanticWorkingConditions)
    (F : SampleGeneratedNonemptyPrefixEnumerationFamily (M := M)
      (enumeratedSampleGeneratedWordParseWitnessConstructionExact
        G obs K f hfanout hG).ruleSkeleton) :
    (enumeratedSampleGeneratedNonemptySampleConsistencyExact
      G obs K f hfanout hG F).toWorkingMCFG.SemanticWorkingConditions := by
  exact (enumeratedSampleGeneratedNonemptySampleConsistencyExact
    G obs K f hfanout hG F).semanticWorkingConditions

end SampleGeneratedNonemptySampleConsistencyExact

end FIv21
