import LeanCfgProject.MCFG.FI_v2_1_ActualRefinedRuleListsFintype

/-!
# FI v2.1 Lean experiment: semantic summary for actual refined rule lists

This file records the immediate semantic consequences of the actual refined-rule
list construction.  The important point is that the concrete finite-monoid
refined grammar now comes from explicit lists rather than from an abstract
certificate supplied by hand.
-/

namespace FIv21

universe u v w

section ActualRefinedRuleListsSummary

variable {N : Type w} {α : Type u}
variable {M : Type v} [Monoid M] [Fintype M]

/-- Tuple language of the actual finite-monoid refined-rule enumeration. -/
noncomputable def ActualFintypeRefinedTupleLanguage
    (G : WorkingMCFG N α) (obs : α → M)
    (hG : G.SemanticWorkingConditions)
    (A : RefinedNonterminal G M) : Set (Tuple α (G.arity A.base)) :=
  (actualFintypeConcreteRuleEnumeration G obs hG).TupleLanguage A

/-- Soundness of the actual finite-monoid refined-rule lists. -/
theorem actualFintypeRefinedTupleLanguage_sound
    (G : WorkingMCFG N α) (obs : α → M)
    (hG : G.SemanticWorkingConditions)
    (A : RefinedNonterminal G M) :
    ActualFintypeRefinedTupleLanguage G obs hG A ⊆
      OutputTypedTupleLanguage G obs A := by
  intro x hx
  exact (actualFintypeConcreteRuleEnumeration G obs hG).tupleLanguage_sound A hx

/-- Forgetting output types maps the actual finite-monoid refined tuple language
into the ordinary base tuple language. -/
theorem actualFintypeRefinedTupleLanguage_forgets_to_base
    (G : WorkingMCFG N α) (obs : α → M)
    (hG : G.SemanticWorkingConditions)
    (A : RefinedNonterminal G M) :
    ActualFintypeRefinedTupleLanguage G obs hG A ⊆
      FIv21.TupleLanguage G A.base := by
  intro x hx
  exact (actualFintypeConcreteRuleEnumeration G obs hG).tupleLanguage_forgets_to_base A hx

/-- Tuples generated by the actual finite-monoid refined lists have the output
type advertised by the refined nonterminal. -/
theorem actualFintypeRefinedTupleLanguage_has_output_type
    (G : WorkingMCFG N α) (obs : α → M)
    (hG : G.SemanticWorkingConditions)
    (A : RefinedNonterminal G M)
    {x : Tuple α (G.arity A.base)}
    (hx : x ∈ ActualFintypeRefinedTupleLanguage G obs hG A) :
    tupleType obs x = A.outTy := by
  exact (actualFintypeConcreteRuleEnumeration G obs hG).tupleLanguage_has_output_type A hx

/-- The actual finite-monoid refined-rule lists give the finite output-type
refinement certificate expected by the older finite-refined-grammar layers. -/
noncomputable def actualFintypeOutputTypeRefinementCertificate
    (G : WorkingMCFG N α) (obs : α → M)
    (hG : G.SemanticWorkingConditions) :
    FintypeOutputTypeRefinementCertificate G obs :=
  (actualFintypeConcreteRuleEnumeration G obs hG).toFintypeOutputTypeRefinementCertificate

/-- The actual finite-monoid refined-rule lists induce an output-type
refinement grammar containing all ordinary output-type rule refinements. -/
theorem actualFintypeOutputTypeRefinementCertificate_containsAll
    (G : WorkingMCFG N α) (obs : α → M)
    (hG : G.SemanticWorkingConditions) :
    (actualFintypeOutputTypeRefinementCertificate G obs hG).toOutputTypeRefinedGrammar.ContainsAllOrdinaryRuleRefinements := by
  exact (actualFintypeOutputTypeRefinementCertificate G obs hG).containsAllOrdinaryRuleRefinements

end ActualRefinedRuleListsSummary

end FIv21
