import LeanCfgProject.MCFG.FI_v2_1_LearnerWordConsistencyExact

/-!
# FI v2.1 Lean experiment: Gold wrapper with learner-side word consistency

This forty-sixth layer adds a characteristic-sample wrapper that records not
only target-side start witnesses after the characteristic sample, but also an
abstract learner-side sample-word consistency obligation for a sample-indexed
learner word semantics.

The limiting distributional identification theorem is inherited from the
start-witness wrapper.  The new content is the interface that a future canonical
learner grammar must instantiate: after every sufficiently rich positive sample,
all sample words are generated by the learner-side word language associated
with that sample.
-/

namespace FIv21

universe u v w

section LearnerWordConsistencyGold

variable {N : Type w} {α : Type u}
variable [DecidableEq α]
variable {M : Type v} [Monoid M] [Fintype M]

/-- A sample-indexed learner-side word semantics for a concrete extracted-sample
learner.  In the eventual grammar-level development, this should be the string
language of the canonical learner grammar extracted from `K`. -/
abbrev ConcreteExtractedSampleLearnerWordSemantics
    {G : WorkingMCFG N α} {obs : α → M}
    (A : ConcreteExtractedSampleLearner G obs) :=
  (K : Finset (Word α)) → Set (Word α)

/-- Grammar-target characteristic sample with post-threshold exactness,
target-side start witnesses, and learner-side sample-word consistency. -/
structure GrammarConcreteLearnerWordCharacteristicSample
    {G : WorkingMCFG N α} {obs : α → M}
    (A : ConcreteExtractedSampleLearner G obs)
    (LH : ConcreteExtractedSampleLearnerWordSemantics A) where
  startWitness : GrammarConcreteStartWitnessCharacteristicSample A
  learner_word_after_extending :
    ∀ K : Finset (Word α),
      SampleExtends startWitness.base.sample K →
      PositiveForLanguage K G.StringLanguage →
        ConcreteExtractedSampleLearnerWordConsistent (A K) (LH K)

namespace GrammarConcreteLearnerWordCharacteristicSample

/-- Forget learner-side word consistency and keep the start-witness
characteristic-sample certificate. -/
def toGrammarConcreteStartWitnessCharacteristicSample
    {G : WorkingMCFG N α} {obs : α → M}
    {A : ConcreteExtractedSampleLearner G obs}
    {LH : ConcreteExtractedSampleLearnerWordSemantics A}
    (C : GrammarConcreteLearnerWordCharacteristicSample A LH) :
    GrammarConcreteStartWitnessCharacteristicSample A :=
  C.startWitness

/-- Post-threshold exact/context/word/start plus learner-side sample-word
consistency. -/
def exact_start_learner_word_after
    {G : WorkingMCFG N α} {obs : α → M}
    {A : ConcreteExtractedSampleLearner G obs}
    {LH : ConcreteExtractedSampleLearnerWordSemantics A}
    (C : GrammarConcreteLearnerWordCharacteristicSample A LH)
    (K : Finset (Word α))
    (hExt : SampleExtends C.startWitness.base.sample K)
    (hPos : PositiveForLanguage K G.StringLanguage) :
    ConcreteExtractedSampleExactStartLearnerWordForGrammar (A K) (LH K) :=
  { exact_start := C.startWitness.exact_context_word_start_after K hExt hPos
    learner_word := C.learner_word_after_extending K hExt hPos }

/-- Post-threshold learner-side generation of a sampled word. -/
theorem sample_word_generated_by_learner_after
    {G : WorkingMCFG N α} {obs : α → M}
    {A : ConcreteExtractedSampleLearner G obs}
    {LH : ConcreteExtractedSampleLearnerWordSemantics A}
    (C : GrammarConcreteLearnerWordCharacteristicSample A LH)
    (K : Finset (Word α))
    (hExt : SampleExtends C.startWitness.base.sample K)
    (hPos : PositiveForLanguage K G.StringLanguage)
    (w : Word α) (hw : w ∈ K) :
    w ∈ LH K := by
  exact (C.exact_start_learner_word_after K hExt hPos).sample_word_generated_by_learner w hw

/-- Post-threshold target-side start-symbol derivation witness for a sampled
word. -/
theorem sample_word_start_derives_after
    {G : WorkingMCFG N α} {obs : α → M}
    {A : ConcreteExtractedSampleLearner G obs}
    {LH : ConcreteExtractedSampleLearnerWordSemantics A}
    (C : GrammarConcreteLearnerWordCharacteristicSample A LH)
    (K : Finset (Word α))
    (hExt : SampleExtends C.startWitness.base.sample K)
    (hPos : PositiveForLanguage K G.StringLanguage)
    (w : Word α) (hw : w ∈ K) :
    ∃ h : 1 = G.arity G.start,
      DerivesTuple G G.start (castTuple h (singletonTuple w)) := by
  exact C.startWitness.sample_word_start_derives_after K hExt hPos w hw

/-- Limiting distributional identification follows by forgetting the
learner-side word-consistency field. -/
theorem identifiesInLimit
    {G : WorkingMCFG N α} {obs : α → M}
    {A : ConcreteExtractedSampleLearner G obs}
    {LH : ConcreteExtractedSampleLearnerWordSemantics A}
    (C : GrammarConcreteLearnerWordCharacteristicSample A LH) :
    FiniteHypothesisIdentifiesGrammarInLimit A.toFiniteHypothesisLearner G := by
  exact GrammarConcreteStartWitnessCharacteristicSample.identifiesInLimit
    C.startWitness

/-- Pointwise limiting context correctness also follows by forgetting the
learner-side word-consistency field. -/
theorem eventuallyCorrectContexts
    {G : WorkingMCFG N α} {obs : α → M}
    {A : ConcreteExtractedSampleLearner G obs}
    {LH : ConcreteExtractedSampleLearnerWordSemantics A}
    (C : GrammarConcreteLearnerWordCharacteristicSample A LH) :
    FiniteHypothesisEventuallyCorrectContexts
      A.toFiniteHypothesisLearner G.StringLanguage := by
  exact GrammarConcreteStartWitnessCharacteristicSample.eventuallyCorrectContexts
    C.startWitness

end GrammarConcreteLearnerWordCharacteristicSample

end LearnerWordConsistencyGold

end FIv21
