import LeanCfgProject.MCFG.FI_v2_1_SampleGeneratedPrefixNodeEnumerationGold

/-!
# FI v2.1 Lean experiment: word-level parse witnesses

The previous layer exposes finite prefix-node enumeration witnesses.  This file
bundles such a witness at the level of a sample word: a word `w ∈ K` together
with a prefix-node enumeration for `w`.  The result is the first compact
sample-consistency interface for the generated terminal+concat `WorkingMCFG`
shell.

This remains certificate-driven: it does not yet automatically construct the
prefix-node enumeration for every word.  It states exactly what evidence is
needed to prove that a sample word is generated by the sample-generated grammar.
-/

namespace FIv21

universe u v w

section SampleGeneratedWordParseWitness

variable {N : Type w} {α : Type u}
variable [DecidableEq α]
variable {M : Type v} [Monoid M] [Fintype M]

/-- A word-level parse witness for the generated grammar skeleton: the word is
in the finite sample and has a prefix-node enumeration. -/
structure SampleGeneratedWordParseWitness
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (R : SampleGeneratedRuleSkeleton G obs K) (w : Word α) where
  sample_mem : w ∈ K
  parse : SampleGeneratedPrefixNodeEnumeration (M := M) R w

namespace SampleGeneratedWordParseWitness

/-- The endpoint of the prefix-node parse as a listed decomposition node. -/
def endpoint
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    {R : SampleGeneratedRuleSkeleton G obs K} {w : Word α}
    (W : SampleGeneratedWordParseWitness (M := M) R w) :
    ListedSampleGeneratedDecompositionNode R :=
  W.parse.endpoint

/-- The endpoint exposes exactly the indexed word. -/
theorem endpoint_middle_eq
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    {R : SampleGeneratedRuleSkeleton G obs K} {w : Word α}
    (W : SampleGeneratedWordParseWitness (M := M) R w) :
    W.endpoint.middle = w := by
  exact W.parse.endpoint_middle_eq

/-- The endpoint tuple is listed among the generated nonterminals. -/
theorem endpoint_tuple_mem_nonterminals
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    {R : SampleGeneratedRuleSkeleton G obs K} {w : Word α}
    (W : SampleGeneratedWordParseWitness (M := M) R w) :
    W.endpoint.node.tupleNonterminal ∈ R.nonterminals := by
  exact W.endpoint.tuple_mem_nonterminals

/-- The endpoint context is listed among the generated nonterminals. -/
theorem endpoint_context_mem_nonterminals
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    {R : SampleGeneratedRuleSkeleton G obs K} {w : Word α}
    (W : SampleGeneratedWordParseWitness (M := M) R w) :
    W.endpoint.node.contextNonterminal ∈ R.nonterminals := by
  exact W.endpoint.context_mem_nonterminals

/-- The endpoint context is licensed by the sample named distribution for the
endpoint tuple. -/
theorem endpoint_context_mem_sampleDistribution
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    {R : SampleGeneratedRuleSkeleton G obs K} {w : Word α}
    (W : SampleGeneratedWordParseWitness (M := M) R w) :
    W.endpoint.context ∈ SampleNamedDistribution K W.endpoint.tuple := by
  exact W.endpoint.context_mem_sampleDistribution

/-- A word-level parse witness gives membership in the generated
terminal+concat grammar shell. -/
theorem word_mem_stringLanguage
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    {R : SampleGeneratedRuleSkeleton G obs K} {w : Word α}
    (W : SampleGeneratedWordParseWitness (M := M) R w) :
    w ∈ (terminalConcatEnumeratedRuleListPackage (M := M) R).toWorkingMCFG.StringLanguage := by
  exact W.parse.word_mem_stringLanguage (M := M)

end SampleGeneratedWordParseWitness

/-- A sample-level parse-witness package: every word in `K` has a word-level
parse witness. -/
structure SampleGeneratedSampleParseWitnesses
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (R : SampleGeneratedRuleSkeleton G obs K) where
  witness : ∀ w : Word α, w ∈ K → SampleGeneratedWordParseWitness (M := M) R w

namespace SampleGeneratedSampleParseWitnesses

/-- Retrieve the word-level witness for a sample word. -/
def witnessOfMem
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    {R : SampleGeneratedRuleSkeleton G obs K}
    (P : SampleGeneratedSampleParseWitnesses (M := M) R)
    {w : Word α} (hw : w ∈ K) :
    SampleGeneratedWordParseWitness (M := M) R w :=
  P.witness w hw

/-- Every sample word is generated by the generated terminal+concat grammar
shell. -/
theorem word_mem_stringLanguage
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    {R : SampleGeneratedRuleSkeleton G obs K}
    (P : SampleGeneratedSampleParseWitnesses (M := M) R)
    {w : Word α} (hw : w ∈ K) :
    w ∈ (terminalConcatEnumeratedRuleListPackage (M := M) R).toWorkingMCFG.StringLanguage := by
  exact (P.witnessOfMem (M := M) hw).word_mem_stringLanguage (M := M)

/-- Set-inclusion form of sample consistency for the generated grammar shell. -/
theorem sample_subset_stringLanguage
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    {R : SampleGeneratedRuleSkeleton G obs K}
    (P : SampleGeneratedSampleParseWitnesses (M := M) R) :
    ∀ w : Word α,
      w ∈ K →
        w ∈ (terminalConcatEnumeratedRuleListPackage (M := M) R).toWorkingMCFG.StringLanguage := by
  intro w hw
  exact P.word_mem_stringLanguage (M := M) hw

/-- The endpoint associated with a sample word exposes that word. -/
theorem endpoint_middle_eq_of_mem
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    {R : SampleGeneratedRuleSkeleton G obs K}
    (P : SampleGeneratedSampleParseWitnesses (M := M) R)
    {w : Word α} (hw : w ∈ K) :
    (P.witnessOfMem (M := M) hw).endpoint.middle = w := by
  exact (P.witnessOfMem (M := M) hw).endpoint_middle_eq

/-- The endpoint context for every parsed sample word is licensed by the sample
named distribution. -/
theorem endpoint_context_mem_sampleDistribution_of_mem
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    {R : SampleGeneratedRuleSkeleton G obs K}
    (P : SampleGeneratedSampleParseWitnesses (M := M) R)
    {w : Word α} (hw : w ∈ K) :
    (P.witnessOfMem (M := M) hw).endpoint.context ∈
      SampleNamedDistribution K (P.witnessOfMem (M := M) hw).endpoint.tuple := by
  exact (P.witnessOfMem (M := M) hw).endpoint_context_mem_sampleDistribution

end SampleGeneratedSampleParseWitnesses

end SampleGeneratedWordParseWitness

end FIv21
