import LeanCfgProject.MCFG.FI_v2_1_NamedSentenceContext

/-!
# FI v2.1 Lean experiment: syntax of working binary MCFG rules

This file is the third formalization layer for the FI v2.1 MCFG paper.

The first file formalizes fixed finite-monoid observations and abstract tuple
substitutability.  The second file gives concrete named sentence contexts.  The
present file adds a lightweight syntax for the *working binary linear
nondeleting MCFG presentations* used in the paper.

The goal of this layer is deliberately modest: it gives typed objects for
binary templates, their simultaneous substitution operation, and a grammar
record carrying start, terminal, and binary rules.  It does not yet formalize
full derivation trees, reducedness, productivity, reachability, or the canonical
learner construction.
-/

namespace FIv21

universe u v

section Templates

variable {α : Type u}

/-- Atoms occurring in the body of a binary MCFG template.

A binary rule combines a left child tuple of arity `dB` and a right child tuple
of arity `dC`.  A template atom is either a terminal symbol, a reference to a
left-child component, or a reference to a right-child component. -/
inductive TemplateAtom (α : Type u) (dB dC : Nat) where
  | terminal : α → TemplateAtom α dB dC
  | leftVar : Fin dB → TemplateAtom α dB dC
  | rightVar : Fin dC → TemplateAtom α dB dC
  deriving Repr

/-- A template word is a list of terminals and child-component variables. -/
abbrev TemplateWord (α : Type u) (dB dC : Nat) :=
  List (TemplateAtom α dB dC)

/-- Evaluate a single template atom under a pair of child tuples. -/
def evalTemplateAtom {dB dC : Nat}
    (x : Tuple α dB) (y : Tuple α dC) : TemplateAtom α dB dC → Word α
  | TemplateAtom.terminal a => [a]
  | TemplateAtom.leftVar i => x i
  | TemplateAtom.rightVar j => y j

/-- Simultaneous substitution of child tuple components into a template word. -/
def evalTemplateWord {dB dC : Nat}
    (x : Tuple α dB) (y : Tuple α dC) : TemplateWord α dB dC → Word α
  | [] => []
  | a :: rest => evalTemplateAtom x y a ++ evalTemplateWord x y rest

@[simp] theorem evalTemplateWord_nil {dB dC : Nat}
    (x : Tuple α dB) (y : Tuple α dC) :
    evalTemplateWord x y ([] : TemplateWord α dB dC) = [] := rfl

@[simp] theorem evalTemplateWord_cons {dB dC : Nat}
    (x : Tuple α dB) (y : Tuple α dC)
    (a : TemplateAtom α dB dC) (rest : TemplateWord α dB dC) :
    evalTemplateWord x y (a :: rest) =
      evalTemplateAtom x y a ++ evalTemplateWord x y rest := rfl

/-- A binary template tuple with output arity `e` and child arities `dB,dC`. -/
abbrev TemplateTuple (α : Type u) (e dB dC : Nat) :=
  Fin e → TemplateWord α dB dC

/-- Evaluate a whole template tuple. -/
def evalTemplateTuple {e dB dC : Nat}
    (body : TemplateTuple α e dB dC)
    (x : Tuple α dB) (y : Tuple α dC) : Tuple α e :=
  fun i => evalTemplateWord x y (body i)

/-- A lightweight nondeleting condition: each child component occurs somewhere.

The paper's working form requires each variable to occur exactly once in the
whole body.  For this early syntax layer we record the weaker, useful predicate
that every child component occurs at least once.  A later file can strengthen
this to exact-once linearity by adding an occurrence-counting layer. -/
def TemplateTuple.Nondeleting {e dB dC : Nat}
    (body : TemplateTuple α e dB dC) : Prop :=
  (∀ i : Fin dB, ∃ o : Fin e, TemplateAtom.leftVar i ∈ body o) ∧
  (∀ j : Fin dC, ∃ o : Fin e, TemplateAtom.rightVar j ∈ body o)

end Templates

section RuleSyntax

variable {N : Type v} {α : Type u}

/-- A start rule `S → A`, represented by its child `A`.

The ambient grammar record stores the start symbol separately. -/
structure StartRule (N : Type v) where
  child : N
  deriving Repr

/-- A terminal rule `A → (a)`.

The paper restricts terminal rules to fan-out one.  The predicate
`TerminalRule.WellTyped` below records that restriction relative to an arity
map. -/
structure TerminalRule (N : Type v) (α : Type u) where
  lhs : N
  terminal : α
  deriving Repr

namespace TerminalRule

/-- Terminal rules are well-typed when their left-hand side has arity one. -/
def WellTyped (arity : N → Nat) (ρ : TerminalRule N α) : Prop :=
  arity ρ.lhs = 1

/-- The one-component tuple generated by a terminal rule. -/
def outputTuple (ρ : TerminalRule N α) : Tuple α 1 :=
  fun _ => [ρ.terminal]

@[simp] theorem outputTuple_apply (ρ : TerminalRule N α) (i : Fin 1) :
    ρ.outputTuple i = [ρ.terminal] := rfl

end TerminalRule

/-- A binary MCFG rule with dependent arities.

If `arity A = e`, `arity B = dB`, and `arity C = dC`, then a rule
`A → body(B,C)` has a body indexed by `Fin e`, with variables referring to
components of the two child tuples. -/
structure BinaryRule (N : Type v) (α : Type u) (arity : N → Nat) where
  lhs : N
  left : N
  right : N
  body : TemplateTuple α (arity lhs) (arity left) (arity right)

namespace BinaryRule

/-- Apply a binary rule to two child tuples by simultaneous substitution. -/
def apply {arity : N → Nat} (ρ : BinaryRule N α arity)
    (x : Tuple α (arity ρ.left))
    (y : Tuple α (arity ρ.right)) : Tuple α (arity ρ.lhs) :=
  evalTemplateTuple ρ.body x y

/-- Nondeleting predicate for a binary rule. -/
def Nondeleting {arity : N → Nat} (ρ : BinaryRule N α arity) : Prop :=
  TemplateTuple.Nondeleting ρ.body

@[simp] theorem apply_component {arity : N → Nat} (ρ : BinaryRule N α arity)
    (x : Tuple α (arity ρ.left))
    (y : Tuple α (arity ρ.right))
    (i : Fin (arity ρ.lhs)) :
    ρ.apply x y i = evalTemplateWord x y (ρ.body i) := rfl

end BinaryRule

end RuleSyntax

section GrammarRecord

variable (N : Type v) (α : Type u)

/-- A lightweight record for the working binary MCFG presentations of the paper.

This is syntax only.  Later files may add derivation semantics, reducedness,
reachability/productivity, and the canonical learner. -/
structure WorkingMCFG where
  start : N
  arity : N → Nat
  arity_pos : ∀ A : N, 0 < arity A
  startRules : List (StartRule N)
  terminalRules : List (TerminalRule N α)
  binaryRules : List (BinaryRule N α arity)

namespace WorkingMCFG

variable {N : Type v} {α : Type u}

/-- Fan-out bound for the nonterminals of a grammar. -/
def FanoutAtMost (G : WorkingMCFG N α) (f : Nat) : Prop :=
  ∀ A : N, G.arity A ≤ f

/-- The start symbol has fan-out one. -/
def StartArityOne (G : WorkingMCFG N α) : Prop :=
  G.arity G.start = 1

/-- All terminal rules are well-typed. -/
def TerminalRulesWellTyped (G : WorkingMCFG N α) : Prop :=
  ∀ ρ : TerminalRule N α, ρ ∈ G.terminalRules → ρ.WellTyped G.arity

/-- All binary rules satisfy the nondeleting side condition. -/
def BinaryRulesNondeleting (G : WorkingMCFG N α) : Prop :=
  ∀ ρ : BinaryRule N α G.arity, ρ ∈ G.binaryRules → ρ.Nondeleting

/-- The presentation-level working side conditions currently represented in
this syntax layer.  This is intentionally weaker than the paper's full working
form; exact-once linearity and start separation are left for later layers. -/
def BasicWorkingConditions (G : WorkingMCFG N α) : Prop :=
  G.StartArityOne ∧ G.TerminalRulesWellTyped ∧ G.BinaryRulesNondeleting

/-- If a grammar has fan-out at most `f`, then every listed binary rule has
left-hand side, left child, and right child of arity at most `f`. -/
theorem binaryRule_arities_le_of_fanout
    (G : WorkingMCFG N α) {f : Nat} (hG : G.FanoutAtMost f)
    {ρ : BinaryRule N α G.arity} (hρ : ρ ∈ G.binaryRules) :
    G.arity ρ.lhs ≤ f ∧ G.arity ρ.left ≤ f ∧ G.arity ρ.right ≤ f := by
  exact ⟨hG ρ.lhs, hG ρ.left, hG ρ.right⟩

end WorkingMCFG

end GrammarRecord

end FIv21
