import LeanCfgProject.MCFG.FI_v2_1_SampleGeneratedWordParseWitnessConstruction

/-!
# FI v2.1 Lean experiment: exact package for word-parse witness construction

This layer packages prefix-node-enumeration constructors against the generated
terminal+concat grammar shell.  It converts a family of prefix-node enumerations
for all sample words into the existing sample-parse witness package, and hence
into sample inclusion in the generated `WorkingMCFG` shell.
-/

namespace FIv21

universe u v w

section SampleGeneratedWordParseWitnessConstructionExact

variable {N : Type w} {α : Type u}
variable [DecidableEq α]
variable {M : Type v} [Monoid M] [Fintype M]

/-- Exact package for constructing word-level parse witnesses from prefix-node
enumerations. -/
structure SampleGeneratedWordParseWitnessConstructionExact
    (G : WorkingMCFG N α) (obs : α → M) (K : Finset (Word α)) where
  wordParseExact : SampleGeneratedWordParseWitnessExact G obs K

namespace SampleGeneratedWordParseWitnessConstructionExact

/-- The underlying rule skeleton. -/
def ruleSkeleton
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (E : SampleGeneratedWordParseWitnessConstructionExact G obs K) :
    SampleGeneratedRuleSkeleton G obs K :=
  E.wordParseExact.ruleSkeleton

/-- The generated rule-list package. -/
noncomputable def ruleLists
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (E : SampleGeneratedWordParseWitnessConstructionExact G obs K) :
    SampleGeneratedRuleListPackage G obs K :=
  E.wordParseExact.ruleLists

/-- The generated working grammar shell. -/
noncomputable def toWorkingMCFG
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (E : SampleGeneratedWordParseWitnessConstructionExact G obs K) :
    WorkingMCFG (SampleGeneratedGrammarNonterminal
      E.ruleLists.ruleSkeleton.skeleton) α :=
  E.wordParseExact.toWorkingMCFG

/-- The generated grammar shell is semantically well-formed. -/
theorem semanticWorkingConditions
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (E : SampleGeneratedWordParseWitnessConstructionExact G obs K) :
    E.toWorkingMCFG.SemanticWorkingConditions := by
  exact E.wordParseExact.semanticWorkingConditions

/-- A word-construction object gives membership in the generated grammar shell. -/
theorem wordConstruction_mem_stringLanguage
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (E : SampleGeneratedWordParseWitnessConstructionExact G obs K)
    {w : Word α}
    (C : SampleGeneratedWordParseWitnessConstruction (M := M) E.ruleSkeleton w) :
    w ∈ E.toWorkingMCFG.StringLanguage := by
  exact E.wordParseExact.wordWitness_mem_stringLanguage
    (M := M) C.toWordParseWitness

/-- A sample-level construction gives sample inclusion in the generated grammar
shell. -/
theorem sampleConstruction_subset_stringLanguage
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (E : SampleGeneratedWordParseWitnessConstructionExact G obs K)
    (C : SampleGeneratedSampleParseWitnessConstruction (M := M) E.ruleSkeleton) :
    ∀ w : Word α, w ∈ K → w ∈ E.toWorkingMCFG.StringLanguage := by
  exact E.wordParseExact.sampleWitnesses_subset_stringLanguage
    (M := M) C.toSampleParseWitnesses

end SampleGeneratedWordParseWitnessConstructionExact

/-- Exact package including a prefix-node-enumeration constructor for every
sample word. -/
structure SampleGeneratedSampleParseWitnessConstructionExact
    (G : WorkingMCFG N α) (obs : α → M) (K : Finset (Word α)) where
  exactPackage : SampleGeneratedWordParseWitnessConstructionExact G obs K
  construction :
    SampleGeneratedSampleParseWitnessConstruction (M := M) exactPackage.ruleSkeleton

namespace SampleGeneratedSampleParseWitnessConstructionExact

/-- The generated grammar shell. -/
noncomputable def toWorkingMCFG
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (E : SampleGeneratedSampleParseWitnessConstructionExact G obs K) :
    WorkingMCFG (SampleGeneratedGrammarNonterminal
      E.exactPackage.ruleLists.ruleSkeleton.skeleton) α :=
  E.exactPackage.toWorkingMCFG

/-- The generated grammar shell is semantically well-formed. -/
theorem semanticWorkingConditions
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (E : SampleGeneratedSampleParseWitnessConstructionExact G obs K) :
    E.toWorkingMCFG.SemanticWorkingConditions := by
  exact E.exactPackage.semanticWorkingConditions

/-- Every sample word is generated by the generated grammar shell. -/
theorem sample_subset_stringLanguage
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (E : SampleGeneratedSampleParseWitnessConstructionExact G obs K) :
    ∀ w : Word α, w ∈ K → w ∈ E.toWorkingMCFG.StringLanguage := by
  exact E.exactPackage.sampleConstruction_subset_stringLanguage
    (M := M) E.construction

/-- The construction can be viewed as the earlier sample-parse witness package. -/
def toSampleParseWitnesses
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (E : SampleGeneratedSampleParseWitnessConstructionExact G obs K) :
    SampleGeneratedSampleParseWitnesses (M := M) E.exactPackage.ruleSkeleton :=
  E.construction.toSampleParseWitnesses

end SampleGeneratedSampleParseWitnessConstructionExact

/-- Concrete exact package using the enumerated word-parse witness layer. -/
noncomputable def enumeratedSampleGeneratedWordParseWitnessConstructionExact
    (G : WorkingMCFG N α) (obs : α → M) (K : Finset (Word α))
    (f : Nat) (hfanout : 1 ≤ f) (hG : G.SemanticWorkingConditions) :
    SampleGeneratedWordParseWitnessConstructionExact G obs K :=
  { wordParseExact :=
      enumeratedSampleGeneratedWordParseWitnessExact G obs K f hfanout hG }

/-- The concrete generated grammar shell is semantically well-formed. -/
theorem enumeratedSampleGeneratedWordParseWitnessConstructionExact_semantic
    (G : WorkingMCFG N α) (obs : α → M) (K : Finset (Word α))
    (f : Nat) (hfanout : 1 ≤ f) (hG : G.SemanticWorkingConditions) :
    (enumeratedSampleGeneratedWordParseWitnessConstructionExact
      G obs K f hfanout hG).toWorkingMCFG.SemanticWorkingConditions := by
  exact (enumeratedSampleGeneratedWordParseWitnessConstructionExact
    G obs K f hfanout hG).semanticWorkingConditions

end SampleGeneratedWordParseWitnessConstructionExact

end FIv21
