import LeanCfgProject.MCFG.FI_v2_1_SampleGeneratedTerminalEnumeration

/-!
# FI v2.1 Lean experiment: exact package for terminal-enumerated generated grammars

This layer packages the terminal-enumeration construction.  It records the
underlying sample-generated rule skeleton and computes terminal candidates from
its listed decomposition nodes.  The exported concrete fact is the first
unconditional sample-consistency statement for the generated `WorkingMCFG`
shell: every sampled singleton word `[a]` is generated.
-/

namespace FIv21

universe u v w

section SampleGeneratedTerminalEnumerationExact

variable {N : Type w} {α : Type u}
variable [DecidableEq α]
variable {M : Type v} [Monoid M] [Fintype M]

/-- Exact package for terminal-enumerated generated working grammars. -/
structure SampleGeneratedTerminalEnumerationExact
    (G : WorkingMCFG N α) (obs : α → M) (K : Finset (Word α)) where
  ruleSkeleton : SampleGeneratedRuleSkeleton G obs K

namespace SampleGeneratedTerminalEnumerationExact

/-- The terminal-enumerated rule-list package. -/
noncomputable def ruleLists
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (E : SampleGeneratedTerminalEnumerationExact G obs K) :
    SampleGeneratedRuleListPackage G obs K :=
  terminalEnumeratedRuleListPackage (M := M) E.ruleSkeleton

/-- The generated working grammar shell. -/
noncomputable def toWorkingMCFG
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (E : SampleGeneratedTerminalEnumerationExact G obs K) :
    WorkingMCFG (SampleGeneratedGrammarNonterminal
      E.ruleLists.ruleSkeleton.skeleton) α :=
  E.ruleLists.toWorkingMCFG

/-- The terminal-enumerated grammar shell satisfies the semantic working
conditions already proved for generated working grammars. -/
theorem semanticWorkingConditions
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (E : SampleGeneratedTerminalEnumerationExact G obs K) :
    E.toWorkingMCFG.SemanticWorkingConditions := by
  exact E.ruleLists.toWorkingMCFG_semanticWorkingConditions

/-- Listed singleton-middle nodes derive their exposed singleton tuple. -/
theorem node_derives_singleton
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (E : SampleGeneratedTerminalEnumerationExact G obs K)
    {X : SampleGeneratedDecompositionNode E.ruleSkeleton.skeleton}
    {a : α}
    (hX : X ∈ E.ruleSkeleton.decompositionNodes)
    (hmid : X.decomposition.middle = [a]) :
    DerivesTuple E.toWorkingMCFG
      (SampleGeneratedGrammarNonterminal.node X)
      (singletonTuple [a]) := by
  exact SampleGeneratedRuleListPackage
    .terminalEnumerated_node_derives_singleton (M := M)
      E.ruleSkeleton hX hmid

end SampleGeneratedTerminalEnumerationExact

/-- Concrete exact package using the enumerated subword decomposition skeleton
and generated singleton terminal candidates. -/
noncomputable def enumeratedSampleGeneratedTerminalEnumerationExact
    (G : WorkingMCFG N α) (obs : α → M) (K : Finset (Word α))
    (f : Nat) (hfanout : 1 ≤ f) (hG : G.SemanticWorkingConditions) :
    SampleGeneratedTerminalEnumerationExact G obs K :=
  { ruleSkeleton := enumeratedSampleGeneratedRuleSkeleton G obs K f hfanout hG }

/-- The concrete terminal-enumerated output grammar is semantically well-formed. -/
theorem enumeratedSampleGeneratedTerminalEnumerationExact_semantic
    (G : WorkingMCFG N α) (obs : α → M) (K : Finset (Word α))
    (f : Nat) (hfanout : 1 ≤ f) (hG : G.SemanticWorkingConditions) :
    (enumeratedSampleGeneratedTerminalEnumerationExact G obs K f hfanout hG)
      .toWorkingMCFG.SemanticWorkingConditions := by
  exact (enumeratedSampleGeneratedTerminalEnumerationExact
    G obs K f hfanout hG).semanticWorkingConditions

/-- Singleton sample words are generated by the concrete exact package. -/
theorem enumeratedSampleGeneratedTerminalEnumerationExact_singleton
    (G : WorkingMCFG N α) (obs : α → M) (K : Finset (Word α))
    (f : Nat) (hfanout : 1 ≤ f) (hG : G.SemanticWorkingConditions)
    {a : α} (ha : ([a] : Word α) ∈ K) :
    ([a] : Word α) ∈
      (enumeratedSampleGeneratedTerminalEnumerationExact G obs K f hfanout hG)
        .toWorkingMCFG.StringLanguage := by
  exact enumeratedTerminalRuleListPackage_singleton_sample_mem_stringLanguage
    (M := M) G obs K f hfanout hG ha

end SampleGeneratedTerminalEnumerationExact

end FIv21
