import LeanCfgProject.MCFG.FI_v2_1_SampleGeneratedWorkingGrammarGold

/-!
# FI v2.1 Lean experiment: derivation lemmas for sample-generated working grammars

The previous layer turned sample-generated rule candidates into an actual
`WorkingMCFG` shell.  This file is the first derivation-facing layer for that
shell.  It proves that generated terminal, binary-concatenation, and start-rule
candidates can be used by the ordinary `DerivesTuple` constructors.

The statements remain conservative: the enumerated grammar currently has
canonical start rules and empty terminal/binary lists unless extra candidates
are supplied.  Nevertheless, the bridge from generated rule-list membership to
MCFG derivability is now explicit.
-/

namespace FIv21

universe u v w

section SampleGeneratedWorkingGrammarDerivation

variable {N : Type w} {α : Type u}
variable [DecidableEq α]
variable {M : Type v} [Monoid M] [Fintype M]

namespace SampleGeneratedRuleListPackage

/-- Generated start rules are well-typed in the sample-generated working grammar
shell. -/
theorem startRuleOfCandidate_wellTyped
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (P : SampleGeneratedRuleListPackage G obs K)
    (C : SampleGeneratedStartCandidate P.ruleSkeleton.skeleton) :
    (startRuleOfCandidate (M := M) C).WellTyped P.toWorkingMCFG := by
  rfl

/-- All generated start rules are well-typed. -/
theorem toWorkingMCFG_startRulesWellTyped
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (P : SampleGeneratedRuleListPackage G obs K) :
    P.toWorkingMCFG.StartRulesWellTyped := by
  intro ρ hρ
  unfold SampleGeneratedRuleListPackage.toWorkingMCFG
    SampleGeneratedRuleListPackage.startRules at hρ
  rcases List.mem_map.mp hρ with ⟨C, _hC, hEq⟩
  cases hEq
  exact P.startRuleOfCandidate_wellTyped C

/-- The generated working grammar shell satisfies the semantic working
conditions represented by the current derivation layer. -/
theorem toWorkingMCFG_semanticWorkingConditions
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (P : SampleGeneratedRuleListPackage G obs K) :
    P.toWorkingMCFG.SemanticWorkingConditions := by
  exact ⟨P.toWorkingMCFG_basicWorkingConditions,
    P.toWorkingMCFG_startRulesWellTyped⟩

/-- The terminal rule generated by a singleton-middle candidate outputs exactly
that candidate's exposed singleton tuple. -/
theorem terminalRuleOfCandidate_outputTuple_eq_node_tuple
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    {S : SampleGeneratedLearnerGrammarSkeleton G obs K}
    (C : SampleGeneratedTerminalCandidate S) :
    TerminalRule.outputTuple (terminalRuleOfCandidate (M := M) C) =
      C.node.decomposition.tuple := by
  funext i
  have hi : i = 0 := Subsingleton.elim i 0
  subst i
  simp [terminalRuleOfCandidate, TerminalRule.outputTuple,
    SubwordSampleDecomposition.tuple, singletonTuple, C.middle_eq]

/-- A listed terminal candidate gives a tuple derivation of its exposed singleton
tuple in the generated working grammar shell. -/
theorem terminalCandidate_derives_node_tuple
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (P : SampleGeneratedRuleListPackage G obs K)
    {C : SampleGeneratedTerminalCandidate P.ruleSkeleton.skeleton}
    (hC : C ∈ P.terminalCandidates) :
    DerivesTuple P.toWorkingMCFG
      (SampleGeneratedGrammarNonterminal.node C.node)
      C.node.decomposition.tuple := by
  have hRule : terminalRuleOfCandidate (M := M) C ∈ P.terminalRules :=
    P.terminalRule_mem_of_candidate_mem hC
  have hWT : (terminalRuleOfCandidate (M := M) C).WellTyped
      P.toWorkingMCFG.arity :=
    terminalRuleOfCandidate_wellTyped (M := M) C
  have hD := DerivesTuple.terminal
      (G := P.toWorkingMCFG) (terminalRuleOfCandidate (M := M) C) hRule hWT
  have hOut : TerminalRule.outputTuple (terminalRuleOfCandidate (M := M) C) =
      C.node.decomposition.tuple :=
    terminalRuleOfCandidate_outputTuple_eq_node_tuple (M := M) C
  simpa [hOut] using hD

/-- The binary rule generated by a concatenation candidate maps the two exposed
child tuples to the exposed result tuple. -/
theorem binaryRuleOfConcatCandidate_apply_node_tuples
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    {S : SampleGeneratedLearnerGrammarSkeleton G obs K}
    (C : SampleGeneratedConcatCandidate S) :
    (binaryRuleOfConcatCandidate (M := M) C).apply
      C.left.decomposition.tuple C.right.decomposition.tuple =
      C.result.decomposition.tuple := by
  funext i
  have hi : i = 0 := Subsingleton.elim i 0
  subst i
  simp [binaryRuleOfConcatCandidate, BinaryRule.apply, singletonConcatTemplate,
    evalTemplateTuple, evalTemplateWord, evalTemplateAtom,
    SubwordSampleDecomposition.tuple, singletonTuple, C.middle_eq]

/-- A listed binary-concatenation candidate can be applied to two already-derived
child tuples. -/
theorem binaryCandidate_derives_apply
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (P : SampleGeneratedRuleListPackage G obs K)
    {C : SampleGeneratedConcatCandidate P.ruleSkeleton.skeleton}
    (hC : C ∈ P.concatCandidates)
    {x : Tuple α 1} {y : Tuple α 1}
    (hx : DerivesTuple P.toWorkingMCFG
      (SampleGeneratedGrammarNonterminal.node C.left) x)
    (hy : DerivesTuple P.toWorkingMCFG
      (SampleGeneratedGrammarNonterminal.node C.right) y) :
    DerivesTuple P.toWorkingMCFG
      (SampleGeneratedGrammarNonterminal.node C.result)
      ((binaryRuleOfConcatCandidate (M := M) C).apply x y) := by
  have hRule : binaryRuleOfConcatCandidate (M := M) C ∈ P.binaryRules :=
    P.binaryRule_mem_of_candidate_mem hC
  exact DerivesTuple.binary
    (G := P.toWorkingMCFG) (binaryRuleOfConcatCandidate (M := M) C)
    hRule x y hx hy

/-- If the two child exposed tuples of a listed concatenation candidate are
derivable, then the exposed result tuple is derivable. -/
theorem binaryCandidate_derives_result_tuple
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (P : SampleGeneratedRuleListPackage G obs K)
    {C : SampleGeneratedConcatCandidate P.ruleSkeleton.skeleton}
    (hC : C ∈ P.concatCandidates)
    (hLeft : DerivesTuple P.toWorkingMCFG
      (SampleGeneratedGrammarNonterminal.node C.left)
      C.left.decomposition.tuple)
    (hRight : DerivesTuple P.toWorkingMCFG
      (SampleGeneratedGrammarNonterminal.node C.right)
      C.right.decomposition.tuple) :
    DerivesTuple P.toWorkingMCFG
      (SampleGeneratedGrammarNonterminal.node C.result)
      C.result.decomposition.tuple := by
  have hD := P.binaryCandidate_derives_apply (M := M) hC hLeft hRight
  have hEq := binaryRuleOfConcatCandidate_apply_node_tuples (M := M) C
  simpa [hEq] using hD

/-- A listed generated start candidate lifts a derivation of its child node to a
derivation from the generated root. -/
theorem startCandidate_lifts_node_derivation
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (P : SampleGeneratedRuleListPackage G obs K)
    {C : SampleGeneratedStartCandidate P.ruleSkeleton.skeleton}
    (hC : C ∈ P.ruleSkeleton.startCandidates)
    {x : Tuple α 1}
    (hx : DerivesTuple P.toWorkingMCFG
      (SampleGeneratedGrammarNonterminal.node C.node) x) :
    DerivesTuple P.toWorkingMCFG
      SampleGeneratedGrammarNonterminal.root x := by
  have hRule : startRuleOfCandidate (M := M) C ∈ P.startRules :=
    P.startRule_mem_of_candidate_mem hC
  have hWT : (startRuleOfCandidate (M := M) C).WellTyped P.toWorkingMCFG :=
    P.startRuleOfCandidate_wellTyped C
  have hD := DerivesTuple.start
      (G := P.toWorkingMCFG) (startRuleOfCandidate (M := M) C)
      hRule hWT x hx
  simpa [startRuleOfCandidate, SampleGeneratedGrammarNonterminal.arity] using hD

/-- A listed start candidate whose child derives the singleton word tuple gives
membership in the string language of the generated grammar shell. -/
theorem mem_stringLanguage_of_startCandidate_node_derives
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (P : SampleGeneratedRuleListPackage G obs K)
    {C : SampleGeneratedStartCandidate P.ruleSkeleton.skeleton}
    (hC : C ∈ P.ruleSkeleton.startCandidates)
    {w : Word α}
    (hw : DerivesTuple P.toWorkingMCFG
      (SampleGeneratedGrammarNonterminal.node C.node)
      (singletonTuple w)) :
    w ∈ P.toWorkingMCFG.StringLanguage := by
  have hStart : DerivesTuple P.toWorkingMCFG
      SampleGeneratedGrammarNonterminal.root (singletonTuple w) :=
    P.startCandidate_lifts_node_derivation (M := M) hC hw
  exact WorkingMCFG.mem_StringLanguage_of_start_derives
    P.toWorkingMCFG w rfl hStart

end SampleGeneratedRuleListPackage

end SampleGeneratedWorkingGrammarDerivation

end FIv21
