import LeanCfgProject.MCFG.FI_v2_1_StartRuleSampleWitnessGold

/-!
# FI v2.1 Lean experiment: learner-side sample-word consistency

This forty-fourth layer introduces the learner-side word-consistency interface.
The previous files gave target-side start-derivation witnesses for sample words.
Here we do not yet define the full canonical learner grammar.  Instead we allow
a later learner grammar construction to expose a word language `LH` for a finite
hypothesis and record the single consistency obligation that every word in the
finite sample is generated by that learner-side language.

This is the intended bridge between the distribution-level learner already
formalized and the eventual grammar-level canonical learner.
-/

namespace FIv21

universe u v w

section LearnerWordConsistencySkeleton

variable {N : Type w} {α : Type u}
variable [DecidableEq α]
variable {M : Type v} [Monoid M] [Fintype M]

/-- A finite hypothesis is sample-word consistent with a proposed learner-side
word language when every word in its underlying finite sample belongs to that
language.

The language is a parameter because the full canonical learner grammar has not
yet been defined in this Lean development. -/
def FiniteHypothesisSampleWordConsistent
    (H : FiniteLearnerHypothesis α M) (LH : Set (Word α)) : Prop :=
  ∀ w : Word α, w ∈ H.sampleSet → w ∈ LH

namespace FiniteHypothesisSampleWordConsistent

/-- Pointwise form of finite-hypothesis sample-word consistency. -/
theorem sample_word_generated
    {H : FiniteLearnerHypothesis α M} {LH : Set (Word α)}
    (C : FiniteHypothesisSampleWordConsistent H LH)
    (w : Word α) (hw : w ∈ H.sampleSet) :
    w ∈ LH := by
  exact C w hw

/-- Sample-word consistency is monotone under enlargement of the learner-side
word language. -/
theorem mono
    {H : FiniteLearnerHypothesis α M} {LH LH' : Set (Word α)}
    (C : FiniteHypothesisSampleWordConsistent H LH)
    (hsub : LH ⊆ LH') :
    FiniteHypothesisSampleWordConsistent H LH' := by
  intro w hw
  exact hsub (C w hw)

end FiniteHypothesisSampleWordConsistent

/-- Concrete extracted sample data is learner-word consistent with `LH` when
its induced finite hypothesis is sample-word consistent with `LH`. -/
def ConcreteExtractedSampleLearnerWordConsistent
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (E : ConcreteExtractedSampleData G obs K) (LH : Set (Word α)) : Prop :=
  FiniteHypothesisSampleWordConsistent E.toFiniteLearnerHypothesis LH

namespace ConcreteExtractedSampleLearnerWordConsistent

/-- Pointwise learner-side generation of an externally sampled word. -/
theorem sample_word_generated
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    {E : ConcreteExtractedSampleData G obs K} {LH : Set (Word α)}
    (C : ConcreteExtractedSampleLearnerWordConsistent E LH)
    (w : Word α) (hw : w ∈ K) :
    w ∈ LH := by
  apply C
  rw [E.finiteHypothesis_sampleSet]
  exact hw

/-- Concrete learner-word consistency as a finite-hypothesis consistency
statement. -/
theorem toFiniteHypothesis_consistency
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    {E : ConcreteExtractedSampleData G obs K} {LH : Set (Word α)}
    (C : ConcreteExtractedSampleLearnerWordConsistent E LH) :
    FiniteHypothesisSampleWordConsistent E.toFiniteLearnerHypothesis LH := by
  exact C

/-- Monotonicity under enlargement of the proposed learner-side language. -/
theorem mono
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    {E : ConcreteExtractedSampleData G obs K} {LH LH' : Set (Word α)}
    (C : ConcreteExtractedSampleLearnerWordConsistent E LH)
    (hsub : LH ⊆ LH') :
    ConcreteExtractedSampleLearnerWordConsistent E LH' := by
  exact FiniteHypothesisSampleWordConsistent.mono C hsub

end ConcreteExtractedSampleLearnerWordConsistent

end LearnerWordConsistencySkeleton

end FIv21
