import LeanCfgProject.MCFG.FI_v2_1_LearnerWordConsistencyGold

/-!
# FI v2.1 Lean experiment: learner word-semantics interface

This forty-seventh layer packages the abstract learner-side word language used
in the previous learner-word consistency files as explicit semantics data.

The full canonical learner grammar is still not defined here.  Instead, this
file records the interface that such a grammar must later instantiate: for each
extracted finite sample datum, it provides a learner-side word language and a
proof that every sampled word is generated by that language.
-/

namespace FIv21

universe u v w

section LearnerWordSemanticsInterface

variable {N : Type w} {α : Type u}
variable [DecidableEq α]
variable {M : Type v} [Monoid M] [Fintype M]

/-- Word-semantics data for one concrete extracted sample datum.

The field `wordLanguage` is intended to become the string language of the
canonical learner grammar extracted from the sample.  For now it is an abstract
language together with the consistency obligation that it contains all words of
the finite sample. -/
structure ConcreteExtractedSampleWordSemanticsCertificate
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    (E : ConcreteExtractedSampleData G obs K) where
  wordLanguage : Set (Word α)
  sample_consistent :
    ConcreteExtractedSampleLearnerWordConsistent E wordLanguage

namespace ConcreteExtractedSampleWordSemanticsCertificate

/-- The finite-hypothesis sample-word consistency induced by the semantics
certificate. -/
theorem toFiniteHypothesisSampleWordConsistent
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    {E : ConcreteExtractedSampleData G obs K}
    (C : ConcreteExtractedSampleWordSemanticsCertificate E) :
    FiniteHypothesisSampleWordConsistent
      E.toFiniteLearnerHypothesis C.wordLanguage := by
  exact C.sample_consistent.toFiniteHypothesis_consistency

/-- Pointwise learner-side generation of a sampled word. -/
theorem sample_word_generated
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    {E : ConcreteExtractedSampleData G obs K}
    (C : ConcreteExtractedSampleWordSemanticsCertificate E)
    (w : Word α) (hw : w ∈ K) :
    w ∈ C.wordLanguage := by
  exact ConcreteExtractedSampleLearnerWordConsistent.sample_word_generated
    C.sample_consistent w hw

/-- Enlarge the learner-side language while preserving sample-word
consistency. -/
def mono
    {G : WorkingMCFG N α} {obs : α → M} {K : Finset (Word α)}
    {E : ConcreteExtractedSampleData G obs K}
    (C : ConcreteExtractedSampleWordSemanticsCertificate E)
    (LH' : Set (Word α))
    (hsub : C.wordLanguage ⊆ LH') :
    ConcreteExtractedSampleWordSemanticsCertificate E :=
  { wordLanguage := LH'
    sample_consistent :=
      ConcreteExtractedSampleLearnerWordConsistent.mono
        C.sample_consistent hsub }

end ConcreteExtractedSampleWordSemanticsCertificate

/-- Sample-indexed word-semantics data for a concrete extracted-sample learner.

This packages the abstract semantics `(K ↦ LH K)` together with the statement
that every sample word is generated by the corresponding learner-side language.
-/
structure ConcreteExtractedSampleLearnerWordSemanticsCertificate
    {G : WorkingMCFG N α} {obs : α → M}
    (A : ConcreteExtractedSampleLearner G obs) where
  wordLanguage : ConcreteExtractedSampleLearnerWordSemantics A
  sample_consistent :
    ∀ K : Finset (Word α),
      ConcreteExtractedSampleLearnerWordConsistent (A K) (wordLanguage K)

namespace ConcreteExtractedSampleLearnerWordSemanticsCertificate

/-- The one-sample word-semantics certificate obtained by evaluating a
sample-indexed semantics certificate at `K`. -/
def atSample
    {G : WorkingMCFG N α} {obs : α → M}
    {A : ConcreteExtractedSampleLearner G obs}
    (C : ConcreteExtractedSampleLearnerWordSemanticsCertificate A)
    (K : Finset (Word α)) :
    ConcreteExtractedSampleWordSemanticsCertificate (A K) :=
  { wordLanguage := C.wordLanguage K
    sample_consistent := C.sample_consistent K }

/-- Pointwise learner-side generation of a sampled word at sample `K`. -/
theorem sample_word_generated
    {G : WorkingMCFG N α} {obs : α → M}
    {A : ConcreteExtractedSampleLearner G obs}
    (C : ConcreteExtractedSampleLearnerWordSemanticsCertificate A)
    (K : Finset (Word α))
    (w : Word α) (hw : w ∈ K) :
    w ∈ C.wordLanguage K := by
  exact (C.atSample K).sample_word_generated w hw

/-- View a semantics certificate as the older bare sample-indexed semantics
function. -/
def toBareSemantics
    {G : WorkingMCFG N α} {obs : α → M}
    {A : ConcreteExtractedSampleLearner G obs}
    (C : ConcreteExtractedSampleLearnerWordSemanticsCertificate A) :
    ConcreteExtractedSampleLearnerWordSemantics A :=
  C.wordLanguage

end ConcreteExtractedSampleLearnerWordSemanticsCertificate

end LearnerWordSemanticsInterface

end FIv21
