import LeanCfgProject.MCFG.FI_v2_1_SubwordUnitEdgeEnumerationExact

/-!
# FI v2.1 Lean experiment: Gold wrapper for subword unit-edge enumeration

This file packages learners that return subword-unit-edge enumeration data and
forgets them to the previously checked subword-context enumeration learner.  The
point is that unit-edge witnesses are now generated by finite same-context and
same-type filtering over the enumerated subword decompositions.
-/

namespace FIv21

universe u v w

section SubwordUnitEdgeEnumerationGold

variable {N : Type w} {α : Type u}
variable [DecidableEq α]
variable {M : Type v} [Monoid M] [Fintype M]

/-- A learner mapping each finite sample to subword-unit-edge enumeration data. -/
abbrev SubwordUnitEdgeEnumerationLearner
    (G : WorkingMCFG N α) (obs : α → M) :=
  (K : Finset (Word α)) → SubwordUnitEdgeEnumerationData G obs K

/-- Forget a unit-edge enumeration learner to the subword-context enumeration
learner. -/
noncomputable def SubwordUnitEdgeEnumerationLearner.toSubwordContextEnumerationLearner
    {G : WorkingMCFG N α} {obs : α → M}
    (A : SubwordUnitEdgeEnumerationLearner G obs) :
    SubwordContextEnumerationLearner G obs :=
  fun K => (A K).toSubwordContextDecompositionData

/-- Forget a unit-edge enumeration learner to the finite-hypothesis learner. -/
noncomputable def SubwordUnitEdgeEnumerationLearner.toFiniteHypothesisLearner
    {G : WorkingMCFG N α} {obs : α → M}
    (A : SubwordUnitEdgeEnumerationLearner G obs) :
    FiniteHypothesisLearner α M :=
  A.toSubwordContextEnumerationLearner.toFiniteHypothesisLearner

/-- Characteristic sample certificate for a subword-unit-edge enumeration
learner. -/
structure SubwordUnitEdgeEnumerationCharacteristicSample
    {G : WorkingMCFG N α} {obs : α → M}
    (A : SubwordUnitEdgeEnumerationLearner G obs) (L : Set (Word α)) where
  sample : Finset (Word α)
  positive : PositiveForLanguage sample L
  exact_after_extending :
    ∀ K : Finset (Word α),
      SampleExtends sample K →
      PositiveForLanguage K L →
        SubwordUnitEdgeEnumerationExactForLanguage (A K) L

namespace SubwordUnitEdgeEnumerationCharacteristicSample

/-- Forget to the previous subword-context enumeration characteristic-sample
interface. -/
noncomputable def toSubwordContextEnumerationCharacteristicSample
    {G : WorkingMCFG N α} {obs : α → M}
    {A : SubwordUnitEdgeEnumerationLearner G obs} {L : Set (Word α)}
    (C : SubwordUnitEdgeEnumerationCharacteristicSample A L) :
    SubwordContextEnumerationCharacteristicSample
      A.toSubwordContextEnumerationLearner L :=
  { sample := C.sample
    positive := C.positive
    exact_after_extending := by
      intro K hExt hPos
      exact (C.exact_after_extending K hExt hPos).toSubwordContextEnumerationExact }

/-- Unit-edge enumeration characteristic samples identify the target at the
finite-hypothesis distribution level. -/
theorem identifiesInLimit
    {G : WorkingMCFG N α} {obs : α → M}
    {A : SubwordUnitEdgeEnumerationLearner G obs} {L : Set (Word α)}
    (C : SubwordUnitEdgeEnumerationCharacteristicSample A L) :
    FiniteHypothesisIdentifiesInLimit A.toFiniteHypothesisLearner L := by
  exact C.toSubwordContextEnumerationCharacteristicSample.identifiesInLimit

/-- Pointwise context-membership form of limiting identification. -/
theorem eventuallyCorrectContexts
    {G : WorkingMCFG N α} {obs : α → M}
    {A : SubwordUnitEdgeEnumerationLearner G obs} {L : Set (Word α)}
    (C : SubwordUnitEdgeEnumerationCharacteristicSample A L) :
    FiniteHypothesisEventuallyCorrectContexts A.toFiniteHypothesisLearner L := by
  exact C.toSubwordContextEnumerationCharacteristicSample.eventuallyCorrectContexts

/-- After the threshold, filtered same-context/same-type pairs give unit
reachability in the induced finite hypothesis. -/
theorem typedPair_unitReach_after
    {G : WorkingMCFG N α} {obs : α → M}
    {A : SubwordUnitEdgeEnumerationLearner G obs} {L : Set (Word α)}
    (C : SubwordUnitEdgeEnumerationCharacteristicSample A L)
    {K : Finset (Word α)}
    (hExt : SampleExtends C.sample K)
    (hPos : PositiveForLanguage K L)
    {P : SubwordDecompositionPair (α := α) K}
    (hP : P ∈ typedSameContextSubwordPairs (α := α) obs (A K).subwordDecompositions) :
    (A K).toSubwordContextDecompositionData.toSampleExtractedRuleLists.UnitReach
      P.src.tuple P.tgt.tuple := by
  exact (C.exact_after_extending K hExt hPos).typedPair_unitReach hP

/-- The concrete unit-edge enumeration learner represents every observed sample
word by a listed and supported subword decomposition after the threshold. -/
theorem enumerated_supported_sample_word_after
    {G : WorkingMCFG N α} {obs : α → M} {L : Set (Word α)}
    {f : Nat} {hfanout : 1 ≤ f} {hG : G.SemanticWorkingConditions}
    (C : SubwordUnitEdgeEnumerationCharacteristicSample
      (enumeratedSubwordUnitEdgeEnumerationLearner G obs f hfanout hG) L)
    {K : Finset (Word α)}
    (_hExt : SampleExtends C.sample K)
    (_hPos : PositiveForLanguage K L)
    {w : Word α} (hw : w ∈ K) :
    ∃ S : SubwordSampleDecomposition (α := α) K,
      S ∈ ((enumeratedSubwordUnitEdgeEnumerationLearner G obs f hfanout hG) K).subwordDecompositions ∧
      S.sampleWord = w ∧
      (((enumeratedSubwordUnitEdgeEnumerationLearner G obs f hfanout hG) K).support.SupportsTuple S.tuple) ∧
      (((enumeratedSubwordUnitEdgeEnumerationLearner G obs f hfanout hG) K).support.SupportsContext S.context) ∧
      S.context ∈ SampleNamedDistribution K S.tuple := by
  exact enumeratedSubwordUnitEdgeEnumerationData_supported_sample_word G obs K f hfanout hG hw

end SubwordUnitEdgeEnumerationCharacteristicSample

/-- Grammar-target characteristic sample abbreviation for subword-unit-edge
enumeration learners. -/
abbrev GrammarSubwordUnitEdgeEnumerationCharacteristicSample
    {G : WorkingMCFG N α} {obs : α → M}
    (A : SubwordUnitEdgeEnumerationLearner G obs) :=
  SubwordUnitEdgeEnumerationCharacteristicSample A G.StringLanguage

/-- Grammar-target characteristic sample abbreviation for the concrete learner
using enumerated subword decompositions and filtered unit edges. -/
abbrev GrammarEnumeratedSubwordUnitEdgeEnumerationCharacteristicSample
    {G : WorkingMCFG N α} {obs : α → M}
    (f : Nat) (hfanout : 1 ≤ f) (hG : G.SemanticWorkingConditions) :=
  SubwordUnitEdgeEnumerationCharacteristicSample
    (enumeratedSubwordUnitEdgeEnumerationLearner G obs f hfanout hG) G.StringLanguage

end SubwordUnitEdgeEnumerationGold

end FIv21
