import LeanCfgProject.MCFG.FI_v2_1_FiniteHypothesisGold

/-!
# FI v2.1 Lean experiment: output-type refinement substrate

This file is the fourteenth formalization layer for the FI v2.1 MCFG paper.

The previous layers developed the fixed-observation, named-context,
distribution-transport, finite-support, finite-hypothesis, and Gold-style
identification infrastructure.  This file starts the next main block:
output-type refinement of MCFG nonterminals by the fixed monoid observation.

The scope is intentionally conservative.  We do not yet construct the full
refined grammar.  Instead, we prove the key bookkeeping fact needed for that
construction:

* the observation type of a binary-rule output is computable from the binary
  template and the observation types of the two child tuples.

This is the formal substrate for the paper's typed nonterminals
`A^{p_1,...,p_d}`.
-/

namespace FIv21

universe u v w

section TemplateOutputTypes

variable {α : Type u}
variable {M : Type v} [Monoid M]

/-- Observation contribution of a single template atom, given the already-known
componentwise output types of the left and right child tuples. -/
def templateAtomType {dB dC : Nat}
    (obs : α → M) (leftTy : Fin dB → M) (rightTy : Fin dC → M) :
    TemplateAtom α dB dC → M
  | TemplateAtom.terminal a => obs a
  | TemplateAtom.leftVar i => leftTy i
  | TemplateAtom.rightVar j => rightTy j

/-- Observation type of a template word, computed syntactically from the
template and the child output types. -/
def templateWordType {dB dC : Nat}
    (obs : α → M) (leftTy : Fin dB → M) (rightTy : Fin dC → M) :
    TemplateWord α dB dC → M
  | [] => 1
  | a :: rest =>
      templateAtomType obs leftTy rightTy a *
        templateWordType obs leftTy rightTy rest

@[simp] theorem templateWordType_nil {dB dC : Nat}
    (obs : α → M) (leftTy : Fin dB → M) (rightTy : Fin dC → M) :
    templateWordType obs leftTy rightTy
      ([] : TemplateWord α dB dC) = 1 := rfl

@[simp] theorem templateWordType_cons {dB dC : Nat}
    (obs : α → M) (leftTy : Fin dB → M) (rightTy : Fin dC → M)
    (a : TemplateAtom α dB dC) (rest : TemplateWord α dB dC) :
    templateWordType obs leftTy rightTy (a :: rest) =
      templateAtomType obs leftTy rightTy a *
        templateWordType obs leftTy rightTy rest := rfl

/-- Observation type of an evaluated template atom agrees with the syntactic
atom-type computation. -/
theorem evalTemplateAtom_type {dB dC : Nat}
    (obs : α → M)
    (x : Tuple α dB) (y : Tuple α dC)
    (a : TemplateAtom α dB dC) :
    evalObs obs (evalTemplateAtom x y a) =
      templateAtomType obs (tupleType obs x) (tupleType obs y) a := by
  cases a with
  | terminal a =>
      simp [evalTemplateAtom, templateAtomType, evalObs]
  | leftVar i =>
      rfl
  | rightVar j =>
      rfl

/-- Observation type of an evaluated template word is computed entirely from
the template and the child tuple types. -/
theorem evalTemplateWord_type {dB dC : Nat}
    (obs : α → M)
    (x : Tuple α dB) (y : Tuple α dC)
    (w : TemplateWord α dB dC) :
    evalObs obs (evalTemplateWord x y w) =
      templateWordType obs (tupleType obs x) (tupleType obs y) w := by
  induction w with
  | nil =>
      simp [evalTemplateWord, templateWordType, evalObs]
  | cons a rest ih =>
      simp [evalTemplateWord, templateWordType, evalObs_append,
        evalTemplateAtom_type, ih, mul_assoc]

/-- Output type of a whole binary template tuple, computed from the child output
types. -/
def templateTupleType {e dB dC : Nat}
    (obs : α → M)
    (body : TemplateTuple α e dB dC)
    (leftTy : Fin dB → M) (rightTy : Fin dC → M) :
    Fin e → M :=
  fun i => templateWordType obs leftTy rightTy (body i)

/-- The componentwise observation type of an evaluated template tuple is the
syntactically computed template-tuple type. -/
theorem evalTemplateTuple_type {e dB dC : Nat}
    (obs : α → M)
    (body : TemplateTuple α e dB dC)
    (x : Tuple α dB) (y : Tuple α dC) :
    tupleType obs (evalTemplateTuple body x y) =
      templateTupleType obs body (tupleType obs x) (tupleType obs y) := by
  funext i
  exact evalTemplateWord_type obs x y (body i)

end TemplateOutputTypes

section RuleOutputTypes

variable {N : Type w} {α : Type u}
variable {M : Type v} [Monoid M]

namespace TerminalRule

/-- The fixed-observation output type of a terminal rule before arity casting.
Terminal rules produce a one-component tuple. -/
def outputType (obs : α → M) (ρ : TerminalRule N α) : Fin 1 → M :=
  fun _ => obs ρ.terminal

/-- The one-component tuple generated by a terminal rule has the expected
one-component observation type. -/
theorem outputTuple_type
    (obs : α → M) (ρ : TerminalRule N α) :
    tupleType obs ρ.outputTuple = ρ.outputType obs := by
  funext i
  simp [tupleType, outputTuple, outputType, evalObs]

end TerminalRule

namespace BinaryRule

/-- The output type of a binary rule when its left and right child output types
are known. -/
def outputType {arity : N → Nat}
    (obs : α → M) (ρ : BinaryRule N α arity)
    (leftTy : Fin (arity ρ.left) → M)
    (rightTy : Fin (arity ρ.right) → M) :
    Fin (arity ρ.lhs) → M :=
  templateTupleType obs ρ.body leftTy rightTy

/-- Applying a binary rule preserves the syntactically computed output type. -/
theorem apply_tupleType {arity : N → Nat}
    (obs : α → M) (ρ : BinaryRule N α arity)
    (x : Tuple α (arity ρ.left))
    (y : Tuple α (arity ρ.right)) :
    tupleType obs (ρ.apply x y) =
      ρ.outputType obs (tupleType obs x) (tupleType obs y) := by
  exact evalTemplateTuple_type obs ρ.body x y

/-- If the two child tuples have prescribed output types, then the result of the
binary rule has the corresponding rule output type. -/
theorem apply_has_outputType {arity : N → Nat}
    (obs : α → M) (ρ : BinaryRule N α arity)
    (x : Tuple α (arity ρ.left))
    (y : Tuple α (arity ρ.right))
    (leftTy : Fin (arity ρ.left) → M)
    (rightTy : Fin (arity ρ.right) → M)
    (hx : tupleType obs x = leftTy)
    (hy : tupleType obs y = rightTy) :
    tupleType obs (ρ.apply x y) =
      ρ.outputType obs leftTy rightTy := by
  rw [ρ.apply_tupleType obs x y, hx, hy]

end BinaryRule

end RuleOutputTypes

section RefinedNonterminals

variable {N : Type w} {α : Type u}
variable {M : Type v} [Monoid M]

/-- A nonterminal refined by a componentwise output type.

For a grammar `G`, the intended reading is the paper's notation
`A^{p_1,...,p_d}`: the base nonterminal is `A`, and `outTy` assigns an
observation value to each of its `G.arity A` components. -/
structure OutputTypedNonterminal (arity : N → Nat) (M : Type v) where
  base : N
  outTy : Fin (arity base) → M

/-- The refined nonterminals associated with a grammar and a fixed observation
monoid. -/
abbrev RefinedNonterminal (G : WorkingMCFG N α) (M : Type v) :=
  OutputTypedNonterminal G.arity M

namespace OutputTypedNonterminal

/-- A tuple has the output type carried by a refined nonterminal. -/
def AcceptsTuple {arity : N → Nat}
    (obs : α → M) (A : OutputTypedNonterminal arity M)
    (x : Tuple α (arity A.base)) : Prop :=
  tupleType obs x = A.outTy

/-- Packaging a tuple together with the proof that it has a prescribed
componentwise output type. -/
structure TypedTuple {arity : N → Nat}
    (obs : α → M) (A : OutputTypedNonterminal arity M) where
  tuple : Tuple α (arity A.base)
  hasType : A.AcceptsTuple obs tuple

/-- Forget the type proof and keep the underlying tuple. -/
def TypedTuple.toTuple {arity : N → Nat}
    {obs : α → M} {A : OutputTypedNonterminal arity M}
    (x : TypedTuple obs A) : Tuple α (arity A.base) :=
  x.tuple

/-- The underlying tuple of a typed tuple has the advertised output type. -/
theorem TypedTuple.tuple_hasType {arity : N → Nat}
    {obs : α → M} {A : OutputTypedNonterminal arity M}
    (x : TypedTuple obs A) :
    tupleType obs x.toTuple = A.outTy :=
  x.hasType

end OutputTypedNonterminal

namespace RefinedNonterminal

variable (G : WorkingMCFG N α)

/-- The arity of a refined nonterminal is the arity of its base nonterminal. -/
def arity (A : RefinedNonterminal G M) : Nat :=
  G.arity A.base

@[simp] theorem arity_eq (A : RefinedNonterminal G M) :
    arity G A = G.arity A.base := rfl

end RefinedNonterminal

end RefinedNonterminals

section TypedDerivations

variable {N : Type w} {α : Type u}
variable {M : Type v} [Monoid M]

/-- A typed derivation statement: the base grammar derives the underlying tuple,
and the tuple has the output type attached to the refined nonterminal.

This is not yet the full refined grammar.  It is the semantic predicate that the
future refined grammar should generate exactly. -/
def DerivesOutputTypedTuple
    (G : WorkingMCFG N α) (obs : α → M)
    (A : RefinedNonterminal G M)
    (x : Tuple α (G.arity A.base)) : Prop :=
  DerivesTuple G A.base x ∧ tupleType obs x = A.outTy

/-- The untyped derivation part of a typed derivation. -/
theorem DerivesOutputTypedTuple.derives
    {G : WorkingMCFG N α} {obs : α → M}
    {A : RefinedNonterminal G M}
    {x : Tuple α (G.arity A.base)}
    (h : DerivesOutputTypedTuple G obs A x) :
    DerivesTuple G A.base x :=
  h.1

/-- The output-type part of a typed derivation. -/
theorem DerivesOutputTypedTuple.has_output_type
    {G : WorkingMCFG N α} {obs : α → M}
    {A : RefinedNonterminal G M}
    {x : Tuple α (G.arity A.base)}
    (h : DerivesOutputTypedTuple G obs A x) :
    tupleType obs x = A.outTy :=
  h.2

/-- A binary derivation step has the output type computed from the two typed
children and the binary template.

This is the main bridge toward the future refined binary-rule construction:
given typed child derivations, the parent refined nonterminal is determined by
`ρ.outputType`. -/
theorem binary_step_has_output_type
    {G : WorkingMCFG N α} (obs : α → M)
    (ρ : BinaryRule N α G.arity)
    (x : Tuple α (G.arity ρ.left))
    (y : Tuple α (G.arity ρ.right))
    (leftTy : Fin (G.arity ρ.left) → M)
    (rightTy : Fin (G.arity ρ.right) → M)
    (hx : tupleType obs x = leftTy)
    (hy : tupleType obs y = rightTy) :
    tupleType obs (ρ.apply x y) =
      ρ.outputType obs leftTy rightTy := by
  exact BinaryRule.apply_has_outputType obs ρ x y leftTy rightTy hx hy

end TypedDerivations

end FIv21
