/-
Copyright (c) 2026 Takayuki Kuriyama. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Takayuki Kuriyama
-/
import LeanCfgProject.MCFG.FinalReachableTheorem

/-!
# OutputTypeRefinementPresentation.lean

Thirty-seventh clean Lean experiment for the fixed-observation MCFG project.

The earlier files `OutputTypeRefinement.lean` and `OutputTypeLift.lean`
formalized the local typed-rule machinery for the paper's output-type
refinement `G^h`.

This file starts turning that machinery into a finite presentation interface.

It introduces:

* a finite set of typed nonterminals;
* finite sets of typed terminal, binary, and start rules;
* closure conditions saying that the endpoints of typed rules are present
  among the typed nonterminals;
* a small derivation relation generated by the finite typed terminal and
  binary rules;
* an erasure theorem saying that every derivation in this finite typed
  presentation is an output-typed derivation over the original grammar.

This is not yet the full construction of `G^h` or its trimmed subgrammar
`G̃₀`, but it is the first finite-presentation layer needed for that
construction.

No theorem here uses `sorry`.
-/

namespace MCFG

universe u v w

section Presentation

variable {N : Type v} {α : Type u} {M : Type w} [Monoid M]

/-- A finite presentation of part of the output-type refinement of a grammar.

The presentation stores finite sets of typed nonterminals and typed rules,
together with local closure conditions. -/
structure OutputTypeRefinementPresentation
    (G : WorkingMCFG N α) (obs : α → M) where
  nonterminals : Finset (TypedNonterminal G M)
  terminalRules : Finset (TypedTerminalRule G)
  binaryRules : Finset (TypedBinaryRule G M)
  startRules : Finset (TypedStartRule G M)

  terminal_lhs_mem :
    ∀ τ : TypedTerminalRule G,
      τ ∈ terminalRules →
        τ.lhs obs ∈ nonterminals

  binary_lhs_mem :
    ∀ τ : TypedBinaryRule G M,
      τ ∈ binaryRules →
        τ.lhs obs ∈ nonterminals

  binary_left_mem :
    ∀ τ : TypedBinaryRule G M,
      τ ∈ binaryRules →
        τ.left ∈ nonterminals

  binary_right_mem :
    ∀ τ : TypedBinaryRule G M,
      τ ∈ binaryRules →
        τ.right ∈ nonterminals

  start_child_mem :
    ∀ σ : TypedStartRule G M,
      σ ∈ startRules →
        σ.child ∈ nonterminals

namespace OutputTypeRefinementPresentation

variable {G : WorkingMCFG N α} {obs : α → M}

/-- A typed nonterminal is present in the finite presentation. -/
def HasNonterminal
    (P : OutputTypeRefinementPresentation G obs)
    (X : TypedNonterminal G M) : Prop :=
  X ∈ P.nonterminals

/-- A typed terminal rule is present in the finite presentation. -/
def HasTerminalRule
    (P : OutputTypeRefinementPresentation G obs)
    (τ : TypedTerminalRule G) : Prop :=
  τ ∈ P.terminalRules

/-- A typed binary rule is present in the finite presentation. -/
def HasBinaryRule
    (P : OutputTypeRefinementPresentation G obs)
    (τ : TypedBinaryRule G M) : Prop :=
  τ ∈ P.binaryRules

/-- A typed start rule is present in the finite presentation. -/
def HasStartRule
    (P : OutputTypeRefinementPresentation G obs)
    (σ : TypedStartRule G M) : Prop :=
  σ ∈ P.startRules

/-- The left-hand side of a present terminal rule is present. -/
theorem terminal_lhs_present
    (P : OutputTypeRefinementPresentation G obs)
    {τ : TypedTerminalRule G}
    (hτ : P.HasTerminalRule τ) :
    P.HasNonterminal (τ.lhs obs) :=
  P.terminal_lhs_mem τ hτ

/-- The parent of a present binary rule is present. -/
theorem binary_lhs_present
    (P : OutputTypeRefinementPresentation G obs)
    {τ : TypedBinaryRule G M}
    (hτ : P.HasBinaryRule τ) :
    P.HasNonterminal (τ.lhs obs) :=
  P.binary_lhs_mem τ hτ

/-- The left child of a present binary rule is present. -/
theorem binary_left_present
    (P : OutputTypeRefinementPresentation G obs)
    {τ : TypedBinaryRule G M}
    (hτ : P.HasBinaryRule τ) :
    P.HasNonterminal τ.left :=
  P.binary_left_mem τ hτ

/-- The right child of a present binary rule is present. -/
theorem binary_right_present
    (P : OutputTypeRefinementPresentation G obs)
    {τ : TypedBinaryRule G M}
    (hτ : P.HasBinaryRule τ) :
    P.HasNonterminal τ.right :=
  P.binary_right_mem τ hτ

/-- The child selected by a present typed start rule is present. -/
theorem start_child_present
    (P : OutputTypeRefinementPresentation G obs)
    {σ : TypedStartRule G M}
    (hσ : P.HasStartRule σ) :
    P.HasNonterminal σ.child :=
  P.start_child_mem σ hσ

/-- A conjunction form useful when destructing a present binary rule. -/
theorem binary_nodes_present
    (P : OutputTypeRefinementPresentation G obs)
    {τ : TypedBinaryRule G M}
    (hτ : P.HasBinaryRule τ) :
    P.HasNonterminal τ.left ∧
      P.HasNonterminal τ.right ∧
        P.HasNonterminal (τ.lhs obs) := by
  exact ⟨P.binary_left_present hτ,
    P.binary_right_present hτ,
    P.binary_lhs_present hτ⟩

end OutputTypeRefinementPresentation

end Presentation


section PresentationDerivations

variable {N : Type v} {α : Type u} {M : Type w} [Monoid M]
variable {G : WorkingMCFG N α} {obs : α → M}

/-- Derivations generated by a finite output-type-refinement presentation.

This relation uses only the typed terminal and binary rules present in the
finite presentation.  Start rules are kept separately because the target
language still lives at the grammar start symbol. -/
inductive PresentationDerives
    (P : OutputTypeRefinementPresentation G obs) :
    (X : TypedNonterminal G M) → Tuple α (G.arity X.base) → Prop where
  | terminal
      {τ : TypedTerminalRule G}
      (hτ : P.HasTerminalRule τ) :
      PresentationDerives P (τ.lhs obs)
        (castTuple τ.wellTyped.symm τ.baseRule.outputTuple)
  | binary
      {τ : TypedBinaryRule G M}
      (hτ : P.HasBinaryRule τ)
      {x : Tuple α (G.arity τ.baseRule.left)}
      {y : Tuple α (G.arity τ.baseRule.right)}
      (hx : PresentationDerives P τ.left x)
      (hy : PresentationDerives P τ.right y) :
      PresentationDerives P (τ.lhs obs)
        (τ.baseRule.apply x y)

namespace PresentationDerives

variable {P : OutputTypeRefinementPresentation G obs}

/-- A presentation derivation erases to an output-typed derivation over the
original grammar. -/
theorem toOutputTypedDerives
    {X : TypedNonterminal G M}
    {x : Tuple α (G.arity X.base)}
    (h : PresentationDerives P X x) :
    OutputTypedDerives (G := G) (obs := obs) X x := by
  induction h with
  | terminal hτ =>
      exact OutputTypedDerives.mk
        (DerivesTuple.terminal
          (ρ := τ.baseRule) τ.inGrammar τ.wellTyped)
        (τ.cast_outputTuple_matches_lhs obs)
  | binary hτ hx hy ihx ihy =>
      exact OutputTypedDerives.binary τ ihx ihy

end PresentationDerives

end PresentationDerivations

end MCFG


namespace PresentationDerives

variable {N : Type v} {α : Type u} {M : Type w} [Monoid M]
variable {G : WorkingMCFG N α} {obs : α → M}
variable {P : OutputTypeRefinementPresentation G obs}

/-- A presentation derivation erases all the way to an ordinary derivation in
the original grammar. -/
theorem erase
    {X : TypedNonterminal G M}
    {x : Tuple α (G.arity X.base)}
    (h : PresentationDerives P X x) :
    DerivesTuple G X.base x :=
  h.toOutputTypedDerives.erase

/-- A presentation derivation satisfies the output type stored in its
nonterminal. -/
theorem tuple_type_eq
    {X : TypedNonterminal G M}
    {x : Tuple α (G.arity X.base)}
    (h : PresentationDerives P X x) :
    tupleType obs x = X.out :=
  h.toOutputTypedDerives.tuple_type_eq

end PresentationDerives

end MCFG
